### ISSUE TITLE
[WEB] Animate RotateZ is not possible on web platform

### ISSUE THREAD

**Issue by dagatsoin** [Microsoft/reactxp#1000]
## Issue
We can't use the rotateZ transform property on the web plateform.

```
Styles.createAnimatedViewStyle({
      transform: [
        { translateX: this.cursorAnimatedValues.translateX },
        { translateY: this.cursorAnimatedValues.translateY },
        { rotateX: this.cursorAnimatedValues.rotateX },
        { rotateY: this.cursorAnimatedValues.rotateY },
        { rotateZ: this.cursorAnimatedValues.rotateZ },
        { scaleX: this.cursorAnimatedValues.scaleX },
        { scaleY: this.cursorAnimatedValues.scaleY },
      ]
    })
```
## Current behavior:

Setting a rotateZ in a stylesheet leads as this invalid `transform` string because the Z value is set to `NaN`

![](https://files.gitter.im/msreactxp/Lobby/LEKD/image.png)

## Workaround

Use `rotate` field instead.

## Possible fix

add the missing unit for rotateZ here: https://github.com/Microsoft/reactxp/blob/9483e91763f5df77adda639af3f8d71c06012bc8/src/web/Animated.tsx#L42

**Comment by deregtd** [comment]
Fair enough suggestion, but out of curiosity, why not use "rotate" instead of "rotateZ"?  Should have the same exact effect.

**Comment by dagatsoin** [comment]
Yes indeed, I will add this workaround.
If you are agree, I will make a PR on this.

**Comment by deregtd** [comment]
That's fine.

**Comment by dagatsoin** [comment]
Continuing discussion in #1001 if needed.
