### ISSUE TITLE
Error when inheriting from Text

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#1003]
```ts
// test.ts
import { Text } from 'reactxp';

export class Label extends Text {}
```

Emits:

>error TS2515: Non-abstract class 'Label' does not implement inherited abstract member 'focus' from class 'Text'.
>error TS2515: Non-abstract class 'Label' does not implement inherited abstract member 'getSelectedText' from class 'Text'.
>error TS2515: Non-abstract class 'Label' does not implement inherited abstract member 'requestFocus' from class 'Text'

Seems like some type annotations don't work as intended?

**Comment by erictraut** [comment]
The ReactXP classes are not designed to be base classes. You should define a new custom component that uses the ReactXP classes in their render function.
