### ISSUE TITLE
Type issues when mapping `React.Children.map` and `RX.Component`

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#1009]
Hi,

I see some cryptic error that arises when using `React.Children.map` to wrap the `string` nodes into  a `Label` component. 

I can't make sense of why that happens, but subclassing the `BaseButton` component (see below) from `React.Component` makes the error go away. 😕 

Also the error goes away when replacing the custom `Label` with `Text` which makes no sense to me either, or when casting the `child` to string, i.e `<Label>{child.toString()}</Label>`.

That's what `tsc` outputs:

```
$  test tsc
test.tsx:16:17 - error TS2322: Type '{ children: string | ({} & string) | ({} & number) | (ReactElement<any> & string) | (ReactNodeArray & string) | (ReactPortal & string) | (string & {}) | (number & {}) | (false & {}) | ... 5 more ... | (string & ReactPortal); }' is not assignable to type 'Readonly<{ children?: string | number | undefined; }>'.
  Types of property 'children' are incompatible.
    Type 'string | ({} & string) | ({} & number) | (ReactElement<any> & string) | (ReactNodeArray & string) | (ReactPortal & string) | (string & {}) | (number & {}) | (false & {}) | (true & {}) | ... 4 more ... | (string & ReactPortal)' is not assignable to type 'string | number | undefined'.
      Type 'false & {}' is not assignable to type 'string | number | undefined'.
        Type 'false & {}' is not assignable to type 'number'.

16             ? (<Label>{child}</Label>)
                   ~~~~~


Found 1 error.
```

* test.tsx*

```tsx
import * as React from 'react';
import { Button, Component, Text } from 'reactxp';

export class Label extends Component<{ children?: React.ReactText }> {
  render() {
    return <Text>{this.props.children}</Text>;
  }
}

class BaseButton extends Component<{ children?: React.ReactNode }> {
  render() {
    return (
      <Button>
        {React.Children.map(this.props.children, (child) => (
          typeof child === 'string'
            ? (<Label>{child}</Label>)
            : child
        ))}
      </Button>
    );
  }
}
```

Source code repo: https://github.com/pronebird/reactxp-bug-1

**Comment by berickson1** [comment]
It looks like type inferences are causing issues here since you're returning Label|React.Node. I believe you need to force a more generic return type of React.Node
The following works for me:
```
  render() {
    return (
      <Button>
        {React.Children.map<React.ReactNode, React.ReactNode>(this.props.children, (child) => {
          if (typeof child === 'string') {
            const str: string = child;
            return (<Label>{str}</Label>)
          } else {
            return child;
          }
        })}
      </Button>
    );
  }
```

**Comment by pronebird** [comment]
@berickson1 

No that's not the case. I can return `<Label>{"some text"}</Label>` without any issues. The problem seems to be in the type of `child`. 

Passing `child` as is, even after checking with `typeof child === 'string'` makes TypeScript think that the variable can still be something else but not a `string`. Asserting the type works just fine. I don't know if that's a bug in RX or TS or somewhere else or an expected behaviour.
