### ISSUE TITLE
Disable scrollToTop after tapped in VirtualListView

### ISSUE THREAD

**Issue by shengjie77** [Microsoft/reactxp#1010]
Is there any way to disable scrollToTop after tapped item in VirtualListView? I can't find any props to control this behavior.

**Comment by berickson1** [comment]
selectItemKey now (reactxp-virtuallistview@2.0.0-rc.3) has a configurable parameters (shouldScroll, default true) that can be used to decide if we should scroll on selection of item. By default tapping on items will not scroll, if you want to scroll you'll have to call selectItemKey directly
