### ISSUE TITLE
Various errors while trying to run Windows app

### ISSUE THREAD

**Issue by gabeljz** [Microsoft/reactxp#1011]
In Windows 10 (running in VirtualBox), various errors will be encountered while trying to run the Windows app for any of the [samples](https://github.com/Microsoft/reactxp/tree/master/samples) or a bare app freshly created by `create-rx-app`, version 0.4.14.

Despite two days of trials and errors, I have not succeeded in building a windows app created from `create-rx-app`, is it possible to make the process as error-free and robust as the process at https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md ?

Or provide a npm module of this project that can be added to an existing project that was created with `react-native init`?

### Error 1

> Attempt by security method 'System.Reactive.Concurrency/CoreDispatcherScheduler..ctor(Windows.UI.Core.CoreDispatcher)' to access security critical type 'Windows.UI.Core.CoreDispatcher' failed.
> 
> Assembly 'System.Reactive, Version=4.0.0.0, Culture=neutral, PublicKeyToken=<XXX>' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model. Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

See [picture](https://user-images.githubusercontent.com/12538029/51966968-0563a480-24a9-11e9-92dc-be8239e583e5.png)

### Error 2

> Application rxphelloworld has not been registered.
>
> Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on before. If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the packager in the correct app folder (e.g. cd into the app folder and run 'npm start').
>
> This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent. 

See [picture](https://user-images.githubusercontent.com/12538029/51966978-0dbbdf80-24a9-11e9-891c-afc8a6116f1c.png)

# Steps to produce the errors

1. `$ git clone https://github.com/Microsoft/reactxp.git`
    * commit baa599957e6dca5a1c33cb154f15fcb2105b1d4e 
2. `$ cd reactxp/samples/hello-world-js/`
3. `$ yarn install`
4. `$ npm run start:windows` or `$ react-native run-windows`
    * This will fail to build with the following error messages in command prompt:
        * Cannot import the keyfile `RXPHelloWorld_TemporaryKey.pfx`
        * A certificate with thumbprint <XXX> that is specified in the project cannot be found in the certificate store.
        * The certificate specified is not valid for signing.
5. To overcome the errors in step 4, `$ react-native windows` and answer "y" to every question prompt.
6. `$ npm run start:windows` or `$ react-native run-windows`
    * Metro bundler will try to run, but encounter error message ".packager.bat" is not recognised as an internal or external command, operable program or batch file.
        1. Press "ctrl+c" to bypass this error.
        2. Metro bundler load the dependency graph for a long time, but never show that it is "done".
    * The app will show error message "Unable to load JS bundle".
7. Restart Windows
8. `$ cd reactxp/samples/hello-world-js/`
9. `$ npm run start:windows` or `$ react-native run-windows`
    * Metro bundler will bypass the ".packager.bat" by itself and show "done" in loading the dependency graph rather fast.
    * The app will encounter **Error 1**.
10. Restart Windows
11. `$ cd reactxp/samples/hello-world-js/`
12. `$ react-native windows` and answer "y" to every question prompt.
13. `$ npm run start:windows` or `$ react-native run-windows`
    * Metro bundler will bypass the ".packager.bat" by itself and show "done" in loading the dependency graph rather fast.
    * The app will encounter **Error 2**.
    
# Prove environment setup by successfully building app from react-native-init

To prove that my environment is setup properly and functional, I can successfully run a bare app created by following the instruction on https://github.com/Microsoft/react-native-windows/blob/master/docs/GettingStarted.md :

1. `$ react-native init --version 0.57.7 BareApp`
2. `$ cd BareApp`
3. `$ yarn add rnpm-plugin-windows --dev`
4. `$ react-native windows`
5. `$ react-native run-windows`

# Environment Setup

* Host OS: macOS Mojave Version 10.14.2
* Guest OS: Windows 10 Enterprise (Evaluation - Build 201812) VM in VirtualBox, downloaded from https://developer.microsoft.com/en-us/windows/downloads/virtual-machines, which includes:
    * Windows 10 Enterprise October 2018 Update Evaluation
    * Visual Studio 2017 version 15.9 with the UWP, desktop C++, and Azure workflows enabled
    * Visual Studio Code
    * Windows Template Studio extension
    * Windows UWP samples (latest)
    * Windows Subsystem for Linux enabled with Ubuntu installed
    * Developer mode and bash enabled
* Node v10.15.0 and npm 6.4.1, installed via nvm
* react-native-cli 2.0.1
* react-native 0.57.7
* git version 2.20.1.windows.1
* yarn 1.13.0
* create-rx-app 0.4.14

**Comment by a-tarasyuk** [comment]
@gabeljz If you have any issues related to [create-rx-app](https://github.com/a-tarasyuk/create-rx-app), please post them on the appropriate repository. `create-rx-app` under the hood uses react-native-windows., also for new applications generated on windows environment it creates [self-signed certificate] as it does by react-native-windows.

Also, if your error related to self-signed certificate (#4 in you list), you don't need run `react-native windows` you need just updated your [self-signed certificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps). `react-native windows` will override your windows application, if you did it you need to fix on your own some of the code requirements for ReactXP, for instance, change `MainComponentName`.

Anyway, if you have problems with  `create-rx-app` add issues on the appropriate repository. 

@erictraut I think this issue can be closed because it does not relate to reactxp.

**Comment by gabeljz** [comment]
@a-tarasyuk, I faced problems running the samples in reactxp as well, I thought that those samples were created by `create-rx-app` too. So I thought that this is the parent project and would be the better place to post this issue.

Anyway, I can't post any issue in [create-rx-app](https://github.com/a-tarasyuk/create-rx-app), the "Sumit new issue" button is disabled for me.

**Comment by a-tarasyuk** [comment]
@gabeljz

> faced problems running the samples in reactxp as well

I see the only problem related to [self-signed certificate](https://docs.microsoft.com/en-us/powershell/module/pkiclient/new-selfsignedcertificate?view=win10-ps), I described this in my previous message. 

> Anyway, I can't post any issue in create-rx-app, the "Sumit new issue" button is disabled for me.

It is free repo, and [anyone](https://github.com/a-tarasyuk/create-rx-app/issues) can post issue - it looks weird.

**Comment by gabeljz** [comment]
Reposted to https://github.com/a-tarasyuk/create-rx-app/issues/10
