### ISSUE TITLE
RXPTest Build Fails

### ISSUE THREAD

**Issue by P-Blackburn** [Microsoft/reactxp#1019]
RXPTest fails to build on a fresh clone of reactxp - Please can someone point me in the right direction, as I am new to this stuff?

Following the [README.md](https://github.com/Microsoft/reactxp/blob/d07171694b85114c90cf9c22d8fd2fa9d1c6b0ae/samples/RXPTest/README.md) 

in RXPTest folder I execute
`npm install`

but build fails when I then try to run:
`npm run rn-watch`

It seems the reason is because of changes to commit 9483e91763f5df77adda639af3f8d71c06012bc8.

If I understand correctly `npm install` looks at the package.json file and installs the latest published reactxp package rather than use the local updated (unpublished?) package.  

What do I do to force the RXPTest to use the local version of reactxp which has the updates?

Or is there some other fundamental step I am missing in what I am doing?

**Comment by berickson1** [comment]
You'll need to copy the reactxp dist folder structure into the node_modules/reactxp of RXPTest.
Exact details are described in: https://github.com/dagatsoin/reactxp/blob/master/CONTRIBUTING.md


To get around #1013 (which will be resolved in next ReactXP publish), you'll need to install a newer `"@types/react": "16.7.20"`, to the devDependencies to complete building the test app

**Comment by P-Blackburn** [comment]
Thanks - that resolved matters.  I wonder if in the sample project README.md files it might be an idea to reference the relevant section of reactxp [CONTRIBUTING.md](https://github.com/Microsoft/reactxp/blob/master/CONTRIBUTING.md#testing-your-change) as a possible solution when there are unpublished reactxp dependent changes?  (I am happy to do the quick edits)
