### ISSUE TITLE
Navigator: Disable animation on popToTop

### ISSUE THREAD

**Issue by blelem** [microsoft/reactxp#1027]
When calling popToTop on the navigator, the application flickers badly when the stack of pages to pop is anything more than 3 pages.

It seems like the navigator pops the top page (with animation), then pops the second page (with animation),...  This all happens quickly, but not quickly enough, the effect is very visible : a lot of things are drawn on screen during short period of time. 

That effect can be seen on both on Android and iOS apps. On the web client, there are no flickers, the popToTop transition is clean.

Am I missing some obvious parameter, or is this just a bug?

**Comment by erictraut** [comment]
The author of the reactxp-navigator extension is no longer working on the project. You may need to dig into this yourself. If you find a fix, a contribution would be welcome.

**Comment by fbartho** [comment]
@blelem is this still a concern? I'd be happy to merge a fix for this, but I don't currently use the `navigation` extension in my own apps.

**Comment by blelem** [comment]
Ah, a trip down the memory lane! This is not an issue for us anymore, we replaced reactxp-navigator with the [react-router](https://reactrouter.com/). 
Feel free to close this error. I would recommend to mark reactxp-navigator as deprecated though, if a maintainer for that extention hasn't yet been found.

**Comment by fbartho** [comment]
I've opened ticket #1234 to discuss deprecating!

**Comment by fbartho** [comment]
Thanks @blelem for your prompt response, as it makes this project easier to maintain.
