### ISSUE TITLE
Build Issues (following recent update 589c23)

### ISSUE THREAD

**Issue by P-Blackburn** [Microsoft/reactxp#1028]
@msfterictraut The changes you checked in about 23 hours ago are they correct?

It seems reactxp's package.json now has a dependency on  "@types/react": "16.8.3"  
yet the RXPtest's package.json has dependency on "react": "^16.6.3" 

and it would appear the latest released react available is 16.8.2  

It seems this update breaks the build....   Is there any guidance you can give me of what I do to make the build now work - or is the dependency in of 16.8.3 incorrect - perhaps it should be 16.6.3 or 16.8.2 ??

**Comment by erictraut** [comment]
The minor version numbers of @types/react and react are not necessarily in sync. They are separate repos with separate maintainers.

What build is broken for you? Are you trying to build ReactXP from source? Or is your own project's build broken? In either case, can you give me a sample of the build break?

Incidentally, whenever I prepare to publish a new version of reactxp, I run "npm update" and "npm outdated" to ensure that it's using the latest published versions of its dependent modules.

**Comment by P-Blackburn** [comment]
I was/a trying (again) to build RXPTest from scratch following the Readme instructions.

I will blow the reactxp folders away and try again from scratch and post the precise errors...

**Comment by P-Blackburn** [comment]
# Build issues

I renamed this issue "Build Issues". To research the following I blew away my development machine image and installed everything from scratch (inc Android Studio et al)  and followed the Readme.md instructions in the reaxtxp project and sample project folders..  All the samples build and deployed except for RXPTest.  


## Problem with Building RXPTest (for Android)

In Android Studio the build fails with an error in gradle of unresolved dependencies:

![image](https://user-images.githubusercontent.com/47189653/52983061-22710080-33e1-11e9-9fac-55d80fe304b9.png)

It seems the error is failing to resolve `com.facebook.react:react-native:0.57.8`



## Suggestion 1: `npm i` 

The Readme.md file in each of the samples (hello-world, hello-world-js, Image List, TodoList)  all need to be updated to ensure the developer following the instructions especially for the first time executes `npm i`  or `npm install` on each sample project.  The RXPTest README.md makes this clear but the other projects don't.   (I'll do a PR to make that clear(er))  

## Suggestion 2  (TodoList Sample):

The instructions do not make clear that if trying to deploy at least to a physical Android device that it is necessary to execute `adb reverse tcp:8081 tcp:8081`  before deploying to the device - It might ostensibly be covered by the Readme.md saying "Open the project (in the android directory) in Android Studio and *build it like any other React Native project.*     However, it might help to make this clearer, and again I'll include that in a PR.
