### ISSUE TITLE
Rerender Popup on component change

### ISSUE THREAD

**Issue by hwbartle** [Microsoft/reactxp#1032]
I have a component that is being displayed in a popup. The component needs to expand and contract based on an internal state value. If the popup is near the edge of the window container, it will render correctly around the available space. However, when the component's size changes, the popup does not recalculate and the now larger component will render offscreen.

Is there a clean way to have the popup's dimensions/position recalculate? If not, can it be created?

**Comment by erictraut** [comment]
The popup measurement logic assumes that the content size doesn't change after initial measurement. If you need the size to change, you'll need to dismiss the popup and show it again. This can typically happen within a single frame, so it looks fine. If the contents are very complex, it can take a couple of frames for the render operation and measurement to complete.
