### ISSUE TITLE
Button type attribute (web)

### ISSUE THREAD

**Issue by junseld** [Microsoft/reactxp#1034]
currently `RX.Button` doesn't allow setting a `type` and doesn't set one so for most browsers it uses `type="submit"` as default.

Is this intentional? maybe not significant because you don't use forms? isn't it better to use `type="button"` as default?

We use the form element in our login and we refactored some stuff (making clickable icons use RX.Button). Now the icon in the form is triggered on enter instead of the original submit button.

How do you recommend to handle those cases? not using forms and manually handling an enter press to trigger a submit function? icons use RX.View as Clickhandler?

**Comment by erictraut** [comment]
Relying on browser-based forms won't work for cross-platform (native) code, so they're not generally used for ReactXP apps. So yes, handling an enter press to trigger a submit function is the recommended approach.

**Comment by junseld** [comment]
Ok I thought you would say that ;)
How do you recommend to use the browsers autofill/autocomplete and saving of credentials? doesn't it only work with form elements? 
I'm not really a web guru and only found that you have to use forms to do that.

**Comment by erictraut** [comment]
Is this for a log-in page for your app? Those are often integrated as a separate web page (e.g. using the OAuth standard) hosted in an RX.WebView. If you need to write your own custom log-in page from scratch and it's a requirement that it use the bower's credential saving, then you'll need to write it specifically for the web platform and use forms. A different solution would be required for native versions of your app.

**Comment by junseld** [comment]
ok thanks. 
Sad that I can't specifiy the button type or that it isn't `type=button` by default but I guess it makes sense since react-native doesn't have anything similar.

**Comment by kg-currenxie** [comment]
I don't understand this reasoning. ReactXP has **plenty (!)** of web-only, ios-only and android-only props, as well as web-only styling attributes.
Just add the `type` prop on the web platform, and ignore it in the others?

Just this missing prop, forced us to do this ugly s**t :(
```
const PlatformButton = ({ children, type, style, onPress, onHoverStart, onHoverEnd }: any) => {
  return Platform.getType() === 'web' ? (
    <button type={type} style={style} onClick={onPress} onMouseEnter={onHoverStart} onMouseLeave={onHoverEnd}>
      {children}
    </button>
  ) : (
    <RxButton onPress={onPress} style={style} onHoverStart={onHoverStart} onHoverEnd={onHoverEnd}>
      {children}
    </RxButton>
  )
}
```

**Comment by deregtd** [comment]
To some extent, yes, we add custom props per platform where appropriate.  The problem is that the type attribute on button shouldn't really apply to reactxp apps, since "forms" aren't a thing in ReactXP, so needing a type there shouldn't be applicable.  Do you have a use for the type field outside of a <form>?

**Comment by kg-currenxie** [comment]
### Props
```
activeOpacity: number = undefined; // iOS and Android only
ariaControls: string = undefined; // Web only
id: string = undefined; // Web only
disableTouchOpacityAnimation: boolean = false;  // iOS and Android only
onAccessibilityTapIOS: (e: SyntheticEvent) => void; // iOS Only
shouldRasterizeIOS: boolean = false; // iOS only
underlayColor: string = undefined; // iOS and Android only
resizeMethod: 'auto' | 'resize' | 'scale' = 'auto'; // Android only
allowFontScaling: boolean = true; // Android and iOS only
mode: 'dialog' | 'dropdown' = 'dialog'; // Android only
bounces: boolean = true; // iOS only
keyboardDismissMode: 'none' | 'interactive' | 'on-drag'; // Native only
overScrollMode?: 'auto' | 'always' | 'never'; // Android only
pagingEnabled: boolean = false; // Android & iOS only
snapToInterval: number = undefined; // iOS only
scrollsToTop: boolean = false; // iOS only
tabNavigation?: 'local' | 'cycle' | 'once'; // Windows only
allowFontScaling: boolean = true; // Android and iOS only
ellipsizeMode: 'head' | 'middle' | 'tail'; // Android & iOS only
allowFontScaling: boolean = true; // Android and iOS only
clearButtonMode: 'never' | 'while-editing' | 'unless-editing' | 'always'; // Windows, iOS only
keyboardAppearance: 'default' | 'light' | 'dark'; // iOS only
accessibilityLiveRegion: AccessibilityLiveRegion = undefined; // Android and web only
activeOpacity: number = undefined; // iOS and Android only
ariaLabelledBy?: string = undefined; // Web only
ariaRoleDescription?: string = undefined; // Web only
disableTouchOpacityAnimation: boolean = false;  // iOS and Android only
importantForLayout: boolean = false; // Web only
shouldRasterizeIOS: boolean = false; // iOS only
viewLayerTypeAndroid: 'none' | 'software' | 'hardware'; // Android only property
underlayColor: string = undefined; // iOS and Android only
useSafeInsets: boolean = false; // iOS only
```

### Methods
```
// The focus does not go outside the view with restrictFocusWithin by default,
// setFocusRestricted() allows to turn this restriction off and back on.
setFocusRestricted(restricted: boolean): void; // web only
setFocusLimited(limited: boolean): void; // web only
interface AlertOptions {
  icon?: string; // Web only
  theme?: AlertModalTheme;  // Web only
  rootViewId?: string;  // Web, ios, android only
}
backButtonEvent: SubscribableEvent<() => boolean>(); // (Android only)
setBackgroundColor(color: string, animated: boolean): void; // Android only
useCustomScrollbars(enable: boolean): void; // Web only
```

### Styling
```
elevation: number; // Android only
wordBreak: 'break-all' | 'break-word'; // Web only
appRegion: 'drag' | 'no-drag'; // Web only
cursor: 'pointer' | 'default'; // Web only
```

What's the harm in adding one more platform specific prop? 🤔 
@erictraut thoughts? :)

**Comment by kg-currenxie** [comment]
> To some extent, yes, we add custom props per platform where appropriate. The problem is that the type attribute on button shouldn't really apply to reactxp apps, since "forms" aren't a thing in ReactXP, so needing a type there shouldn't be applicable. Do you have a use for the type field outside of a FORM?

Maybe forms aren't a thing, but highly related to `Input`.

Are bounces a part of ReactXP? We'll yes, because people want to control it in iOS
 (`bounces: boolean = true; // iOS only`)
Is type part of ReactXP, it should because people want to control it on the Web? Same reason imo :)

**Comment by deregtd** [comment]
So here's the logic.  The additional props are designed to add flavor to a specific platform feature -- theming, accessibility, etc.  But in all those cases, the general fallback behavior of the control is still applicable across all platforms without the platform-specific properties.

Type= drastically changes the behavior of the <input field such that you can't be using type= on web and the same control on another platform in the same way.  So, given that your behavior is already web-specific, I'm confused why you want to bother using an RX control there, when you can just use an <input there instead?  If there's some case I'm missing here that makes it fit within the general logic/guidelines in my first paragraph, I'm/we're completely open to changing the behavior, but this request so far sounds like wanting to use RX for a web page.

And, to be clear, I'm using RX in a personal project that's only for web, because I like the animation and accessibility APIs that RX provides, but I freely mix RX and web-only components on that project to get my web-specific functionality where I want it.

Hope that makes sense.  Not trying to be a turd or anything, just sticking to base principles of the project. :)

**Comment by kg-currenxie** [comment]
Thanks for the explanation.

Yes, indeed we're using RXP for our react-native app, as well as our web site.

We chose RXP to be able to build a (mostly) single UI library that works for both (chosen over `react-native-web`).
I'm aware that we can (or maybe should) use a web (html) component where necessary, but ofc we want to minimize those cases.

In this case, a single prop is breaking the button case, where we instead are forced to implement a web and a RN specific component (basically duplicating 150 lines of code) :sob:

**Comment by deregtd** [comment]
That's what I'm trying to understand -- if it's really a cross-platform control, how does setting type= "fix" your case that works fine on RN?  If there's some cross-plat behavior we can work in here, I'm open to it.  But can you go into more detail on exactly what type= settings you're using, when, and why?

**Comment by kg-currenxie** [comment]
I guess the problem arises when mixing platform and non-platform. On the web side we wrap our forms in an actual `<form>`-tag, and then handling the enter-key event, which submit's that form-tag, which is then intercepted `<form onSubmit={...}`

**Comment by deregtd** [comment]
Yeah -- that's what I do across the board.  Use the RX controls everywhere, and catch the same keyboard interaction/submit behavior on all platforms.  When you start using desktop RN platforms, or a tablet, or a bluetooth keyboard attached to phone/tablet, you run into all kinds of edge cases where you wish you just had the same behavior on RN that you do on web.

**Comment by kg-currenxie** [comment]
Thanks for the discussion. We'll try going with that route :)
