### ISSUE TITLE
Popup does not shop up while using multiple node_modules

### ISSUE THREAD

**Issue by shengjie77** [Microsoft/reactxp#1037]
My project structure is like this
```
my-project
|--node_modules
|--src
|--components
    |--MyPopup
    |--Others
    |--node_modules
```
`MyPopup` which is imported from `compoennts` does not show up while i'm using it in `src`. That's because xp is using FrontLayerViewManager as singleton. And I got 2 node_modules which means 2 instance of FrontLayerViewManager. So RootView cannot receive event after invoking `Popup.show`.

**Comment by erictraut** [comment]
It sounds like you're instantiating ReactXP twice in the same app. That's going to break lots of things.

I'm not sure what "MyPopup" is or who packaged it. If it's an independently-packaged component, it should list reactxp as a peer dependency, not a regular dependency. Only your main app should have reactxp as a regular dependency.

**Comment by shengjie77** [comment]
Thx a lot!
