### ISSUE TITLE
create new app - crashed on android

### ISSUE THREAD

**Issue by hmheng** [Microsoft/reactxp#1038]
Dear team,

the freshly created app is crashed on android, cannot even run it up, but it is possible to run on web.
- Device: Samsung galaxy note 9 & asus zenfone 2 laser

**Comment by deregtd** [comment]
Are you able to do a generic react native app on android, and there's something specific about reactxp?

**Comment by hmheng** [comment]
yeap, generic react native works fine.




Best Regards,
Marvin

________________________________

**Comment by deregtd** [comment]
Interesting.  Mostly issues with that have had to do with not running adb reverse.

What's the crash?

**Comment by hmheng** [comment]
It did deploy to the phone. but when I start the app, it just crashed and stopped working. no further error. hmm.




Best Regards,
Marvin

________________________________

**Comment by gabeljz** [comment]
Hi, I encountered the same problem and had opened an issue - https://github.com/a-tarasyuk/create-rx-app/issues/12.

Currently, there is a suggested fix, https://github.com/a-tarasyuk/create-rx-app/issues/12#issuecomment-470458598.

I am still clarifying some questions with the maintainers though.

**Comment by erictraut** [comment]
This appears to be an issue with create-rx-app, not reactxp. Closing this issue.
