### ISSUE TITLE
RXPTest - APIs - Popup - Auto-dismissing popup doesn't auto-dismiss on web

### ISSUE THREAD

**Issue by sbeca** [Microsoft/reactxp#1040]
Testing the web version of RXPTest on:
- macOS 10.14.3
- Chrome 72.0.3626.121

Popup 3, which is supposed to auto-dismiss after 2 seconds, doesn't reliably auto-dismiss. Sometimes it does but the majority of the time it does not.

**Comment by erictraut** [comment]
Thanks for the report. I think this was a recently-introduced regression. I introduced a fix, which will appear in the next published version.
