### ISSUE TITLE
Disable user interaction with the view

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#1049]
Hi,

Is there any way to disable a user interaction with a view? `ignorePointerEvents` only applies to the specific view but then allows for pointer events in the children sub-views. I'd like to disable the entire sub-tree from receiving the clicks.

What we normally use is `pointer-events: none` but I can't apply it to the `View` because `ViewStyle` does not have such property as `pointerEvents` so I get a corresponding TypeScript error. I could of course `@ts-ignore` the `pointerEvents` property and it would even work on the web but it seems like a hack.

The reason why I need to disable the entire sub-tree is because I run animations when switching between views, that's precisely when I don't want users to interact with the views that are being animated.

By looking at the `blockPointerEvents`, it seems that it does exactly what I need but on mobile only. However, the underlying code for `blockPointerEvents` seems to actually toggle the internal `pointerEvents` flag. I wonder why not to extend the support to the web platform, given that it's about the same functionality.

**Comment by erictraut** [comment]
I presume that you want to prevent not only pointer events but also touch gestures? Your solution wouldn't work with touch gestures, and it wouldn't work on native platforms in general. 

One thought is to temporarily render a transparent child view that covers the entire view (i.e. is rendered last so it's the top-most child to be rendered). It would need to use absolution positioning with left, right, top and bottom set to 0.

That approach still won't prevent keyboard interactions, but it should prevent all mouse and touch interactions.

**Comment by pronebird** [comment]
>I presume that you want to prevent not only pointer events but also touch gestures? Your solution wouldn't work with touch gestures, and it wouldn't work on native platforms in general.

Correct. I'd like no user interaction to be allowed when animating the transition between two views.

>One thought is to temporarily render a transparent child view that covers the entire view (i.e. is rendered last so it's the top-most child to be rendered). It would need to use absolution positioning with left, right, top and bottom set to 0.

That's definitely a solution.

**Comment by aschultz** [comment]
ignorePointerEvents appears to be implemented for both RN and web. blockPointerEvents is currently RN-only, but would be very useful to have on web.

In particular, consider a component structured like so:
`<View>
    {this.props.children}
    <Decorator />
</View>`

where Decorator is absolutely positioned on top of the child elements and fills 100% width/height, but is semi-transparent (say, a gradient). Without blockPointerEvents, there's no easy way to mark the Decorator as transparent to clicks.

You could use ignorePointerEvents, but you'd have to manually apply it to every descendant of Decorator *and* you'd have to deal with interop for any non-ReactXP elements. That's basically a non-starter.

**Comment by aschultz** [comment]
ignorePointerEvents appears to be implemented for both RN and web. blockPointerEvents is currently RN-only, but would be very useful to have on web.

In particular, consider a component structured like so:
<View> {this.props.children} <Decorator /> </View>

where Decorator is absolutely positioned on top of the child elements and fills 100% width/height, but is semi-transparent (say, a gradient). Without blockPointerEvents, there's no easy way to mark the Decorator as transparent to clicks.

You could use ignorePointerEvents, but you'd have to manually apply it to every descendant of Decorator and you'd have to deal with interop for any non-ReactXP elements. That's basically a non-starter.
