### ISSUE TITLE
Animation incorrectly finishes immediately on web

### ISSUE THREAD

**Issue by sbeca** [microsoft/reactxp#1054]
Using the following example code:
```typescript
import React from 'react';
import RX from 'reactxp';

export class App extends RX.Component {
    animatedValue: RX.Animated.Value | undefined;
    animation: RX.Types.Animated.CompositeAnimation | undefined;

    componentDidMount(): void {
        this.animatedValue = new RX.Animated.Value(0);
        this.animation = RX.Animated.timing(this.animatedValue, {
            toValue: 2,
            duration: 10000,
            useNativeDriver: true
        });

        console.log('Start: ' + Date.now());
        this.animation.start(() => {
            console.log('Finish: ' + Date.now());
        });
    }

    render(): React.ReactNode {
        return (
            null
        );
    }
}
```

Running in an iPhone simulator I get what I would expect, i.e. the start and finish times are about 10000ms apart. For example:
```
Start: 1552523588474
Finish: 1552523598510
```

However, running it on the web I don't get what I would expect, and instead the animation seems to finish immediately. For example:
```
Start: 1552523605823
Finish: 1552523605824
```

My set up is:
- macOS 10.14.3
- Xcode 10.1
- iPhone X simulator, running iOS 12.1
- Web build running in Chrome 73.0.3683.75
- Dependences:
  -  "react": "16.6.3",
  -  "react-dom": "16.6.3",
   - "react-native": "0.58.6",
   - "reactxp": "1.6.0-rc.3",

**Comment by deregtd** [comment]
The web implementation has a "feature" that I don't know how much I like, wherein it tries to point out that you have a bug by, if the component you're animating a style for isn't yet mounted (i.e. the style's not bound to any mounted component), it immediately finishes the animation, since there's no work to do.  I don't remember the reasoning behind this decision, but @erictraut would.

In any event, if you first mount a component in your render function, then grab the ref in a ref callback, and then start the animation in the componentDidMount lifecycle function of your main component there, you should get the same 10-ish seconds.

**Comment by sbeca** [comment]
Hi @deregtd, thanks for the extra information. This "feature" isn't completely intuitive so would it be possible for ReactXP to throw a console warning or something when it happens, to help track down issues faster in the future?

For future reference, I was able to get native and web platforms to behave the same with the following code:
```typescript
import React from 'react';
import RX from 'reactxp';

export class App extends RX.Component {
    testRef: TestComponent | undefined;

    render(): React.ReactNode {
        return (
            <TestComponent ref={this._onRef} />
        );
    }

    private _onRef(ref: TestComponent): void {
        this.testRef = ref;
    }
}

export interface TestComponentState {
    animatedValue: RX.Animated.Value;
}

export class TestComponent extends RX.Component<RX.Types.CommonProps, TestComponentState> {
    animation: RX.Types.Animated.CompositeAnimation | undefined;

    constructor(props: Readonly<RX.Types.CommonProps>) {
        super(props);

        this.state = {
            animatedValue: new RX.Animated.Value(0)
        };
    }

    componentDidMount(): void {
        this.animation = RX.Animated.timing(this.state.animatedValue, {
            toValue: 1,
            duration: 10000,
            useNativeDriver: true
        });

        console.log('Start: ' + Date.now());
        this.animation.start(() => {
            console.log('Finish: ' + Date.now());
        });
    }

    render(): React.ReactNode {
        const { animatedValue } = this.state;

        const animatedStyle: RX.Types.AnimatedViewStyle = {
            opacity: animatedValue
        };

        return (
            <RX.View style={{ flex: 1 }}>
                <RX.Animated.View style={animatedStyle}>
                    <RX.Text>
                        Test Text
                    </RX.Text>
                </RX.Animated.View>
            </RX.View>
        );
    }
}
```

**Comment by erictraut** [comment]
ReactXP animations are meant to animate style attributes on mounted components. If used in other contexts, it is considered a programming error, and the results will be non-deterministic. ReactXP animations are _not_ meant to provide a general timing mechanism. If you need a timer, there are other well-defined ways to get that behavior.

The web animation support is implemented using CSS for performance reasons, which is why its behavior differs from what you see on RN.

**Comment by sbeca** [comment]
Sorry for the spam @deregtd, but I think I've found a deeper issue.

While the code I posted in my previous message worked for setting the `opacity` value, if I try to change it to set any `transform` values, it works on native platforms but finishes immediately on web.

Here is my example script that displays this issue:
```typescript
import React from 'react';
import RX from 'reactxp';

export class App extends RX.Component {
    testRef: TestComponent | undefined;

    render(): React.ReactNode {
        return (
            <TestComponent ref={this._onRef} />
        );
    }

    private _onRef(ref: TestComponent): void {
        this.testRef = ref;
    }
}

export interface TestComponentState {
    animatedValue: RX.Animated.Value;
}

export class TestComponent extends RX.Component<RX.Types.CommonProps, TestComponentState> {
    animation: RX.Types.Animated.CompositeAnimation | undefined;

    constructor(props: Readonly<RX.Types.CommonProps>) {
        super(props);

        this.state = {
            animatedValue: new RX.Animated.Value(0)
        };
    }

    componentDidMount(): void {
        this.animation = RX.Animated.timing(this.state.animatedValue, {
            toValue: 200,
            duration: 10000,
            useNativeDriver: true
        });

        console.log('Start: ' + Date.now());
        this.animation.start(() => {
            console.log('Finish: ' + Date.now());
        });
    }

    render(): React.ReactNode {
        const { animatedValue } = this.state;

        const animatedStyle: RX.Types.AnimatedViewStyle = {
            transform: [{ translateY: animatedValue }]
        };

        return (
            <RX.View style={{ flex: 1 }}>
                <RX.Animated.View style={animatedStyle}>
                    <RX.Text>
                        Test Text
                    </RX.Text>
                </RX.Animated.View>
            </RX.View>
        );
    }
}
```

**Comment by erictraut** [comment]
At first glance, this one looks like it should work fine. If you can't figure out the issue, let me know, and I'll debug it further.

**Comment by erictraut** [comment]
One issue is that you're not using the style creation API (RX.Styles.createAnimatedViewStyle), but I don't think that will matter in this case. 

Your code is similar to the "HelloWorld" ReactXP sample. Check out [MainPanel.tsx](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/src/views/MainPanel.tsx).

**Comment by sbeca** [comment]
Hi @erictraut, thanks for your help, you've hit the nail on the head.

If you don't use the style creation API (`RX.Styles.createAnimatedViewStyle`) then `RX.Styles._adaptStyles` won't be called which is needed to change `transform` styles into `animatedTransforms` and `staticTransforms` which is what `RX.Animated.AnimatedComponentGenerated._updateStyles` expects.

For future reference, I was able to get native and web platforms to behave the same with the following code:
```typescript
import React from 'react';
import RX from 'reactxp';

export class App extends RX.Component {
    testRef: TestComponent | undefined;

    render(): React.ReactNode {
        return (
            <TestComponent ref={this._onRef} />
        );
    }

    private _onRef(ref: TestComponent): void {
        this.testRef = ref;
    }
}

export interface TestComponentState {
    animatedValue: RX.Animated.Value;
}

export class TestComponent extends RX.Component<RX.Types.CommonProps, TestComponentState> {
    private animatedStyle: RX.Types.AnimatedViewStyleRuleSet;
    private animation: RX.Types.Animated.CompositeAnimation | undefined;

    constructor(props: Readonly<RX.Types.CommonProps>) {
        super(props);

        this.state = {
            animatedValue: new RX.Animated.Value(0)
        };

        this.animatedStyle = RX.Styles.createAnimatedViewStyle({
            transform: [{ translateY: this.state.animatedValue }]
        });
    }

    componentDidMount(): void {
        this.animation = RX.Animated.timing(this.state.animatedValue, {
            toValue: 200,
            duration: 10000,
            useNativeDriver: true
        });

        console.log('Start: ' + Date.now());
        this.animation.start(() => {
            console.log('Finish: ' + Date.now());
        });
    }

    render(): React.ReactNode {
        return (
            <RX.View style={{ flex: 1 }}>
                <RX.Animated.View style={this.animatedStyle}>
                    <RX.Text>
                        Test Text
                    </RX.Text>
                </RX.Animated.View>
            </RX.View>
        );
    }
}
```

**Comment by erictraut** [comment]
Great! Glad you god it working.
