### ISSUE TITLE
Image ResizeMode "cover" seems broken on the web

### ISSUE THREAD

**Issue by psegalen** [Microsoft/reactxp#106]
Hi,
I'm trying to add pictures on my ReactXP app in cover resize mode but it doesn't seem functional on the web, here is how it renders:
![image](https://cloud.githubusercontent.com/assets/3963529/26393769/29fb2666-406b-11e7-8ef3-edf754b90462.png)
As you can see, there's white space around the picture, it shouldn't as it is in cover resize mode which is supposed to fit the entire underlying div, am I right?

**Comment by erictraut** [comment]
@psegalen, I'm unable to repro this problem. It seems to be working fine for me. I added the following lines to the hello-world app (in MainPanel.tsx's render method):

<RX.Image
    style={ RX.Styles.createImageStyle({
        height: 200,
        width: 200
    }, false) }
    source='https://cdn.photographylife.com/wp-content/uploads/2016/01/Zabriskie-Point-Panorama-400-MP.jpg'
    resizeMode='cover'
/>

Here's what I see:
![screen shot 2017-05-24 at 11 13 03 am](https://cloud.githubusercontent.com/assets/7040122/26418674/f76e84ac-4071-11e7-9613-d2d064a60ff4.png)

Is it possible that you have horizontal padding? Or perhaps the space that you're seeing is actually part of your image?

Or perhaps it's a browser compat issue? I've tested on Safari and Chrome. Looks like you're using Chrome too?

**Comment by erictraut** [comment]
Ah, I just figured it out. We currently allow you to specify resizeMode as both a style attribute and a prop. If you pass it as a prop, it works correctly. If you pass it as a style attribute, it doesn't. I'm not sure why resizeMode is supported in both cases. It appears that we copied this from React Native. 

I think my preference is to remove the style attribute entirely and force everyone to use the prop instead. This would clean things up.

**Comment by erictraut** [comment]
I've made the change to Types.d.ts to eliminate the resizeMode as a style attribute. As I mentioned above, it's redundant and wasn't properly supported on web anyway.

**Comment by psegalen** [comment]
Great! I'll try it as soon as possible. Many thanks!

Le 24 mai 2017 8:28 PM, Eric Traut <notifications@github.com> a écrit :

I've made the change to Types.d.ts to eliminate the resizeMode as a style attribute. As I mentioned above, it's redundant and wasn't properly supported on web anyway.

**Comment by psegalen** [comment]
Works like a charm with the prop!
Thanks @erictraut!
