### ISSUE TITLE
RX.TextInput onBlur get bound value?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#1064]
In a `RX.TextInput` I have a value (it can also be empty and I would type a value), when I focus in the field, then blur it, I am trying to hook into the blur function and access the value onblur for validation:

```js
export default class TextInputTest extends RX.Component {
  onBlurTextInputValue(e) {
    alert("hi"); // works on blur
    alert(e); // returns [object Object] but how to access the value here from passed e
    alert(e.value); // undefined

    // Ensure string is over 5 characters on blur
    if(e.length < 6) {
        alert('Must be at least 5 characters on blur');
    }
  }

  render() {
    const text = "focus then blur me, I should alert my value on blur";

    return (
      <RX.View style={styles.wrapper}>
        <RX.TextInput
          ref={el => (this.textAreaTest = el)}
          value={text}
          onBlur={e => this.onBlurTextInputValue(this)}
          style={styles.textInput}
        />
      </RX.View>
    );
  }
}
```

[Here is a working example](https://codesandbox.io/s/k9xxrl12j5) [the component path is src->components->TextInputTest]

Any idea how to get the value from the onBlur event passed `(e)`?

**Comment by a-tarasyuk** [comment]
```typescript
e.target.value
```
?

what about using `state` to store `value`?

**Comment by MovingGifts** [comment]
@a-tarasyuk The state in the linked example works, but `e.target.value` didn't work. I know I used to access the value from the passed `e` however, not sure what happened or why I can't access the value off of the blur event anymore.

Shouldn't we be able to access it form there too?

**Comment by a-tarasyuk** [comment]
[`e.target.value`](https://codesandbox.io/s/w22vj388w7)

**Comment by MovingGifts** [comment]
So the pitfall was **this** (no pun intended):

`onBlur={e => this.onBlurTextInputValue(this)}`

when changing `this` to `e`:

`onBlur={e => this.onBlurTextInputValue(e)}`

It gives the correct text input value. Thank you for the quick responses @a-tarasyuk!
