### ISSUE TITLE
Add ReactXP as template in Visual Studio 2019/code

### ISSUE THREAD

**Issue by hmheng** [microsoft/reactxp#1067]
Since it is supported by Microsoft's Skype team, I would recommend to add ReactXP as cross platform template in VS. At the same time, to promote and encourage more usage too.

**Comment by erictraut** [comment]
Thanks for the suggestion. I can relay that idea to the VS team, but it would have much more impact coming directly from you and other developers directly. I recommend that you post your suggestion on the VS Code GitHub site and try to get it upvoted by others. The VS Code team is very responsive to developer inputs.

**Comment by hmheng** [comment]
I raised log to VSCode team. 
https://github.com/Microsoft/vscode/issues/71431

What about VS2019 team?

**Comment by geminiyellow** [comment]
i dont think we need a `template` in vs[c].
we can use `create-rx-app`  create a startkit and set it output folder to `public`, right?
or just include a git submodule.
