### ISSUE TITLE
Broken type definitions (reactxp-virtuallistview)

### ISSUE THREAD

**Issue by liron-navon** [microsoft/reactxp#1070]
I followed the setup from reactxp documentation, but typescript says it's wrong, it is called internally inside the library.

```
ERROR in [at-loader] ./node_modules/reactxp-virtuallistview/dist/VirtualListView.d.ts:48:89 
    TS2314: Generic type 'CommonStyledProps<T, C>' requires 2 type argument(s).
```

<img width="736" alt="Screen Shot 2019-03-28 at 23 11 16" src="https://user-images.githubusercontent.com/18119833/55193241-12ea9180-51af-11e9-9a39-d7b26d11ec64.png">

**Comment by erictraut** [comment]
Can you explain in more detail what you're trying to do and what steps you took?

The ReactXP [TodoList sample app](https://github.com/Microsoft/reactxp/tree/master/samples/TodoList) uses the reactxp-virtuallistview extension. I verified that the latest version builds and runs without errors.

**Comment by berickson1** [comment]
If you delete your local package and node_modules then start clean, you'll see the error. I'll have a PR out shortly to address

**Comment by liron-navon** [comment]
@berickson1 thanks!

For anyone looking at this, I added a flag to `tsconfig.json`, it solved those errors by ignoring modules type errors 🤷‍♀️.
```
"skipLibCheck": true
```
