### ISSUE TITLE
Any plans to release a new version?

### ISSUE THREAD

**Issue by MANTENN** [Microsoft/reactxp#1084]
I personally think this is an exciting project, and will solve the electron issue. It's a question of stability, and how easy it'll be to integrate React Native on Windows-it took me some time getting started. 

The last release was on 2017, as far as I know, Skype was rebuilt with ReactXP. I also noticed this project has a lot of contributors--2000. 

Any updates?

**Comment by mikehardy** [comment]
Not sure why the tags aren't pushed to github so the releases show up there, but it's active and is being shepherded nicely from what I can tell. There was a release recently.

https://www.npmjs.com/package/reactxp

**Comment by berickson1** [comment]
There are regular publishes of reactxp. Version history is tracked on the docs folder since there's multiple releases from the repo

https://github.com/Microsoft/reactxp/blob/master/docs/versions/version_history.md

**Comment by erictraut** [comment]
For historical reasons, we don't use the GitHub "releases" tab. All versions are documented on the [documentation site](https://microsoft.github.io/reactxp/versions/version_history.html).

I've just added a dummy GitHub release that points people there.

**Comment by brunolemos** [comment]
Curious to know why don't you do it on both places. At least the tags. People may get the impression the project is not active and discard it as an option.

**Comment by mikehardy** [comment]
...as a small side note there was some twittering today asking for the current best way to get more broad multi-platform support (as I know @brunolemos is currently twitter famous(tm) for :-) ) and the general public believes reactxp doesn't work with react-native 0.60+, which will erode userbase as well. I only mention it because I think that's a shame as it appears to be working well

**Comment by deregtd** [comment]
Interesting.  We're about to release a 2.0.0 final, so that's as good a time as any to make things known.  Any idea where the no-0.60+ belief is coming from, so we can address that at release time?

**Comment by mikehardy** [comment]
Was just idle/harmless twitter blather but the phrasing implying it didn't work with RN60 and no challenges https://twitter.com/browniefed/status/1196642397670662144 - at the same time the peer dependencies bands were just loosed :-), so "not working with >=0.60" is sort of baked in to the current public release https://github.com/microsoft/reactxp/commit/6eeaf420e2ef055d340612de99d792944c98e58f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L23

But more importantly - "about to release a 2.0.0" - sweet! Thanks guys

**Comment by deregtd** [comment]
Gotcha.  Okie, well, we'll make sure to list that specifically in the release notes for 2.0.0.  We've had several people test out the new rc.2 and had good success with it, so I don't think there's any pending issues after the one tiny post-rc.2 commit I made.  Probably in the next week one of us will find time to do all the heavy lifting to do the actual final release.
