### ISSUE TITLE
Building for MacOS

### ISSUE THREAD

**Issue by MaxBorsch** [microsoft/reactxp#1085]
In #19 @erictraut mentioned that MacOS support was mostly implemented. I can see that there's a `/src/macos` but I can't seem to find any documentation or build scripts for macos, and there's no mention of it in the README. Any help is appreciated- thanks!

**Comment by dynamicpacket** [comment]
I was looking for help on this as too. How can we "start:macos" and build for it as well? Please help us reactxp team, there are many people afraid to ask but wondering the same.

**Comment by deregtd** [comment]
So, the short version is that we developed it using what used to be the internal Microsoft port of react-native, and have been waiting for them to open-source their implementation that includes macos support.  It appears that they have done so:
https://github.com/Microsoft/react-native

In theory, if you switch the react-native package you're currently using over to the releases from the MS fork there, you should be able to start building macos projects with it.  

In _THEORY_, the only stuff you need to interface with it is to take an empty MacOS app, add react-native to it the same as if it were an ios app (use either cocoapods or the mess of including the source directly via projects), and then here's an example ViewManager implementation from one of our internal projects:

```
- (void)viewDidLoad
  {
    [super viewDidLoad];

#ifdef DEBUG
    NSURL *jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
    NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
    
    NSDictionary *launchOptions = @{};
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                           moduleName:@"RXApp"
                                    initialProperties:nil
                                        launchOptions:launchOptions];
    
    rootView.backgroundColor = [NSColor clearColor];
    [self.view addSubview:rootView];
    
    rootView.autoresizingMask = NSViewWidthSizable | NSViewHeightSizable | NSViewMinXMargin | NSViewMaxXMargin | NSViewMinYMargin | NSViewMaxYMargin;
    rootView.frame = self.view.bounds;
  }
```

**Comment by David-Melo** [comment]
@deregtd Thank you for this. I have been on the lookout for this.

I have been experimenting with your theories today and have encountered an obstacle, I was hoping you could help or if you had some insight.

While attempting to add Microsoft's react-native package into an empty MacOS app with cocoapods, I'm getting an error:

[!] The platform of the target `myreactxpapp` (macOS 10.14) is not compatible with `React/Core (0.58.6-microsoft.31)`, which does not support `osx`.

I looked at their branches and I see one named 51-macos. Could it be that MacOS support is not currently on their master branch? I opened an issue over there asking the same.

Thanks for your help on this. I appreciate it and I know many others do. We are excited at the possibilities. Thanks again.

**Comment by deregtd** [comment]
I'm actually not sure, since I've never used that branch, and I moved teams from where I was actively using the macos branch a couple months ago. :(

See if they can help you more or if you get radio silence and then I'll try to poke around and see what I can learn.

**Comment by acoates-ms** [comment]
The macos implementation is in master.  Its currently on RN 0.58.  -- We dont have any branches to support other versions currently.  We also haven't done any work to get things to work out of the box, since we often have our own internal tooling around its usage.

**Comment by deregtd** [comment]
My macos/ios combo app currently has this for its podfile, in case it helps:

# Targets for which we don't want to currently treat warnings
# as errors because the target has enough warnings that fixing
# them all will take some time.
# PLEASE DO NOT ADD TO THIS LIST. ONLY REMOVE FROM IT.
skip_treat_warnings_as_errors = [
  'React',
  'glog',
  'Folly',
  'DoubleConversion'
]

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if !skip_treat_warnings_as_errors.include?(target.name)
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'YES'
      end
      if skip_treat_warnings_as_errors.include?(target.name)
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
      end

      if target.name == 'React'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'RCT_MAIN_THREAD_WATCH_DOG_THRESHOLD=0.020' # seconds
        ]
      end
    end
  end
end

target 'AppIOS' do
  platform :ios, '10.0'
end

target 'AppMACOS' do
  platform :osx, '10.10'
end
