### ISSUE TITLE
RX.Animated: Does not play nice with Functional/Hooks based wrapping components.

### ISSUE THREAD

**Issue by fbartho** [Microsoft/reactxp#1086]
Using reactxp 1.6.0 & react-native 0.59.4 I made a trivial wrapper component that would fade in its children on present.
```typescript
export const FadeInView = ({
	duration,
	delay,
	children,
}: {
	duration: number;
	delay: number;
	children?: React.ReactNode;
}) => {
	const styleRef = useRef<
		ReturnType<typeof RX.Styles.createAnimatedViewStyle>
	>();

	useEffect(() => {
		const opacity = new RX.Animated.Value(0);
		styleRef.current = RX.Styles.createAnimatedViewStyle({
			opacity,
		});

		RX.Animated.timing(opacity, {
			toValue: 1,
			duration,
			delay,
			easing: RX.Animated.Easing.InOut(),
			useNativeDriver: true,
		}).start();

		// Starts the animation on mount or if duration, delay change.
	}, [duration, delay]);

	return (
		<RX.Animated.View style={styleRef.current}>{children}</RX.Animated.View>
	);
};
```

This component was passed delay/duration parameters, and I expected to see an animation.

What I actually got was "no animation", the component's children were instantly visible.

A roughly equivalent Class Based Component had no such problems:
```typescript
export class FadeInView extends React.Component<{
	duration: number;
	delay: number;
	children?: React.ReactNode;
}> {
	private opacityValue = new RX.Animated.Value(0);
	private opacityStyle = RX.Styles.createAnimatedViewStyle({
		opacity: this.opacityValue,
	});
	componentDidMount() {
		const { duration, delay } = this.props;
		RX.Animated.timing(this.opacityValue, {
			toValue: 1,
			duration,
			delay,
			easing: RX.Animated.Easing.InOut(),
			useNativeDriver: true,
		}).start();
	}
	render() {
		const { children } = this.props;
		return (
			<RX.Animated.View style={this.opacityStyle}>{children}</RX.Animated.View>
		);
	}
}
```

**Comment by berickson1** [comment]
I'm on mobile, so unable to test this theory but I believe your mutation of ref.current inside of useEffect is the cause of this.
When you render you access styleref.current, once mounted you replace styleref.current with a new value. React has no way to know this has changed. 

If you were to create the AnimatedValue and associated style outside of the useEffect function and only leave the RX.Animated.timing usage inside, I believe this would resolve your issue.

**Comment by fbartho** [comment]
@berickson1 -- so if I did that, I would need to call `opacityValue.setValue(0)` to reset it to zero instead of re-assigning it, if I understand you correctly?

Interesting. I'm still new to the right way to use `useEffect`/hooks so thanks!

I guess I thought useEffect firing would trigger a re-render / I thought useEffect happened synchronously on first load?

**Comment by fbartho** [comment]
That worked! Thanks for the hint @berickson1 

Final working implementation:
```typescript
export const FadeInView = ({
	duration,
	delay,
	children,
}: {
	duration: number;
	delay: number;
	children?: React.ReactNode;
}) => {
	const opacity = new RX.Animated.Value(0);
	const style = RX.Styles.createAnimatedViewStyle({
		opacity,
	});

	useEffect(() => {
		opacity.setValue(0);
		RX.Animated.timing(opacity, {
			toValue: 1,
			duration,
			delay,
			easing: RX.Animated.Easing.InOut(),
			useNativeDriver: true,
		}).start();

		// Starts the animation on mount or if duration, delay change.
	}, [duration, delay, opacity]);

	return <RX.Animated.View style={style}>{children}</RX.Animated.View>;
};
```

**Comment by fbartho** [comment]
In the interest of sharing my adventure in hooks, I realized that I still want to `useRef` for my value/styles, because otherwise every time they render due to parent-component behaviors, this would break the animation.

Final-final (hopefully) implementation:
```typescript
export const FadeInView = ({
	duration,
	delay = 0,
	children,
}: {
	duration: number;
	delay?: number;
	children?: React.ReactNode;
}) => {
	// useRef so that regardless of the re-renders of this component, the same value/style instances are used
	const opacityRef = useRef(new RX.Animated.Value(0));
	const styleRef = useRef(
		RX.Styles.createAnimatedViewStyle({
			opacity: opacityRef.current,
		}),
	);

	useEffect(() => {
		const opacity = opacityRef.current;

		// Reset the value, because this might have executed before
		opacity.setValue(0);

		// Trigger the animation
		RX.Animated.timing(opacity, {
			toValue: 1,
			duration,
			delay,
			easing: RX.Animated.Easing.InOut(),
			useNativeDriver: true,
		}).start();

		// Starts the animation on mount or if duration, delay change.
	}, [duration, delay]);

	return (
		<RX.Animated.View style={styleRef.current}>{children}</RX.Animated.View>
	);
};
```

**Comment by berickson1** [comment]
My understanding is that useEffect runs after every render completed but doesn't cause a re-render. It's effectively componentDidMount + componentDidUpdate

**Comment by MattTuring** [comment]
@fbartho Thank you so much for posting your hook solution, helped me understand how to use hooks in ReactXP as well as functional components, I feel like the docs don't cover either of these topics well.
