### ISSUE TITLE
Any overlap of reactXP with create-react-native-app?

### ISSUE THREAD

**Issue by QuantumInformation** [Microsoft/reactxp#109]
Seems like they are doing some nice stuff with https://github.com/react-community/create-react-native-app.

Could reactXP take advantage of it?

**Comment by berickson1** [comment]
@dabit3 created https://github.com/react-native-training/create-xp-app which seems similar. You should be able to leverage that.

**Comment by dabit3** [comment]
@QuantumInformation We're hoping to get some ideas to improve [Create-XP-App](https://github.com/react-native-training/create-xp-app/), feel free to submit an [issue](https://github.com/react-native-training/create-xp-app/issues) for any improvements you'd like to see!

We've just updated the repo to include the most up to date versions, at least to my knowledge.

**Comment by QuantumInformation** [comment]
So AFAIK there is no overlap between this project and https://github.com/react-community/create-react-native-app?
