### ISSUE TITLE
Any suggestions on implementing different HTML tags on the web?

### ISSUE THREAD

**Issue by maanishoo** [microsoft/reactxp#1097]
Any suggestions on implementing html tags such as h1, section, article, etc. on the web? 🤔

**Comment by erictraut** [comment]
Those are web constructs that have no analog in the world of cross-platform apps. My best advice is to not use them. Ask yourself what value (if any) they're providing in the web version of your app.

If it's not an option to avoid them, you could write your own ReactXP extension for each one. You would need to determine how each one maps to a corresponding native UI element for all platforms your app supports. On the web, it could emit the corresponding tag. It's significant work — especially if there are accessibility considerations with any of the elements.

**Comment by alexstanbury** [comment]
I presume this is required due to SEO, H1, H2 etc are important for that. I am going to look into writing an extension that allows specifying what html tag to output for the web version as an attribute on the `<RX.Text>` tag.
