### ISSUE TITLE
[Question] Does React Xp supports Android and Apple tv?

### ISSUE THREAD

**Issue by canyavall** [microsoft/reactxp#1099]
We are checking options for an hybrid app and ReactXp is one of the possible options. We would like to know if it supports Android TV and Apple TV

Thank you ^_^

**Comment by mikehardy** [comment]
I have built for those targets and the build works, but I have not attempted to use the functionality myself. I've seen ReactXP pay more attention to accessibility than most projects though so maybe trying out the todolist sample (for functionality test) and/or the RXPTest (used for unit tests mostly) and checking is the best path. They are both right in the repo
