### ISSUE TITLE
react-addons-perf is in web prod build

### ISSUE THREAD

**Issue by necolas** [Microsoft/reactxp#11]
`react-addons-perf` looks like it's ending up in production builds, as I experienced a build error when the package was not a peerDependency

```
ERROR in ./~/reactxp/dist/common/Profiling.js
Module not found: Error: Cannot resolve module 'react-addons-perf' in /path-to-app/node_modules/reactxp/dist/common
 @ ./~/reactxp/dist/common/Profiling.js 15:11-39
```

**Comment by erictraut** [comment]
There's currently no separate build of ReactXP for production versus development, so there's no way to conditionalize this at runtime. I'm tempted to just remove the Profiling class altogether (or repackage it as a ReactXP extension) because it's not really in keeping with the ReactXP philosophy.

**Comment by erictraut** [comment]
OK, I've removed the Profiling class altogether - along with the dependency on react-addons-perf.
