### ISSUE TITLE
[VirtualListView] Items disappear when scrolling 

### ISSUE THREAD

**Issue by novi-kolacic** [microsoft/reactxp#1100]
Hi there,

I am using the latest version of VirtualListView - 2.0 and when I am trying to scroll up/down, the items in the list are disappearing. 

**Device:**
Samsung Galaxy Tab A 10.1"
Android 8.1

This is my dependency list: 

`"dependencies": {
    "lodash": "4.17.11",
    "react": "16.6.3",
    "react-dom": "16.6.3",
    "react-native": "0.58.6",
    "react-native-windows": "0.57.1",
    "reactxp": "1.6.1",
    "reactxp-navigation": "1.6.1",
    "reactxp-virtuallistview": "2.0.0",
    "resub": "1.0.13",
    "simplerestclients": "0.2.7",
    "synctasks": "0.3.3",
    "prop-types": "15.7.2"
  }`

There are two cases : 

1. When `skipRenderIfItemUnchanged` is set to `false` and when `animateChanges` is set to `false`.

First time when I open the screen with the list, if I try to scroll, items will disappear. But if I click on some item, after that scrolling will be normal and items won't disappear. (invisible items will be back in normal state)

**List:** 

<img width="513" alt="Screen Shot 2019-05-31 at 3 51 53 PM" src="https://user-images.githubusercontent.com/51246101/58731163-0c99b100-83bc-11e9-99a4-68570fb2b4cd.png">

**Items from store:**

<img width="558" alt="Screen Shot 2019-05-31 at 3 49 17 PM" src="https://user-images.githubusercontent.com/51246101/58731084-d6f4c800-83bb-11e9-91ee-e743f19b138a.png">

**Render item:**

<img width="1038" alt="Screen Shot 2019-05-31 at 3 48 51 PM" src="https://user-images.githubusercontent.com/51246101/58731044-c04e7100-83bb-11e9-95c3-168e56d0f06b.png"> 

2. When `skipRenderIfItemUnchanged` is set to `true` and when `animateChanges` is set to `true`.

First time when I open the screen with the list, if I try to scroll, items will disappear. After that, if I try to click on some item, other items will stay invisible.

**Note:** Both problems won't happen if `onPress()` is set to Root view, but I don't want that as it is possible to use `onItemSelected` provided by `VirtualListView`.

Any ides? Thanks!

**Comment by erictraut** [comment]
@berickson1, any thoughts on this one?

**Comment by berickson1** [comment]
I altered the TodoList sample to look basically like what you have (see below) & am unable to reproduce the issue. Can you provide an example that I can run locally?
<img width="370" alt="Screen Shot 2019-07-17 at 2 52 28 AM" src="https://user-images.githubusercontent.com/1418465/61366498-8b4c8f80-a83e-11e9-8a1b-1f0cd7308dcd.png">

<img width="832" alt="Screen Shot 2019-07-17 at 2 56 02 AM" src="https://user-images.githubusercontent.com/1418465/61366489-87207200-a83e-11e9-9e41-21dfe563e639.png">

**Comment by fbartho** [comment]
@novi-kolacic -- is this still a concern? I'm going to close this since you never replied to @berickson1's request for clarification. But please feel to reply back, and I'm happy to reopen it!
