### ISSUE TITLE
server side rendering support

### ISSUE THREAD

**Issue by alidcastano** [microsoft/reactxp#1105]
related to #201

browser dependencies aside, you still need a way to extract the style element / css on the server 

linking rnw web API for this for reference: https://github.com/necolas/react-native-web/blob/master/docs/guides/server-side-rendering.md

**Comment by erictraut** [comment]
This use case is pretty far afield of what ReactXP was designed for. Some of the classes in ReactXP are stateful, so I don't know if this is really feasible.
