### ISSUE TITLE
Ondrag method cannot working android,windows and ios

### ISSUE THREAD

**Issue by ganesanrbt** [microsoft/reactxp#1108]
I am using ondrag,ondragstart and ondragend using RX.View.It cannot work the method.How to solve the problem?

**Comment by erictraut** [comment]
We're going to need more information to diagnose your problem. What symptom are you seeing? Are you able to post some sample code?

**Comment by erictraut** [comment]
The drag events are documented as being specific to mouse-based platforms. They are not implemented on iOS and Android. They should work fine on Windows, MacOS and Web.

**Comment by fbartho** [comment]
I'm going to close this question since the documentation covers it!

Alternatively if there's a clear way to implement this so it works on iOS/Android/Windows, please reply back, and we can turn this into a feature request!
