### ISSUE TITLE
Suggestion: yarn start should be included as a start script

### ISSUE THREAD

**Issue by kg-currenxie** [microsoft/reactxp#1111]
With RN, I always only use `yarn start` to start the metro bundler, and go to XCode and go to `Product / Perform Action / Run without building`. This saves 1-2 minutes of build time that `yarn run:ios` does.

You should include a normal `yarn start` script by default (generated by using create-xp-app), to make it more familiar to RN devs switching to RN-XP :)

I guess `yarn run rn-cli start` is the same, but still..

**Comment by mikehardy** [comment]
I’m not sure this should be recommended, it’s an optimization but for me anyway it breaks ios9 (which must have a bundle in place / cannot use the dev server) if it were enabled by default. For people that want performance you should set the environment variable SKIP_BUNDLING to achieve the performance boost while still maintaining a “works everywhere” default stance https://github.com/facebook/react-native/pull/14731

**Comment by erictraut** [comment]
You're welcome to create any scripts you'd like within your own projects. I don't think it makes sense to add this to the reactxp sample apps.

**Comment by kg-currenxie** [comment]
Didn't know it broke ios9 :D And haven't seen SKIP_BUNDLING before. Thanks guys.
