### ISSUE TITLE
GestureView pan events don't trigger on mobile web

### ISSUE THREAD

**Issue by thegalah** [microsoft/reactxp#1115]
To reproduce this you can deploy to a website and view it from the mobile browser or simply open chrome inspector tools and toggle device toolbar to on. Now non of the pan gestures work or are detected.

- "reactxp": "1.5.0"
- "react-native": "0.57.8"

**Comment by erictraut** [comment]
Yes, pan events are not implemented for the web platform. Contributions are welcome. This hasn't been a priority for the core reactxp contributors because we've assumed that anyone who wants to implement more sophisticated touch-based gestures on mobile will build a native Android or iOS app.

**Comment by deregtd** [comment]
Implemented in #1167 .  Will be available when merged/released. :)
