### ISSUE TITLE
[Docs] URL for Navigator extension returns NetInfo docs

### ISSUE THREAD

**Issue by JonathanReiss15** [microsoft/reactxp#1122]
The URL: [https://microsoft.github.io/reactxp/docs/extensions/navigator.html](https://microsoft.github.io/reactxp/docs/extensions/navigator.html) returns the docs for NetInfo instead of Navigator

![image](https://user-images.githubusercontent.com/5341402/61741115-09c89600-ad45-11e9-8de2-6186aa82a6ca.png)

**Comment by erictraut** [comment]
Thanks for the bug report. It's now fixed.
