### ISSUE TITLE
MetroBundler error

### ISSUE THREAD

**Issue by octane92** [microsoft/reactxp#1130]
I'm unable to run the TodoList sample. It worked before, but now I get an error in Metro Bundler and the app fails to load on android.

Steps:

- Cloning master branch.
- In samples/TodoList folder running: npm install, npm run start-android, npm run start.
- Running adb command: adb reverse tcp:8081 tcp:8081
- Opening samples/TodoList/android folder in Android Studio.
- Building & starting app in Android Studio.

When loading the app, Metro bundler shows the following error:

> error: bundling failed: Error: Unable to resolve module `./temp/android/rnapp/js/app/AppBootstrapperNative.js` from `E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\index.android.js`: The module `./temp/android/rnapp/js/app/AppBootstrapperNative.js` could not be found from `E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\index.android.js`. Indeed, none of these files exist:
>   * `E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\temp\android\rnapp\js\app\AppBootstrapperNative.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
>   * `E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\temp\android\rnapp\js\app\AppBootstrapperNative.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
>     at ModuleResolver.resolveDependency (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
>     at ResolutionRequest.resolveDependency (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
>     at DependencyGraph.resolveDependency (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
>     at Object.resolve (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\lib\transformHelpers.js:261:42)
>     at dependencies.map.result (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)
>     at Array.map (<anonymous>)
>     at resolveDependencies (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
>     at E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
>     at Generator.next (<anonymous>)
>     at asyncGeneratorStep (E:\Work\Workspace\reactxp_development\reactxp_test\reactxp\samples\TodoList\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)

There is no "AppBootstrapperNative.js" file in the "./temp/android/rnapp/js/app" folder.
Tried with shorter path, cloning into my root folder, same error occurred.

Nothing changed on my system since it last worked. I installed the [react-native-qrcode-scanner package](https://github.com/moaazsidat/react-native-qrcode-scanner) in another sample project when I noticed the above Metro Bundler error, and tried with a fresh clone, that produced the same error.

**Comment by mikehardy** [comment]
I think that sample uses typescript and gulp for bundling so some pre-run step seemed to not work? 

I just rebased to master in my local checkout and I cannot reproduce, following the documented README steps worked for me

**Comment by octane92** [comment]
The pre-run steps show no error on console, all of them finishes, and watching for changes in the typescript files starts. But yes, it will be something with some pre-run steps, when compiling the typescript code and copying the js files to the temp/android folder.
