### ISSUE TITLE
Unable to run npm start:ios

### ISSUE THREAD

**Issue by tonystaark** [microsoft/reactxp#1133]
Hi, I have a problem in running npm start:ios . However, I don't have any problem when executing the web version. Here is the screenshot that shows the error. How to resolve?
<img width="1280" alt="Screen Shot 2019-08-29 at 11 21 30 AM" src="https://user-images.githubusercontent.com/16837659/63907863-9c98d680-ca4f-11e9-9899-86e21b8a5949.png">

**Comment by mikehardy** [comment]
second link http://www.seanbehan.com/how-to-fix-xcrun-error-unable-to-find-utility-instruments-not-a-developer-tool-or-in-path/ from https://duckduckgo.com/?q=xcrun+error+unable+to+find+utility+instruments&ia=web looks right on

**Comment by tonystaark** [comment]
Appreciate. Thanks

**Comment by tonystaark** [comment]
Hi I have gotten rid of previous error after fixing according to the link you provided but now new error came up. 
<img width="1280" alt="Screen Shot 2019-08-29 at 4 14 03 PM" src="https://user-images.githubusercontent.com/16837659/63922959-455b2c00-ca78-11e9-8d0c-280d34399625.png">

**Comment by mikehardy** [comment]
I would follow the standard react native documentation for a cli quickstart using React-native 0.59 until that worked searching stackoverflow and docs for answers until it worked. Then I'd try reactxp which is a layer on top and only works once react native is working

I'd use reactxp 1.x versions as well

**Comment by tonystaark** [comment]
I noticed that when I git clone this repo and copy the sample out by following the guides at  https://microsoft.github.io/reactxp/ , I will get the above error when I tried to run in ios environment .

But it turned out to be okay if I create a whole new project by doing `npx create-rx-app my-project-name`.
