### ISSUE TITLE
Using ReactXP with Expo

### ISSUE THREAD

**Issue by tonystaark** [microsoft/reactxp#1134]
Hello, I have been searching everywhere but cant seem to find the relevant info. The boilerplate of reactXP provided here supports running IOS and Android in their own simulators. But what if I want to get Expo running in ReactXP, is it possible to do so?

**Comment by mikehardy** [comment]
well ReactXP doesn't contain any native code itself, which is typically the barrier with Expo. So I imagine it would be possible but welding them together might be challenging. I have no direct Expo experience except as a maintainer on other react-native libraries with regard to the native-code-or-not question - that always gets the answer that you need to eject and use ExpoKit but, not the case here

**Comment by fbartho** [comment]
@tonystaark -- I think you can just import RX and start using it. Just like any other 3rd party JS library! Are you running into any issues?
