### ISSUE TITLE
Popup ignores keyboard changes

### ISSUE THREAD

**Issue by liorJuice** [microsoft/reactxp#1136]
the popup interface doesn't seem to change the placement of the popup when the keyboard opens, even if the keyboard covers it.  this is rather weird seeing it does redraw the popup on page resize on the web.
this happens on both ios and android.

**Comment by erictraut** [comment]
This is expected behavior. If your app changes its page size in response to keyboard open events, the popup will be repositioned. If you don't change the page size when the keyboard opens, the keyboard may overdraw the popup.

**Comment by liorJuice** [comment]
thanks for the answer.
can you elaborate more on how to do this?
i couldn't get it to work.
it would be very useful to document this in the popup service documentation.
