### ISSUE TITLE
Using native import() function

### ISSUE THREAD

**Issue by rpunkfu** [microsoft/reactxp#1137]
Hi folks, thanks a lot for this library! 👍 

I've a problem making browser's native `import()` function work when using it.
I know I should use `webpackIgnore` directive but it doesn't work:
```
await import(/* webpackIgnore: true */FOO_URL)
```

After running this code, I get this error: 
```
Uncaught (in promise) Error: Cannot find module 'http://127.0.0.1:6502/foo.js'
```

Is there something overriding this `webpackIgnore` directive in reactxp?

**Comment by deregtd** [comment]
Nope...  Didn't even know there was such a thing as an import function in the browser.

**Comment by rpunkfu** [comment]
I've resolved this issue by changing the `.ts` parser options in webpack's config:
`{ test: /\.tsx?$/, loader: 'babel-loader', include: APP_PATH, parser: { import: false } }`
