### ISSUE TITLE
Web - Detect if touch device?

### ISSUE THREAD

**Issue by MovingGifts** [microsoft/reactxp#1138]
Is there is a built-in way to check if the current device accessing the reactxp app is a touch device?

**Comment by deregtd** [comment]
You have to unfortunately decide what this means for yourself, as there's a huge hybrid range between "fully touch" and "fully keyboard".  What is a surface book?  What is an iPad with a usb keyboard and mouse?  etc.

FWIW, in my apps I have a simple mouse-detecting resub store where the root view has an onmousemove event, and if it ever gets the event, it flicks the store to "mouse available" mode and the UI updates appropriately, but by default it assumes touch-only until it gets a signal that a mouse exists.

**Comment by MovingGifts** [comment]
Thanks for the quick response! Sounds good, I just wanted a confirmation that it's not built in. That's a pretty cool way of doing it, thank you for sharing. Cheers!

**Comment by deregtd** [comment]
Yeah -- it's enough of a nuanced problem that we wanted to make people think about it a little bit, as there is really no one-size-fits-all approach here at all. :)
