### ISSUE TITLE
Sample TODOList doesn't work...

### ISSUE THREAD

**Issue by dahersoftware** [microsoft/reactxp#1142]
I am a new developer in Mobile/Web development and I was really excited about reactXP.
After searching a lot on internet I couldn't see even a single app example and code repo sample example (ToDoList ) doesn't work, It has a lot of typescript errors. Although creating a new app using 
create-rx-app AppName worked fine.

Is it possible to get a bug free sample code examples? Any other article reference that explains the basic components of using ReactXP. For example there is no clear description of what would be your main entry point for cross platform app until I figured out looking inside the code (setMainView). I am not complaining here but If basic entry points are clear then more people can try to understand the library and a few of them can contribute too.

**Comment by berickson1** [comment]
I'm not seeing any compiler errors after doing a clean checkout - can you provide more details?

See my console output below - I can also successfully compile with start-android
```
Mbp:TodoList berickson$ rm -rf node_modules/
Mbp:TodoList berickson$ npm run start-web

> todolist@2.0.0-rc.1 start-web /src/reactxp/samples/TodoList
> npm install && npm run gulp-web


> fsevents@1.2.9 install /src/reactxp/samples/TodoList/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download
[fsevents] Success: "/src/reactxp/samples/TodoList/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" is installed via remote

> core-js@3.1.4 postinstall /src/reactxp/samples/TodoList/node_modules/@babel/register/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.9 postinstall /src/reactxp/samples/TodoList/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.1.4 postinstall /src/reactxp/samples/TodoList/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 1679 packages from 780 contributors and audited 80121 packages in 32.345s
found 3064 vulnerabilities (23 low, 3041 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> todolist@2.0.0-rc.1 gulp-web /src/reactxp/samples/TodoList
> cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=web

[08:23:09] platform: web
[08:23:09] developer mode: enabled
[08:23:09] source maps: true
[08:23:09] Using gulpfile /src/reactxp/samples/TodoList/gulpfile.js
[08:23:09] Starting 'run'...
[08:23:09] Starting 'clean'...
[08:23:09] Finished 'clean' after 21 ms
[08:23:09] Starting 'copy'...
[08:23:09] Finished 'copy' after 101 ms
[08:23:09] Starting 'build'...
[08:23:09] Starting 'copy'...
[08:23:09] Finished 'copy' after 77 ms
[08:23:09] Starting 'compile-rn'...
[08:23:09] Finished 'compile-rn' after 434 μs
[08:23:09] Finished 'build' after 78 ms
[08:23:09] Starting 'apply-aliases'...
[08:23:09] Finished 'apply-aliases' after 5 ms
[08:23:09] Starting 'watch'...
[08:23:09] Finished 'watch' after 3.6 ms
[08:23:09] Starting 'webpack-js-watch'...

webpack is watching the files…

[BABEL] Note: The code generator has deoptimised the styling of /src/reactxp/samples/TodoList/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
Hash: 309e1835e26dac701e01
Version: webpack 4.35.3
Time: 10835ms
Built at: 09/11/2019 8:23:22 AM
     Asset      Size  Chunks             Chunk Names
    app.js  2.66 MiB    main  [emitted]  main
app.js.map  4.36 MiB    main  [emitted]  main
Entrypoint main = app.js app.js.map
```

**Comment by mikehardy** [comment]
I might have some recent insight on this - if you pull master right now and use yarn, it does not compile. There are typescript errors (mentioned in #1141 side note)

If you use npm it will respect package-lock.json (yarn will not) and there must be something in the versions that don't work.

So I'm going to guess here: @dahersoftware - were you trying to use npm?

And as for examples it might be that the TodoList is sufficient as I didn't see anything else on the web, but when I built my project (closed source, sorry) it was fully sufficient for me.

**Comment by dahersoftware** [comment]
@mikehardy & @berickson1 Thank you for quick reply. Mike yes I am using npm, I will try that with yarn also I will explore TodoList more and come back with questions.

**Comment by mikehardy** [comment]
I apologize as I think I misspoke at first and then edited: npm works for me, yarn does not, right now on master. So if you were already using npm perhaps there will be no change. My hunch was that package-lock.json contained an interlocking set of dependencies that works, whereas a clean install using just the semver ranges does not (based on the errors I saw). My hunch might be wrong. Either way the TodoList really was a great starter in my case at least. Good luck

**Comment by dahersoftware** [comment]
@berickson1  I removed node module and I got these errors:

[BABEL] Note: The code generator has deoptimised the styling of /Users/vkumar/reactXP/reactxp/samples/TodoList/node_modules/react-dom/cjs/react-dom.development.js as it exceeds the max of 500KB.
Hash: bc647fa96ca05fcda989
Version: webpack 4.35.3
Time: 11252ms
Built at: 09/11/2019 9:13:38 PM
     Asset      Size  Chunks             Chunk Names
    app.js  2.66 MiB    main  [emitted]  main
app.js.map  4.36 MiB    main  [emitted]  main
Entrypoint main = app.js app.js.map

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperNative.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperNative.tsx(34,15)
      TS2416: Property '_getInitialUrl' in type 'AppBootstrapperNative' is not assignable to the same property in base type 'AppBootstrapper'.
  Type '() => Promise<string | undefined>' is not assignable to type '() => STPromise<string | undefined>'.
    Type 'Promise<string | undefined>' is not assignable to type 'STPromise<string | undefined>'.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperNative.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperNative.tsx(35,9)
      TS2741: Property '[Symbol.toStringTag]' is missing in type 'STPromise<string | undefined>' but required in type 'Promise<string | undefined>'.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperWeb.tsx
./src/ts/app/AppBootstrapperWeb.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/app/AppBootstrapperWeb.tsx(38,15)
      TS2416: Property '_getInitialUrl' in type 'AppBootstrapperWeb' is not assignable to the same property in base type 'AppBootstrapper'.
  Type '() => Promise<string | undefined>' is not assignable to type '() => STPromise<string | undefined>'.
    Type 'Promise<string | undefined>' is missing the following properties from type 'STPromise<string | undefined>': always, done, fail, thenAsync, and 3 more.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx
./src/ts/controls/Modal.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx(212,1)
      TS1005: ',' expected.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx
./src/ts/controls/Modal.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx(213,1)
      TS1005: '}' expected.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx
./src/ts/controls/Modal.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx(89,9)
      TS2722: Cannot invoke an object which is possibly 'undefined'.

ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx
./src/ts/controls/Modal.tsx
[tsl] ERROR in /Users/vkumar/reactXP/reactxp/samples/TodoList/src/ts/controls/Modal.tsx(116,9)
      TS2722: Cannot invoke an object which is possibly 'undefined'.

**Comment by mikehardy** [comment]
I just reproduced this locally. It's the result you get if you are on reactxp.git#master right now. I saw those errors with `npm run start-android` Seems TodoList is out-of-sync somehow with that SyncTasks PR?

When I run `git co cd48a4b19c9d8963cf1b25eb4ca582dc7ef2a75e` (equivalent to 2.0.0-rc.1 tag` then do `npm run start-android` it worked for me.

**Comment by berickson1** [comment]
Oh, I see what you mean - the samples are up to date with the latest unpublished version of reactxp, which had a breaking change.  For now, follow @mikehardy 's suggestion and go back a couple commits
