### ISSUE TITLE
RX.Image.getMetadata

### ISSUE THREAD

**Issue by alariej** [microsoft/reactxp#1144]
I was hoping to use RX.Image.getMetadata to obtain the size of a local image. I am currently testing on Android. Using parameter url = "content://com.android.providers.downloads.documents/document/531", I get what seems to be a RN error: "Unsupported uri scheme for encoded image fetch!".

However, the same url works perfectly in the RN function Image.getSize, which seems to be the function exposed by getMetadata.

Any reason why a local url would not work here?

**Comment by berickson1** [comment]
`RX.Image.getMetadata` first calls `RN.Image.fetch` to prefetch the item and ensure it's in the cache. My guess is that `RN.Image.fetch` doesn't support callig with local URIs, If you try calling `RN.Image.fetch` with your local URI, do you get the same error?

**Comment by mikehardy** [comment]
without thinking deeply on it: a FileProvider config issue? Just reminds me of them - I have info here https://github.com/mikehardy/react-native-update-apk#manual-steps-for-android

apologies if this is completely unrelated or you've already nailed FileProviders

**Comment by alariej** [comment]
Yes, I do get the error when calling `RN.Image.prefech` (no "fetch" in my RN version) with local URIs. You can actually imply this from the RN function definitions (uri vs. url):

`static getSize(uri: string, success: (width: number, height: number) => void, failure: (error: any) => void): any;`
`static prefetch(url: string): any;`

I guess I will keep using `RN.Image.getSize` for the mobile platforms, and will find a solution for the other ones.
