### ISSUE TITLE
RX.Linking.deepLinkRequestEvent does not trigger

### ISSUE THREAD

**Issue by alariej** [microsoft/reactxp#1150]
I am testing incoming deep linking on Android with the goal of being able to share images from the Gallery app to my RX app. The code in my app is:
```
RX.Linking.deepLinkRequestEvent.subscribe(event => {
   console.log(event);
   // do something here
});
```
The intent in AndroidManifest.xml is:
```
<intent-filter>
   <action android:name="android.intent.action.SEND" />
   <category android:name="android.intent.category.DEFAULT" />
   <data android:mimeType="image/*" />
</intent-filter>
```
I also added `android:launchMode="singleInstance"` as an activity parameter to ensure that the launched instance is the one with the already subscribed event.

The app instance launches correctly from the background when clicking the app icon in the "Share via" menu in the Gallery app, but the deepLinkRequestEvent never triggers.

My code is in the same section with `RX.App.activationStateChangedEvent` and `RX.Network.connectivityChangedEvent`, which both trigger correctly on their respective events.

Am I missing something on how to implement deep linking with ReactXP?

**Comment by mikehardy** [comment]
I help maintain react-native-firebase which also has linking functionality, and it's very difficult for people to set up correctly. I think you might want singleTop vs singleInstance and you have to be careful that your MainActivity is actually the LAUNCHER one (e.g., if you integrate with react-native-splash-screen or similar the default guides there have you set up a different activity and it breaks the intent data passing chain).

I'd suggest posting the whole AndroidManifest if possible or at least all the relevant bits from outer XML container down to the application and activity

**Comment by mikehardy** [comment]
Hmm - seems fine except maybe try singleTop or singleTask vs singleInstance (though a final setting should be considered carefully - easy to switch for a test)

I would not recommend react-native-firebase only to handle links, it's a sledgehammer for a fly in that scenario. I'm not aware of any comprehensive guides and unfortunately that's a support burden for react-native-firebase so if you find any that would be useful

**Comment by alariej** [comment]
Quick feedback on this issue. I ended up using ReactContext with a React module called DeviceEventManagerModule for emitting events out of MainActivity.java.

In the ReactXP app, I use the React Native module DeviceEventEmitter with the addListener() function.

This allows to listen to incoming intents of various MIME types, such as image, application, text, etc.

I did set the launch mode to singleTask in AndroidManifest.xml.

Still, I imagine that RX.Linking was meant to bring this functionality within ReactXP directly, so I wonder why it doesn't work.

**Comment by fbartho** [comment]
We've had deepLinking working with ReactXP in our app for 3 years on iOS/Android.

I don't know exactly what you're struggling with @alariej -- could you respond back if this is still a problem for you?

For now, I'm going to close this ticket as it has been a year, but please let me know if we should reopen?

**Comment by alariej** [comment]
I am still using the solution I mentioned above (https://github.com/microsoft/reactxp/issues/1150#issuecomment-552104729), and I haven't looked further at this issue. Once again, I am looking for incoming intents of various MIME types (images, files, etc.) on Android and according to the ReactXP documentation, the appropriate RX.Linking event should be `deepLinkRequestEvent`. Unfortunately, there is no example for it, neither in the doc nor in the ReactXP samples. @fbartho, it would be great if you could provide a working example from your app. I would rather use a ReactXP solution than the RN one I currently use.

**Comment by fbartho** [comment]
@alariej here is my code-sample, it's really trivial though:

```typescript
/** Globally hook in for catching deep links that were used to open the app */
RX.Linking.getInitialUrl().then((url) => {
	if (url) {
		// Shove the link in breadcrumbs, it will be dispatched when we resolve
		// from unknown/firstLaunch to logged-in/logged-out
		synchronouslyPushBreadcrumbBatch(
			makeBreadcrumbBatch({ route: RouteKey.deepLink, params: { url } }),
		);
	}
});

/** Handle DeepLinks that arrive while the app is *already* running */
RX.Linking.deepLinkRequestEvent.subscribe((url: string) => {
	if (url) {
		NavigationService.navigate(RouteKey.deepLink, { url });
	}
});
```

I think you should debug "Deep Linking on React-Native" in general, within your app. -- If it works with RN's Linking, then it should work with ReactXP.

Separately though, I don't think I exactly understand `incoming intents of various MIME types` -- if you're trying to handle raw File Shares, or other native intents, I don't think React-Native supports that as part of their DeepLinking API (heck I didn't know that they supported it at all) -- I could easily be wrong here.

I think `deepLinkRequestEvent` is only about traditional URL deep-linking (today).

**Comment by alariej** [comment]
I think you are right. Deep linking in RN only applies to URL's. In my case I need to "link" other types of request (image / file sharing) coming from 3rd party apps. I guess RX.Linking is not the right tool for that. In any case thanks for looking at this.
