### ISSUE TITLE
Using timing animations breaks jest snapshots

### ISSUE THREAD

**Issue by st-currenxie** [microsoft/reactxp#1168]
We are using a timing animation in our button component and generate snapshots from our Storybook stories by using the storyshots addon.

When we generate our snapshots we get the following error when we are using the timing animation: _Cannot set property 'transform' of undefined_.

Any thoughts on this particular issue?

**Comment by deregtd** [comment]
Off hand, I can only assume that the mocks they're using aren't properly creating a style property.  Can you track down where in the reactxp code it's exceptioning just to validate?

**Comment by fbartho** [comment]
Is this still a concern @st-currenxie? Like @deregtd mentioned, I don't think this is something that ReactXP is breaking, but rather that when using jest, lots of libraries need to have correct jest mocks loaded.

Please reply back and we can reopen this ticket if it's still an active concern.
