### ISSUE TITLE
Wrong import of reactxp-virtuallistview

### ISSUE THREAD

**Issue by martinnov92** [Microsoft/reactxp#117]
Hello,

I think you wrongly imported VirtualListView in this example [https://github.com/Microsoft/reactxp/blob/master/docs/docs/extensions/virtuallistview.md]()

`import { VirtualListView, VirtualListViewItemInfo } from 'virtuallistview';`

Shouldn´t it be `import { VirtualListView, VirtualListViewItemInfo } from 'reactxp-virtuallistview'`? 

Thank you

**Comment by erictraut** [comment]
@martinnov92, you are correct. Thanks for pointing it out. I just pushed a fix.
