### ISSUE TITLE
Object is not a function React Apollo Hook

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1174]
Hello im trying to use react apollo hooks library to connect to a graphql backend  but give me this error in render:
TypeError: Object(...) is not a function
    at Module.useMutation

this is my component:
 
import * as RX from 'reactxp';

import gql from 'graphql-tag'
import { useMutation } from '@apollo/react-hooks';

const CREATEDRAFT_MUTATION = gql`
mutation CreateDraft($title: String!, $content: String!, $imaginaryPartX: [Float!], $imaginaryPartY: [Float!], $IterMAX: Int!, $NDMAX: Int!, $dataType: String!, $materialType: String!) {
    createDraft(title: $title, content: $content, imaginaryPartX: $imaginaryPartX,  imaginaryPartY: $imaginaryPartY, IterMAX: $IterMAX, NDMAX: $NDMAX, dataType: $dataType, materialType: $materialType ) {
                    title
                    content
                    dataType                    
                    materialType                    
                    imaginaryPartX
                    imaginaryPartY
                    dfImaginaryPartX
                    dfImaginaryPartY
                    dfRealPartX
                    dfRealPartY                   
    }
  }
`

const BtnDraft= ({title,content,imaginaryPartX,imaginaryPartY, IterMAX, NDMAX, dataType, materialType}:{title:string,content:string,imaginaryPartX:number[],imaginaryPartY:number[], IterMAX:number, NDMAX:number, dataType: string, materialType:string}) => {
  
    const [addTodo, { data }] = useMutation(CREATEDRAFT_MUTATION);
   
  return (    
  <RX.View>
    {data?'success':''}
    <RX.Button onPress={(e)=> {
            e.preventDefault();
            addTodo({ variables: ({ title,content,imaginaryPartX,imaginaryPartY,
              IterMAX, NDMAX, dataType,materialType} )
          })}}>Execute</RX.Button></RX.View>
  );
  };
  
export default BtnDraft;

And my import:

     <BtnDraft title={this.state.title} content={this.state.content} imaginaryPartX={this.state.imaginaryPartX} 
                            imaginaryPartY={this.state.imaginaryPartY} dataType={this.state.dataType} materialType={this.state.materialType}
                            IterMAX={this.state.IterMAX} NDMAX={this.state.NDMAX}/>

Is a problem of reactxp or apollo? .. im getting this error with Urql librate too

**Comment by fbartho** [comment]
This is not a ReactXP problem, we’re using both ReactXP and Apollo in our project. 

Looking at your code, nothing jumps out as an obvious cause, sorry!
