### ISSUE TITLE
 Failed to load resource in todolist example

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1177]
hello im running the TodoList typescript example but when try to load an image give this error, i dont make any changes to code:

todo-logo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by deregtd** [comment]
Hey.  What platform are you trying to run it on?  Web or one of the RN platforms?

**Comment by GolfredoPerezFernandez** [comment]
Hi in web platform

**Comment by deregtd** [comment]
Any chance you're building on Windows?  Looks like we're hitting this:
https://github.com/gulpjs/gulp/issues/1847

(I just tried building this all on my windows box and hit the same issue it looks like you're hitting, but we've done almost all testing building on MacOS in the past. :) )

**Comment by deregtd** [comment]
Can you try this branch and see if it fixes your problem:
https://github.com/microsoft/reactxp/tree/ddr/todowindowsbuilds

**Comment by GolfredoPerezFernandez** [comment]
yes, work :) thanks a lot

**Comment by deregtd** [comment]
Sweet.  Merged to master.
