### ISSUE TITLE
frontent frozen when addTodo is making calculations

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1179]
hello Im using todolist example and I trying to use a mathematics formulas inside addTodo of TodoStore, but while he calculates all others the component stay frozen until the function addTodo finish...  any solution please :) 

this is my code:

----CreateTodoPanel.tsx----------

<SimpleButton 
                             onPress={(e)=> this.saveTodo(e) }
                             disabled={this.state.cargado}
                             buttonStyle={{justifyContent:'center', alignItems:'center',marginBottom:5,marginTop:10,width:200}} text={'Create Account'}/>
. 
.
.
    private async saveTodo  (e: RX.Types.SyntheticEvent)  {
            this.setState({
                cargado:true
            })
            await this._confirm();
        }

        async  _confirm() {
        const {  
            content,
            title,
            imaginaryPartY,
            imaginaryPartX,    
            IterMAX,
            NDMAX,        
             } =this.state
             
          const todo=  await TodosStore.addTodo(
              title,  content, this.state.dataType,
              this.state.materialType,imaginaryPartX,imaginaryPartY, IterMAX, NDMAX );
                
             TodosStore.setTodo(todo); 
                this.setState({
                     cargado:false
                 })
                         
             NavContextStore.navigateToTodoList(NavContextStore.isUsingStackNav() ? undefined :todo.id)                    
      }

------TodoStore.tsx--------

  addTodo(title: string, content: string, dataType: string, materialType: string,
         imaginaryPartX: number[] , imaginaryPartY: number[],IterMAX:number, NDMAX:number ) {
        const now = Date.now().valueOf();
//Here is the Calculus..
const res =   this.levenbergMarquartAlgorithm(imaginaryPartX,imaginaryPartY,IterMAX,NDMAX) 
.
 let newTodo: Todo = {
                id:now.toString(),
                title,
                content,
                dataType,
                materialType,
                dfRealPartX:res.dfRealPartX,
                dfRealPartY:res.dfRealPartY,
                dfImaginaryPartX:res.dfImaginaryPartX,
                dfImaginaryPartY:res.dfImaginaryPartY,
                imaginaryPartX:res.imaginaryPartX,
                imaginaryPartY:res.imaginaryPartY,
                creationTime: now,
            };
            
    this._todos = this._todos.concat(newTodo);
    
            // Asynchronously write the new todo item to the DB.
            LocalDb.putTodo(newTodo);
    
            this.trigger();
    
            return newTodo;
         

    }

**Comment by deregtd** [comment]
Javascript is single-threaded.  You have to split your work up, run it later, or run it on a service worker.

**Comment by GolfredoPerezFernandez** [comment]
any example? im not a big expert :(

**Comment by GolfredoPerezFernandez** [comment]
Can you give me a little example please

**Comment by deregtd** [comment]
Sorry, this is actually a very advanced javascript topic to deal with.  There is no right answer and has to take into account a ton of requirements around what your clients are, where you can offload CPU to, etc.
