### ISSUE TITLE
Can't scroll horizonal & vertical

### ISSUE THREAD

**Issue by stijnvanderlaan** [microsoft/reactxp#1183]
When I set horizontal on the ScrollView it only scroll's horizontal and not vertically, setting vertical is not supported anymore? Testen on web, don't know about other platforms.

**Comment by berickson1** [comment]
This is a limitation of React Native. Previously the vertical prop only affected web. To keep cross platform compatibility, the behaviour was updated to only allow horizontal or vertical  (when horizontal=false or undefined) scroll, not both simultaneously.

**Comment by fbartho** [comment]
The TypeScript types now make this a bit clearer, so I'm going to close this ticket for now. If there's still work that we can do in ReactXP, please write back!
