### ISSUE TITLE
Animated GIF rendering on Web and Android

### ISSUE THREAD

**Issue by alariej** [microsoft/reactxp#1188]
Hello

From the documentation, `RX.Image` should be able to display GIF images. I ran the sample _RXPTest_ on the web and I could see the _heart.gif_ file being correctly animated.

However in my test application, the animation on the web sometimes does not occur, with only a static frame being displayed. For example, there is no GIF animation when `RX.Image` is contained within a _VirtualListView_.

On Android, I can never see any GIF animation, whatever the container is. Only static frames are being displayed.

Is this normal?

**Comment by fbartho** [comment]
@alariej -- I think this is an issue with react-native core. Have you read their documentation? https://reactnative.dev/docs/0.42/image#gif-and-webp-support-on-android

It mentions that you need to add extra configuration for Gif to work. Would you mind checking if that fixes your issue?

**Comment by mikehardy** [comment]
I remember looking at this when it came in, and I have an animated gif working correctly? 🤷

**Comment by alariej** [comment]
Thanks for looking at this. I added `implementation "com.facebook.fresco:animated-gif:1.10.0"` (version 2.0.0 does not work with RN 0.59) to the app/build.gradle dependencies and I can now see animated GIF images on Android.
