### ISSUE TITLE
Picker not part of RN core any more

### ISSUE THREAD

**Issue by yoshi415** [microsoft/reactxp#1199]
We noticed this yellow warning after upgrading to RN 0.62.0:

`Picker has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/picker' instead of 'react-native'. See https://github.com/react-native-community/react-native-picker`

Included picker needs to be updated to community package.

**Comment by mikehardy** [comment]
I noticed that too. When a similar thing happened with netinfo, the PR to handle it (by extracting it to an extension) looked like this: #1119

**Comment by fbartho** [comment]
@yoshi415 I've slotted this into the next reactxp release on the roadmap! Let's talk about the details
