### ISSUE TITLE
Best way to wire browser's back button with the Navigator?

### ISSUE THREAD

**Issue by psegalen** [Microsoft/reactxp#120]
Hello,
I'm trying to support the browser back button in my web app.
I have some components representing pages and I have a Navigator at the root of my app.
I want the navigator to correctly handle the back button, I've tried to manipulate HTML5 `history` object (with `history.pushState()` when I push a new route in my Navigator and subscribe to global event `popstate` in my root component in order to do a `Navigator.pop()` when the back button is pressed.
Is it the best way or is there another one which is better?

**Comment by erictraut** [comment]
Yes, I think that's the best way to do it. That's how we handle it in the Skype app.

Here's the code we use:

`
import NavigationStateStore = require('../stores/NavigationStateStore');
import UrlConverter = require('../utils/UrlConverter');

class PageUrlService {
    private _handlingPopState = false;
    private _navigatingToNewPlace = false;

    startup() {
        NavigationStateStore.subscribe(() => this._onNavigationStateStoreChange());
        window.addEventListener('popstate', e => this._onUrlChange(e));
    }

    private _onNavigationStateStoreChange() {
        if (!this._handlingPopState) {
            const navContext = NavigationStateStore.getCurrentNavigationContext();
            let newUrl = UrlConverter.getUrlForNavigationContextStack(navContext);

            this._navigatingToNewPlace = true;
            window.history.pushState(null, null, newUrl);
            this._navigatingToNewPlace = false;
        }
    }

    private _onUrlChange(e: any) {
        if (!this._navigatingToNewPlace) {
            let navAction = UrlConverter.getNavigationActionForDeepLink(window.location.href);

            if (navAction) {
                this._handlingPopState = true;
                navAction();
                this._handlingPopState = false;
            }
        }
    }
}

export = new PageUrlService();
`

**Comment by psegalen** [comment]
Wow! Thanks @erictraut, it's very useful indeed!
Will the Skype apps be open-sourced at any point in the future? It would be nice to have such a big picture! :)
