### ISSUE TITLE
Unrecognized command "run-android"

### ISSUE THREAD

**Issue by alexbom** [microsoft/reactxp#1201]
Hello!
I've get this error on **yarn start:android** from Android Studio.
Before this i've started emulator **Nexus 5X API 29 x86**.
Tried to remove **node_modules** and install again - no profit.
**yarn start:web** is working fine.

package.json

> {
>   "name": "friendler",
>   "private": true,
>   "main": "index.js",
>   "version": "1.0.0",
>   "scripts": {
>     "rn-cli": "node scripts/react-native.js",
>     "start:android": "npm run rn-cli run-android",
>     "start:windows": "npm run rn-cli run-windows",
>     "start:ios": "npm run rn-cli run-ios",
>     "start:web": "cross-env platform=web webpack-dev-server --config=web/webpack/dev.js --progress --colors --mode=development",
>     "start:rn-dev-server": "npm run rn-cli start --reset-cache",
>     "build:web": "cross-env platform=web webpack --config=web/webpack/prod.js --progress --colors --mode=production",
>     "test": "jest -c jest/jest.config.js",
>     "test:watch": "npm run test --watch",
>     "test:debug": "node --inspect-brk node_modules/.bin/jest -c jest/jest.config.js --runInBand",
>     "build:types": "tsc --emitDeclarationOnly",
>     "type-check": "tsc --noEmit",
>     "type-check:watch": "npm run type-check -w",
>     "lint": "eslint --config .eslintrc --ext .ts,.tsx src"
>   },
>   "devDependencies": {
>     "@babel/core": "7.7.4",
>     "@babel/plugin-proposal-decorators": "7.7.4",
>     "@babel/preset-env": "7.7.4",
>     "@react-native-community/cli": "3.0.4",
>     "@types/enzyme": "3.10.3",
>     "@types/jest": "24.0.23",
>     "@types/node": "^12.7.2",
>     "@types/webpack": "^2.2.14",
>     "@typescript-eslint/eslint-plugin": "2.9.0",
>     "@typescript-eslint/parser": "2.9.0",
>     "awesome-typescript-loader": "3.1.2",
>     "babel-loader": "8.0.6",
>     "compression-webpack-plugin": "3.0.0",
>     "cross-env": "6.0.3",
>     "enzyme": "3.10.0",
>     "enzyme-adapter-react-16": "1.15.1",
>     "enzyme-to-json": "3.4.3",
>     "eslint": "6.7.1",
>     "eslint-loader": "3.0.2",
>     "eslint-plugin-jest": "23.1.0",
>     "eslint-plugin-react": "7.17.0",
>     "eslint-plugin-reactxp": "0.1.7",
>     "file-loader": "^1.1.9",
>     "fork-ts-checker-webpack-plugin": "3.1.1",
>     "html-webpack-plugin": "3.2.0",
>     "jest": "24.9.0",
>     "json-loader": "^0.5.7",
>     "metro-react-native-babel-preset": "0.57.0",
>     "rnpm-plugin-windows": "0.4.1",
>     "source-map-loader": "^0.1.6",
>     "ts-node": "^3.2.1",
>     "tslint": "5.8.0",
>     "tslint-microsoft-contrib": "5.0.0",
>     "typescript": "3.7.2",
>     "uglifyjs-webpack-plugin": "^1.3.0",
>     "webpack": "4.41.2",
>     "webpack-cli": "3.3.10",
>     "webpack-dev-server": "3.9.0",
>     "webpack-merge": "4.2.2"
>   },
>   "dependencies": {
>     "@types/lodash": "^4.14.104",
>     "@types/react-dom": "^16.0.4",
>     "@types/react-native": "^0.52.13",
>     "@types/react-redux": "^5.0.15",
>     "@types/webpack-env": "^1.13.6",
>     "dotenv-webpack": "^1.5.5",
>     "history": "^4.7.2",
>     "lodash": "^4.17.15",
>     "moment": "^2.21.0",
>     "raven-js": "^3.27.2",
>     "react": "16.12.0",
>     "react-dom": "16.12.0",
>     "react-native": "0.59.10",
>     "react-native-cli": "^2.0.1",
>     "react-native-windows": "0.59.0-rc.3",
>     "react-redux": "^5.0.7",
>     "react-router-redux": "^4.0.8",
>     "react-yandex-maps": "^2.2.0",
>     "reactxp": "^2.0.0",
>     "reactxp-imagesvg": "^2.0.0",
>     "reactxp-navigation": "^2.0.0",
>     "reactxp-video": "^2.0.0",
>     "redux": "^4.0.0",
>     "redux-api-middleware": "^2.2.0",
>     "redux-devtools-extension": "^2.13.2",
>     "redux-implicit-oauth2": "^1.2.1",
>     "redux-thunk": "^2.3.0",
>     "ts-loader": "^4.0.0"
>   }
> }
>

**Comment by mikehardy** [comment]
These packages look pretty old to me - I would never run on react-native 0.59.x at this point for instance, I would do 0.60.x at minimum, but 0.62.2 is current.

Are you just beginning this project? If so I would upgrade those things as well as the CLI which has much more recent versions.

This is leading up to me saying I believe the current state of the art in react-native is to say 'npm android' by itself (and 'npm ios') as well

Where did those package.json scripts come from? Highly likely some docs or examples need grooming to match up with new react-native styles as they change over time

**Comment by fbartho** [comment]
Closing this, as I believe there's no action items for ReactXP at this time
