### ISSUE TITLE
Trying to deploy web to AWS Amplify

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1202]
Hello im using  AWS Amplify to deploy my website but i cant make it work.. on this part: 
![AFB87459-20A9-4BB1-8320-7B0EADC8B8DF](https://user-images.githubusercontent.com/36853339/82142947-2f5fe800-980e-11ea-8d89-e0a21a631821.png)

 which prebuild  and build command  should be? im using todolist example so i want  that local db Server work so i try several like npm run start-Web & node nodeserver but failed..

**Comment by fbartho** [comment]
I'm not familiar with AWS Amplify, so I have no idea what's going on there. Maybe you could ask on an issue board of forum for AWS stuff?

If you still need help here, please reply back, however I'm going to close this ticket for now, as AWS Amplify isn't something we use or maintain.
