### ISSUE TITLE
How to use libraries with css (web)

### ISSUE THREAD

**Issue by m4tf3r** [microsoft/reactxp#1211]
I am trying to use libraries that provide date and time picker react components (e.g. https://github.com/YouCanBookMe/react-datetime). Components are displayed but they look wrong, like css files are not loaded.

**Comment by fbartho** [comment]
I believe it's up to you to import the CSS from that library into your page's context?

ReactXP doesn't control the styling / components used by a 3rd party library.

**Comment by fbartho** [comment]
@m4tf3r To rephrase my previous answer: I believe `react-datetime` should have documentation on how to add their CSS, and when I look at their page they sort of do:
![Screenshots of the react-datetime Readme and their usage instructions](https://user-images.githubusercontent.com/209712/89556741-b0ec6400-d7c6-11ea-8d5e-6e784dffa00a.png)

-- I'm going to close this issue for now, but if you continue to struggle, please let me know and I can reopen it.
