### ISSUE TITLE
Contributors / Maintainers -- is ReactXP open to more?

### ISSUE THREAD

**Issue by fbartho** [microsoft/reactxp#1223]
My team has been using ReactXP for 2.5 years -- but mostly on React-Native -- the time has finally come to extract some of our stuff into a Design System that we can share between multiple mobile-apps, and our Web experience -- and hopefully publicly down the line we might open source it. -- We're pretty sure we have a great scaffold, but one crucial question that came up is whether RX will be an internal implementation detail, or if we'll expose RX details in our API Surface area (it's much more work to build a facade that hides RX!).

I've noticed that you recently updated things @erictraut + @mikehardy -- so I have faith that this project is still alive!
That said, there are 68 open issues.

I was wondering if you were open to more maintainers supporting this project?
In particular, in the past, I & my team filed the following still-open issues, but for reasons (we weren't using/testing RX on web), we weren't super comfortable opening external PRs to solve them
- #1053
- #1093
- #1128
- #1187
- #1199 (Team-member filed)
- #1221 (Cultural question)
- #1222 (Freshly filed today)

Separate from the issues that we filed ourselves, we're also interested in a bunch of the other open issues.

We've also in general been interested in many of the open PRs over time including #1126 -- Our design system library has a mandate to be accessible from the get-go, and we're setting as high a bar as we can justify to make sure that that happens. #1126 is crucial there!

# My ask(s)

Do you want more maintainers on this project? I'd be happy to both submit PRs and help review PRs submitted by others.

Additionally, I'd love to be able to help labeling tickets, responding to them promptly, and closing them out after a reasonable time of staleness -- (just general housekeeping).

I'm not sure of the process of preparing a release, and obviously there might be reasons we're not privy to that require you to be the one to do this. But once I demonstrate competence I'm also willing to participate there.

I maintain a few other active & healthy projects OSS including [apollo-link-rest](https://github.com/apollographql/apollo-link-rest), [react-native-zendesk-chat](https://github.com/taskrabbit/react-native-zendesk-chat), [react-native-parsed-text](https://github.com/taskrabbit/react-native-zendesk-chat) and tipsi-stripe (Political concerns mean master branch/stable-release is stuck / this one is only partially maintained, but I've been maintaining a Discord channel with a thousand members that have been using the 8.0.0-beta releases in production for a year).

We might have as many as 30 contributors (across 4 teams) to our in-house Design System toolkit, so it would make me feel much more comfortable if we can ensure that reactxp is a healthy and active project!

I'm happy to submit further credentials or discuss context publicly or in a private message conversation.

@erictraut -- I assume you're in charge here :P

**Comment by mikehardy** [comment]
Very interested in the discussion, myself. I wouldn't be contributing code much but I'm a proactive maintainer (as my PRs here show) with react-native-device-info, react-native-firebase and AnkiDroid under my full maintainer / release watch as well as a few other things I keep an eye on.

I will happily continue watching issues / PRs here and commenting if I can add value, or testing locally to make sure they work.

@deregtd is also active here and may have knowledge of the MS internal landscape / plans that ReactXP operates in.

**Comment by erictraut** [comment]
@deregtd and @berickson1 are no longer with Microsoft, and they have told me that they won't be able to dedicate much time to reactxp going forward. I'm still with Microsoft, but I also don't have much time to contribute to reactxp. I've been thinking about the best way to ensure that it is getting the attention that it needs, so this discussion is very timely. @fbartho, I'll follow up with you directly to talk about your ideas above. Thanks!

**Comment by erictraut** [comment]
And @mikehardy, thanks for your continued support and offer to help!

**Comment by fbartho** [comment]
The answer is/was yes! 🎉

**Comment by mikehardy** [comment]
@fbartho fantastic! As I mentioned above, I'll continue watching here and will chip in as I can. You are more than welcome to explicitly `@` tag me any time or assign things for me without asking in advance and I'll apply back pressure if it's not working for me for whatever reason. Cheers
