### ISSUE TITLE
Using ReactXP without TypeScript

### ISSUE THREAD

**Issue by eXigentCoder** [Microsoft/reactxp#124]
Would it be possible to please put together a very simple hello world example that does not use TypeScript?

I know TS is recommended but the FAQ mentions that it's use is optional. I'd rather not get into the debate over which is "better", at the end of the day there will be people who prefer one over the other. 

If there is a basic example we can expand on it and get more people using ReactXP. I did try to put one together quickly but ran into multiple issues.

Thanks!

**Comment by erictraut** [comment]
Perhaps the fastest and easiest way to see what it would look like to use plain JavaScript is to build the existing hello-world sample and look at the output of the TypeScript compiler. Just look in the "./dist" directory. If you prefer es6 to es5, just change the tsconfig.json file before building.

**Comment by eXigentCoder** [comment]
Thank you, that was a great starting point and I'm almost done porting the hello world example. Would you like me to submit a PR once i'm done for any future developers to use as a reference?

**Comment by erictraut** [comment]
I'd be interested in seeing your sample, so please submit a PR. I'm not yet sure whether it makes sense to maintain a parallel "hello world" JS example. I'll decide once I look at your code. Thanks!

**Comment by erictraut** [comment]
Thanks @eXigentCoder for the sample code. I just merged it into the project.

**Comment by eXigentCoder** [comment]
Awesome, thanks!
