### ISSUE TITLE
Repo Process: Squash & Merge -- do people feel strongly about this?

### ISSUE THREAD

**Issue by fbartho** [microsoft/reactxp#1249]
I just realized that reactxp is set to squash-and-merge.

This is jarring for me as an individual, particularly with open-source, as I like to give clear and full credit to people, and in open-source this would prevent multiple people from collaborating on a branch & getting credit.

I think squashing made a bit more sense back in the day when you were doing tons of `git bisects` and people needed to inspect the branching history to understand what happened. -- I don't think this is as common of a use case in the wild / nowadays / on GitHub / with reactxp.

Also squashing often produces huge commits that condense a ton of lines into a single thing, and that loses a bit of the nuance of the intent of the changes on a particular line.

For these reasons I'd like to hear from people and then maybe propose that we switch to a Merge-workflow depending on input from recent contributors.

**Comment by mikehardy** [comment]
Just for the record, for whatever it is worth, I have no opinion personally, here, do what you are most comfortable with :-), from me at least

The only *true* way is rebase with no merge commits allowed though - if only it weren't so painful for people haha. I work in one repo that does that and only squashes from initial / drive by contributors and it's a beautiful commit history. I find merge commits and squash commits both jarring now. But I think it sets too high a bar for irregular contributors so we don't enforce anything. We end up choosing on a PR by PR basis basically

**Comment by erictraut** [comment]
We set it to squash and merge so all changes were "atomic". Each commit represents an independent piece of functionality that can easily and completely be reverted if necessary. And you can go back to any arbitrary commit in the master branch and have high confidence that it will build, run and pass all tests.

If you want to change it, that's your prerogative. Just wanted to provide some background.

**Comment by fbartho** [comment]
Based on that, I'll keep Squash Merging for now, but should that become valuable to change I'll keep the option of a merge commit in mind.

Thanks for the input!
