### ISSUE TITLE
ReactXP Hook issue 

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [microsoft/reactxp#1258]
Hello im trying to convert TodoListPanel of TodoList Example into React Hook and use it with graphq :

import TodoListItem from './TodoListItem';
import { VirtualListView, VirtualListViewItemInfo } from 'reactxp-virtuallistview';

export const UsersQuery = ({
  filterUsers,  
}: {
	filterUsers: TodoListItemInfo[];
}) => {  
  const { loading, error, data, } = useQuery(USER_QUERY, {   
    variables:{searchString:"Bussiness"},    
  })

  if (loading) return  <RX.Text style={_styles.buttomStyle}>{"Loading..."}</RX.Text>;
  if (error) return <RX.Text style={_styles.buttomStyle}>{error}</RX.Text>;
  if (data){
    CurrentUserStore.setUsers(data.filterUsers)
  } 

  const _renderItem = ((details: VirtualListCellRenderDetails<TodoListItemInfo>)=>{ 
   var item= details.item.todo
   return <TodoListItem
    todo={ item}
    height={ _listItemHeight }
    isSelected={ false }
    searchString={'' }
    onPress={ (todoId: number)=>{
      CurrentUserStore.setStoreId(todoId.toString())
      NavContextStore.navigateToTodoList(todoId.toString(), false);}}
  />})

  return <VirtualListView 
  itemList={ filterUsers }
  renderItem={ _renderItem }
  style={ _styles.listScroll }
  />
 
};

Getting this error:, i dont know what im doing wrong 
![image](https://user-images.githubusercontent.com/36853339/108289015-076a3000-7164-11eb-8050-b49c2634b5aa.png)

**Comment by fbartho** [comment]
Your renderItem method should probably use a `useCallback` hook so that it doesn’t change on every render!

That’s probably what VirtualListView is grumpy about, but I’m no expert as we don’t use that in our apps.

**Comment by GolfredoPerezFernandez** [comment]
Thanks works! :)...

export const UsersQuery = ({
  filterUsers,  
}: {
	filterUsers: TodoListItemInfo[];
}) => {  
  const { loading, error, data, } = useQuery(USER_QUERY, {   
    variables:{searchString:"Bussiness"},    
  })

  if (loading) return  <RX.Text style={_styles.buttomStyle}>{"Loading..."}</RX.Text>;
  if (error) return <RX.Text style={_styles.buttomStyle}>{error}</RX.Text>;
  
  useEffect(() => {   
     CurrentUserStore.setUsers(data.filterUsers)

  }, [data]);

	const _renderItem = useCallback(
    (details:VirtualListCellRenderDetails<TodoListItemInfo> ) => (
      <TodoListItem
      todo={ details?.item.todo??{}}
      height={ _listItemHeight }
      isSelected={ false }
      searchString={'' }
      onPress={ (todoId: number)=>{
        CurrentUserStore.setStoreId(todoId.toString())
        NavContextStore.navigateToTodoList(todoId.toString(), false)}}/>
    ),[]);

  return <VirtualListView 
  itemList={ filterUsers }
  renderItem={ _renderItem }
  style={ _styles.listScroll }
  />

};
