### ISSUE TITLE
React XP / Windows Development

### ISSUE THREAD

**Issue by ArcadixPascal** [Microsoft/reactxp#135]
hi 

a) How can we use Visual Studio to develop on a Windows 10 Machine with React XP?
    (e.g. for web version and then use the same for the Windows Native, Apple/Android?)

b) Is the Thin layer documented that allows to output to all this different targets?

c) How serious is Microsoft / Skype about supporting this? (there doesn't seem much material when doing a Google search). 

thanks.

**Comment by erictraut** [comment]
I typically use VSCode on both Windows and Mac for my development. You could also use the full Visual Studio IDE (or any other text editor) as you see fit. 

We've provided extensive documentation [here](https://microsoft.github.io/reactxp/docs/getting-started.html). You will find "getting started" guides, API references, etc. You will also find several samples checked in to github. I recommend starting with the [hello-world](https://github.com/Microsoft/reactxp/tree/master/samples/hello-world) sample.

ReactXP was developed by the Skype team at Microsoft. We have implemented the new Skype client using this library, and there's a sizable development team working on this product. There is no dedicated team at Microsoft focused on the ReactXP alone. The library was released only a few months ago.
