### ISSUE TITLE
Can I Use Skype WEb SDK into ReactXP?

### ISSUE THREAD

**Issue by 86simonepenna** [Microsoft/reactxp#139]
I want to develop an application which use Skype web SDK, how can I do this?
If this is not possible, are there other ways?

Thank you

**Comment by erictraut** [comment]
Please refer to this site for information about the [Skype Web SDK](https://msdn.microsoft.com/en-us/skype/websdk/docs/skypewebsdk).

**Comment by 86simonepenna** [comment]
Ok, I've already implemented a project with skype web sdk and it works all on EDGE. I want create a UWP project but not work. I want UWP because on EDGE of Hololens not work Skype Web SDK.
