### ISSUE TITLE
Can one use Redux instead of ReSub?

### ISSUE THREAD

**Issue by rnarayan** [Microsoft/reactxp#14]
ReactXP looks like a great project. Is it designed to be modular so that a developer can choose the best of breed, say use Redux instead of ReSub, or any other brilliant idea that may replace Redux in the future?

**Comment by erictraut** [comment]
Yes, ReactXP is completely agnostic to the data binding mechanism. You can use Redux, Flux, ReSub, MobX, Baobab, or any other mechanism that you prefer.
