### ISSUE TITLE
TextInput component missing clearButtonMode

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#141]
I noticed that `clearButtonMode` from React Native did not carry over to ReactXP. Is it just a missing prop that was overlooked and will get added, or is there another reason it is missing?

It basically shows the little `x` in a circle on the right of the text input to clear it :)

**Comment by erictraut** [comment]
This is an iOS-specific prop. We generally try to avoid adding props that are platform-specific to ReactXP. We have made a few exceptions where there was a compelling reason to do so. We (the Skype team) took the approach of implementing a clear button ourselves (by rendering a button next to the TextInput). This way, it works on all platforms in a consistent manner. Does this approach work for you?

**Comment by MovingGifts** [comment]
Ah I see, yeah I think for the sake of cross platform consistency we can follow that approach.

Thanks for the quick response :)
