### ISSUE TITLE
No ViewManager defined for class RNSVGPath

### ISSUE THREAD

**Issue by pixare40** [Microsoft/reactxp#143]
Hello, I am running into this issue when I implement the imagesvg component. My component looks like this:
`import { default as RXImageSvg, SvgPath as RXSvgPath } from 'reactxp-imagesvg';`

![capture2](https://user-images.githubusercontent.com/6998142/27458449-042426ca-57a1-11e7-8e4f-7b52d83a79a8.PNG)

my package.json looks like this:
`"dependencies": {
    "react": "15.5.4",
    "react-addons-perf": "15.5.0-rc.2",
    "react-addons-test-utils": "15.5.1",
    "react-dom": "15.5.3",
    "react-native": "0.42.3",
    "react-native-windows": "^0.33.0",
    "reactxp": "0.42.0-rc.3",
    "reactxp-imagesvg": "^0.2.1",
    "resub": "^0.0.16",
    "simplerestclients": "^0.0.13",
    "synctasks": "^0.2.17"
  },`

This is the error when i run on the android emulator:
![capture](https://user-images.githubusercontent.com/6998142/27458224-e38228c8-579f-11e7-9450-1fe4fe680034.PNG)

what could i be doing wrong? it works well on web by the way. Just the android emulator has a problem.

**Comment by erictraut** [comment]
I'm guessing that you haven't registered the RNSVGPath class with RN. You can use the [react-native link](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) command to automate this step. If you want to do it manually, check out [this file](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/android/app/src/main/java/com/rxphelloworld/MainApplication.java) in the hello-world sample.

**Comment by pixare40** [comment]
That was the problem. Thank you @erictraut
