### ISSUE TITLE
Image Component (Local/Remote) source not rendering?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#146]
As a sibling to the `src` directory, I created an `images` directory with a `react.png` in it (I grabbed a copy from the remote url in the gist, and placed it in the local directory to test it).

I added the test to `MainPanel` [here is the gist](https://gist.github.com/MovingGifts/9ce96c8188f7ab6ad266d74562c65f39) and defined the image style and the `RX.Image` respectively.

Here is what I see on both platforms:
![reactxp-image](https://user-images.githubusercontent.com/1202909/27502802-cb0cc7f8-5844-11e7-84ef-7df5e3431f9b.png)

It seems like it's not working with the same source url api for both platforms?

**Comment by MovingGifts** [comment]
I still can't get the local/remote images to show on mobile with:

    <RX.Image source={ './images/react.png' } style={ styles.image } />
    <RX.Image source={ 'http://i.imgur.com/GRIZj68.png' } style={ styles.image } />

Isn't that how it should work in ReactXP?

**Comment by erictraut** [comment]
IIRC, remote images need to be https to comply with security policies on iOS. For local resources, refer to the [React Native documentation](https://facebook.github.io/react-native/docs/images.html) for how to reference static assets.

**Comment by MovingGifts** [comment]
Thanks @erictraut, I was aware of the mobile require syntax for local assets, but for some reason I thought the require syntax would make it work on web as well, but it didn't.

So is this the recommended approach?  
    
    <RX.Image source={ RX.Platform.getType() === 'web'
     ? 'https://url.com/images/asset_1.png'
     : require('./../asset_1.png') }
     style={ styles.image } />

**Comment by erictraut** [comment]
Yes, that should work fine. I recommend abstracting out the messy logic into a utility function though.

Something like this:
```
function getImageSourceUrl(assetName: string) {
    if (RX.Platform.getType() === 'web') {
        return 'https://mydomain.com/images/' + assetName;
    } else {
         return require('./../images/' + assetName);
    }
}
```

**Comment by MovingGifts** [comment]
Abstraction sounds good :) Thanks for the feedback :)

**Comment by MovingGifts** [comment]
It seems the abstraction here won't work :( After trying, react native throws an error as it doesn't like the `assetName` as a variable it seems; hard coding the `assetName` (the messy logic without abstraction) works.

It's weird RN won't render the dynamic `assetName` on mobile. Would have preferred a cleaner implementation like a utility function. Do you think there is a way to get it to work?

**Comment by MovingGifts** [comment]
This works, so will go with this:

```
function getImage(assetName: string, style: RX.Types.ImageStyle) {
    if (RX.Platform.getType() === 'web') {
        return <RX.Image source={ 'https://mydomain.com/images/' + assetName } style={ style } />
    } else {
        return <RX.Image source={ require('./../images/' + assetName) } style={ style } />
    }
}
```

**Comment by MovingGifts** [comment]
Had to hard code the sources, seems like the only way I could find..

**Comment by erictraut** [comment]
You're correct. React Native's loader requires that the full path of the local resource be hard-coded (i.e. provided within the code as a string literal). I forgot about that limitation. Sorry for leading you astray.

Here's how we solved this in the Skype app. We created two separate modules that specified images (and other assets) that needed to be loaded. One implementation was for the web, the other for native. Both of these modules implement a common interface, which ensures that any time a method is added to the interface, it must be implemented for both the web and native implementations. Failure to implement it in both places results in a build-time error. We then use a build-time transform to alias the correct module (web or native). This is done through a build script that uses simple regex replacements. This eliminates any ugly and expensive runtime checks.

I'll try to find time to write a blog post on this topic and provide more details (including source snippets) since others are likely to run into the same problem.

**Comment by MovingGifts** [comment]
Thank you and no worries :) Glad to hear there is a cleaner solution, since it's kind of messy now.

I look forward to your blog post, details, and snippets :)

**Comment by erictraut** [comment]
@MovingGifts, I just posted a new [blog article](https://microsoft.github.io/reactxp/blog/2017/06/29/asset-loading.html) that discusses this topic.

**Comment by MovingGifts** [comment]
@erictraut I just read your blog article, nice write up & thanks for posting it :) To me it all makes sense until the aliasing, that part is a bit confusing for me, and where gulp fits into the whole picture. Would be nice if there was a simpler way :)

I will play around with the implementation and see if I can get it to all work :)

**Comment by erictraut** [comment]
Yeah, the aliasing is needed in cases where you don't want to include the code for multiple platforms in the final bundle. It allows you to "link" only the code that's required for the current platform that you're building. When this is done at build time, it not only results in a smaller app bundle, it also eliminates all of the runtime conditional checks.

**Comment by erictraut** [comment]
I'll point out that the aliasing trick is very useful for things other than assets. We use it more generally to "link in" platform-specific implementations of modules. The mechanism is easily extended to support this pattern.

**Comment by MovingGifts** [comment]
@erictraut Thank you for clarifying the alias use case :) But that leads to the following questions:

1. In `package.json`, if you have x amount of packages for react native and y amount of packages for react, and then some shared like `lodash`. How would you section off packages for native vs web vs shared using aliasing or other means?
2. Sorry to complicate things, but I am getting issues trying to simplify things from my react native transition to ReactXP. For example, to simplify require/import paths, I use [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) I see this as needed, because besides simplifying the require/import paths in our projects, it removes complex relative path `../../../` variations. For example, an image in `AppAssetsNative.ts` required with a hardcoded `../../` which may load correctly in a file using it, but not in another file, where the location would not be correct relative to it (files in different directories referencing the same asset). I am having issues having all this work together :(

It would be awesome if you can put together a very barebones yet functional ReactXP app just to demonstrate the above points in the most minimal way (if you don't mind, as this will be very helpful and will demonstrate correct implementation with ReactXP in some tricky areas).

I am sure it will be very helpful to the community as well :)

**Comment by erictraut** [comment]
I'm not sure what you mean by "section off". Are you asking whether there's a way to conditionally install different sets of node packages based on which platform you're building? There's no need to do this. Just install the superset of all packages needed for all platforms. Remember, the packages listed in the "dependencies" and "devDependencies" section of package.json are simply the packages that need to be installed for your app to build correctly. 

As for your second question, I don't think there's a problem here. AppAssetsNative.ts calls "require" and returns the results. The path that you pass to "require" is relative to the AppAssetsNative.ts file, not to the modules that are importing AppAssets. 

The aliasing technique I discuss in the blog should work fine with the babel plugin you mentioned. In fact, you should be able to run the babel transform pass either before or after the aliasing pass.

I guess you'll need to elaborate more on the issues you're facing.

**Comment by MovingGifts** [comment]
Thank you for explaining the package dependency issue :)

In the blog post's aliasing section, I am not sure where argv comes from to determine the platform. I used [this](https://gist.github.com/MovingGifts/26247429cb79ee903a80c3897740f33e) gulp file, with ReactXP's platform detection instead, but got an error on line 1 when importing RX, fixed it by making it a var instead, then got an error on line 4 (added as a comment in the gist).

I know that in webpack `awesome-typescript-loader` handles all the transforming of `ts/tsx` code to `js`, and webpack outputs the final code to `bundle.js` in the dist directory.

Since webpack handles that, and we're only trying to integrate gulp to "link" the correct assets depending on the platform, can't we just use the apply-aliases by itself?

    gulp.task('run', function(callback) {
        runSequence('apply-aliases');
    });

I apologize for the questions, but I am having a hard time getting it to run smoothly :)

**Comment by erictraut** [comment]
The arvg comes from command-line inputs to gulp. If you type "gulp run --platform=ios", then argv.platform will contain "ios".

The ReactXP library isn't meant to execute within the context of a gulp script, so you shouldn't import it there.

I had a bug in my code that defined config. The colon should be an equal sign. I've updated the blog accordingly.

Sure, you can use gulp to just apply aliases by itself rather than using it for your entire build pipeline. We use a combination of gulp and npm scripts. For example, in our package.json, we define the following scripts:

  "scripts": {
    "install-dependencies": "npm install",
    "gulp-web": "cross-env NODE_ENV=development gulp run --platform=web",
    "gulp-ios": "cross-env NODE_ENV=development gulp run --platform=ios",
    "gulp-android": "cross-env NODE_ENV=development gulp run --platform=android",
    "gulp-tests": "cross-env NODE_ENV=development gulp run --platform=tests",
    "start-web": "npm run install-dependencies && npm run gulp-web",
    "start-ios": "npm run install-dependencies && npm run gulp-ios",
    "start-android": "npm run install-dependencies && npm run gulp-android",
    "start-tests": "npm run install-dependencies && npm run gulp-tests",
    "start-release-web": "npm run install-dependencies && cross-env NODE_ENV=production gulp run-once --platform=web",
    "start-release-ios": "npm run install-dependencies && cross-env NODE_ENV=production gulp run-once --platform=ios",
    "start-release-android": "npm run install-dependencies && cross-env NODE_ENV=production gulp run-once --platform=android"
 }

**Comment by MovingGifts** [comment]
Getting closer, I'm just trying to fill in the inconsistencies so the aliasing works with ReactXP out of the box, so it can help myself and others without all the extra steps we're going through now.

When I run  `npm run gulp-ios`, I get:

```
> rxp@1.0.0 gulp-ios /Users/XPTests
> NODE_ENV=development gulp run --platform=ios

[11:34:51] Using gulpfile ~/XPTests/gulpfile.js
[11:34:51] Starting 'run'...
[11:34:51] 'run' errored after 154 μs
[11:34:51] Error: apply-aliases
    at formatError (/Users/XPTests/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/XPTests/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/XPTests/node_modules/orchestrator/index.js:264:8)
    at /Users/XPTests/node_modules/orchestrator/index.js:275:23
    at finish (/Users/XPTests/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/XPTests/node_modules/orchestrator/lib/runTask.js:29:3)
    at Gulp.<anonymous> (/Users/XPTests/gulpfile.js:54:5)
    at module.exports (/Users/XPTests/node_modules/orchestrator/lib/runTask.js:34:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rxp@1.0.0 gulp-ios: `NODE_ENV=development gulp run --platform=ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rxp@1.0.0 gulp-ios script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[Here is my latest gist](https://gist.github.com/MovingGifts/69e6641d5ab065d6dbcc5fea6c72e85c)

Notes:
 1. In `package.json`, I removed `cross-env` since it wasn't defined.
 2. In gist, I had to require two additional packages for `argv` and `runSequence` to work.
 3. In gist, I commented lines: `7, 8, 44` as I am not sure what they should be in ReactXP.

I am stuck on 3 at the moment and the above error (maybe when 3 is fixed it may resolve the error).

What's missing to get it to work correctly?

**Comment by erictraut** [comment]
The "config" section of the script is intended to provide app-specific paths to your code and build directories. I can't tell you what those paths should be for your particular project. You need to provide them. This has nothing to do with the ReactXP library, it has to do with the way you build your app, so I'm not sure what you mean by "what they should be in ReactXP".

One thing that may help you track down the bug in your gulp script is to define an error handler. I didn't include it in my blog to keep the code simpler, but here's a handler that you can paste in to your gulp script:

var handleError = function(err) {
    console.log(err.toString());
};

This should help provide more details. I suspect that the error has to do with the path configurations.

**Comment by MovingGifts** [comment]
So by default, a ReactXP app created using `create-xp-app` has [this directory structure](https://github.com/react-native-training/create-xp-app/tree/master/src)

My `gulpfile.js` is in the root location, next to `package.json`.

There is the `src` directory with the `.ts/.tsx` and the dist directory with the `.js` output of all components for native and the `bundle.js` for web (from what I understand so far).

Based on that, I tried using the following for the config:

```
var config = {
    aliasify: {
        src: './dist',
        dest: './dist',
        // etc ...
```

I thought the `src` directory would be the directory where the `.js` files are outputted after running through the `awesome-typescript-loader`, and the `dest` directory, will be the same, since we're overwriting all the `.js` there with the `aliases` and want it in the same location.

I also added the `handleError` function right after defining the `config`, but the output in terminal was the same error.

The above `src/dest` paths returned the same error, so I must still be doing something wrong :(

**Comment by MovingGifts** [comment]
I managed to get gulp to not return errors (not sure if it's working correctly though with aliasing yet), because with your same assets setup as per your blog post:

I get this error for native:
```
10:22:25 PM - File change detected. Starting incremental compilation...
src/MainPanel.tsx(6,28): error TS2306: File '/Users/XPTests/src/modules/AppAssets.d.ts' is not a module.
10:22:30 PM - Compilation complete. Watching for file changes.
```

and I get this error for web:
```
ERROR in ./src/MainPanel.tsx
Module not found: Error: Can't resolve './modules/AppAssets' in '/Users/iOS/XPTests/src'
 @ ./src/MainPanel.tsx 12:14-44
 @ ./src/App.tsx
 @ ./src/index.tsx

ERROR in [at-loader] ./modules/AppAssets.d.ts:6:11
    TS2451: Cannot redeclare block-scoped variable 'Assets'.

ERROR in [at-loader] ./src/MainPanel.tsx:6:28
    TS2306: File '/Users/XPTests/src/modules/AppAssets.d.ts' is not a module.

ERROR in [at-loader] ./src/modules/AppAssets.d.ts:6:11
    TS2451: Cannot redeclare block-scoped variable 'Assets'.
```
I'm not really sure how to proceed at this point. I think that's why I was asking for a bare minimum single panel setup showing the aliasing working with ReactXP and gulp to show how it all works by an expert, since I can't get the blog snippets to work as intended and it's taking me way too long to integrate images using a common interface in my react native transition.

**Comment by MovingGifts** [comment]
No worries here.. I just reverted to inline conditionals based on platform to render the images. Even though it's not the cleanest way, it's the easiest way and it works :)

**Comment by vinils** [comment]
Getting the same problems here... I was able to go as far as @MovingGifts (btw tks)
I´ve also change gulp and Im gettting similar error as below:
Error:
"Module not found: Error: Can't resolve 'AppAssets' in 'c:\aaa\reactxp-master-hello-world2\src'"
Gulp´s Changes:
const plataform = process.env.plataform;

var config = {
    aliasify: {
        src: './dist',
        dest: './dist',
        aliases: (argv.platform === 'web') ?
        // Web Aliases
        {
            'AppAssets': './dist/AppAssetsWeb'
        } :
        // Native Aliases
        {
            'AppAssets': './dist/AppAssetsNative'
        }
    }
}

**Comment by wangfaxi1985** [comment]
Why not use
<RX.Image source={require('../../asserts/11.png')} like this
then react native can use ,and web can use also( web will package png file to js)

**Comment by omatrot** [comment]
@vinils Did you managed to resolve this issue ?
I'd like to use the aliasing technique as well to require modules based on the target platform.
The sample apps are not using gulp to build the code.
Besides gulp it seems that cross-env should be installed as well.

**Comment by vinils** [comment]
@omatrot Not as skype did.
my best work around was below:

import RX = require('reactxp');

class Images {
    static HeaderLogo = RX.Platform.getType() === 'web'
        ? 'file:///C:/aaa/expo-19-typescript-master4/assets/HeaderLogo.png'
        : require('./../assets/HeaderLogo.png');
}

export = Images;

**Comment by omatrot** [comment]
@vinils @MovingGifts I made it work with gulp targeting React-Native. Phew ! That was a lot of work. I'll soon blog about it because it is not that simple, at least it was not for me...
I have to make it work targeting web. It will need an extra step to minify/bundle the .js files. I'll be back soon.

**Comment by omatrot** [comment]
Web targeting is working as well. I'll write the blog post tomorrow. There is no watch capability right now bu I'll try to make it work soon.

**Comment by omatrot** [comment]
I just blogged [the first part of my findings](http://matrot.tech/2017/12/22/using-gulp-with-reactxp-part-1/) on this issue.

**Comment by vinils** [comment]
@omatrot  Cool! I´ll try it for sure! tks very much!
