### ISSUE TITLE
Incorrect opacity set on Button.tsx when updating its disabled prop.

### ISSUE THREAD

**Issue by rumit91** [Microsoft/reactxp#151]
I have a button that when the user presses I disable and initiate an async process. Once that async process I re-enable the button, but the opacity is incorrect. 

I suspect the issue is in `setOpacityStyles()` of `Button.tsx` ([line 209](https://github.com/Microsoft/reactxp/blob/master/src/native-common/Button.tsx#L209)) where `currentOpacity` is set to default and then immediately compared with `this._defaultOpacityValue`. 

I can send out a PR for this issue next week.

**Comment by erictraut** [comment]
@rumit91, did you ever have a chance to create a PR with a fix for this?

**Comment by rumit91** [comment]
Unfortunately I did not. Every sprint we kept pushing this bug out, but I just spoke to Seb and we decided to finally tackle it this sprint (should be ready by the end of Oct).

**Comment by rumit91** [comment]
Here's the PR to fix this issue: https://github.com/Microsoft/reactxp/pull/324
