### ISSUE TITLE
How to integrate react native package not to affect web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#155]
In a form with some text inputs, it's a common issue in react native when you open the keyboard on a device, where the keyboard covers the currently focused text input, unless you push the input above the keyboard to see it.

I haven't seen anyway in ReactXP that covers that since it's not a cross platform issue, just mobile devices with onscreen keyboards.

Currently in RN, I use the `KeyboardAwareScrollView`, which wraps the entire child view of the form, like this:

```
<KeyboardAwareScrollView extraHeight={100}>
  <RX.View style={styles.form}>
    <RX.TextInput ...a few of them go here...
  </RX.View>
</KeyboardAwareScrollView>
```

The above works perfectly in RN/ReactXP, but on web of course I get errors, since it does not apply to it. My attempt to ignore this plugin on web was the following:

```
{ RX.Platform.getType() !== 'web' && <KeyboardAwareScrollView extraHeight={100}> }
  <RX.View style={styles.form}>
    <RX.TextInput ...a few of them go here...
  </RX.View>
{ RX.Platform.getType() !== 'web' && </KeyboardAwareScrollView> }
```
But I get this error:
![screen shot 2017-07-04 at 9 15 47 pm](https://user-images.githubusercontent.com/1202909/27845522-14d9fb6e-60fe-11e7-876f-8310a9a5c7af.png)

What would be the correct way to integrate this RN plugin for RN but not for web?

**Comment by erictraut** [comment]
Yeah, that's not valid JSX notation. Here's the way to do it.

```
let myView = (
   <RX.View>
     // ... Etc.
   </RX.View>
);

if (RX.Platform.getType() !== 'web') {
   myView = (
      <KeyboardAwareScrollView>
         { myView }
     </KeyboardAwareScrollView>
   );
}

return myView;
```

**Comment by erictraut** [comment]
Incidentally, this is another place where we use build-time aliasing to avoid the overhead of runtime conditional checks. We have a component called KeyboardAwareView, and we have slightly different implementations for iOS, Android, and Windows UWP. For web, it's basically a no-op implementation.

**Comment by MovingGifts** [comment]
Thanks for the quick response, so a few things..

1. When I use the valid JSX syntax of `myView` and I use `import { KeyboardAwareScrollView } from 'react-native-keyboard-aware-scroll-view'` it works on native, but on web it returns many errors related to RN, and does not render the web version of the view. I am not aware of any way to conditionally import packages for a view based on platform, and here the web tries to import the RN package, which breaks it on web. So is the correct way to handle these scenarios, where there are RN specific packages that aren't needed for web is to use aliasing?
2. Will the KeyboardAwareView component be added to ReactXP any time soon so we can use it?
3. If aliasing is the correct way to handle this scenario, image assets, and possibly other scenarios coming from RN to RN + Web, would you be open to showing a working minimal app example with aliasing? (I really tried my best with the image assets to get them to work with aliasing, but due to the errors and me knowing react native and being new to TypeScript, even though I took a course in TypeScript, I could not get past the errors I posted in the image aliasing issue).

I honestly feel very frustrated since I know RN really well and have an almost complete app; yet I can't seem to connect the dots to have it working on the web with the same code base using ReactXP because of aliasing being a roadblock (without a solid functioning example to follow as a new comer).

**Comment by erictraut** [comment]
1. Yes, aliasing is the best approach here. You could also create a new ReactXP plugin by copying one of the existing plugins (e.g. reactxp-video).
2. We don't have any plans to add KeyboardAwareView to the ReactXP core. It might make for a good ReactXP plugin, but it's not currently on the priority list.
3. I'm not sure if I'll have time to put together another sample this week. I'll add it to the backlog. Maybe someone else in the community can help you out here.

**Comment by MovingGifts** [comment]
Thanks for the responses, I ended up going with this for now as it works so far:

```
let myView = (
   <RX.View>
     // ... Etc.
   </RX.View>
);

if (RX.Platform.getType() !== 'web') {
   var { KeyboardAwareScrollView } = require('react-native-keyboard-aware-scroll-view');

   myView = (
      <KeyboardAwareScrollView>
         { myView }
     </KeyboardAwareScrollView>
   );
}

return myView;
```
