### ISSUE TITLE
How to use ReactXP storage api?

### ISSUE THREAD

**Issue by RohitLuthra19** [Microsoft/reactxp#156]
I am new in <code>ReactXP</code> and I am trying to create a small app using Microsoft <code>ReactXP</code> framework. I want to save key value pair in my local storage. Microsoft provided an api called Storage
https://microsoft.github.io/reactxp/docs/apis/storage.html
https://github.com/Microsoft/reactxp/blob/master/src/web/Storage.ts

And I am trying to use it as 

    onLoginPressed(){
            const user = new User(this.state.userEmail, this.state.password);
            RestClient.login(user).then(success => {
                alert(success.message);
                Storage.setItem('userEmail', success.userInfo.userEmail);
            }).catch(error => {
                alert('Error in login');
            });
        }

but it showing an error 

    ERROR in [at-loader] ./src/Login.tsx:102:21
        TS2339: Property 'setItem' does not exist on type '{ new (): Storage; prototype: Storage; }'.

After understanding the flow of typescript and ReactXP I updated my code as 

```
onLoginPressed(storage: Storage){
        const user = new User(this.state.userEmail, this.state.password);
        RestClient.login(user).then(success => {
            alert(success.message);
            storage.setItem('userEmail', success.userInfo.userEmail)
            this._onPressNavigate();
        }).catch(error => {
            alert('Error in login');
        });
    }
```
But now I am getting following error

![screen shot 2017-07-06 at 12 13 57 am](https://user-images.githubusercontent.com/11659536/27879700-1947ff4c-61e0-11e7-848f-9344c0e99607.png)

Is my code is correct or not? If not please help me to understand it.

**Comment by erictraut** [comment]
You need to import ReactXP. The Storage namespace is accessible from that namespace.

Here's a modified version of your code.

```
import RX = require('reactxp');

onLoginPressed() {
        const user = new User(this.state.userEmail, this.state.password);
        RestClient.login(user).then(success => {
            RX.Storage.setItem('userEmail', success.userInfo.userEmail)
            this._onPressNavigate();
        }).catch(error => {
        });
    }
```

**Comment by RohitLuthra19** [comment]
Thanks @erictraut

**Comment by RohitLuthra19** [comment]
Thanks @erictraut
