### ISSUE TITLE
Is Drawer Navigator available in ReactXP?

### ISSUE THREAD

**Issue by RohitLuthra19** [Microsoft/reactxp#157]
As I have used the stack navigation easily from this documentation https://microsoft.github.io/reactxp/docs/components/navigator.html. Is there is support or feature of Drawer in ReactXP as in https://reactnavigation.org/docs/navigators/drawer

**Comment by MovingGifts** [comment]
Nope, but there is a custom component implementation you can use [here](https://github.com/Microsoft/reactxp/issues/137)

Navigator will be removed soon from ReactXP, so I think you'll be able to use the react navigation package pretty soon.

**Comment by RohitLuthra19** [comment]
So. Should I not use ReactXP Navigator and wait for the react navigation package.

**Comment by erictraut** [comment]
If you're looking to implement drawer functionality and want it to work the same across native and web, I recommend implementing it within ReactXP directly. Sample code is provided in the other thread.

If you're looking for a stack navigator mechanism on small screens (native only) but want to use the same views in a composite (side-by-side) navigation structure on web and large screens (tablets), you should use the react navigation package for small-screen native platforms. For more information about stack-based and composite navigation, refer to [this](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html) blog post.

**Comment by RohitLuthra19** [comment]
Thanks @erictraut

**Comment by geminiyellow** [comment]
hey everybody, how about now?  one year later.

> Navigator will be removed soon from ReactXP

i think navigator is still here, and i still cannot use drawer.
