### ISSUE TITLE
TextInput placeholderTextColor not working on web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#158]
It seems that only native picks up the `placeholderTextColor` prop, but not web. Why not on web? 
I thought it should apply to all platforms, correct?

**Comment by erictraut** [comment]
I don't think there's a standard way to do it in HTML. It may be possible within some browser-specific extensions or DOM manipulations. If you have a specific implementation in mind, feel free to submit a PR.

**Comment by MovingGifts** [comment]
I see, I just thought it would implement something like [this](https://css-tricks.com/almanac/selectors/p/placeholder/):

Here is what I ended up with from the linked resource:
```
::placeholder {
  color: red;
  opacity: 1; /* Firefox */
}
::-webkit-input-placeholder { /* Chrome/Opera/Safari */
  color: red;
}
::-moz-placeholder { /* Firefox 19+ */
  color: red;
  opacity: 1;
}
:-moz-placeholder { /* Firefox 18- */
  color: red;
  opacity: 1;
}
:-ms-input-placeholder { /* IE 10+ */
  color: red;
}
```
I am not sure how pull requests work, and how to implement it on a per TextInput basis (to scan for the `placeholderTextColor` prop on each TextInput, and apply the color respectively).

As a workaround though, since I use the same `placeholderTextColor` on all fields for the most part, adding the above in `index.html` works nicely :)

**Comment by MovingGifts** [comment]
If anyone is willing to add that to ReactXP to work out of the box with `placeholderTextColor` as intended, please feel free :)
