### ISSUE TITLE
Windows Build & TS

### ISSUE THREAD

**Issue by Chathula** [Microsoft/reactxp#16]
When you guys have planned to implement this with Windows Mobiles? Will it come soon?

Can i use reactxp without using typescript ?

**Comment by rohmanhm** [comment]
Yes you can,
you can also using Flow.

> While it is possible to write ReactXP apps in JavaScript, we recommend using TypeScript or Flow instead.

https://microsoft.github.io/reactxp/docs/getting-started.html

**Comment by Chathula** [comment]
If i don't use TS , it is same as RN :-/ what is the + using this instead of RN. (yet there is no windows build too)

**Comment by erictraut** [comment]
I just added a new FAQ that answers your questions and more:
https://microsoft.github.io/reactxp/docs/faq.html

**Comment by erictraut** [comment]
As for Windows Mobile, we don't have a timeline that I can share with you at this time. Contributions to ReactXP are welcome if you want to work on it.

**Comment by Chathula** [comment]
grate!! waiting to see windows build!
