### ISSUE TITLE
VirtualListView onEndReached/onRefresh implementation?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#160]
Coming from react native's `FlatList`, we have these properties:

- Scroll loading (onEndReached): Typically fires off an action to fetch more data (ex. page 2+ data) when scrolling hits the bottom of the list (uses a `onEndReachedThreshold` which is a number distanceFromEnd)
- Pull to refresh (onRefresh / refreshing): Typically fires off an action to fetch new list items and refreshes the list with the new items.

A few questions on this issue:
1. Can one use `FlatList` as is from RN?
2. How can it be implemented using ReactXP's `VirtualListView`?

What's the recommended approach to have this working in ReactXP?

**Comment by erictraut** [comment]
Sure, you can use any RN components you want and combine them with ReactXP. The RN components won't work on web, of course.

The current VirtualListView implementation doesn't support a callback based on scroll position. It assumes that you have the list of items available at the time you render the view. The items themselves are not rendered unless/until they come into view. You could add a scroll callback pretty easily if you want to fork the VirtualListView.

**Comment by erictraut** [comment]
Read the code for VirtualListView. I think it will be pretty obvious where to add it.

**Comment by MovingGifts** [comment]
I read it before opening this issue :)

The closest thing I see is the following, but I don't see `scrollBottom`, where I can put `0`:
 
`onScroll?: (scrollTop: number, scrollLeft: number) => void;`

So is the correct way to calculate the height of the list and use that as the `scrollTop` number?

**Comment by MovingGifts** [comment]
No worries, went with a different approach. I was just trying to map out RN functionality with web :) Thank you for all your responses though and for opening up `VirtualListView` :)
