### ISSUE TITLE
VirtualListView context error?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#161]
Testing out the `VirtualListView` example from the docs produces the error below when navigating to the example set up as a page in js (gist included):

Here is the error:
`FocusableComponentMixin: context error!`

Here is the screenshot:
![screen shot 2017-07-08 at 5 02 38 pm](https://user-images.githubusercontent.com/1202909/27989081-66d8060a-63ff-11e7-834b-b9481f6a2776.png)

[Here](https://gist.github.com/MovingGifts/f6e13e59a2f9e73143017e5727635219) is the gist to reproduce the issue. Any idea how to fix it?

**Comment by pixare40** [comment]
I had this error as well. Upgrade your ReactXP version in package.config and it will be resolved. What is the version you are using now if I may ask?

**Comment by MovingGifts** [comment]
I setup the ReactXP with `create-xp-app` so it has the version included in [this setup](https://github.com/react-native-training/create-xp-app/blob/master/src/package.json).
Which turns out to be`0.42.0-rc.9`

**Comment by pixare40** [comment]
Yeah just upgrade to 0.42.0-rc.10 and all will be well

**Comment by MovingGifts** [comment]
Let me try to update it to the latest manually and I'll check back in :)

**Comment by MovingGifts** [comment]
Thanks a lot, works as intended :)
