### ISSUE TITLE
Web animation differs from Native for parallel translateX and translateY transforms

### ISSUE THREAD

**Issue by Gregor1971** [Microsoft/reactxp#163]
Performing parallel timing animations for both translateX and translateY appears correct in Native... diagonal movement.   (only tried Android)

On the web side, there seems to be a problem.  In parallel, the translate that is set last is the only one to take effect.

[This gist](https://gist.github.com/Gregor1971/0a7e7d9a30a95ed597fa92e16d8ede56) contains a ReactXP component that demonstrates the issue.  When run for web, the sequence timings behave strangely (resets X), and the parallel shows only the Y movement.  There's also a [component for vanilla React](https://gist.github.com/Gregor1971/6be7ec4f19f2fdfed6d2c902db8f6c0f) that works as expected.

The "X Last" and "Y Last" text elements show the same without updating the values.

I merged PR #149 locally, since the changes do touch web Animated, but they're not enough.

**Comment by erictraut** [comment]
Thanks for the bug report. This is a known limitation in the current web implementation of Animated. The current workaround is to nest two RX.View elements and apply separate animated values to each. A little less elegant, but pretty straightforward.

**Comment by erictraut** [comment]
I checked in a fix to the master branch that addresses this limitation. I also updated the unit tests to check for this case.
