### ISSUE TITLE
Separate files for native/web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#164]
Just wondering if we have many platform conditionals in files, it may be better to use a `component.web.js` files, which would have just the web version of the file to render. I am also not sure if many conditionals in files would slow down the app when it's running, since it'll have to do the checks each time it loads those files.

What's the recommended way to handle this in ReactXP for production?

**Comment by erictraut** [comment]
There are very few conditionals in the ReactXP implementation itself. 

As for app-level code that builds upon ReactXP, that's completely up to you. My recommendation is to use a build-time "aliasing" solution like the one I outlined earlier. This completely eliminates the overhead of runtime conditionals — and guarantees that package sizes are kept to a minimum.

**Comment by MovingGifts** [comment]
Thank you :)
