### ISSUE TITLE
Feature Request: Window Size Change Event

### ISSUE THREAD

**Issue by ricklove** [Microsoft/reactxp#166]
A Cross Platform Window Size Change Event would be helpful.

I would expect it to be:

```typescript
RX.UserInterface.windowSizeChangeEvent.subscribe(e=>...)
// Or to match measureWindow:
RX.UserInterface.windowMeasurementChangeEvent.subscribe(e=>...)
```

This would be useful for detecting orientation changes on device, or window size changes in browser.

**Comment by erictraut** [comment]
We felt this would be redundant because you can already implement this event by adding an onLayout callback to the top-level element in your view hierarchy.

**Comment by ricklove** [comment]
Ah, in that case, maybe a note in the documentation where one would expect to find this (as an event next to the MeasureWindow method):

https://microsoft.github.io/reactxp/docs/apis/userinterface.html

**Comment by erictraut** [comment]
@ricklove good suggestion. I just modified the documentation.

**Comment by ricklove** [comment]
Perfect, thanks!
