### ISSUE TITLE
RX.Alert doesn't support buttons on web

### ISSUE THREAD

**Issue by berickson1** [Microsoft/reactxp#169]
If I create an alert that has buttons using RX.Alert, it displays a browser toast without buttons. ON web I can never invoke the callback of buttons.

**Comment by erictraut** [comment]
This is a limitation of the web Notification standard. I don't see any way around this. Do you have suggestions? The web standard does provide a single onClick event that is invoked when the user taps on the notification. We could somehow pass that back through ReactXP, but I don't think that's what you're looking for.

**Comment by berickson1** [comment]
I'm not really sure what the proper behaviour should be, but the component doesn't really conform to the ReactXP idea of cross-plat compat.

Some browsers (firefox/safari) also automatically close these alerts after a few seconds, meaning the user may never see them

Potential Options:
1) Update the docs to indicate that RX.Alert isn't properly supported on web
2) Change RX.Alert to be a custom styled modal on web with buttons (more like native)

**Comment by erictraut** [comment]
@apotra I think you wrote that module originally, right? Do you have a strong opinion one way or another?

**Comment by psegalen** [comment]
Hi you two,
I personally think that web notifications are pretty useful as, like the push notifications on a mobile OS, it can reach users even if they are outside the app (for example if the browser has been minified).
But I agree 100% with @berickson1 about the cross-platform side.
Plus, web notifications aren't alerts (like js `alert()`) so I would go for @berickson1's option 2 for `RX.Alert` and I would create a `RX.Notification` sending a web notification on web and a local notification on Android (I think local notifs aren't supported by iOS), what do you think?

**Comment by MovingGifts** [comment]
I think option 2 would be best for web.

**Comment by MovingGifts** [comment]
I think it's best for the RX.Alert to be written once and work cross platform from the ReactXP side. For web, the RX.Alert with functional buttons (which work on mobile) should be transformed to a modal with functional buttons.

Any chance of this getting implemented as part of core ReactXP?

**Comment by erictraut** [comment]
The challenge with this approach is that we'd need to pick some style for the buttons, and it's possible (likely?) that this style won't match the style in the rest of your app. In all other cases, ReactXP is completely style-agnostic. I guess we could provide style overrides for the various components of the alert dialog so callers can "skin" it to match the rest of their app.

**Comment by MovingGifts** [comment]
I totally agree with the skinning approach here; as long as the developer can override the styles and get alert to modal functionality on web, that would make it cross platform :)

**Comment by MovingGifts** [comment]
@erictraut Just wondering if there is any update on the web alert?

**Comment by erictraut** [comment]
I don't think anyone has done any work on it. @berickson1, was your original bug report prompted by a particular need, or was it just an observation?

**Comment by berickson1** [comment]
The original bug report was found due to an internal usage of RX.Alert with buttons on web, resulting in the user unable to take an action on the alert

**Comment by MovingGifts** [comment]
Would someone from the `ReactXP` team be able to make `RX.Alert` work on web as well so the same alert w/action buttons can be written once and work X platform?

**Comment by MovingGifts** [comment]
btw, I meant as a modal as suggested by @berickson1:

> 2. Change RX.Alert to be a custom styled modal on web with buttons (more like native)

**Comment by psegalen** [comment]
I've created PR #219 to achieve that, @erictraut & @berickson1: please tell me if this is what you had in mind and if the code matches your global practices.

**Comment by MovingGifts** [comment]
@psegalen Awesome, thank you for this! I look forward to using it once it's accepted by @erictraut

**Comment by psegalen** [comment]
I've added two examples of usage (one standard and one styled) in the hello world sample. None of the styling props is mandatory and one can use only some of it.

**Comment by erictraut** [comment]
Thanks @psegalen. I'm on vacation this week and next and have very limited internet connectivity. I'll take a look at it when I return.
