### ISSUE TITLE
WebView iframe on iOS Safari not scrolling

### ISSUE THREAD

**Issue by pixare40** [Microsoft/reactxp#174]
The WebView component iframe is not scrolling on iOS 10 mobile safari. My code looks like so:
![capture](https://user-images.githubusercontent.com/6998142/28250582-fe30914c-6a63-11e7-8e82-437f77afc73a.PNG)

I have tried wrapping it in a scrollview component and a view component but none seems to work. 
applying the style `-webkit-overflow-scrolling: touch;` via desktop safari debugging dev tools following this: https://davidwalsh.name/scroll-iframes-ios seems to fix it. How can I do this with ReactXP? I have tried forking the project and applying the style `WebkitOverflowScrolling: "touch",`  to the ScrollView component following this: https://stackoverflow.com/questions/39053177/how-to-set-webkit-overflow-scrolling-inline-style-on-react-component but the style seems to get stripped. I added it to these bits of code in the scrollview:
![capture3](https://user-images.githubusercontent.com/6998142/28250637-a150ac44-6a65-11e7-9029-1495be278a98.PNG)
![capture4](https://user-images.githubusercontent.com/6998142/28250638-a53eef64-6a65-11e7-857d-c8452d43fdcc.PNG)

**Comment by erictraut** [comment]
You shouldn't need to wrap it in a ScrollView. WebViews should provide scrolling capabilities if the web content is taller or wider than the viewport. Does the app work as you expect on browsers other than iOS 10 mobile safari?

Out of curiosity, why would you want to run a ReactXP app within an iOS browser? The whole purpose of ReactXP is to enable native apps for mobile platforms.

**Comment by pixare40** [comment]
Yes it works well for all other browsers except mobile safari. Not just iOS 10 safari but all mobile safari. I wanted a situation where if you didn't have the app installed you could still get a scaled down version on the web. Like most app companies provide. Is there a way i can apply the style in the fork? And prevent it getting stripped out?

**Comment by erictraut** [comment]
Of course, you're welcome to do anything you want in your own fork. I don't think that ReactXP is stripping it out, however. I suspect that ReactJS is doing so. You can step through the render method of ReactXP's WebView to confirm.

**Comment by pixare40** [comment]
Ah ok i managed to fix this by using classNames on the web view control and using a css stylesheet. Works ok. Thank you for the feedback @erictraut
