### ISSUE TITLE
No React Windows components

### ISSUE THREAD

**Issue by ArcadixPascal** [Microsoft/reactxp#178]
hi
While React XP seems a great concept it doesn't seem viable (unless one has the development power Microsoft / Skype has). There seem to be virtually no components available for Windows Universal (e.g. Js.Coach does not even have a filter for Windows React Components.....). Also any mentioning of React Native and Windows Universal goes back to 2016 (in a google search). I dont think Microsoft is serious when it comes to React Native and Windows Universal. 

Or am i mistaken somehow?

thanks for your info.

**Comment by erictraut** [comment]
ReactXP currently has full support for iOS, Android and web. 

Windows UWP support has been a lower priority, but there are now developers working on it. I don't have any ETA at this time. If this is important to you, contributions are welcome.
