### ISSUE TITLE
Nested buttons issue

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#180]
Coming from react native I was able to nest `TouchableHighlight` in this scenario:

A `TouchableHighlight` list item with an `onPress={() => alert('box')}` with a nested child `TouchableHighlight` with an `onPress={() => alert('box child')}`

I've been changing the `TouchableHighlight` to `RX.Button` for web, so I changed both to be buttons, but I get an error that buttons can't be nested. In response, I changed the parent to a `<RX.View onPress={() => alert('box')} ignorePointerEvents={true}` with the child as a `<RX.Button onPress={() => alert('box child')}` but when I click the child, the parent alert fires.

How can I get the respective element to alert its onPress?

**Comment by erictraut** [comment]
Buttons can't be nested due to limitations on the web (the HTML DOM). Do you need both components to be clickable on the web, or is the nesting needed only for touch-based native apps? If so, you can use a GestureView for one of them instead. Just use the onTap prop.

**Comment by MovingGifts** [comment]
Yup, so I am keeping the TouchableHighlights as is for native, but having a .web version of the files using ReactXP. If I click a child, it should only show the child alert, and if I click anywhere outside the child within the parent, it should only show the parent alert.

I tried a combo of what you mentioned, GestureView for one, button for another, I also tried 2 GestureViews, but no matter, when I click the child the child alerts, but then the parent also alerts.

Any idea how to only have the child alert without bubbling up to the parent?

**Comment by MovingGifts** [comment]
Still having the same issue.. does anyone know how to only have the child onTap/onPress trigger its respective call only, without triggering the parent's onTap/onPress in the process?

**Comment by dryganets** [comment]
There is an API to ignore pointer events, so if your problem is the element covering another you could consider this:
https://github.com/Microsoft/reactxp/blob/master/src/web/View.tsx#L278

Hope this will help you.

**Comment by MovingGifts** [comment]
@dryganets I tried `ignorePointerEvents={true}` on the parent before, but it only prevents `onPress` of the parent itself.

I created 2 boxes below to easily reproduce the issue:

```jsx
<RX.View onPress={() => alert('Parent')} style={{width: 100, height: 100, backgroundColor: 'red', alignItems: 'center', justifyContent: 'center'}}>
  <RX.Button onPress={() => alert('Child')} style={{width: 30, height: 30, backgroundColor: 'black', color: 'white'}}>
    <RX.Text>Child</RX.Text>
  </RX.Button>
</RX.View>
```
Here is how it should work:

Red box (parent) clicked? Parent onPress alert.
Black box (child) clicked? Child onPress alert. Parent onPress do _not_ alert. (The issue is the Parent _does_ alert when it shouldn't, since we clicked the nested child).

Any idea how to get it to work?

**Comment by dryganets** [comment]
Sorry for the delay in response. I had two 20h flights in the row.
Does it looks like an answer to you:

```
const styles = {

 buttonStyle: RX.Styles.createButtonStyle({
        width: 30,
        height: 30,
        backgroundColor: 'black',
    }),

viewStyle: RX.Styles.createViewStyle ({
        width: 100, 
        height: 100, 
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center'
    }),
}

 _childClick = (e: RX.Types.SyntheticEvent) => {
        alert('Child');
        e.stopPropagation();
    }

  <RX.View onPress={() => alert('Parent')} style={ styles.viewStyle}>
                <RX.Button onPress={ this._childClick } style={styles.buttonStyle}>
                            <RX.Text>Child</RX.Text>
                        </RX.Button>
                    </RX.View>
```

**Comment by dryganets** [comment]
stopPropagation stops event bubbling.

**Comment by MovingGifts** [comment]
@dryganets No worries and thank you so much; `stopPropagation` worked perfectly :)
