### ISSUE TITLE
Popup to only close via dismiss

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#183]
If you click anywhere outside a popup it dismisses the popup which is great, but in some popups with fields, we need to explicitly dismiss the popup by clicking a button inside the popup (which runs `RX.Popup.dismiss(_popupId)` and some other functions) So clicking outside should NOT dismiss the popup, only the button press should.

Is there anyway to disable outside clicks from dismissing the popup so we can dismiss it explicitly?

**Comment by erictraut** [comment]
There's currently no way to do this, but I'd be open to adding it as a PopupOption. Alternatively, you can implement it without using a Popup and simply render a View at an absolution position on top of your other visual elements. This is pretty straightforward unless you want/need to take advantage of the complex positioning logic in RX.Popup.

**Comment by MovingGifts** [comment]
Yup the complex positioning of the popup is needed, would be a great PopupOption :)

**Comment by erictraut** [comment]
Sounds reasonable. Feel free to submit a PR. Make sure to implement it on both react native and web.

**Comment by MovingGifts** [comment]
I feel that my skill level doesn't allow me to make this implementation in core; I was hoping someone from the ReactXP team or someone more comfortable with the core would implement it, but I totally understand if it doesn't get added.

I think it will be a useful core addition :)

**Comment by erictraut** [comment]
I've added the new option to PopupOptions. It's called preventDismissOnPress, and it's implemented on both web and native. It will be available through npm the next time reactxp is published (typically about once a week).

**Comment by MovingGifts** [comment]
Awesome! Thank you so much :)
