### ISSUE TITLE
VirtualListView: Responsive width of items, scrollbar, load more

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#185]
This question is 3 fold:

1. On web, my `VirtualizedList` items should have a `width: 700` but a `width: 320` (in case of user viewing from phone web). How can this responsiveness be done with ReactXP? In normal web css, we use media queries, but not sure how to handle this with ReactXP.

2. In most websites, there is a full page height scroll bar on the right hand side of the scrollable pages, and when you scroll down to a list of items, you automatically scroll through the items by scrolling the page (and can have a sticky header). With `VirtualizedList` the scroll bar is only applied to the list itself when it has many items, but the top header area is missing a chunk of the scroll bar which makes the page look weird. Is there any possible to solution to this (so the scrollbar fills the page height)?

3. I want to include a load more button at the end of the list, so when you scroll all the way to the bottom of a 50 item list for example, the button is there at the end of the list. What's the correct way to include it (does it become a list item, or is there a better way)?

**Comment by erictraut** [comment]
I presume that you're talking about the VirtualListView (i.e. reactxp-virtuallistview)? Or are you talking about some other "VirtualizedList" component?

The width of VirtualListView items is determined by the width of its container. You can use whatever strategy you want for responsive widths. I talk about the approach we used in Skype in this [blog article](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html).

I'm not sure what you mean by "top header area". The VirtualListView has no concept of a "header". 

The "load more" button would be a list item at the bottom.

**Comment by MovingGifts** [comment]
1. Yup I meant `VirtualListView`, sorry about the name mix up.

2. I went over the article, but I didn't see any way mentioned on how you get the window width to apply a certain width in the react js styles (I don't think I can mix media queries with the styles.js of each component, so not sure how to do it correctly).

3. I am struggling with the load more. I really need to be able to access the index of the items I am rendering so I can add the load more if there is a next pagination link only. Here is what I have so far for 10 items:
```
_renderItemsListItem(item, itemIndex) {
    console.log(itemIndex); // doesn't work, any way to get the index here?
    if(itemsStore.hasPaginationNextUrl && itemIndex == 10) {
      return (
        <RX.Button>Load More</RX.Button>
        );
    }

    return (
      <RX.View>
        <ListItem item={item} />
      </RX.View>
    );
  }
  ....
<VirtualListView
  itemList={ this.itemsListData }
  renderItem={ this._renderItemsListItem }
  skipRenderIfItemUnchanged={ true }
  />
```
Is there anyway to get the index of the item being rendered in the `_renderItemsListItem` function to be able to display the footer. I also just realized that since I display 10 items, and then the load more if the `itemsStore.hasPaginationNextUrl` exists, I am not even sure if that would work correctly.

Any idea how to implement this correctly?

**Comment by erictraut** [comment]
VirtualListView doesn't provide any way to determine the index of the items that are currently in view. You'd need to modify it to do this.

**Comment by MovingGifts** [comment]
Bummer... Is there any reason behind the index not being provided? I figured since I can't use the RN FlatList on web, which has a `ListFooterComponent` prop which handles this on mobile, I'd have to use the index for web using my approach above. But since it's not provided and I am not too technical, I am not sure how to proceed.

Any chance a footer prop or index can be provided by the library?

**Comment by erictraut** [comment]
We didn't need this functionality, so we didn't implement it. Doing so would require a fair amount of work. You're welcome to clone the code and modify it if you want, but we don't plan to add this functionality. Doing so would complicate an already-complicated component.

**Comment by MovingGifts** [comment]
Yeah it sounds pretty complicated. Did you guys use infinite scrolling then as a solution? I may give that a shot instead. I really just want to keep it as simple as possible to load more items :)

**Comment by MovingGifts** [comment]
Sorry to post again, but I am really stuck. I've been trying for hours to find a way to tell that I am scrolled all the way at the bottom of the list (so I can fire off a call to load more items) but I can't get any indication that the scroll position is at the bottom of the list. Also the heights of items can be different, so it would be hard to do a calculation of number of items x fixed height.

I added `onScroll` as it seemed like the only prop that deals with scroll position:
```
<VirtualListView
  itemList={ this.itemsListData }
  renderItem={ this._renderItemsListItem }
  skipRenderIfItemUnchanged={ true }
  onScroll={(scrollTop) => {
    this.endReached = scrollTop > 100 ? true : false;
  }}
  />
```
That updates `endReached` to true when I scroll down 100px, but I am trying to essentially have the opposite work, something like this:
  ```
onScroll={(scrollBottom) => {
    this.endReached = scrollBottom < 100 ? true : false;
  }}
```
But that doesn't exist. What am I missing to get this to work?

**Comment by MovingGifts** [comment]
@erictraut Thanks for your help :) I ended up using a regular `.map` for the portion where I needed to load more items (where I didn't have an entire list ready to serve). This works nicely and is much simpler than trying to integrate the footer from the RN `FlatList` to `VirtualListView`.
