### ISSUE TITLE
How to center vertically in ScrollView?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#186]
I am trying to vertically align an `ActivityIndicator` in a `ScrollView` but I get this instead:

![reactxp-scrollview-vertical-align](https://user-images.githubusercontent.com/1202909/28598010-096b5be8-716f-11e7-99ad-b511fd9aba0d.gif)

[Here is my gist.](https://gist.github.com/MovingGifts/ed3622f558cce077b0cca4276783e99f)

Note: If I use a `View` instead of a `ScrollView` I can get it to vertically align, but I am using a `ScrollView` around my screen views, so I am wondering how to align the activity indicator vertically to fill the remaining red space.

**Comment by erictraut** [comment]
Are you trying to center something vertically within the viewPort of the scroll view or within the scrolling (interior) view itself? It doesn't really make sense to center within the scrolling view because the height of the scrolling view is defined by its contents, not its viewPort. 

If you want to temporarily position something (like an ActivityIndicator) vertically within the viewPort, then make it a peer to the scroll view and use 'absolute' positioning so it is rendered above the ScrollView.

**Comment by MovingGifts** [comment]
When I load some results, I show an `ActivityIndicator`, if none exist, I show a placeholder "no items" vertically in the center of where they would appear.

When I load the results, scroll works perfectly, but when the content is the `ActivityIndicator` or the placeholder, it should be vertically center aligned where the results would appear (I think absolute positioning won't work in this case, since the header can also have additional items under it which occupy height before the lists start; also the placeholder should be within the actual list area, so cannot be absolute positioned).

I can hard code a `top: number` for the `ActivityIndicator`/placholder but only as a last resort, it would be much better to have those items vertically align, as it looks much better.

Any ideas?

**Comment by erictraut** [comment]
As I said above, the height of the scrolling view is defined by its contents. If it is smaller than the view port, it is always justified to the top. 

To do what you want, you will need to force the size of the contents to be the same height as the view port. You can do this by specifying an onLayout callback for the RX.ScrollView. You can then manually set the height of the RX.View within the scroll view.

Something like this:

```
private _scrollViewHeight = 0;

render() {
    var containerStyle = RX.Styles.createViewStyle({
        minHeight: this._scrollViewHeight,
        flex: 1,
        alignSelf: 'stretch',
        alignItems: 'center',
        justifyContent: 'center'
    }, false);

    return (
        <RX.ScrollView onLayout={ this._onLayoutScroll }>
            <RX.View style={ containerStyle }>
                <RX.ActivityIndicator size='large' color='gray'/>
            </RX.View>
        </RX.ScrollView>
    );
}

_onLayoutScroll  = (e: RX.Types.ViewOnLayoutEvent) => {
    this._scrollViewHeight = e.height;
}
```

**Comment by MovingGifts** [comment]
I see what you mean. I was thinking something like css's `height: 100%` as opposed to calculating it every time, not sure if this will impact performance as you navigate around the app since it will calculate it on each view.
