### ISSUE TITLE
VirtualListView renderItem never called

### ISSUE THREAD

**Issue by joshmanderson** [Microsoft/reactxp#188]
If a `VirtualListView` is wrapped by another view (e.g. `RX.View`, `RX.ScrollView`), then the `renderItem` prop function on the `VirtualListView` is **never** called.

If I make the `VirtualListView` the root of the **entire** component hierarchy (which in my case means making it the root view of my entire app), then the `renderItem` prop function is called normally.

Is there something that I'm missing here? Surely I'm doing something wrong...

An example render method where `this._renderItem` will be called:
```
render() {
    return (
      <VirtualListView
        itemList={this._listViewItemsFromProps(this.props.items)}
        renderItem={this._renderItem}
        style={styles.listScroll}
        skipRenderIfItemUnchanged={true}
        animateChanges={true}
      />
    );
  }
```

An example render method where `this._renderItem` will **not** be called:
```
render() {
    return (
      <RX.View>
        <VirtualListView
          itemList={this._listViewItemsFromProps(this.props.items)}
          renderItem={this._renderItem}
          style={styles.listScroll}
          skipRenderIfItemUnchanged={true}
          animateChanges={true}
        />
      </RX.View>
    );
  }
```

**Comment by ms-deregtd** [comment]
VirtualListView fills the container that it's placed in, so you need to size the containing view and then place it in there.  If you place it in an empty view, then that makes it 0x0 and so it doesn't render anything.

Also, please don't wrap it in a ScrollView. :)

**Comment by joshmanderson** [comment]
Oh ok. Thanks for the tip.
I'm extremely new to reactxp, may I ask why I shouldn't wrap it in a scrollview?

**Comment by erictraut** [comment]
The VirtualListView uses a ScrollView internally. Unless you really want a scrolling list within another scrolling list (which is generally bad UI design), you shouldn't include a VirtualListView in another ScrollView.

To fix your code above, give the containing RX.View the following style:
```
styles: {
    listContainer: RX.Styles.createViewStyle({
        flex: 1,
        alignSelf: 'stretch'
    })
}
```
This will force the container to expand to the size of its containing view (or the entire screen/window if it's at the top of the hierarchy)..

**Comment by joshmanderson** [comment]
Ah that makes sense, yeah I won't wrap it in a ScrollView.
Thanks for the example fix for the view style :)
