### ISSUE TITLE
Responsive elements?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#189]
I was wondering if something like this can be possible (specially for web):

The below is what I was looking to implement coming from [here](https://gist.github.com/grabbou/72767db51f97fe86cfea):
> I think it would be nicer to just nest the media query inside the selector like this, it looks more like the structure of media queries in css.

```js
StyleSheet.create({
  container: {
    fontSize: 16,

    '@media (min-width: 500px) and (min-height: 600px)': {
      fontSize: 10,
    },  
  },
});
```
or
```js
StyleSheet.create({
  container: {
    fontSize: 16,
  },
  '@media (min-width: 500px) and (min-height: 600px)': {
    container: {
      fontSize: 10,
    },  
  },
});
```

I've read the blog article on the Skype client btw for responsiveness, but I didn't really understand how to implement it into the app just like I would with media queries in the element defined styles.

**Comment by erictraut** [comment]
No, that approach won't work. It's not compatible with inline styles on the web nor with React Native. You'll need to use a different approach like the one I outlined in my blog article. Please give it another read, and let me know what's not clear.

**Comment by mghazanfar** [comment]
Okay. What I received from the blog is Skype is using some "ResponsiveWidthStore" that keeps Skype responsive. What if I want my Webpages to be responsive? No method has been declared either on blog or ReactXP website to use the "ResponsiveWidthStore". We are restricted not to use width in percentages then how can I make things responsive? My text vanishes when Webpage is opened on small devices! Help me Please!

**Comment by ms-deregtd** [comment]
We have a very simple store (it's like 15 lines of code) that listens for when the width of the master element changes, and then if it goes between certain breakpoints (x PX, y PX, z PX) it changes a master responsiveness parameter and emits that change.  Any components that need to be responsive listen for that store value and adjust their rendering appropriately.

For most percentage-based things, you should just be doing them in a flex-ey way.  Flex-grow will make your sub-component fill an appropriate ratio of space (sharing with its siblings) up to its parent's size.  So, do things with absolute sizes where needed (and responsively), and then use flex-grow to fill the rest of the space with dynamic-sized content.

**Comment by cptmcnugget** [comment]
@ms-deregtd could you elaborate how do you listen when the width changes? is it possible to do straight from the javascript? 

for example in plain React Native I would probably use 
https://facebook.github.io/react-native/docs/dimensions.html

**Comment by erictraut** [comment]
David is referring to something we call the "ResponsiveWidthStore". You can read more about it in one of my [blog posts](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html). We adjust the size using an onLayout prop on the outermost RX.View of the app. ReactXP implements the onLayout prop, which is called when the dimensions of the view change. 

If you use ReactXP, you can use various ReactXP extension that provide implementations on RN and the web. Video is a good example. You can see how it's used in the [HelloWorld app](https://github.com/Microsoft/reactxp/tree/master/samples/hello-world) provided with ReactXP.

If you need something that does not have a corresponding ReactXP extension, you can either write your own extension or write conditional code within your app that selects the appropriate implementation.

Yes, in a ReactXP app, your package.json would have dependencies for both native and web.

I recommend you check out the HelloWorld sample to see if it makes sense.
