### ISSUE TITLE
Mac OS Support

### ISSUE THREAD

**Issue by yangwuan55** [Microsoft/reactxp#19]
There is [macos](https://github.com/ptmt/react-native-macos)

**Comment by zhengying** [comment]
+1 
please support MacOS

**Comment by erictraut** [comment]
We don't have any plans to add MacOS support at this time, but we are happy to accept contributions.

**Comment by Sioxas** [comment]
because of Microsoft

**Comment by jpca999** [comment]
What OS do you officially support ?

**Comment by chuyik** [comment]
@jpca999 
> ReactXP currently supports the following platforms:
>
> - iOS (React Native)
> - Android (React Native)
> - Web (React)
> - Windows 10 – UWP (React Native) - in progress
> 
> Other platforms such as Windows 7 & 8, MacOS, and Linux can be targeted using a web wrapper solution like Electron.

See https://microsoft.github.io/reactxp/docs/faq.html

**Comment by m1ck2** [comment]
Not your bullshit. 

    Life's short. So stand tall and live it to the fullest. Don't sell yourself short or you will end up with the short end of the stick. 

On 18 Apr 2017, at 12:25 pm, Edward Chu <notifications@github.com> wrote:

@jpca999

ReactXP currently supports the following platforms:

iOS (React Native)
Android (React Native)
Web (React)
Windows 10 – UWP (React Native) - in progress
Other platforms such as Windows 7 & 8, MacOS, and Linux can be targeted using a web wrapper solution like Electron.

See https://microsoft.github.io/reactxp/docs/faq.html

**Comment by QuantumInformation** [comment]
I got a fright for a moment, that you couldn't use this lib to dev on a mac.

**Comment by erictraut** [comment]
MacOS support is now (mostly) implemented, so I'm closing this issue.

**Comment by TooSweetVasu** [comment]
@erictraut , Thanks, This is great news!
Any plans to update the samples to include "macos" support or provide a simple tutorial to develop for Mac OS ?

**Comment by colinramsay** [comment]
> MacOS support is now (mostly) implemented, so I'm closing this issue.

Does this mean _native_ MacOS support? It would be good to get something added to the samples folder, happy to help if pointed in the right direction.

**Comment by divs1210** [comment]
Any updates on the docs?

**Comment by tsaiDavid** [comment]
@erictraut - would love any updates for usage on MacOS

**Comment by wbroek** [comment]
Any help or comment would be appreciated how to get ReactXP going for Mac OS

What I got so far is that I saw support in the source for platform, macos so we can define the platform as we run gulp
`cross-env NODE_ENV=development node node_modules/gulp/bin/gulp run --platform=macos` (of course you can create as an npm script)

Then created a index file for Mac OS; `index.macos.js` which contains the startup code to the files created with gulp task
`
var AppBootstrapperNative = require('./temp/macos/rnapp/js/app/AppBootstrapperNative.js');
`

We then run the Metro bundler (`npm start`) and it should not complain and run.

But if I now start an electron instance to localhost:8081 there is only a white screen and no errors what so ever....?

_It would also be nice if it could work with something like https://github.com/ptmt/react-native-macos it already has great support for react native components_
