### ISSUE TITLE
Modal allows interaction with underlying controls on Android

### ISSUE THREAD

**Issue by gianluca-nitti** [Microsoft/reactxp#192]
I read in the [Modal API docs](https://github.com/Microsoft/reactxp/blob/master/docs/docs/apis/modal.md) that

> This interface displays a view that overlays all other views rendered by the app, preventing any direct user interaction with the overlayed views.

which is working as expected on web - I can't click buttons in the underlying components when a modal dialog is shown - but, for me at least, not on Android (can't test for iOS).
In other words, in an application running on the Android emulator which is showing a dialog, I can click on buttons which are children of the view which is visible under the dialog. When I touch said buttons, their onPress event is fired even though there is an active Modal dialog which should prevent user interaction with them.

**Comment by erictraut** [comment]
Thanks for the bug report. This bug was specific to Android (didn't affect iOS). I published a new version of ReactXP (0.42.0-rc.22) that fixes the problem.

**Comment by gianluca-nitti** [comment]
Thank you for the very quick fix, just updated the reactxp dependency in my application to the latest version (0.42.0-rc.22) and everything works as expected.
