### ISSUE TITLE
BUG: TextInput OnChangeText does not trigger when changed back to initial value

### ISSUE THREAD

**Issue by ricklove** [Microsoft/reactxp#197]
TextInput OnChangeText event works fine, except in the case when the value is changed back to the initial value.

## Example

- 'abc' (Initial)
- 'abcd' (OnChangeEvent('abcd'))
- 'abc' (NO EVENT)

## Platform

- Web

## Version

- 0.42.0-rc.20

## Workaround

Use 'defaultValue' instead of 'value'

**Comment by erictraut** [comment]
Which platform(s)?

**Comment by ricklove** [comment]
So, I was still researching it. I have only confirmed on web. I am reading the source code to see if maybe I am behind...

**Comment by ricklove** [comment]
Ok, I found the problem in the debugger:

From https://github.com/Microsoft/reactxp/blob/master/src/web/TextInput.tsx:

```
    private _onInput = (e: React.FormEvent) => {
        if (!e.defaultPrevented) {
            let el = ReactDOM.findDOMNode<HTMLInputElement>(this);
            if (el) {
                // Has the input value changed?
                const value = el.value || '';

// ---
// NOTE: This compares to the state.inputValue which only ever gets an initial state value
// Changes will only trigger the event call if the value is different then (initial) value rather then the last value
// ---
                if (this.state.inputValue !== value) {
                    // If the parent component didn't specify a value, we'll keep
                    // track of the modified value.

// ---
// NOTE: This is only set if it is undefined
// So, the state.inputValue will only ever have initialState
// ---
                    if (this.props.value === undefined) {
                        this.setState({
                            inputValue: value
                        });
                    }

                    if (this.props.onChangeText) {
                        this.props.onChangeText(value);
                    }
                }

                this._checkSelectionChanged();
            }
        }
    }
```

## Suggested Solutions:

- Change the state.inputValue every time
- Track another value _lastChangeTextValue and call onChangeText if the value is different then _lastChangeTextValue

## Note:

This should also be made in the setValue method

**Comment by ricklove** [comment]
Ok, it seems a simple work around is to simply use 'defaultValue' instead of value.

I'm not sure what purpose 'value' serves in comparison to 'defaultValue'.

**Comment by erictraut** [comment]
I think it's working as designed. I've updated the documentation to make it clearer. You can use it in one of two modes — one where the value prop is specified and one where it's not. I'm not a big fan of this approach (seems somewhat inelegant and difficult to understand), but it's consistent with RN's TextInput component.

**Comment by ricklove** [comment]
Ok, well there is still a bug in the logic because if the ```value``` is set, **there is no way to know when the user changes the value back to the initial value.** I.e. if you rely on the onChangeText to inform you of every user input as it is made, it will not inform you any time the user changes the value back to the initial value.

**Therefore the ```value``` property can only be used to produce broken behavior as it is (and would be the source of a hard to identify bug that would be very frustrating to the end user).** 

If the onChangeText should trigger every time the value is changed immediately (which it does), it must also trigger when the user goes back to the initial value. (Because it has already notified of a change from the initial value, and it must now notify that that change was reversed.)

If the onChangeText only triggered upon onBlur or acceptance of the final value (which it does not do), then it would make sense to not trigger an event if the user manually reversed their change and essentially did a no-op.

**Comment by erictraut** [comment]
If `value` is set, any change that results in the text becoming something other than `value` will cause onChangeText to be called. In this mode of operation, the caller is expected to re-render the component with a new value — e.g. the string passed to onChangeText or a filtered version thereof. Here's some sample code.

```
render() {
   return <TextInput value={ this.state.filteredInput } />
}

_onChangeText(newValue: string) {
    this.setState({ filteredInput: this._filterInput(newValue) });
}
```

If you don't want to re-render the component each time the input changes, you can use the other mode of operation, which uses an `initialValue` prop.

**Comment by ricklove** [comment]
Ah, I see the use-case. 

Thanks for giving the example of the filter, that makes sense why this exists now.
