### ISSUE TITLE
open source Skype built on ReactXp

### ISSUE THREAD

**Issue by thisisjaiswal** [Microsoft/reactxp#198]
ReactXp is great news but the information and community around it is very limited. So starting a new project on it is little scary.  there are lots of questions, like can I use relay with this ?
while RN community is large and lots of starter kit and examples are available. having a complete working sample open sourced would help the developers in large extent.

**Comment by erictraut** [comment]
The back-end service APIs for Skype are not open, so we have no plans to release an open-sourced version of Skype.

However, if you're looking for a more complete ReactXP sample app, the (TodoList sample)[https://github.com/Microsoft/reactxp/tree/master/samples/TodoList] provides demonstrates many concepts including data binding, local storage, navigation and complex components built from ReactXP primitives.

**Comment by thisisjaiswal** [comment]
Basically, I wanted to use [RN + Relay/GraphQL with aws] and there are lots of samples/examples available with this combination. but couldn't find much with ReactXp. As its mentioned ReactXp is superset of RN so  everything which is possible with RN should be possible with ReactXp. RN community is pretty big. So if I choose ReactXp will it be [All of RN + some pretty good feature] OR [a whole new but mini world] ?? I'm not sure about it.  some clarification in this front would be every helpful. if I just replace RN with XP in any starterkit, will it work ? if yes, then its very exciting else I don't understand the benefit.  Finding solution for GraphQL would be I think answer to all my doubts. Is there any such samples available ?

**Comment by thisisjaiswal** [comment]
Btw, a sample GraphQL API like StarWars, can be built to open source Skype. 100% features are not required. but a good production sample would be every helpful to get started with ReactXp. and also with this MS can make an entry in opensource world of GraphQL.

**Comment by thisisjaiswal** [comment]
Hi, @erictraut , can you point me any sample for ReactXp+Relay (or apollo). or guide me if Apollo for RN will work with ReactXp.

**Comment by erictraut** [comment]
I'm not aware of any published samples using ReactXP+Relay. You should have no problem using ReactXP in conjunction with Relay/GraphQL. As with React and RN, ReactXP doesn't dictate the data binding or eventing mechanisms, so any such mechanism should work fine. Give it a try, and let us know if you run into any issues.

The purpose of ReactXP is to allow you to write apps that span RN and React JS (web). If you have no need to run your code in a browser, then ReactXP provides relatively little extra value, and I recommend sticking with just RN.

ReactXP is both a subset and a superset of RN. It's a subset in that it doesn't expose all features of RN. It exposes only those that we've found to be important and are applicable to RN.iOS, RN.Android, and web apps. It's a superset in that it provides some components and APIs that are not found within RN but build upon RN's capabilities.

You can choose to break ReactXP's abstraction and write parts of your app directly to the RN interface (or to native RN modules), but this code will necessarily be platform-specific, whereas code that strictly sticks with the ReactXP abstraction will be cross-platform.

**Comment by geminiyellow** [comment]
maybe a `real-world` example is better than the `hello-world`.

**Comment by erictraut** [comment]
This is why we've written the [https://github.com/Microsoft/reactxp/tree/master/samples/TodoList](TodoList sample). It's not a sophisticated app, but it's better than hello-world at demonstrating how to build a functional program.

**Comment by neelimabhukya** [comment]
how to implement google maps in reactxp

**Comment by andrespch** [comment]
is there any known on-production project demonstrating ReactXP on the browser?

**Comment by erictraut** [comment]
The Skype web client hasn't yet been released publicly. It's still in beta testing. You can use any of the sample projects to see demos of ReactXP in the browser, including the RXPTest app that I recently wrote. It exercises all of the functionality exposed by ReactXP.

**Comment by ASerga** [comment]
@thisisjaiswal, @geminiyellow I with some enthusiasts started e-shop project as complex examples. 
For API is GraphQL only (apollo-client).
https://github.com/react-cross-platform/reactxp-shop

@erictraut I also fill huge lack of complex examples, especially with responsive styling.

**Comment by ArtemSerga** [comment]
@thisisjaiswal, @geminiyellow I with some enthusiasts started e-shop project as complex examples. 
For API is GraphQL only (apollo-client).
https://github.com/react-cross-platform/reactxp-shop

@erictraut I also fill huge lack of complex examples, especially with responsive styling.
