### ISSUE TITLE
[RN 0.48] Update RN.NetInfo consumption

### ISSUE THREAD

**Issue by rigdern** [Microsoft/reactxp#199]
While submitting [a pull request](https://github.com/facebook/react-native/pull/14618) to Facebook, a couple of APIs got renamed.

Here's a summary of how the API changed in React Native 0.48:

| Old API | New API | Usage in ReactXP |
|---|---|---|
| `RN.NetInfo.fetch()` | `RN.NetInfo.getConnectionInfo()` | [link](https://github.com/Microsoft/reactxp/blob/011adaeea9697ea8c490cc27dc1a4cd7814b42c7/src/native-common/Network.ts#L38-L39) |
| enum returned by `fetch()` | [enums returned by `getConnectionInfo()`](https://github.com/facebook/react-native/blob/046f600cc23ff2d4aeb57be8e5606347f19b76d2/Libraries/Network/NetInfo.js#L103-L124) | [link](https://github.com/Microsoft/reactxp/blob/011adaeea9697ea8c490cc27dc1a4cd7814b42c7/src/native-common/Network.ts#L47-L60) |

**Comment by erictraut** [comment]
I made the required change.
