### ISSUE TITLE
Windows Phone is Really Dead?

### ISSUE THREAD

**Issue by be5invis** [Microsoft/reactxp#20]

**Comment by xiyouMc** [comment]
That`s a good question!!!

**Comment by fjaweihyafei** [comment]
This question reminds me of lots disappointed things...

**Comment by yunxifd** [comment]
I love windows phone!!

**Comment by huiliangShen** [comment]
good question...but, maybe no answer...

**Comment by landsman** [comment]
Sure. Look on these phones ... they are ridiculous.

**Comment by ladycc33** [comment]
im looking now. hello how r u
