### ISSUE TITLE
CRNA vs create-xp-app

### ISSUE THREAD

**Issue by thisisjaiswal** [Microsoft/reactxp#202]
ReactXp is great and lucrative. but its very difficult to leave CRNA for create-xp-app.

**Comment by ms-deregtd** [comment]
I always just take sample apps and start modifying them.  I've never understood the appeal of CRNA, since every app you're going to create is different.  Once a fully working cross-platform sample app exists, you can just modify that to add more functionality.

**Comment by thisisjaiswal** [comment]
any suggestions for "a fully working cross-platform sample app" ?

**Comment by erictraut** [comment]
I recommend looking at the [TodoList sample](https://github.com/Microsoft/reactxp/tree/master/samples/TodoList). It demonstrates simple navigation, local data storage, and data binding.
