### ISSUE TITLE
Expose an AppRegistry.registerComponent equivalent to allow multiple different root views in RN apps

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#203]
ReactXP is currently limited to one root component, `RXApp`, and doesn't allow for developers to register and use others.  This is a major limitation when integrating ReactXP into an existing iOS/Android application.  

Consider the scenario where a native app wants to have 2 react-based screens and the rest of the application is written in native code.  This isn't easily done with the current implementation of ReactXP due to the reliance on `UserInterface.setMainView` and the internal use of `RootView`.

Proposed solution:

- Expose an equivalent interface to `AppRegistry.registerComponent `
- Internally wrap that registered component in a higher-order component that:
    - uses `componentWillMount` to call `UserInterface.setMainView` with the original component
    - renders `RootView`.

I have a local (hacked) implementation of the above that makes me believe it is a feasible approach.  I'm happy to clean that up and send out a PR if this is something the team wants to implement.

**Comment by dryganets** [comment]
Hi @Fitzpasd,
The feature you want to add, exist in react-native only and we are trying to keep the core of the reactxp as slim as possible.
You could make a reactxp extension which exposes this API.
Feel free to use any of https://github.com/Microsoft/reactxp/tree/master/extensions/ as a template.
Remeber, you need to have a stubs/implementation for not react-native platforms to make it cross-platform.

**Comment by erictraut** [comment]
Hi @Fitzpasd, thanks for the submission. This is good work.

I understand @dryganets perspective, but I'm going to overrule him in this case. I think this is a worthwhile addition to ReactXP. However, I think we should reconsider the interface. Rather than exposing a new AppRegistry namespace, which is an RN-specific concept, I'd like to simply add a new method (perhaps "registerRootView"?) to the existing RX.UserInterface namespace that allows callers to register alternative root views.

I'd like to avoid complex or non-deterministic interactions between setMainView and registerRootView. Let's think about how to simplify that.

**Comment by Fitzpasd** [comment]
I like the idea of merging this interface into `RX.UserInterface`, I think that fits nicer.

The coupling with `setMainView` is concerning.  How about introducing a property on `RootView` that can be used to set the initial mainView in the ctor?

**Comment by Fitzpasd** [comment]
I opened another PR that implements the above approach.  Useful for discussion on how best to implement this.

**Comment by neelimabhukya** [comment]
how to implement datepicker or calander in reacrtxp?

**Comment by erictraut** [comment]
ReactXP doesn't currently expose a date picker or calendar control. The native platforms (iOS and Android) offer these controls through React Native. Browsers have no standard date/calendar controls, so you'd need to find/build something there.

**Comment by erictraut** [comment]
@neelimabhukya, let me suggest that you post questions like this in the [Gitter forum](https://gitter.im/msreactxp/Lobby?source=orgpage) that we've set up for ReactXP. Github is useful for submitting bugs and feature requests, but not as much for general questions like this.
