### ISSUE TITLE
Know when VirtualListItem is not visible.

### ISSUE THREAD

**Issue by pixare40** [Microsoft/reactxp#207]
Hello,

Is there a way to know when a VirtualListViewItem in the VirtualListView is no longer visible? Like is scrolled offscreen and is no longer visible?

**Comment by erictraut** [comment]
No, there's currently no way. It could be added. Feel free to fork a copy and/or contribute a PR.

**Comment by pixare40** [comment]
@erictraut Will do. Thank you
