### ISSUE TITLE
hr tage supported?

### ISSUE THREAD

**Issue by waheed25** [Microsoft/reactxp#209]
i want to use hr tage in reactxp is it possible to uselike that???
` <hr className={className} {...other} />; `
if yes than how??? anyone can give me an example

**Comment by erictraut** [comment]
No, there's no equivalent of <hr> for React Native, so it doesn't make sense to use it in a ReactXP app. There are other ways to render a horizontal separator line if that's your intent.

**Comment by waheed25** [comment]
can you explain in which way you are saying???

**Comment by erictraut** [comment]
If you're trying to render a gray divider bar, you can do so with a <RX.View> tag. Just style it with a fixed height (say, two pixels) and a backgroundColor of gray.
