### ISSUE TITLE
<RX.image/> tag is not working         

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#211]
Code     <RX.Image source={'https://www.w3schools.com/css/img_fjords.jpg'}/>.The page is blank without any errors.kindly comment plz

**Comment by erictraut** [comment]
Hmm, it's working for me. Which platform are you testing it on?

**Comment by erictraut** [comment]
Are you able to access that URL in other apps (e.g. a browser)? The sample code doesn't provide an onError handler, so if the image isn't able to load for some reason, it doesn't contain any logic to display an error message. You could, of course, add such logic.

**Comment by adnan1naeem** [comment]
@rachitGulati   Thanks for giving advice .It really worked.But I am facing an issue of adjusting image in container .can u please tell what is the alternate of  css property of background position in reactxp.It supports this property or not?

**Comment by adnan1naeem** [comment]
@rachitGulati Thanks for giving advice .It really worked.But I am facing an issue of adjusting image in container .can u please tell what is the alternate of css property of background position in reactxp.It supports this property or not?

**Comment by erictraut** [comment]
There is no equivalent of the CSS background position in ReactXP. No such property is available in React Native. It does support various resize modes.

**Comment by adnan1naeem** [comment]
@erictraut   Kindly tell the exact resize mode properties  supported by reactxp like background-Size in css

**Comment by erictraut** [comment]
Please refer to the [RX.Image documentation](https://microsoft.github.io/reactxp/docs/components/image.html).
