### ISSUE TITLE
React.NET

### ISSUE THREAD

**Issue by thisisjaiswal** [Microsoft/reactxp#212]
Hi Team,
As far as I have understood React and its ecosystem, It's not just 'A JAVASCRIPT LIBRARY FOR BUILDING USER INTERFACES', it's a CONCEPT. where instead of writing programs in a particular language, which can only be compiled by its compiler, we write everything (UI, events, animations, server calls...) as a function, and all... this function does is ... return a String. All the MAGIC happens in 'native modules', which takes this 'String Instructions' and translates them to native code to run in respective platform. 
These string instructions are, as of now, written in JSX syntax, then compiled to basic JavaScript, which then run on JavaScript engine, 
By going deep into this CONCEPT, I see an opportunity of .NET implementation of this,  React.NET.
where you will write string instructions in pure XAML, then compile to .net, and then run on CLR/mono engine.  
Now if JSX can be converted to Javascript, and XAML to .NET,
XAML to Javascript should be possible too, which will target web (which is a limitation in Xamarin).  
Being a Silverlight fan in past, It would be wish come true for us, to write web components in .NET again.
and I'm sure Microsoft is looking for such an opportunity too.

The possibilities seems to be limitless, I am even imagining a possibility of a compiler, which will convert these instructions directly to native code. 

Looking at the efforts being made by Microsoft, to capture Cross-Platform market,  I think this suggestion, for possibility of a React.NET framework, is worth a consideration.

**Comment by erictraut** [comment]
There is already a Windows version of React Native that is under development. In any case, what you're suggesting here is beyond the scope of the ReactXP project.
