### ISSUE TITLE
PaddingHorizontal on RX.TextInput isn't working at the html version

### ISSUE THREAD

**Issue by Kelvne** [Microsoft/reactxp#213]
PaddingHorizontal on RX.TextInput doesn't adds padding-right and padding-left to the input on the html version

**Comment by erictraut** [comment]
I tested it on both Chrome and Edge, and it seems to work fine in both cases. Can you provide more details or a code sample?

**Comment by MovingGifts** [comment]
@Kelvne make sure the `paddingHorizontal` is not an inline style of the element, but defined as an `RX.Styles.createTextInputStyle` and referenced in the element as a style.

**Comment by Kelvne** [comment]
@erictraut, @MovingGifts Yeah! That was the problem, I did that while testing some stuff at an inline style object of the style. Just tried with `createTextInputStyle` and it worked! 

This can be closed now!

**Comment by erictraut** [comment]
Yes, ReactXP requires that you call createXXXStyle to create styles. These methods transform some properties to make them compatible with HTML or React Native.
