### ISSUE TITLE
no ListView component?

### ISSUE THREAD

**Issue by LittleKey** [Microsoft/reactxp#22]
I'd like that very importance for mobile

**Comment by ajonno** [comment]
totally agree. any plans to provide a FlatList/ListView ?

**Comment by erictraut** [comment]
A cross-platform list view can be created using the primitives already defined in ReactXP. As such, we've decided not to add it as a peer component to the other primitives. We have developed a highly-optimized VirtualListView component that we use within Skype. It's more flexible and faster than the existing list views that we know of, and it's written using ReactXP, so it's completely cross-platform. I'd like to open-source that component at some point in the not-too-distant future.

**Comment by ajonno** [comment]
Brilliant! Do you have an eta on providing VirtualListView as part of ReactXP (open source) ?

**Comment by qingyangmoke** [comment]
VirtualListView ?  expect it .

**Comment by mogarick** [comment]
> I'd like to open-source that component at some point in the not-too-distant future
Does that means "maybe" or is it something really being added to the roadmap for the next month, quarter, etc.?
A ListView is something really fundamental. Even though people can use the basic building blocks available at this moment, doing an well implemented ListView is no trivial task as the very own FB React Native Team can attest. They've just released some new components for this matter. I'd like to hear a more clear position for the reactxp/Skype team about releasing its VirtualListView as part of ReactXP basic components.
Congratulations for this new lib that looks pretty promising!

**Comment by tswitcher** [comment]
I don't know what I was doing so please forgive me all I done was go threw
and look  if I started something bad for y'all please forgive me God bless

**Comment by erictraut** [comment]
I'm working on it, and I hope to have it published (along with documentation) possibly by the end of this week — or within the next month at the longest.

**Comment by erictraut** [comment]
I had time to work on it this evening. I've updated the repo to include a new ReactXP "extension" — a component called VirtualListView. I've included [documentation](https://microsoft.github.io/reactxp/docs/extensions/virtuallistview.html), which includes some sample code. I also published it on [npm](https://www.npmjs.com/package/reactxp-virtuallistview). Enjoy!
