### ISSUE TITLE
RX.TextInput - get height to expand text area?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#220]
I have a `RX.TextInput` with multiline true, to serve as a vertically expanding text area, depending on the height of the `RX.TextInput` content. I am trying to get the height of the `RX.TextInput` element but I can't seem to be able to get the height.

```js
<RX.TextInput
    multiline={true}
    ref="textArea"
    style={[styles.textArea, {minHeight: 20, height: this.refs.textArea.height}]}
/>
```

Any idea how to get the height of the `this.refs.textArea` `RX.TextInput` to achieve an expanding text input area? Is there a better way of having an auto vertically expanding text area? In React Native for example, we have TextInput's `onContentSizeChange`  property for this purpose, like so:

```js
<TextInput
    multiline={true}
    onContentSizeChange={(event) => {
        this.setState({ height: event.nativeEvent.contentSize.height })
    }}
   ...
/>
```
But no such prop exists in `ReactXP`, which is why I was going the ref route to get the height (which didn't give me the height btw).

How to get the height of a `RX.TextInput`?

**Comment by erictraut** [comment]
You can use the onLayout prop if you want to be notified of a height change in ReactXP.

**Comment by MovingGifts** [comment]
@erictraut `onLayout` doesn't seem to work with `RX.TextInput`, even though it works with `RX.View`

**Comment by erictraut** [comment]
Ah, you're right. We didn't provide an onLayout for TextInput.

**Comment by MovingGifts** [comment]
@erictraut Will `onLayout` prop be added to `RX.TextInput` (when back from vacation)? Is there any way of getting the actual height for the time being?

**Comment by erictraut** [comment]
Multiline TextInput controls are not designed to change in size based on the content. The height is assumed to be static (defined at layout time). If the multi-line text doesn't fit within the available space, the contents will scroll vertically within the control. It sounds like you want to have the control change height based on the contents. To do this, you'll need to measure the height of the contents and manually adjust the height of the control.

The height of the contents are not available directly in ReactXP today. I see a way that we might be able to implement it, but it's kind of gross. It would require using the onContentSizeChange prop on RN and the scrollHeight property on the web. I can put this on the backlog, but it's low priority.

In the meantime, you can use another technique that we use in the Skype client. You can write code to render the text from the RX.TextInput into a separate RX.Text. This text can be rendered beneath the RX.TextInput using transparent color (or at some location offscreen) so it's not visible. Unlike RX.TextInput, RX.Text will resize vertically to accommodate whatever text you render, and you can use its onLayout callback to measure the height of the contents. Then you can adjust the height of the RX.TextInput accordingly, perhaps applying some reasonable maximum height.

**Comment by MovingGifts** [comment]
Will give that a shot thank you :)

**Comment by MovingGifts** [comment]
It seems `RX.Text` also does not have `onLayout`, just the `RX.View`. I set up a [gist here](https://gist.github.com/MovingGifts/85314b8aa33af5240594171eacb16213) since I'm still having a hard time and spent two days on this already and pulling my hair out (and still can't get it to work correctly).

The gist will show two approaches:
```jsx
onLayoutInputLoaded = (e) => {
      // Aproach 1
      // this.inputHeight = e.height;
      // console.log(this.inputHeight);

      // Approach 2
      inputScrollHeight = ReactDOM.findDOMNode(this.hiddenTextArea).scrollHeight;
      this.inputHeight = inputScrollHeight;
      console.log(inputScrollHeight);
}
```
Both are close but not 100% correct behavior. If you start typing 1 thru 20 with enter after each number like this:
```
1
2
3
4
5
6
etc..
```
You will see that the text area on the bottom "shifts" the 1 up, but instead you should see all the content with no shifting at all (just like the text in the visible box above, which is to be hidden, but is just there for visual feedback). Also when you reach 3 and hit back space, it erases 3 but the blinking text input indicator is not right after 2, it is hidden where 3 was.

Is there any viable solution where it would work as expected with ReactXP?

**Comment by MovingGifts** [comment]
I have a [web example as well working perfectly here](https://codepen.io/anon/pen/WZRRGy) and the textarea expands/shrinks in react native as well, but I just can't get it to work in ReactXP.

Can someone please help? I can't get past this part with everything I tried.

**Comment by maanishoo** [comment]
For anyone that might encounter this issue, this seems to work:

                   <RX.View>
				<RX.TextInput
					value={value}
					onChangeText={onChangeText}
					style={[{height: this.state.height, minHeight: 28}, style]}
					{...props}
				/>

				<RX.View
					style={{position: 'absolute'}}
					onLayout={e => {
						this.setState({height: e.height + 28})
					}}
				>
					<RX.Text
						style={styles.text}
					>{value}</RX.Text>
				</RX.View>
			</RX.View>
