### ISSUE TITLE
How to implement table in reactxp?

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#221]
<RX.table> </Rx.Table>  not supported

**Comment by erictraut** [comment]
Please explain what you're trying to do in more detail. Tables are used for many purposes. You're correct that there's no such thing as an HTML-style "table" in ReactXP (or React Native, for that matter).

**Comment by adnan1naeem** [comment]
I  just want to add grid system or table in my code.I was wondering how to implement it

**Comment by erictraut** [comment]
You can build it out of Views using flexbox layout directives. For long vertical tables, you'll want to use a virtualized list such as [this one](https://microsoft.github.io/reactxp/docs/extensions/virtuallistview.html).
