### ISSUE TITLE
How to set default props in reactxp?

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#224]

**Comment by erictraut** [comment]
I don't understand your question. Please elaborate.

Some props are required; most are optional. If you don't specify an optional prop, the component will assume a default value for that prop. The documentation for each component explains which props are required and the default (assumed) value for each optional prop.

**Comment by Zydnar** [comment]
I need to use static defaultProps inside my Component but I don't know how to declare props to make from one side in parent component the property optional but inside this Component don't get errors like this.props[name]? is of type number|undefined. I think this is related question: [https://stackoverflow.com/a/40029990/4392611](https://stackoverflow.com/a/40029990/4392611) however it's old and the solution doesn't work for me

**Comment by deregtd** [comment]
Can you give a code snippet of what you're trying and what doesn't work?  That stackoverflow has the correct way to define default props in typescript, but it sounds like your issue is around some sort of optional typing?

**Comment by Zydnar** [comment]
Let's start with minimum, so I will know what I'm doing wrong:
```typescript
export interface SwipeCardsProps{ //I can't find React.Props so I can't extend as in SO answer
    cards: Card[];
    stackOffsetX?: number;
    stackOffsetY?: number;
//...other props
}
export class SwipeCards  extends Component<SwipeCardsProps, SwipeCardsState> {
    static defaultProps = {
    stackOffsetX: 25,
    stackOffsetY: 0,
    };

    someFunction = () =>{
        //where I get my error
        let offsetX = this.props.stackOffsetX * cards.length - i * this.props.stackOffsetX;
        //...
    }
//render and everything else
}

```

**Comment by berickson1** [comment]
@Zydnar - The following code compiles and works as you'd expect. Check to see if you're using the latest @types/react.

The interface type should list the prop as required, but the use-site will have a different type due to react typings "magic".

```
import React from 'react';
import RX from 'reactxp';

type Card = {
}

export interface SwipeCardsProps{ //I can't find React.Props so I can't extend as in SO answer
    cards: Card[];
    stackOffsetX: number;
    stackOffsetY: number;
//...other props
}

interface SwipeCardsState {}

export class SwipeCards  extends RX.Component<SwipeCardsProps, SwipeCardsState> {
    static defaultProps = {
        stackOffsetX: 25,
        stackOffsetY: 0,
    };
    someFunction = () =>{
        //where I get my error
        let offsetX = this.props.stackOffsetX * this.props.cards.length - 1 * this.props.stackOffsetY;
        console.log('offset ' + offsetX);
        //...
    }
    
    render() {
        this.someFunction();
        return null;
    }
}

export function renderComponent(): JSX.Element {
    return <SwipeCards
    cards={[{}, {}, {}]}
    />
}
```
