### ISSUE TITLE
How to have a checkbox and radio button in  reactxp

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#231]

**Comment by erictraut** [comment]
It's simple to write controls like check boxes and radio buttons using ReactXP primitives if you want them. See the hello world sample for a simple toggle control. 

Note, however, that 1980's-era checkbox and radio button controls are not very common on mobile apps. You might want to look at modern iOS or Android apps to get ideas for more touch-friendly controls.

**Comment by adnan1naeem** [comment]
In modern mobile apps we should go for switch instead of radios and checkbox.This is what you are telling?
