### ISSUE TITLE
Text component content can not change 

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/reactxp#233]
render(){
          let codeTex = this.state.checkCodeTime || 'Code';
          Log.i('@@@@@@@@@@@',codeTex +'');
　　　return (
                    <RX.Button onPress={this._onGetCode} style={[styles.codeBtn]}>
                        <RX.Text style={styles.codeTxt}>
                            {codeTex}
                        </RX.Text>
                    </RX.Button>
                    
);
} 
console log is 
![image](https://user-images.githubusercontent.com/5296419/29762303-7743e7ce-8c00-11e7-8308-7b4421818236.png)

**but the web interface not change ,the Button's text alway is 'Code'**

can tell me why ?

**Comment by erictraut** [comment]
Is checkCodeTime a number? You may need to convert it to text (e.g. call toString).

**Comment by wangfaxi1985** [comment]
when i change to this 
<RX.Text style={styles.codeTxt}>
{codeTex +''}
</RX.Text>
**it also always is ＇Code＇!!!!!!**
other question: why number can in Text ?

**Comment by wangfaxi1985** [comment]
I have another test 
    render() {
        const code = this.timer+" ";
        console.log('@@@@@:'+code);
        return (
            <fm.component.TitleComponent ref='titleLayout' isShowTitle={false}>
                <fm.component.widget.FitImage source='asserts/login/logo.png' style={styles.img}>
                </fm.component.widget.FitImage>
                <rx.Text>
                    {code}
                </rx.Text>
            </fm.component.TitleComponent>
        );
    }

bug always print:
![image](https://user-images.githubusercontent.com/5296419/29803864-307e2302-8cb1-11e7-8340-a3621a1dfd36.png)

**Comment by wangfaxi1985** [comment]
I change my code to this:
![image](https://user-images.githubusercontent.com/5296419/29819254-721997f6-8cf2-11e7-844d-34878b8f2628.png)
but:
![image](https://user-images.githubusercontent.com/5296419/29819325-d209fea8-8cf2-11e7-87b8-d6121cf6a839.png)

the Text Component 's content( children) always the first set string ,
cant change from ＇Code＇ to ＇56＇，＇54＇，＇53＇　．．．．

**Comment by wangfaxi1985** [comment]
！！！！！！！！！
i find the reason!!!!
my TitleComponent's State is:
interface State {
 children:React.ReactNode | React.ReactNode[];
}
delete the state's children property ,the program is ok
