### ISSUE TITLE
when navigator back,Component not call  componentWillUnmount (reactxp-navigation)

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/reactxp#235]
when navigator back,Component not call  componentWillUnmount -- (web)
i want a callback when navigator back?  how can i do 

reactxp-navigation:1.0.6

**Comment by dryganets** [comment]
I see the root cause of the bug - we have direct state manipulations in navigator for the web.
Trying to figure out why it is done this way as I'm not an author of this code.

Thank you for reporting this.

**Comment by wangfaxi1985** [comment]
i just read reactxp-navigation source ,()
because when pop back complete ,method :_cleanScenesPastIndex ,if condition　dissatisfaction ( i navigate to root Component)
