### ISSUE TITLE
Provision for platform specific Styles

### ISSUE THREAD

**Issue by shoaibmerchant** [Microsoft/reactxp#24]
I am trying to understand how the Styles system can be utilized to design components across screen sizes (any pointers?). In React Native there is an ability to create styles specific to platforms using the `Platform.select` api.

```
container: {
        ...Platform.select({
            ios: {
                // ios specific
            },
            android: {
                // android specific
            }
        })
    }
```
Is the same possible with ReactXP?

**Comment by erictraut** [comment]
It's important not to conflate platform with screen size. There are, after all, Android and iOS devices with larger screens, and some browser windows are very small. Screen size can also change while the app is running, whereas platform cannot. With that in mind, let's consider two questions:

1. How can components adjust their styles and behaviors based on screen size?
2. How can components adjust their styles based on platform?

For the first question, we've tried a number of approaches. The one that we found works best is a simple "ResponsiveWidthStore" that stores the current width of the screen. Components that want to change their behavior based on screen size can subscribe to this store and update their internal state based on the current screen size. We update this store through an onLayout handler at the top of our app's UI view hierarchy. I plan to write about this in more detail in an upcoming blog.

For the second question, we try to avoid platform-specific styles in general. In some cases, it's required. In those cases, we tend to use platform-specific overrides in our code. This allows us to maintain all of the common style attributes without duplication. Only the platform-specific overrides are then required.

```
container: RX.Styles.createViewStyle({
    marginHorizontal: 16,
    backgroundColor: '#eee',
    ...
}),
containerIOS: RX.Styles.createViewStyle({
    // Override the background color on iOS only
    backgroundColor: '#ccc'
})

<RX.View style={ [styles.container, RX.Platform.getType() === 'ios' ? styles.containerIOS : null] } />
```
I'm open to adding a platform selection API as well. I think that's more elegant than the solution we've been using in some cases.

**Comment by shoaibmerchant** [comment]
Thanks for the super insightful reply @erictraut and yes the screen size and platform specific styles should be addressed separately. I will look forward to your blog with more details on the approach

For the second question, the platform selection API will help keeping the code clean and the component independent of such overrides. I will check it out and see if I can add a PR.

**Comment by erictraut** [comment]
I dug into this a bit more. I don't like the way that Platform.select works in React Native because it does not allow for static type checking using TypeScript. We find that static type checking is very important for large and complex code bases, and we were careful when defining the ReactXP interface to construct it in a way that type checking can be effective. This is why, for example, we defined separate methods for createTextStyle and createViewStyle.

**Comment by sideshowfree** [comment]
I want all my text messages and call to be clear and readable with no codes

**Comment by sideshowfree** [comment]
I don't want any of my text messages and calls to be hidden I want them all clear with no codes

**Comment by sideshowfree** [comment]
I want all my text messages and call to be clear and readable with no codes

**Comment by joaodfmota** [comment]
Maybe:

```javascript
container: {
            ios: {
                // ios specific
            },
            android: {
                // android specific
            }
    }[Platform.getType()];
```
