### ISSUE TITLE
How to animate scroll to element across browsers?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#241]
I have 20 items (RX.View elements) and I want to scroll to item 7.

Here is the scroll to portion with the comments describing the issue of my current solution:

```jsx
scrollToRef(itemRef) {
  // The ref access here returns "is not a function" error not sure why as this.rowz[itemRef] does exist
  // this.rowz[itemRef].scrollIntoView({block: 'start', behavior: 'smooth'});

  // Since above doesn't work, we'll access the element from ReactDOM instead
  ReactDOM.findDOMNode(this.rowz[itemRef]).scrollIntoView({block: 'start', behavior: 'smooth'});

  // Issue is that using "scrollIntoView" some browsers will scroll with animation while others ignore the scrollIntoView options and jump to element without animation
  // Is there any way to animate the scroll across all browsers for a consistent animated scroll experience?
  // I know the offsetTop we need to scroll to is 460
  // ReactXP Code...
}
```
[Here](https://gist.github.com/MovingGifts/c481a234121260d3bfd395a9362e2a50) is a gist to reproduce the issue.

**Comment by erictraut** [comment]
If a browser doesn't support automatic animation, you would need to write JS code to animate the scroll yourself - using a timer.

**Comment by MovingGifts** [comment]
I can't seem to find something that helps; do you mind sharing a resource?

**Comment by erictraut** [comment]
Set a repeating timer (say, once every 10ms) that calls setScrollTop each time with a value that varies between the starting scroll value and the desired scroll value. You can either do it linearly (i.e. move the same amount each timer tick) or if you want to get really fancy, you can apply some easing function to it that makes it speed up or slow down as it's animating.

**Comment by MovingGifts** [comment]
Thank you for pointing me in the right direction :) I found [this resource](https://stackoverflow.com/questions/8917921/cross-browser-javascript-not-jquery-scroll-to-top-animation) to be very helpful.

**Comment by m1ck2** [comment]
Oh shit I may need a hand getting this started every ten minutes and then
email everyone.
