### ISSUE TITLE
Consider fully implementing RN's pointerEvents API

### ISSUE THREAD

**Issue by deregtd** [Microsoft/reactxp#243]
RX has a couple of APIs that deliver part of the functionality that RN's pointerEvents API delivers (I think RX's are booleans called ignorePointerEvents and blockPointerEvents). Replacing RX's ignorePointerEvents and blockPointerEvents props with pointerEvents would have a couple of benefits:
It would offer a more familiar API to RN users
It'll give RX more functionality

One concern might be about how to implement this on web. I think the web implementation could be done using a technique like the following:

// CSS rules that we can generate with JavaScript so RX doesn't need to ship with a stylesheet file:
.reactxp-descendants-pointer-events-auto * {
  pointer-events: auto;
}
.reactxp-descendants-pointer-events-none * {
  pointer-events: none !important;
}

// Then we'll set style and className like the following for the various values of the pointerEvents prop:

// When pointerEvents prop is 'none':
style.pointerEvents = "none";
className = "reactxp-descendants-pointer-events-none"

// When pointerEvents prop is 'box-none':
style.pointerEvents = "none";
className = "reactxp-descendants-pointer-events-auto"

// When pointerEvents prop is 'box-only':
style.pointerEvents = "auto";
className = "reactxp-descendants-pointer-events-none"

// When pointerEvents prop is 'auto':
style.pointerEvents = "auto";

**Comment by erictraut** [comment]
@deregtd, do you have a specific need for this? If not, I think we should just stick with the simpler (and already implemented) ignore/blockPointerEvents props.
