### ISSUE TITLE
Popup did not show in web

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/reactxp#249]
I want to toast String like android's toast:
`export type ToastOption = {
    getAnchor: () => React.Component<any, any>;
    content?: string;
    render?: (anchorPosition: rx.Types.PopupPosition, anchorOffset: number,
        popupWidth: number, popupHeight: number) => JSX.Element;
}

export let show = (option: ToastOption) => {
    if (!option.content && !option.render) {
        return;
    }
    if (option.content) {
        option.render = (anchorPosition: rx.Types.PopupPosition, anchorOffset: number,
            popupWidth: number, popupHeight: number): JSX.Element => {
            return rx.createElement(rx.Text, null, option.content);
        }
    }
    let popupOptions: rx.Types.PopupOptions = {
        getAnchor: option.getAnchor,
        renderPopup: option.render,
        positionPriorities: ['bottom'],
    };
    rx.Popup.dismiss(ID);
    rx.Popup.show(popupOptions, ID, 500);
    rx.Popup.autoDismiss(ID, 1500);
}
export let dismiss = () => {
    rx.Popup.dismiss(ID);
}`

in android ,it display in the center of screen

my Problem is :
1.how to set this pop to bottom of screen?
2.in web brower,this popup did not display

**Comment by wangfaxi1985** [comment]
![image](https://user-images.githubusercontent.com/5296419/30017561-517e5858-918c-11e7-8b81-b76879649d91.png)
this capture look like :
1.when call :rx.Popup.show(popupOptions, ID, 500);,_popupShowDelayTimer wiill be general
２．when call:rx.Popup.autoDismiss(ID, 1500); _popupShowDelayTimer will be cancle
may be this is the reason

**Comment by MovingGifts** [comment]
Please format your code for others to read and help you. Thank you :)

**Comment by erictraut** [comment]
I don't think I'd recommend using a Popup for a toast. ReactXP's Popup implementation uses a transparent layer that overlays the rest of your app and captures any taps/clicks that occur outside of the popup. It's useful for things like popup menus where you don't want users to be able to interact with the rest of the UI until the popup is dismissed. In your case, I recommend that you render your toast within your app using a standard view. This is how we implement the toast in the Skype app. We animate it so it slides in from the top of the screen, and then it slides up and off the screen after a predetermined duration.

Here's [a gist](https://gist.github.com/erictraut/fb83e7f39bea07158731c9b20f9d10cd) that contains a stripped-down version of our code. Feel free to copy and modify as you see fit. This component also makes use of a service to track which notification is currently displayed so multiple toasts can be queued and displayed in succession. Here's [a gist](https://gist.github.com/erictraut/0f7da096537f39470552ba40a6bfedd9) for this service as well.

**Comment by wangfaxi1985** [comment]
thank very much ,that 's very helpful
