### ISSUE TITLE
RX.TextInput how to use blur()?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#251]
I'm trying to trigger the `blur()` functionality on the text input from a function, but can't seem to get it to work.

```jsx
<RX.TextInput ref={element => this.textInputRef = element}
              onBlur={ () => alert('not focused') } />
```
And inside my function, the below does not blur the text input programmatically:
```jsx
this.textInputRef.blur();
```
Instead, I get this error: `Uncaught TypeError: Cannot read property 'blur' of undefined`.

What would be the correct way to programmatically blur the text input?

**Comment by erictraut** [comment]
Sounds like this.textInputRef is undefined, which means the component hasn't been mounted or has already been unmounted.

**Comment by MovingGifts** [comment]
My mistake! The text input programmatically blurs correctly - thank you for the pointer :)
