### ISSUE TITLE
how can i implent waterfall style listview and Grid listview

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/reactxp#254]
I need waterfall sytle listview and gride sytle listview 
how can i implent it?

**Comment by deregtd** [comment]
You'll have to make an array of responses from your component's render() function, and if you need it to be a fixed grid, each row will need to be a list of <view>s with fixed sizes (or at least equivalent grow/shrink/overflow parameters.)  Same way you'd do it in reactJS if all you had were DIVs that couldn't be tables. :)
