### ISSUE TITLE
ImgSvg not working for Native in "Storybook" && Unable to find variable: Symbol

### ISSUE THREAD

**Issue by mghazanfar** [Microsoft/reactxp#255]
1- ImgSvg does not work for "npm run storybook" on Native but perfectly working for Web Storybook using "npm run storybook-web". When "npm run storybook" is run, it gives the error :
The development server returned response error code: 500

URL: http://172.20.32.246:19001/node_modules/expo/AppEntry.bundle?platform=android&dev=true&strict=false&minify=false&hot=true&assetPlugin=expo/tools/hashAssetFiles

Body:
{"from":"F:\\work\\ReactXP\\new\\new_setup\\bluerain-ui\\node_modules\\reactxp-imagesvg\\node_modules\\react-native-svg\\elements\\Rect.js","to":"react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass","message":"Unable to resolve module `react-native/Libraries/Renderer/src/renderers/native/createReactNativeComponentClass` from `F:\\work\\ReactXP\\new\\new_setup\\bluerain-ui\\node_modules\\reactxp-imagesvg\\node_modules\\react-native-svg\\elements\\Rect.js`: Module does not exist in the module map\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
processBundleResult
    BundleDownloader.java:172
access$100
    BundleDownloader.java:38
execute
    BundleDownloader.java:108
emitChunk
    MultipartStreamReader.java:69
readAllParts
    MultipartStreamReader.java:116
onResponse
    BundleDownloader.java:96
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

What I am getting from this error that it is unable to find rect.js file at "node_modules\reactxp-imagesvg\node_modules\react-native-svg\elements"  while I assured the presence of this module and file. Please help me. I urgently need to run storybook and test my components.

2- If I remove importing stories from ImgSvg's component (described above in 1), it gives error for my simple component. The error is: "Unable to find variable: Symbol". Full error is:
Can't find variable: Symbol
assembleStyles
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:59015:50
loadModuleImplementation
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:118:41
guardedLoadModule
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:72:36
_require
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56:77
<unknown>
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:57328:20
loadModuleImplementation
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:108:12
guardedLoadModule
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:72:36
_require
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56:77
<unknown>
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56908:28
loadModuleImplementation
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:108:12
guardedLoadModule
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:72:36
_require
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56:77
<unknown>
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:1263:8
loadModuleImplementation
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:108:12
guardedLoadModule
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:72:36
_require
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56:77
<unknown>
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:1239:20
loadModuleImplementation
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:108:12
guardedLoadModule
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:65:45
_require
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:56:77
global code
    AppEntry.bundle?platform=android&dev=true&hot=true&minify=false:105014:9

Please resolve both issues for me ASAP!
Reminder: Both of these components are working perfectly on storybook for web but are not working for native apps. Help. I have spent my whole day (6-8 hours) on it!

**Comment by mghazanfar** [comment]
Please respond!

**Comment by erictraut** [comment]
I don't have any experience with storybook, so I'm afraid I can't help you out. Maybe someone else in the community can answer.

**Comment by mghazanfar** [comment]
I am eagerly waiting! I need to test my components on Native storybook to move further. Can you please ask experts of storybook in the community to help me out here?

**Comment by erictraut** [comment]
I think you'll need to seek out help from someone in the Storybook community. Looks like no one else in the ReactXP community uses Storybook.
