### ISSUE TITLE
Animated `s EndCallback not invoke

### ISSUE THREAD

**Issue by wangfaxi1985** [Microsoft/reactxp#259]
![Uploading image.png…]()

when animate end,why the EndCallback not invoke

**Comment by wangfaxi1985** [comment]
![image](https://user-images.githubusercontent.com/5296419/30202720-0159ae44-94b2-11e7-9ca3-29cf40c82850.png)

**Comment by wangfaxi1985** [comment]
android is ok,bug web is not ok

**Comment by erictraut** [comment]
Your code looks correct to me. 

Are you sure that you are using the openValue and translateValue in a style that's in use by a mounted component? It's possible that the web implementation won't call the end callback if one of the animated values isn't translated into a CSS animation.

**Comment by asdanilenk** [comment]
@wangfaxi1985 you also should not keep openValue and translateValue in the state, these should be just regular fields in your class. Keeping them in state will cause unnecessary re-renders of your component

**Comment by wangfaxi1985** [comment]
ok tks ,@asdanilenk

**Comment by erictraut** [comment]
Did you get the code working? If so, please close this issue.

**Comment by erictraut** [comment]
No response, so assuming issue is closed.
