### ISSUE TITLE
RX.WebView do not have onMessage and postMessage 

### ISSUE THREAD

**Issue by qingyangmoke** [Microsoft/reactxp#26]
RX.WebView 

Props 
onMessage 

Methods
postMessage

**Comment by erictraut** [comment]
The ReactXP WebView interface does define a postMessage method. You are correct that it's not currently implemented for the native implementation of WebView. Thanks for pointing out that bug.

The ReactXP WebView interface does not currently define an onMessage method. I think it may be worth adding, but we'd need to implement it for all platforms (including web) and document it.

I see that you've posted a PR with part of this change - thanks!

**Comment by Vangog-4** [comment]
[

1. 

](url)

**Comment by erictraut** [comment]
I finally had time to implement this support. It's published in the latest version of ReactXP: 0.51.0-alpha.2.
