### ISSUE TITLE
Cannot read property 'props' of null

### ISSUE THREAD

**Issue by waheed25** [Microsoft/reactxp#264]
i am trying to run RX.modal in storybook but i am getting this error 
Cannot read property 'props' of null
here is my code
`constructor(props) {
		super(props);
		this.showDialog = this.showDialog.bind(this);

	}
	showDialog() {
		console.log('in Dialog')
		const _modalId = 'ErrorDialog';

		let dialog = (
			<RX.View >
				<RX.Text >
					'An error occurred'
				</RX.Text>
				<RX.Button
					onPress={ this._onOkButtonPress }>
					<RX.Text >
						'OK'
					</RX.Text>
				</RX.Button>
			</RX.View>
		);
		RX.Modal.show(dialog, _modalId);
	}` 
and here is my render function 
 `render() {
		console.log('props are::', this.props);
		return (<RX.View style={{ backgroundColor: '#e5e5e5' }}>
				<RX.Button onPress={this.showDialog}><RX.Text>click here</RX.Text></RX.Button>
			</RX.View>
		);
	}`

**Comment by asdanilenk** [comment]
@waheed25 can you please post a full stack trace of the error you are getting?

**Comment by erictraut** [comment]
Please try to replicate the problem outside of storybook.

**Comment by waheed25** [comment]
without storybook it runs perfect!!!

**Comment by erictraut** [comment]
@waheed25, sounds like it's a storybook issue, not a reactxp issue.
