### ISSUE TITLE
Equal child widths with flex not working?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#272]
I have a very minimal setup of a parent view, with two children (blue box and yellow box), and a text in each child.

The parent has a defined width and `flexDirection: row`.
The children are set to `flex: 1` to take up exactly half of the parent width.

However, I end up with this instead of equal widths of the children:

![screen shot 2017-09-14 at 11 24 43 pm](https://user-images.githubusercontent.com/1202909/30465577-cdacae9a-99a5-11e7-8846-3e101d5c1b7e.png)

[Here is a gist](https://gist.github.com/MovingGifts/0439b4cc63e5c2ef8b21c3f9020db75e) to test the issue.

Note: I noticed that if I manually inspect the styles of each child box, there is no explicit `flex: 1`, but when I add it in the inspector for each child box, the width of the children become equal which is the desired behavior.

Any idea how to get the desired behavior by just using flex as in the gist code? I really don't want to manually set a width on each child, but use flex instead.

**Comment by erictraut** [comment]
"flex: 1" is shorthand in ReactXP for "flexBasis: auto, flexGrow: 1, flexShrink: 1". What you want here is "flexBasis: 0, flexGrow: 1". You can remove the "flex: 1" and specify these attributes individually.

**Comment by MovingGifts** [comment]
Yup, that did it :) Thank you for the insight, I had no idea why it wasn't working.
