### ISSUE TITLE
Text not selectable?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#283]
I just noticed that with this text:
```jsx
<RX.Text>Try to select me</RX.Text>
```
The text rendered in web is not selectable by mouse (if you double click text/click mouse and drag on text, you can't select it).

1. Just wondering why it's not selectable and if there is any way to make it selectable?
2. Does this impose any penalty by search engines not finding text content to index? For example,  if someone is searching Google, not sure if this text would be returned as part of the relevant search or if it will be ignored all together.

**Comment by erictraut** [comment]
There is a "selectable" prop on RX.Text. See documentation [here](https://microsoft.github.io/reactxp/docs/components/text.html).

Unless you're doing server-side HTML generation, #2 is not relevant. All of the HTML in a ReactXP app is generally generated client-side, so there's no opportunity for search engines to index them anyway. ReactXP is designed for dynamic web apps, not for mostly-static web pages.

**Comment by MovingGifts** [comment]
I totally missed the "selectable" prop, thank you for that. I think indexing is pretty important in my situation for people to be able to come from search engines via search (as opposed to directly typing the url to discover the content). Is there any way at all to have a website built with ReactXP to be indexed or is it just impossible. Does plain react js also have the same limitation?

This is new to me coming from php, so I had no idea about search engines not finding the content.

**Comment by erictraut** [comment]
You're confusing a website with a web app. ReactXP is a web app framework. Search engines index websites. Search engines index the HTML that's returned from the server. They don't run the javascript code in your page. A web app build with ReactXP (or React JS or any other modern web app framework) generates HTML dynamically by running javascript.

**Comment by MovingGifts** [comment]
Thank you for the clarification, I always thought that if the end result is rendered in the browser, which was accessed via a url, then that "rendered page" should be cached and indexed by search engines without any issues, since it's HTML at the end of the day in the browser when you inspect it. I came across [this article](http://andrewhfarmer.com/react-seo/) on react seo, but it seems that only Google _may_ be able to read them.

Either way, I hope that down the line with the popularity of these js frameworks, like React, there will be a way to have the final rendered pages discoverable and searchable with search engines.

**Comment by mrm1ck** [comment]
@erictraunt can I speak to you somehow
