### ISSUE TITLE
Error  of foucsableManager Mixin

### ISSUE THREAD

**Issue by adnan1naeem** [Microsoft/reactxp#290]
console.error node_modules/reactxp/dist/web/utils/FocusManager.js:386
    FocusableComponentMixin: context error!

**Comment by MovingGifts** [comment]
@adnan1naeem Did you resolve this? I get this too.

**Comment by MovingGifts** [comment]
Solved, it's because the `setMainView` was not set like this `RX.UserInterface.setMainView(<REACTCOMPONENETHERE />);`
