### ISSUE TITLE
RX.TextInput onSubmitEditing does not focus multiline true correctly

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#307]
So when we have the following, one textinput and one textinput multiline, when hitting enter on the first one, the `onSubmitEditing` that runs focuses the second textinput (multiline), but the position of the blinking cursor is **not** in the correct position in the multiline.

```jsx
// snippet from fully working simple gist link below
<RX.TextInput
    ref={element => this.field1 = element}
    style={styles.field1}
    placeholder="Text Input"
    value={this.state.field1}
    onChangeText={this.onChangeField1Value}
    onSubmitEditing={e => this.field2.focus()}
    />

<RX.View style={{height: 20}}></RX.View>

<RX.TextInput
    ref={element => this.field2 = element}
    style={styles.field2}
    multiline={true}
    placeholder="Text Area"
    value={this.state.field2}
    onChangeText={this.onChangeField2Value}
/>
```
I made this [very simple gist](https://gist.github.com/MovingGifts/eed29b4155973d78737b06cf3a8a03b0) showing the `ReactXP` issue. If you remove the `multiline` attribute the focus is fine, but then we cannot enable `multiline` which is what we need.

I looked up the [repo code](https://github.com/Microsoft/reactxp/blob/master/src/web/TextInput.tsx#L180) but couldn't really figure out why the blinking cursor shows up on the second line instead of starting on the first position on the first line.

Any idea how to fix this?

**Comment by a-tarasyuk** [comment]
@MovingGifts  You can use `onKeyPress` instead of `onSubmitEditing`, because in [`onSubmitEditing` ](https://github.com/Microsoft/reactxp/blob/master/src/web/TextInput.tsx#L181) there is no preventing default behavior for Entering. For `textarea` default behavior for entering is add \and that why cursor always in the wrong position.

```
<RX.TextInput
   ....
   onKeyPress={this.onSubmit}
/>
```

```
private onSubmit = (e) => {
  const ENTER_KEY = 13;

  if (e.keyCode === 13) {
    e.preventDefault();
    this.field2.focus();
  }
}
```

I can make a pull request if it makes sense to add this logic to the core library.

**Comment by MovingGifts** [comment]
@a-tarasyuk Thank you for the explanation :) That actually works quiet well for web, I don't have a mobile device to test on atm, but does it work on mobile as well? I mean would the `onKeyPress` be picked up for a custom `returnKeyType` below?

```js
// iOS and android prop for controlling return key type
returnKeyType: 'done' | 'go' | 'next' | 'search' | 'send';
```

Do we remove `onSubmitEditing` from mobile as well and just use the `onKeyPress`? I just want to know the correct way to implement this that would work correctly on all platforms :)

**Comment by a-tarasyuk** [comment]
@MovingGifts Based on code [TextInput](https://github.com/Microsoft/reactxp/blob/master/src/native-common/TextInput.tsx#L171) for "Native Devises" this logic exists. Need to test on mobile.

**Comment by a-tarasyuk** [comment]
@MovingGifts I think you can use `onKeyPress`, anyway, need to check on mobile.

**Comment by erictraut** [comment]
@MovingGifts  if that addresses your problem, please close the issue.
