### ISSUE TITLE
measureLayoutRelativeToWindow returns undefined on android

### ISSUE THREAD

**Issue by Fulanko** [Microsoft/reactxp#311]
I updated ReactXP to version 0.46.3 and noticed that `measureLayoutRelativeToWindow` doesn't seem to work correctly on android.

When using the function inside `componentDidMount` it returns the correct layoutInfo object, but on android x, y, width and height are all set to undefined.

**Comment by erictraut** [comment]
Which version of RN are you using? This seems to work for me with the latest version of ReactXP and version 0.51.x of RN.

**Comment by Fulanko** [comment]
I tried using RN 0.51.0 and ReactXP 0.51.0-alpha.5, but still get the same results.

On Web: {x: 0, y: 335, width: 412, height: 140}
On Android: {x: undefined, y: undefined, width: undefined, height: undefined}

```javascript
RX.UserInterface.measureLayoutRelativeToWindow(this).then(function(layoutInfo) {
  console.log(layoutInfo);
});
```

**Comment by Fulanko** [comment]
I figured out that the problem is related to [this RN bug](https://github.com/facebook/react-native/issues/3282).

Adding `onLayout={null}` to the affected component fixes the bug and the correct values are returned on android.
