### ISSUE TITLE
Support for SVGCircle, SVGPolygon, SVGClip and SVGRect

### ISSUE THREAD

**Issue by KSanthanam** [Microsoft/reactxp#312]
Please add support for SVGCircle, SVGPolygon, SVGClip, SVGRect.

**Comment by erictraut** [comment]
We don't have any plans to add these, but I'd be supportive of the feature if you want to contribute it to the project.

**Comment by KSanthanam** [comment]
I will try. Which version should I make Pull Request on?

**Comment by erictraut** [comment]
The latest version (master branch). We generally don't back-port major new features to older versions.

**Comment by Fitzpasd** [comment]
Seems like this would be well suited as an extension.  You could leverage [react-native-svg](https://github.com/react-native-community/react-native-svg) to simplify things.

**Comment by erictraut** [comment]
Yes, if this is added, it should be a modification of the existing reactxp-imagesvg extension. You would need to make it work with both react-native-svg and with browsers.

**Comment by Fitzpasd** [comment]
Would you modify `reactxp-imagesvg` or replace it with a more well named `reactxp-svg`?

**Comment by erictraut** [comment]
Modify the existing one. There's no need for a duplicate extension.

**Comment by KSanthanam** [comment]
I am adding to existing extension. I intend to make it work for iOS, Android & Web. The current extension is left out for windows anyway. So I won't be adding for Windows. The SVG components I will be adding are 
    Circle,
    Ellipse,
    G,
    Line,
    Polygon,
    Polyline,
    Rect,
    Text (Maybe)

**Comment by KSanthanam** [comment]
@erictraut Current reactxp-imagesvg (reactxp/extensions/imagesvg) has problem running for android. The react-native-svg it sources is v5.4.0. It throws following error.

Error while updating property 'd' in shadow node of type: RNSVGPath

To fix this error you need to downgrade react-native-svg to 4.6.1. But downgrading creates old issues. 

iOS works fine with current react-native-svg 5.4.0.

Can you please guide me. Can I go ahead and add these features even though they won't work for android?

**Comment by cellcortex** [comment]
I guess this never made it in. @erictraut  are you still willing to accept PRs for circle and polygon?

**Comment by erictraut** [comment]
Yes, happy to accept a PR.

@deregtd, just want to confirm that you're not working on this already. IIRC, you decided to create a separate extension to handle file-based SVGs, so you decided not to continue to augment this extension, right?

**Comment by deregtd** [comment]
Yes, I forked this and added a ton more fields to it to support more of the file-ish case, so I think we've diverged, at least for now.

**Comment by Fitzpasd** [comment]
We also have work that enables `Def`, `LinearGradient`, `RadialGradient`, `Rect`, `Stop` and `Svg` that I'd be happy to PR once we settle on the best extension for this to live in.

**Comment by kg-currenxie** [comment]
@Fitzpasd was there ever any progress on that? :) We're quite interested in using `LinearGradient`!

**Comment by Fitzpasd** [comment]
Not from my side, and I no longer work at the company that owned that work, so I won't be contributing anything here.
