### ISSUE TITLE
RX.View onLayout doesn't fire

### ISSUE THREAD

**Issue by kgroat** [Microsoft/reactxp#317]
I have a project where I'm trying to use the onLayout handler to dynamically resize a view's height based on its width.  Unfortunately, I can't seem to get the event to fire, no matter what I try to do.

I'm using `reactxp` version `0.46.3`.  I'm attempting to get it to fire in an Android Nexus 5X emulator.

This is the code I'm working with:
```
const { width = 200 } = this.state.layout
<RX.View
  style={[styles.container, { height: width * RATIO }]}
  onPress={onPress}
  onLayout={layout => this.setState({ layout })}>
  <RX.Image source={image} resizeMode='cover' resizeMethod='scale' />
  <LinearGradient
    colors={['transparent', 'rgba(0, 0, 0, 0.5)']}
    style={styles.gradient}>
    <RX.Text style={styles.minorText}>
      {minor}
    </RX.Text>
    <RX.Text style={styles.titleText}>
      {title}
    </RX.Text>
  </LinearGradient>
</RX.View>
```

I've tried replacing the handler with one that puts the values directly onto the class instance, and even replaced it with `console.log` and have never once seen it fire when using remote debugging.

**Comment by erictraut** [comment]
@kgroat, were you able to get this working? We use the onLayout callback extensively within the Skype client, so I know that it works in most cases. If you're not seeing it work, there must be something different about your usage.

**Comment by erictraut** [comment]
No response — and not able to reproduce, so closing.
