### ISSUE TITLE
No border on RX.TextInput on Web

### ISSUE THREAD

**Issue by omatrot** [Microsoft/reactxp#319]
I have a RX.TextInput in a custom component:

<RX.TextInput
                    placeholder={'Enter reminder'}
                    onChangeText={this._onChangeText}
                    style={ _styles.textInput }
                    autoFocus={true}
                    keyboardType={'default'}
                />
The style is defined like this:

textInput: RX.Styles.createTextInputStyle({
        margin: 12,
        padding: 4,
        borderColor: '#999',
        borderWidth: 1,
        borderStyle: 'solid',
        height: 30,
        fontSize: 16
    })
I have the following problem:

On web (at least Safari/Chrome), I have no border. Chrome developer tools shows  
> border:none

 in the element.style, which of course explains the lack of border.

On iOS and Android, the border is fine.

Any help appreciated.

**Comment by erictraut** [comment]
Sounds like a bug in the web implementation. As a short-term workaround, you can enclose the TextInput in a View that has a border.

**Comment by omatrot** [comment]
I was not using the latest version of react-xp.
Fixed my package.json by looking at dependencies of the samples.
Sorry about that
