### ISSUE TITLE
RX.Text numberOfLines only works when 1

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#321]
When you have a long `RX.Text` and want to limit the `numberOfLines` to any number greater than `1`, it does not respect the `numberOfLines` value (something like `2` for example). Only `1` seems to work for one line. How can one use the `numberOfLines` for multiple lines on web?

Is this desired behavior or a bug?

**Comment by erictraut** [comment]
This isn't desired, but it's a limitation we need to live with. HTML doesn't currently provide support for limiting the number of lines to a value > 1. There is a proposed extension to the HTML standard that provides this functionality, but it's not yet ratified or adopted by any of the major browsers.

**Comment by MovingGifts** [comment]
Ah - I see, I was a bit confused since the docs didn't specify it was a mobile platform specific prop, so I thought it would work across platforms. Thank you for filling in the gaps :)
