### ISSUE TITLE
Fix the Navigator extension documentation

### ISSUE THREAD

**Issue by omatrot** [Microsoft/reactxp#326]
The doc states that you can install the extension with npm.
At the time of this writing, it fails:

> npm install reactxp-navigator
> npm ERR! code E404
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/reactxp-navigator
> npm ERR! 404
> npm ERR! 404  'reactxp-navigator' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by xogeny** [comment]
For anybody who finds this issue, the what you really need to install is `reactxp-navigation`.

**Comment by erictraut** [comment]
I fixed the documentation.
