### ISSUE TITLE
Question/Docs Feature Request: React-Native Version Roadmap

### ISSUE THREAD

**Issue by fbartho** [Microsoft/reactxp#328]
I'm trying to evaluate this library for use as we migrate a native app to react-native. One concern that I ran into is that ReactXP is currently targeting react-native 0.46.x, but the current stable version of react-native is 0.49. I'm happy to see that reactxp gets updated roughly monthly, so I'm trying to figure out what the plan/roadmap for adopting new react-native versions is.

Additionally, this maybe would be a valuable topic to discuss or link to from the README.

**Comment by erictraut** [comment]
In general, ReactXP works with newer versions of RN as long as there aren't breaking changes (as there was in RN 0.44). I'm not aware of any issues with using ReactXP with RN 0.49 at this time. Let us know if run into any problems.

**Comment by fbartho** [comment]
Thanks for the quick answer! -- Perhaps this is a react-native newbie question, but when I set react-native to * in package.json (to figure out what everything should be resolving to), I get the following warning/errors:
```
warning "reactxp@0.46.4" has incorrect peer dependency "react@^15.4.1".
warning "reactxp@0.46.4" has incorrect peer dependency "react-native@^0.46.0".
```

Should I either ignore the peer dependency warning or should I be doing something different?

If reactxp is compatible, shouldn't the the react-native peer dependency say something like `0.46.x | 0.47.x | 0.48.x | 0.49.x` ?

**Comment by erictraut** [comment]
You can ignore the peer dependency warnings. We should update them to react@^16.0.0.

**Comment by fbartho** [comment]
I appreciate the clear answer, thank you. Also, I'm happy that it looks like ReactXP will be a good choice for us.

Feel free to close this ticket, or simplify it into a request for a line in the Readme on the topic, I consider my core question solved.
