### ISSUE TITLE
Modal alert disable background dismiss prop

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#329]
I am trying to explicitly dismiss a specific modal alert by having the user explicitly click one of the buttons provided and prevent dismissing the modal by clicking the background.

Cleanest solution would be to add a prop to modal alert in ReactXP like `preventDismissOnPress: true` to prevent background dismiss of modal alert.

Similiar to `Popup` here:
```js
// By default, clicks or taps outside of a popup (unless they are on the
// anchor) will not dismiss the active popup. If true, this overrides the
// default behavior, in which case the popup must be dismissed explicitly.
preventDismissOnPress?: boolean;
```

@erictraut would you consider a pull request for this?

**Comment by erictraut** [comment]
I think this is the way Modal works by default, no? A click/tap outside of the modal should be ignored. If you want to handle clicks/taps outside of the modal differently, you can render your modal as a full-screen container that's transparent (or semi-transparent if you prefer), and then render the content of your modal as a sub-view within this full-screen view.

**Comment by MovingGifts** [comment]
Sorry for the confusion; I was talking about this [Alert](https://microsoft.github.io/reactxp/docs/apis/alert.html) component (specifically the web alert implementation).

Currently tapping outside the alert on web dismisses the alert and there is currently no way to override this behavior without a prop.

**Comment by erictraut** [comment]
Ah, that makes more sense. 

Alerts on RN platforms are dismissed if the user clicks/taps outside of the alert, and there's no way to override this behavior, so I don't think it makes sense to add a web-specific property to override it there. If you want this behavior, you can use a Modal.

**Comment by MovingGifts** [comment]
Makes sense, I'll just have to conditionally do it that way for specific alerts for web I guess. Thanks for the feedback!
