### ISSUE TITLE
node_modules/reactxp/dist/common/Types.d.ts(224,54): error TS2314: Generic type 'HTMLAttributes<T>' requires 1 type argument(s).

### ISSUE THREAD

**Issue by umairfarooq44** [Microsoft/reactxp#334]
I am getting this error :

`node_modules/reactxp/dist/common/Types.d.ts(224,54): error TS2314: Generic type 'HTMLAttributes<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(393,25): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(394,37): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(395,36): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(396,44): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(397,43): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(398,28): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(399,29): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(400,30): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(401,28): error TS2314: Generic type 'TouchEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(402,27): error TS2314: Generic type 'TouchEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(403,26): error TS2314: Generic type 'TouchEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(404,32): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(405,41): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(727,38): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(728,33): error TS2314: Generic type 'DragEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(729,38): error TS2314: Generic type 'ClipboardEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(730,34): error TS2314: Generic type 'FocusEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(731,33): error TS2314: Generic type 'FormEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(732,34): error TS2314: Generic type 'MouseEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(733,34): error TS2314: Generic type 'TouchEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(734,31): error TS2314: Generic type 'UIEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/common/Types.d.ts(735,34): error TS2314: Generic type 'WheelEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/web/Button.d.ts(14,28): error TS2314: Generic type 'MouseEvent<T>' requires 1 type argument(s).
node_modules/reactxp/dist/web/Picker.d.ts(5,24): error TS2314: Generic type 'SyntheticEvent<T>' requires 1 type argument(s).`

I am using react :16.0.0 and reactxp: 0.42.10
The problem is some types are incorrect e.g. in reactxp/dist/common/Types.d.ts(224,54):
The type is  `React.HTMLAttributes` but if  `React.HTMLAttributes<any>` is given error is gone, same with other errors.

**Comment by erictraut** [comment]
ReactXP 0.42.x isn't compatible with react 16.0.x because of breaking changes that were made in the types interface. ReactXP 0.46.x fixes those issues.

**Comment by amnajunaid** [comment]
@erictraut  Can you please tell when are you planning to publish 0.46.x ?

**Comment by erictraut** [comment]
It was published late last month. We're now up to version 0.46.3. You can check out the full version history [here](https://microsoft.github.io/reactxp/versions/version_history.html).

**Comment by erictraut** [comment]
Oops, I stand corrected. The changes I made for compatibility with React 16.0.0 were not in 0.46.3. I'll need to publish 0.46.4 so you can get to those. I'll do that shortly (sometime today).

**Comment by erictraut** [comment]
OK, version 0.46.5 is now published.
