### ISSUE TITLE
Add documentation for webpack configuration

### ISSUE THREAD

**Issue by Guichaguri** [Microsoft/reactxp#337]
The documentation should include a recommended Webpack configuration for bundling web apps.

React Native provides a way to distinguish platforms with file extensions (`.android.js`, `.ios.js`, `.windows.js`) as documented in [Platform Specific Code](https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions). If every ReactXP app uses a Webpack config that supports `.web.js` extensions, we can write react-dom specific code or "native" modules using web APIs.

With that, we can easily make native modules work on the web too.

**Comment by erictraut** [comment]
The TodoList sample now demonstrates advanced webpack configuration. https://github.com/Microsoft/reactxp/tree/master/samples/TodoList.
