### ISSUE TITLE
Why `RX.Component`?

### ISSUE THREAD

**Issue by SukantGujar** [Microsoft/reactxp#34]
Please see my original question on SO: http://stackoverflow.com/questions/43342570/what-features-does-rx-component-class-provide-over-react-component.

**Comment by george-cz** [comment]
You can tell by the sources, that RX.Component is just React.Component. You can use both. This way you don't have to import React.

https://github.com/Microsoft/reactxp/blob/master/src/web/ReactXP.ts#L131

**Comment by SukantGujar** [comment]
Thanks @george-cz. IMO this should be mentioned in the docs as it's an important detail. Are you taking PRs for the documentation?

**Comment by SukantGujar** [comment]
FYI, added a tag for [reactxp on SO](http://stackoverflow.com/questions/tagged/reactxp), please review and add tag-info as appropriate.

**Comment by george-cz** [comment]
@SukantGujar thats not up to me, however feel free to create a PR :)

**Comment by SukantGujar** [comment]
Done! https://github.com/Microsoft/reactxp/pull/36

**Comment by erictraut** [comment]
I merged your PR. Thanks for the contribution!
