### ISSUE TITLE
VirtualListView redraws itself while being invisible

### ISSUE THREAD

**Issue by omatrot** [Microsoft/reactxp#343]
I use the VirtualListView with the navigator as in the TodoList sample.
I may be wrong but setting the log property to a method that sends text to the console on web shows that the list seems to redraw itself every second or so, though it is not visible (you're past the first navigator route).

It goes like this indefinitely....

```
ExerciseList.tsx:115 Container Height Change: 104 to 128
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 152
ExerciseList.tsx:115 Container Height Change: 128 to 152
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 176
ExerciseList.tsx:115 Container Height Change: 152 to 176
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 200
ExerciseList.tsx:115 Container Height Change: 176 to 200
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 224
ExerciseList.tsx:115 Container Height Change: 200 to 224
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 248
ExerciseList.tsx:115 Container Height Change: 224 to 248
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
ExerciseList.tsx:115 New layout height: 272
ExerciseList.tsx:115 Container Height Change: 248 to 272
ExerciseList.tsx:115 CalcNewRenderedItemState: O:0 + A:0 + R:32 + B:0 = 32, FilledViewable: true
```

I'm afraid this will eat battery power.
What do you think ?

**Comment by erictraut** [comment]
Are you adding new items to your list every few seconds? That would explain why the VLV is updating the container height. It will continue to do so until you've exceeded the height of the view port (the visible portion of the list) * 1.5. The "* 1.5" is because the VLV renders up to 50% beyond the end of the list.

The VLV doesn't know whether it's obscured by some other view. Depending on the type of navigator you're using and how it's configured, it may unmount views that are pushed onto the navigator stack. Some navigators will keep the top and next-to-top views mounted so the app is responsive when popping the top.

**Comment by omatrot** [comment]
The list contains only one item. None are added right now.
I'm using the reactxp-navigation component.

**Comment by erictraut** [comment]
A few more things to investigate...

Are you seeing similar behavior from the Todo sample app? I don't think it does, so you can use it to determine what's different in your app.

What view is the parent of your VLV? Its height needs to be bounded (e.g. based on the size of the containing window or screen). Perhaps your VLV's parent is allowing the VLV itself to grow in height?

**Comment by omatrot** [comment]
I started from the TotoList sample...
You're right there is no such behavior in the sample app.

I'll try to find out what's different...

**Comment by omatrot** [comment]
Found it !
The style was missing on the parent view.
<RX.View style={ _styles.listContainer }>
Everything is fine now.
Thank you for your help.
