### ISSUE TITLE
Sprite image for web images?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#345]
When I look at my app in web, the image assets (icons) aren't "preloaded", so when I navigate around the app, I see blank areas where the image(s) should go, until they they are loaded. This "empty" image is bad UX, as it gives off a "slow loading" or "freezing" feel to the app.

Before turning to React Native/ReactXP, for web, I used to use a single sprite image with css to choose the proper x,y coordinates for each image to render the image correctly without the load time for each image, since it is a single sprite image loaded.

I am wondering, how can we use a sprite in ReactXP?

**Comment by erictraut** [comment]
Here are a few ideas. Maybe one (or a combination of multiple) can help you out.

1. Switch from raster images to vector. SVGs are much smaller and take almost no time to decode, so they load and render much faster.
2. Use your sprite approach. Write a component that uses the RX.Image to draw your full sprite sheet, uses a transform to position the desired sprite into position, and an RX.View container to "clip" the remainder of the sprite sheet so it isn't visible.
3. Write a custom ReactXP sprite plug-in that contains platform-specific code. We ended up doing this for the Skype client for our animated emoticons, which are encoded as vertical strips of animation frames.
4. Don't use a sprite sheet but instead add code to preload your images when your app starts. We use this trick in the Skype client for the most important images. As long as your cache control headers are set correctly, the browser (and RN) should cache these images locally until more room is needed in the cache or the TTL expires.

**Comment by MovingGifts** [comment]
I think point 2 (the sprite approach) would work best, but I don't think this would apply to mobile, since mobile have the @2x and @3x images for mobile devices. 

1. So would it have to be a conditional? (For mobile, the local bundled app assets don't need to call any images since they're bundled, but for web, we'd have to make an http request to fetch the sprite sheet once and use the custom `RX.Image` component which you described a method to accomplish it with transforms/and clipping.)
2. If that approach is correct, do you mind sharing a bit more detail on how to actually accomplish your second point?

**Comment by erictraut** [comment]
Yeah, if you use 2x and 3x assets, you'd need to use a conditional approach.

For option #2, render an RX.Image within an RX.View. Set the height/width of the RX.Image to the dimensions of your sprit sheet. Set the height/width of the containing view to the dimensions of an individual sprite. By default, the "overflow" attribute for RX.View is "hidden", which will clip the portion of the sprite sheet outside of the desired sprite. The only remaining trick is to position the desired sprite within the "window" provided by the containing view. You can do that using absolute coordinates (set the top and left attributes) or by using a transform (using translateX and translateY).

**Comment by MovingGifts** [comment]
Thank you for describing it in detail :)

I was alternatively thinking of using base64 since it won't have to load anything from the server and won't have to worry about top/left x/y. Are there any drawbacks to the base64 approach for asset images instead of server loaded asset images or is it the better approach?

**Comment by erictraut** [comment]
Base64 is another potential solution. It has some drawbacks in that it increases your bundle size and can complicate maintenance of your project. You should consider how large your assets are. Base64 makes more sense for small assets.
