### ISSUE TITLE
How to use ReactXP location API

### ISSUE THREAD

**Issue by waheed25** [Microsoft/reactxp#346]
hi, i want to use reactxp location api 
i am using RX.location.getCurrentPosition() and in console there is a value of lat long and others but i am unable to find a runung example or a good example .can anyone please explain this???

**Comment by deregtd** [comment]
I don't understand the question.  Is there a bug in the call?  You just call it and it returns a promise that resolves with the position.

**Comment by waheed25** [comment]
No. I just want to ask is there an example of location API in demo project of react xp???

**Comment by erictraut** [comment]
No, there isn't an example. It's a very basic API though. Just call it, and it should provide the answer.

**Comment by waheed25** [comment]
Yeah I know as I said earlier I am getting response of getCurrentlocation but for better understanding and effective use I just wanted to see usage code or a demo example

**Comment by erictraut** [comment]
You should call RX.Location. isAvailable() first to make sure that the facility is available. If so, you can call RX.Location.getCurrentPosition.

RX.Location.getCurrentPosition().then(position => {
  console.log(position.coords.latitude);
  console.log(position.coords.longitude);
  console.log(position.coords.altitude);
};

**Comment by waheed25** [comment]
Thanks @erictraut

**Comment by waheed25** [comment]
i want to know what is default value of 
enableHighAccuracy
timeout?: number;
maximumAge?: number;

**Comment by erictraut** [comment]
The default for enableHighAccuracy is false. When enabled, this consumes more power (sometimes significantly so). The timeout and maximumAge defaults depend on the underlying platform and/or browser.

**Comment by waheed25** [comment]
Thanks @erictraut

**Comment by waheed25** [comment]
Thanks @erictraut

**Comment by waheed25** [comment]
Thanks @erictraut

**Comment by mghazanfar** [comment]
My browser, whether googleChrome or Mozilla Firefox, asks me for the permissions but behaves only as if it was true. Below is my code:
``` if (Location.isAvailable()) {
			return (
        <View>
            <GMap
                draggable={true}
                height={250}
                region={{ latitude: lat, longitude: lng }}
                zoom={10}
                onMarkerDragEnd={this.onDragEnd}
            />
			<BR.Components.View style={{ flexDirection:'row', justifyContent: 'space-between' }}>
				<BR.Components.View style={{flexDirection:'row'}}>
					<BR.Components.Checkbox />
					<BR.Components.Text style={{ paddingTop:16, fontFamily:'roboto',fontSize:14 }}>Set Manually</BR.Components.Text>
				</BR.Components.View>
				<BR.Components.Text style={{ paddingTop:16, fontFamily:'roboto',fontSize:14, display: 'block' }}>Latitude: {this.state.lat}</BR.Components.Text>
				<BR.Components.Text style={{ paddingTop:16, fontFamily:'roboto',fontSize:14, display: 'block' }}>Longitude: {this.state.lng}</BR.Components.Text>
			</BR.Components.View>
        </View>
			);
		} else {
			return(
			<View>
				<GMap
					draggable={true}
					height={250}
					region={{ latitude: lat, longitude: lng }}
					zoom={10}
					onMarkerDragEnd={this.onDragEnd}
				/>
				<BR.Components.View style={{display:'flex', backgroundColor:'rgba(255,255,255,0.74)', height: 250, top:0,  bottom:0, left: 0, right:0, position: 'absolute', alignItems: 'center', justifyContent: 'center'}}>
					<BR.Components.View>
					{/* The below image is temporary. It will be replaced by Icon component once bluerain-plugin-icon is developed */}
						<BR.Components.Image source="https://dichungtaxi.com/images/warning-28-512.png" style={{width: 80, height: 80, alignSelf: 'center', marginBottom: 12}}/>
						<BR.Components.Text style={styleComponent.disabled}>
						Your location is disabled. Please enable it now to proceed next.
						</BR.Components.Text>
					</BR.Components.View>
				</BR.Components.View>
				<BR.Components.View style={{ flexDirection:'row', justifyContent: 'space-between' }}>
					<BR.Components.View style={{flexDirection:'row'}}>
						<BR.Components.Checkbox disabled />
						<BR.Components.Text style={{ paddingTop:16, fontFamily:'roboto',fontSize:14 }}>Set Manually</BR.Components.Text>
					</BR.Components.View>
				</BR.Components.View>
			</View>);
		}
```
The else part never runs. Please help!

**Comment by waheed25** [comment]
be assure location is available?this is happens when location is not available.

**Comment by mghazanfar** [comment]
@waheed25 Location is available!

**Comment by erictraut** [comment]
isAvailable will always return true if the browser supports location APIs. This API has nothing to do with whether the user has granted permission to access the current location. Your "else" clause will execute only on a browser that doesn't support location APIs.

**Comment by waheed25** [comment]
@mghazanfar you need to clear your browser cache of location by clicking on the navigation icon in chrome and than reloads your page.
Because if you provide permission once and without clearing cache it will not ask again.
