### ISSUE TITLE
How to release production mode for web?

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/reactxp#35]
i see on the `index.html` it loads a file 1.4MB `bundle.js`, normally I split libraries  and the app code into two separate minified javascripts (lib.js and app.js), the lib.js are external libraries that rarely changed, where app.js my custom code that easily changed. How to do this in Reactxp?

**Comment by CreativeKoen** [comment]
You could do something like this in your `webpack.config.js` entry object.
Haven't had the time to test this so please do.

```js
entry: {
	app:  `/path/to/App.tsx`,
	vendor:  [ 'reactxp', 'react-dom', 'rxjs' ]
},
```

**Comment by sideshowfree** [comment]
I will like for all my text messages and calls to stay clear to read with no codes I don't want nothing hiding

**Comment by sideshowfree** [comment]
I will like for all my text messages and calls to stay clear to read with no codes I don't want nothing hiding
