### ISSUE TITLE
Peer dependencies don't work together

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#359]
The current peer dependencies

```
"peerDependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-native": "^0.46.0",
    "react-native-windows": "^0.33.0"
},
```

can't be right.  RN `0.46.x` doesn't work with React `16.0.0` (it will immediately give a runtime error due to the missing `ReactComponentTreeHook`).

The RN version should either be bumped to `0.50`, or the react and react-dom dependencies should be `16.0.0-alpha.12`.  

[This page](https://github.com/react-community/create-react-native-app/blob/master/VERSIONS.md) is useful to see which versions are supported, or [inspecting the package.json](https://github.com/facebook/react-native/blob/0.50-stable/package.json) of the different react-native stable branches.

**Comment by erictraut** [comment]
Thanks for that link. Very useful. I didn't realize there was such tight binding between RN and React versions.

**Comment by erictraut** [comment]
I just pushed a fix.
