### ISSUE TITLE
RXPTodoList sample: TypeScript error TS2554 in EditTodoPanel.tsx

### ISSUE THREAD

**Issue by krablak** [Microsoft/reactxp#360]
Hi, 
unfortunately I met minor unpleasant issue within RXPTodoList sample which produces TypeScript error:

	 ERROR in [at-loader] ./src/EditTodoPanel.tsx:35:9
    TS2554: Expected 1-2 arguments, but got 0.

Here are steps to reproduce it (I just followed instructions from readme):

- git clone https://github.com/Microsoft/reactxp.git
- cd reactxp/samples/TodoList/
- npm install
- npm run web-watch
- TypeScript error message is displayed

Error is caused by calling parent constructor without props with simple workaround/solution:

	class EditTodoPanel extends RX.Component<TodoPanelProps, TodoPanelState> {
		    constructor(props: TodoPanelProps) {
		        super(props);
		        this.state = {};
		    }
		  ....
		  
I know it's super minor issue nevertheless project/technology newcomers could be unnecessarily confused🤔.

My env details:

- node v6.11.2
- npm 3.10.10
- macOS 10.13.1

Thanks for doing great job with ReactXP!

**Comment by erictraut** [comment]
Thanks for the bug report. I just pushed a fix.

**Comment by krablak** [comment]
Thanks for quick fix. It's working now.
