### ISSUE TITLE
Would ReactXP components be opinionated towards UX design patterns which work well on all platforms?

### ISSUE THREAD

**Issue by SukantGujar** [Microsoft/reactxp#37]
My team has also worked on building shared components across React and RN. A challenge we have faced (and still facing) is how to share not just components, but the entire page compositions which render equally well on web as well as device. So far, an Outlook like list > details > more-details kind of layout seems to work well for us. This has turned out to be a more complex problem than the technical challenges around cross-platform components. Please note that this goes beyond the notion of adding responsive components, as you need to provide a uniform and yet platform-oriented interface.

Is the ReactXP framework going to have opinions on how to use the cross-platform components in a way to build great looking and functional apps across platforms?

Thanks

**Comment by erictraut** [comment]
This is the problem we were trying to solve when we created ReactXP. The new Skype client that we're building needs to run across many platforms (and screen sizes), and we wanted the behavior and UX to be consistent across all of them. 

I'm not sure what you see as the difference between "components" and "entire page compositions". A page composition is just a higher-level component, right? 

One of the problems that applies more so to these higher-level components is navigation -- moving between different parts of the app. I plan to write a blog in the near future about how we solved the navigation problem across multiple screen sizes.

**Comment by SukantGujar** [comment]
yes router experience is definitely a big part of it. But basically it's about trying to build a UI composition which allow for great ux while sharing a lot of code. Certain ux patterns like the Outlook UX work great across various form factors. There are some web patterns like modals which don't translate well to devices, and then you have multilevel routes (list -> details -> edit) which work very well on mobile but are difficult to reuse on web.
I think establishing good cross platform patterns would go a long way towards the success of libraries like ReactXP.
Will look forward to your blog.

**Comment by erictraut** [comment]
Yeah, we've struggled with this in some places. In general, we try to arrange collections of controls into panels that our designers can then place in a stacked nav model for mobile or a "composite" (side-by-side) model for larger screens. These same panels can also be used in modals or popups, as appropriate. The top-level navigation and layout logic may differ, but the UI code and related logic within the panel is common across all platforms and screen sizes.

**Comment by Talor-A** [comment]
@erictraut perhaps this is sidetracking a bit but what's the recommended solution for navigation cross platform? react-navigation? react-router?

**Comment by SukantGujar** [comment]
We are using react-router 4 since alpha, it has worked well even before it officially added support for RN.

**Comment by 1331Inv** [comment]
Ｖ

**Comment by joshjordan** [comment]
@erictraut would love to see that blog post and specific examples of how you've solved this

**Comment by erictraut** [comment]
@joshjordan, I just posted a new [blog post](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html) that explains how we're doing navigation within the Skype app.
