### ISSUE TITLE
How does it work under the hood?

### ISSUE THREAD

**Issue by kirakik** [Microsoft/reactxp#370]
Hello,

I am preparing a talk on different available technologies for sharing code between React DOM and React Native, and I would like to mention ReactXP. I searched in your documentation and the code, but I couldn't quite figure how it works under the hood. Does anybody know and would be willing to explain it?

Thank you

**Comment by erictraut** [comment]
This [page](https://microsoft.github.io/reactxp/docs/faq.html) contains a good overview of ReactXP and how it works at a high level. Let me know if you have specific questions.

**Comment by erictraut** [comment]
Here's a slide from one of my presentations. You may find this useful.

![image](https://user-images.githubusercontent.com/7040122/33244909-9f7c6c0c-d2b4-11e7-90ed-27a7de063ce4.png)
