### ISSUE TITLE
AppIcon is not showing up for iOS

### ISSUE THREAD

**Issue by KSanthanam** [Microsoft/reactxp#371]
1) Copy the sample code hello-world
2) open iOS project on Xcode
3) fill the AppIcon images (Contents.json is set properly)
4) npm start
5) react-native run-ios 
The AppIcon you filled does not show up as AppIcon on the simulator or real device after deployment. 
Can you please help to find where the issue is.

**Comment by erictraut** [comment]
The iOS App Icon is not related in any way to ReactXP. It should work like any other iOS app.

**Comment by KSanthanam** [comment]
@erictraut Thank you for pointing this out. I figured out the problem is in Xcode. I thought reactxp was causing it. I am closing this issue.
