### ISSUE TITLE
WebView Route Path change

### ISSUE THREAD

**Issue by waheed25** [Microsoft/reactxp#376]
Hi, i am using reactxp WebView to display a webcontent.It works fine but when i opens up the webpage in WebView  it doesn't change the url of the WebView  like if i opens  [google.com] and than i go to images than the url should be google.com/images  or something like that .Is it possible to change inside of a WebView???.I have used onNavigationStateChange but i run only first time when i click on WebView content.

**Comment by erictraut** [comment]
onNavigationStateChange should be called whenever the navigation state (the URL) changes within the control. As with web pages viewed in a browser, not all clicks / navigations will result in a URL change. This is partly under control of the JavaScript running within the control.

Are you seeing the same behavior on multiple platforms (iOS, Android and web)? Or does the observed behavior differ between platforms?

**Comment by waheed25** [comment]
I didn't use it on iOS or on Android

**Comment by waheed25** [comment]
Url is only change first time and navigation state change is only called first time

**Comment by erictraut** [comment]
Looks like this callback was never implemented for the web. Off the top of my head, I think it should be possible to implement it by installing an event handler on the iframe's history object. Feel free to play around with the implementation (in src/web/WebView.tsx), and if you get something working, submit it back as a PR. If you don't feel comfortable making such a change, we'll leave this issue open to track bug.

**Comment by waheed25** [comment]
Yeah I will try and I will inform you when I reach to some conclusion
