### ISSUE TITLE
Need a better forum for discussion

### ISSUE THREAD

**Issue by erictraut** [Microsoft/reactxp#38]
GitHub is great for tracking issues, but it's a bit cumbersome as a general forum for discussions. We're thinking about creating a ReactXP forum somewhere else. Any suggestions or preferences? A dedicated Facebook Group? Reactiflux? Others?

**Comment by justinhhorner** [comment]
+1 for Reactiflux 👍

**Comment by SukantGujar** [comment]
Slack would work too.

**Comment by joshjordan** [comment]
I'd be willing to host a Discourse forum, if that's the direction you want to go.

**Comment by olivoil** [comment]
[Gitter](https://gitter.im) works well too, I like the integration with search engines. I often find discussions from gitter just by searching issues in google. It makes the community more discoverable and also helps keep the discussions useful after the fact.

**Comment by bayat66** [comment]
سلام .متاسفانه به دلیل خوب متوجه نشدن زبان انگلیسی بعضی وقتها نمیتوانم خوب استفاده کنم.

**Comment by mogarick** [comment]
I also think Gitter would be a good option. Many Github projects use it as forum.

**Comment by ComethTheNerd** [comment]
@SukantGujar suggesting one of Skype's direct competitors?! Controversial!

**Comment by rohmanhm** [comment]
Reactiflux is great one

**Comment by SukantGujar** [comment]
@ComethTheNerd Haha, actually more like MS Teams' competition 😄

**Comment by rohmanhm** [comment]
@erictraut so where we can find a general forum?

**Comment by erictraut** [comment]
I've created a new [Gitter room](https://gitter.im/msreactxp) for discussing ReactXP issues.

**Comment by erictraut** [comment]
I've also added a link to the Gitter room in the [Community page](https://microsoft.github.io/reactxp/community/support.html) on the ReactXP site.
