### ISSUE TITLE
<RX.TextInput returnKeyType="search" mobile safari issue

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#381]
In search field, on mobile safari (iphone), when the below is rendered:

```<RX.TextInput returnKeyType="search" ... />```

The label for the submit button on the virtual keyboard is "return" instead of "Search":

![screen shot 2017-12-12 at 12 55 43 am](https://user-images.githubusercontent.com/1202909/33870677-f290c04e-dedc-11e7-8522-cc34b757d770.png)

If you check out google's search, it shows "Search" which is prominent by being a blue button in the virtual keyboard. An html solution is to do this (requires a form element with an action, and a "search" as part of the name of the input field):
```
<form action="/">
  <input type="search" ... />
</form>
```

Initially, the issue with the "return" button is that it is not too prominent, and also the "Done" button in the safari toolbar on top of the virtual keyboard does not submit, so it is confusing to users when they hit "Done" and nothing happens. I think showing "Search" as mentioned above is the best way to show a prominent action (even if the "Done") does not submit.

Not really sure how to handle this cleanly in ReactXP; any ideas?

**Comment by erictraut** [comment]
Out of curiosity, why is mobile safari an important platform for you? If you're building with ReactXP, I presume that you're making a native app available on iOS.

**Comment by MovingGifts** [comment]
I wanted to provide it as the web app version for url access and when checking from an iPhone via the native mobile safari browser, I encountered this issue.

**Comment by MovingGifts** [comment]
@erictraut For this issue, relating to my recent commit on virtual keyboards on mobile web, a solution would look like this:

```
private _getKeyboardType = () => {
    // Show the correct virtual keyboardType in HTML 5
    let keyboardType = 'text';
    let keyboardTypeProp = this.props.keyboardType;
    let returnKeyTypeProp = this.props.returnKeyType;
        
    if (keyboardTypeProp === 'default') {
        keyboardType = 'text';
    } else if (keyboardTypeProp === 'numeric') {
        keyboardType = 'tel';
    } else if (keyboardTypeProp === 'email-address') {
        keyboardType = 'email';
    } else if (keyboardTypeProp === 'number-pad') {
        keyboardType = 'tel';
    }

    // Show type="search" in HTML5, allows mobile Safari to show correct "Search" action button 
    if (returnKeyTypeProp === 'search') {
        keyboardType = 'search';
    }

    return keyboardType;
}
```

The only addition is:
```
let returnKeyTypeProp = this.props.returnKeyType;
...
// Show type="search" in HTML5, allows mobile Safari to show correct "Search" action button 
if (returnKeyTypeProp === 'search') {
    keyboardType = 'search';
}
```

This allows for `<input type="search"` to be passed to `TextInput.js` from 
`<RX.TextInput returnKeyTypeProp="search"`. The only thing is the developer would need to manually wrap a `<form action="/">` around their web platform implementation where there is a search input, and everything works magically on the mobile web browser.

The reason this is important is because of the rise of PWA (progressive web apps) as well, so that way the `returnKeyTypeProp="search"` works on native AND mobile web/PWA's.

Any thoughts on this?

**Comment by erictraut** [comment]
I like the idea of mapping the "search" keyboard return type to an input type of "search", but I don't like the idea that we can get the correct behavior only if the caller adds an extra "form" tag. 

What do you think about automatically wrapping the ```<input>``` tag within a ```<form>``` tag in this specific case?

**Comment by MovingGifts** [comment]
I also like adding the "search" input type, but not the manual `<form action"/"` part. I think that wrapping the form behind the scenes would work better, but we just have to make sure that the `action` prop on the form `<form action="/">` or `<form action=".">` does not get executed as an actual action within the `TextInput.tsx`

The form would also need this style to look correct when it has the search text input within it:
`<form action="/" style={{display: 'flex', width: '100%'}}>`

I'd like to proceed with the change, but I am not sure how you want to handle the form wrapping/not executing the form action in `TextInput.tsx`

**Comment by erictraut** [comment]
Sounds good. Here are a couple of approaches:
1. Modify ```_getKeyboardType``` to return an object that includes both a "type" string and a "wrapInForm" boolean.
2. Add a second method ```_requiresFormWrapper``` that returns a boolean.

In either case, the render method can then be modified as follows:
```
   let input = (
      <input
         ....
      />
   );

   if (wrapInForm) {
       // Wrap the input in a form tag if required.
       input = (
          <form action=''>
              { input }
         </form>
       );
   }

   return input;
```

**Comment by MovingGifts** [comment]
Sounds good, [pull request](https://github.com/Microsoft/reactxp/pull/417) complete. Thanks for the guidance :)
