### ISSUE TITLE
How to create component like RadioButton ?

### ISSUE THREAD

**Issue by miskeen110** [Microsoft/reactxp#383]
Which is not available in react-xp package? any example will be higly appreciated.

**Comment by erictraut** [comment]
A radio button is an uncommon UI metaphor in modern apps — especially touch-based apps. 

If you really want something that looks and acts like a radio button, you can easily create one using the ReactXP primitives. Just create an RX.Button object that is styled as a rounded square (using borderRadius style attribute). Within the button, include a view that's also rounded and conditionally filled based on the state. Depending on how fancy you want to get, you could add animated transitions, etc.

**Comment by neelimabhukya** [comment]
can you help me with code ?

**Comment by miskeen110** [comment]
<RX.View>
<input type="radio" value="radio1" name="radioGroup" onClick={this.addFunction} />
<input type="radio" value="radio2" name="radioGroup" onClick={this.addFunction} />
</RX.View>

**Comment by erictraut** [comment]
No, you can't use <input> because that's a web-specific tag. You need to use ReactXP primitives.

I'm not going to write the code for you, but I can help answer questions if you get stuck with something. You might want to refer to the [ToggleSwitch.tsx[(https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/src/ToggleSwitch.tsx) component in the hello-world sample.

**Comment by neelimabhukya** [comment]
import React from 'react'
import RX from 'reactxp';
// import MapView from 'react-native-maps';
const styles = {
    roundButton: RX.Styles.createViewStyle({
      margin: 16,
      borderRadius: 16,
      backgroundColor: '#ff0000ab',
      justifyContent: 'CENTER'
      }),
    }
class Location extends RX.Component {
    constructor(props) {
        super(props);

        this.state = {
            latitude: null,
            longitude: null,
            error: null,
        };
    }

    componentDidMount() {
        navigator.geolocation.getCurrentPosition(
            (position) => {
                this.setState({
                    latitude: position.coords.latitude,
                    longitude: position.coords.longitude,
                    error: null,
                });
            },
            (error) => this.setState({ error: error.message }),
            { enableHighAccuracy: true, timeout: 20000, maximumAge: 1000 },
        );
    }

    render() {
        return (
            <RX.View style={{ flexGrow: 1, alignItems: 'center', justifyContent: 'center' }}>
            <RX.Link style={ styles.docLink } url={ 'https://maps.google.com/maps?q=%22+19.22+%22,%22+16.22+%22&hl=es' }>
                        Google maps
                    </RX.Link>
                <RX.Text>Latitude: {this.state.latitude}</RX.Text>
                <RX.Text>Longitude: {this.state.longitude}</RX.Text>
                {this.state.error ? <Text>Error: {this.state.error}</Text> : null}
                {/* <RX.MapView.Animated
      region={this.state.region}
      onRegionChange={this.onRegionChange}
    /> */}
            <RX.Button style={ styles.roundButton } onPress={ this.props.onNavigateSeven }>
      <RX.Text style={ styles.buttonText }>
      REGISTER
      </RX.Text>
      </RX.Button>
      </RX.View>
    );
    
  }
}

export default Location;

**Comment by neelimabhukya** [comment]
By using this I am getting only latitude and longitude details of current location. Instead of that I want current location name as output. can you help me with that?

**Comment by erictraut** [comment]
To convert lat/long into a location name, you'll need to use a geolocation service such as [Google maps](https://developers.google.com/maps/documentation/geolocation/intro), Bing maps, etc. These involve making calls to a REST endpoint. This is well beyond the scope of ReactXP.

**Comment by neelimabhukya** [comment]
Thanks erictraut.. How to make a post method in reactxp?

**Comment by deregtd** [comment]
Network requests are out of scope of ReactXP.  You can try using:

https://github.com/Microsoft/SimpleRestClients

Or looking at the example in ReactXP that uses it:

https://github.com/Microsoft/reactxp/tree/master/samples/ImageList

**Comment by neelimabhukya** [comment]
I am using js not an typescript deregtd. can you help me how to make a post method in reactxp using javascript.
