### ISSUE TITLE
How to create Read More control?

### ISSUE THREAD

**Issue by moulygupta23** [Microsoft/reactxp#385]
Hi all,

I have a long text with <Text> element and I use numberOfLines to truncate the text and show "..." at the end.

I also want to show Read More link If the text was truncated and while clicking on it will open a page.

How can I know if the text was truncated or not?

Thanks!

**Comment by erictraut** [comment]
The truncation is handled by low-level text layout APIs on each platform, and the information you're looking for isn't exposed. This isn't a ReactXP thing. It's not exposed in the HTML DOM or in React Native either.

The only way I can think to do this is to render two versions of the text — one with a vertical constraint and a second without (so it can be rendered as tall as necessary to avoid any truncation). The unconstrained version can be rendered offscreen. You can then measure the height of both views to see if they differ.
