### ISSUE TITLE
is there good chart libs for reactxp

### ISSUE THREAD

**Issue by geminiyellow** [Microsoft/reactxp#397]
any idea?

**Comment by erictraut** [comment]
I'm not aware of any reactxp extensions that provide charting. You'll probably need to either write one yourself or find an existing charting extension for React Native and React JS.

**Comment by geminiyellow** [comment]
hmm... ok, there is not so many extensions let me hard to start to use reactxp. 
cross-paltform is a good idea, but ...

**Comment by bclermont** [comment]
https://github.com/Fulanko/reactxp-chart

**Comment by geminiyellow** [comment]
amazing! @bclermont
