### ISSUE TITLE
RX.TextInput width is too small on Android

### ISSUE THREAD

**Issue by ubwhole** [Microsoft/reactxp#403]
I want to use RX.TextInput.  When I run this code snippet on iOS simulator, the width of the input field shows the entire placeholder text.  On web, I can also see the entire placeholder text.

When I run it on an Android phone, the width of the input field is only a few characters wide.  I only see "INP" and the rest is cutoff.

I have tried using the maxLength (30) and style props to see if that had any affect.  I also used RX.Text as a child to RX.TextInput.  All the options I tried did not help.

Can someone give me some insight into this problem I have?

Following snippet works on iOS and web:
```
<RX.TextInput onChangeText={this._handleChange} placeholder="INPUT Your Name." value={this._getValue()}>
</RX.TextInput>                    
```

Style props used:
```
    inputText: RX.Styles.createTextStyle({
        fontSize: 16,
        minWidth: 30,
        marginBottom: 16
    }
```

**Comment by ubwhole** [comment]
I updated the style on the RX.TextInput element to have a width.  I can specify the size I want the input field to be.

I also created a React Native project with a TextInput element.  The behavior of the input field is different for Android.  When I type characters that is beyond the width of the field, the field width expands to show all of the characters.

**Comment by erictraut** [comment]
Different platforms may have different layout behaviors if you specify no width or a minWidth. You should use an absolute width or style the TextInput such that its width is defined by its parent container.

**Comment by ubwhole** [comment]
Thanks for your reply.  I just tried the minWidth and see the input field is sized accordingly.  

How to style the TextInput so that the width is defined by its parent?  I tried flex and width on the parent view and the width did not adjust to the parent.

**Comment by erictraut** [comment]
You need to use the normal flexbox style attributes. If the parent is using flexDirection: 'column', you'll need to style the child with alignSelf: 'stretch' so its width fills the width of the parent. If the parent is using flexDirection: 'row', you'll need to style the child with flex: 1 to achieve the same effect.
