### ISSUE TITLE
RX.TextInput on mobile web keyboardType not applied

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#409]
It seems that on web (checked on mobile safari), the `keyboardType` prop on `RX.TextInput` does not work correctly. For web, the correct HTML5 values for input type should carry over for a truly hybrid (ios/android/web) virtual keyboard approach.

These are the keyboards that need to be fixed for web to display the correct input type:
`keyboardType: 'default' | 'numeric' | 'email-address' | 'number-pad';`

default -> `<input type="text">`
numeric -> `<input type="tel">`
email-address -> `<input type="email">`
number-pad -> `<input type="tel">`

Above, I listed the correct HTML5 equivalent type to the right of each `keyboardType`. The numeric/number-pad should have tel as the type I think, check the [mobile input types](http://mobileinputtypes.com/) for why it's superior to the `<input type="number">`

Currently, all `keyboardTypes` render as `<input type="text"` in web/mobile web, which should be corrected for a better UX on mobile web.

Any thoughts on this?

**Comment by erictraut** [comment]
This is similar to this issue: https://github.com/Microsoft/reactxp/issues/381. As I mentioned, we have put little or no energy into making mobile browsers work well because we assume that mobile users will want a native experience. If this is important to you, feel free to contribute a PR.
