### ISSUE TITLE
WebView Support for HTML (as text) and "onMessage" notifications

### ISSUE THREAD

**Issue by nir-schleyen** [Microsoft/reactxp#418]
Would be awesome if react XP WebView can support:
1. putting in html as a text (rather than url). (like the ReactNative WebView) 
2. onMessage function that lets the hosted page send notifications to the react app (same as via the "onMessage" method of the react Native component).

**Comment by erictraut** [comment]
These have been on my to-do list for a while. I just implemented them and published a new version: 0.51.0-alpha.2. To see a usage sample, refer to the [RXPTest app](https://github.com/Microsoft/reactxp/blob/master/samples/RXPTest/src/Tests/WebViewDynamicTest.tsx).
