### ISSUE TITLE
More descriptive readme.md

### ISSUE THREAD

**Issue by gautamkrishnar** [Microsoft/reactxp#45]
Shall i make the readme.md more descriptive?
*  Now it contains info about **contact details & code of conduct** only

**Comment by erictraut** [comment]
We've put lots of details in the accompanying documentation pages, which are also checked in to the repo. What else do you propose to add to the README?

**Comment by gautamkrishnar** [comment]
I think we should add all details about the project in the readme. 
A good readme must have:
* Project description
* Installation instruction
* Use cases
* How to contribute
and so on....
Please checkout this template: https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

Its just a suggestion. As this project is now trending on GitHub its important to have a good readme, So that the people can easily get started using it....

**Comment by erictraut** [comment]
I don't want to duplicate the information in the doc pages, but I agree it would be useful to have some high-level summary information in the README.

**Comment by gautamkrishnar** [comment]
Yes 👍 At least we could add the project's description...

**Comment by gautamkrishnar** [comment]
@erictraut You need to update https://github.com/Microsoft/reactxp/blob/master/samples/README.md as well. It doesn't contain instructions to build the app as mentioned in https://microsoft.github.io/reactxp/docs/getting-started.html

**Comment by gautamkrishnar** [comment]
@erictraut Just created a PR. Shall I update the https://github.com/Microsoft/reactxp/blob/master/samples/README.md as well?
