### ISSUE TITLE
how do i add zIndex to css style

### ISSUE THREAD

**Issue by SuperTizzyGod** [Microsoft/reactxp#452]
is any way to support :zIndex for ViewStyle,

when i add zIndex to css style(ViewStyle),visual code hint me err;

is any way to support it(react-native support it)

**Comment by erictraut** [comment]
zindex isn't supported in ReactXP. It's also not supported in RN. We've found that there are always other ways to work around the need for zindex. Just change the rendering order.

**Comment by SuperTizzyGod** [comment]
https://facebook.github.io/react-native/docs/0.36/layout-props.html#zindex
react native 0.36 support it

**Comment by erictraut** [comment]
I'd prefer not to add zindex. In my experience, there's always a cleaner way to implement something without using zindex. I'd be more inclined to add it if zIndex were implemented in a consistent fashion across all supported implementations of RN, but that's not currently the case. It has been added to iOS and Android, but they have different behaviors and limitations.

If you have a specific use case in mind for zindex, let's discuss and see if I can convince you that there's a cleaner way to accomplish your objective.
