### ISSUE TITLE
Error with running react-native eject / upgrade

### ISSUE THREAD

**Issue by runar-rkmedia** [Microsoft/reactxp#459]
I ran into a problem with my iOS not building for some reason. I, therefore, tried to recreate the `ios` and `android` -directories with `react-native eject`, after creating an `app.json`. However,
this resulted in the following error: 

> Application App has not been registered.
> Hint: This error often happens when you're running the packager (local dev server) from a wrong folder. For example you have multiple apps and the packager is still running for the app you were working on b#efore. 
> If this is the case, simply kill the old packager instance (e.g. close the packager terminal window) and start the apackager in the correct app folder (e.g cd into app folder and run 'npm start').
>
> This error can also happen due to a require() error during initialization or failure to call AppRegistry.registerComponent.

I've tried to restart the packager, but the same error is returned. Is this somehow due to how ReactXP itself runs `AppRegisty` behind the scenes?

Is ejecting/upgrading in this way not intended with reactXP?

**Comment by erictraut** [comment]
I suspect the error indicates that you have not [registered the main module as "RXApp"](https://microsoft.github.io/reactxp/docs/using-reactxp.html).

See the [hello-world sample code](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/ios/RXPHelloWorld/AppDelegate.m).

**Comment by runar-rkmedia** [comment]
Oh, great stuff. Thank you so much. I guess this can be closed as well.
