### ISSUE TITLE
TextInput.componentWillReceiveProps seems to be inconsistent between web and native.

### ISSUE THREAD

**Issue by Wheresmind** [Microsoft/reactxp#461]
The code for "**componentWillReceiveProps**" in reactxp/src/web/TextInput.js is : 
`    componentWillReceiveProps(nextProps: Types.TextInputProps) {
        if (nextProps.value !== undefined && nextProps.value !== this.state.inputValue) {
            this.setState({
                inputValue: nextProps.value || ''
            });
        }
    }
`

The code for "**componentWillReceiveProps**" in reactxp/src/native-common/TextInput.js is : 
`
    componentWillReceiveProps(nextProps: Types.TextInputProps) {
        if (nextProps.value !== this.state.inputValue) {
            this.setState({
                inputValue: nextProps.value || ''
            });
        }
    }
`

Notice the missing `nextProps.value !== undefined &&` in the "if" statement of the native implementation. This causes the TextInput components, with no "value" attributes, on Android (probably also IOS), to be cleared every time "setState()" is called on the parent component.

This was noticed in In reactxp@0.46.6.
I also checked the source in the **master** branch and it appears to have the same issue.

**Comment by erictraut** [comment]
Yes, I agree this is a problem. Thanks for diagnosing and reporting!

If you'd like to submit a PR, and I can review & merge it. Or I can fix it when I'm back from vacation.

**Comment by Wheresmind** [comment]
It would be a pleasure to be a collaborator and submit Pull Requests for this project.
