### ISSUE TITLE
material styling for web using reactxp

### ISSUE THREAD

**Issue by colmbrady** [Microsoft/reactxp#463]
Material design defines text fields as having a solid bottom border. I'd like to style RX.Input in this way.

Source: https://material.io/guidelines/components/text-fields.html#text-fields-layout

If I look at the React XP style props available, it seems that the borders (top, left, bottom and right) cant  be styled separately. (https://microsoft.github.io/reactxp/docs/styles.html)

Do you have any suggestions for how I can achieve this?

**Comment by erictraut** [comment]
You could enclose the TextInput in a View container and use one border style for the container and another for the TextInput.

**Comment by colmbrady** [comment]
I was hoping there was an option without having to introduce extra components into the markup.

However, something like below should work, Ill go with that. Thank you.

```
<View>
<TextInput />
<View style={{ borderWidth: 1, borderStyle: 'solid', borderColor: 'black' }} />
</View>
```

**Comment by Ravim-addweb** [comment]
Hi @colmbrady - can you please specify regarding how you integrated Material design with ReactXP? Much appreciated.

**Comment by Joeao** [comment]
@Ravim-addweb Sounds like he followed the design patterns and styled manually rather than integrated with a library

**Comment by colmbrady** [comment]
Yes, we were exploring how much effort it would be to implement material components with React XP. We ended up moving away from ReactXP to React Native (+Web) as a lot of the React Native libraries seem to work well on the web without repackaging.

There is no equivalent to material-ui in React Native from what I can find. React Paper is promising - but incomplete for our requirements.

**Comment by Ravim-addweb** [comment]
Thanks @colmbrady for the feedback.
