### ISSUE TITLE
ToggleSwitch vs ProgressIndicator?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#473]
For the `hello-world-js` example the `SecondPanel.js`, I was creating a boiled down version focused only on the `ToggleSwitch`, but it seems that the animation breaks on the toggle switch the second time you click it, then there is no animation, it just jumps on click.

I narrowed the issue down in to this line in [this gist.](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b#file-secondpanel-js-L34)

Here is the line:

```jsx
componentDidMount() {
    this._startProgressIndicator(); // why does commenting this out break the toggleSwitch?
}
```

I guess I don't understand why commenting out this line (which I thought had to do with with `ProgressIndicator` component break the functionality for the `ToggleSwitch` component). 

Shoudn't the `ToggleSwitch` work correctly without it?

**Comment by erictraut** [comment]
I assume the problem occurs on the web (as opposed to one of the RN platforms)?

Looking at the code, I don't see an obvious problem. I'd need to debug it more deeply, but I won't have time to do that this week.

Does the problem occur with reactxp 0.51.x, or are you still using 0.46.x? I rewrote the web animation code in 0.51.x and fixed a bunch of bugs.

**Comment by MovingGifts** [comment]
Yup, I am testing on the web platform at the moment where it occurs.

I upgraded the reactxp version in the `hello-world-js` to `"reactxp": "^0.51.2"`. I also updated [the gist](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b) with [ToggleSwitch.js](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b#file-toggleswitch-js) file to help debugging.

Still really weird that it occurs though!

**Comment by erictraut** [comment]
There was a bug in the ToggleSwitch implementation. It was starting the animation from within componentWillUpdate rather than componentDidUpdate. React's DOM update code was interfering with the animation.

**Comment by MovingGifts** [comment]
Thank you for that! You're correct, changing `componentDidUpdate` to `componentWillUpdate` makes the animation work now instead of jumping and relying on progessIndicator. The only issue now with the toggle switch is that it takes 2 clicks to start sliding the very first time (the first click is ignored for some reason), then all future clicks toggle the switch as expected.

Any idea how to get it to work from the first click?

**Comment by erictraut** [comment]
I'm not able to repro that behavior. It works fine for me on first click. I've tried multiple browsers and tried removing the video & progress indicator. I also tried both the js and ts versions, and I get the same (correct) behavior.

**Comment by MovingGifts** [comment]
That's weird, since it takes 2 clicks on my side. I updated [the gist](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b) with even more boiled down code for both [SecondPanel](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b#file-secondpanel-js) and [ToggleSwitch](https://gist.github.com/MovingGifts/c32a900d7da08495e7983608d549541b#file-toggleswitch-js)

To demonstrate the issue visually, I added the following alert in ToggleSwitch, which alerts each time on click, but the toggle functionality only works on the second click as you can see below:
```js
// ToggleSwitch.js
_handleClick(e) {
        e.stopPropagation();
        alert('hit');

        if (this.props.onChange) {
            this.props.onChange(!this.props.value);
        }
    }
```
![toggle-ignoring-first-click](https://user-images.githubusercontent.com/1202909/35542617-daafa530-052e-11e8-84b6-2dfc9bcdb338.gif)

The issue is in all browsers tested: FF, Chrome, Safari

These are the versions used from the reactxp samples, I only updated the reactxp version:
```
"react": "16.2.0",
"react-dom": "16.2.0",
"reactxp": "^0.51.2",
```
Not sure how we're not getting the same thing here...

**Comment by erictraut** [comment]
The "ToggleSwitch.js" implementation in your gist doesn't match the version that I checked in. It has bugs. If you pull the latest version from the ReactXP repo, it will work.

**Comment by MovingGifts** [comment]
Awesome, after pulling in the latest version it works flawlessly now without any bugs. Thank you for correcting and pointing the buggy version out!
