### ISSUE TITLE
RX.TextInput: "Warning: `value` prop on `input` should not be null"

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#475]
Looking at the second error below, it never used to happen before but it seems that it's a react error. It happens when a value for the `TextInput` is set in state as `null` (as a default value) before changing it in the view.

![screen shot 2018-01-30 at 7 14 20 am](https://user-images.githubusercontent.com/1202909/35571837-37543978-05a1-11e8-8c4a-68df56076d46.png)

I don't understand why this happens now, since it never used to happen before with the `null` assigned as the default value. I have this all over the app since it was working fine before, but now it shows the error.

I created this issue to bring attention to it and see if there is a way to get the default value of `null` assignment to work as it did before once again, or is the recommended course of action to just replace all the `null` assignments with an empty string `''` or `undefined`?

**Comment by erictraut** [comment]
If you're specifying a defaultValue, it should be a valid string, not null or undefined. An empty string ('') is a valid string.

**Comment by MovingGifts** [comment]
Got it, thank you for getting back so quickly; not sure why it passed before without any errors though.
