### ISSUE TITLE
Image issue in responsive

### ISSUE THREAD

**Issue by ghazaltaimur13** [Microsoft/reactxp#491]
I need to show my image on my full screen width.
I add an image with resizeMode "**cover**"  when i resize my browser screen image not adjust with the screen size. It cuts my image from right and left.
But when i use resizeMode "**auto**", it will resize my image on small screens but on full screen my image shows on center of screen.
Is this possible to show my image to full width and auto resize on small screen?

**Comment by erictraut** [comment]
If the image is a different aspect ratio than the container size, you have two choices: 
1. "cover" will crop the image, either the top/bottom or left/right
2. "contain" will letterbox the image, leaving background color visible on the top/bottom or left/right
I'm not sure which of those two behaviors you desire.
If you want different behaviors based on the screen size or aspect ratio, you'll need to adjust the resizeMode dynamically in the code. You can do this by calling RX.UserInterface. measureWindow() if the container is the full window or screen. Or you can use an onLayout prop to receive the dimensions of any other view in the hierarchy.

**Comment by ghazaltaimur13** [comment]
@erictraut i have dynamically change resizeMode. On Web view i used **cover** but when screen size changes , it dynamically change into "auto". But in small screens "**auto**" conatains alot of space from top and bottom.
Is there any way to avoid spaces from top and bottom in auto mode? Or use anyother resize mode?

**Comment by erictraut** [comment]
Auto equates to “contain”. It sounds like it is working as expected. If you don’t want space above and below, you need to use “cover”.
