### ISSUE TITLE
TextInput does not set all of accessibility properties

### ISSUE THREAD

**Issue by gmangov** [Microsoft/reactxp#493]
The documentation states that TextInput supports common accessibility properties, however the only accessibility property that it sets for RN.TextInput is accessibilityLabel.

**Comment by erictraut** [comment]
For accessibility features, we've taken the pragmatic approach of adding features as we experience a need. If you have a specific need, let us know. Or better yet, feel free to submit a PR.

**Comment by gmangov** [comment]
@erictraut No, you can close it.
