### ISSUE TITLE
Using react-native-web for web implementation

### ISSUE THREAD

**Issue by necolas** [Microsoft/reactxp#50]
The native side of ReactXP is built on react-native. The web side could be built upon react-native-web, which is implementing the react-native API (with custom extensions for web). Let me know if you're interested in talking about it

**Comment by erictraut** [comment]
Please see the [FAQ](https://microsoft.github.io/reactxp/docs/faq.html) for why we did not go this route.

**Comment by ttraenkler** [comment]
I would love to see the idea of sharing code between React Web and React Native flourish. It would help this still small community if these two projects could agree to join forces in one or another way - e.g. by factoring out shared code e.g. for components like `<View>` or `<Animated>` into react-native compatible submodules for the web that can be shared, like I think @necolas has already started as a separate project. I don't know the technical internals of ReactXP, just that it is instead based on react-native, but it would be great if you could at least try to discuss and identify some common ground and a joint way to go forward if technically feasible.
