### ISSUE TITLE
reactxp-imagesvg@latest on web is not compatible with reactxp@0.51.7

### ISSUE THREAD

**Issue by berickson1** [Microsoft/reactxp#502]
ImageSVG uses an API that was removed from reactxp 0.51.7 and will throw an exception when using webShadow since it does the following:
`let aliases = RXStyles.getCssPropertyAliasesCssStyle();`

API removed in 9bb3785d35dcc2f916ccb5a4973064f0ddd6ae47

**Comment by berickson1** [comment]
Reverted breaking change in reactxp 0.51.8 and published 0.51.9, still incompatible in master

**Comment by erictraut** [comment]
@berickson1, my bad. I didn't realize this method was being used by an extension. It's not used internally, and it's not documented as being part of the ReactXP API. I've reverted the change on master and then re-implemented the original bug fix without removing this API. I also added a comment to prevent this in the future. I didn't cherry-pick the fix into 0.51.x. You can do that if you'd like.
