### ISSUE TITLE
Text wrap

### ISSUE THREAD

**Issue by zarubond** [Microsoft/reactxp#509]
Hi,

I have a text which contains new lines ('\r\n') and I want to display only one line from it with RX.Text. I set the property numberOfLines to one and expect to see only one line and the rest of the text to be elisioned.  This works fine on Android but I am having difficulties with Electron. On Electron I can see all lines and all of them are elisioned shown below.

For my case it would be helpful if I could set 'text-wrap: nowrap', but this would solve this problem only for single line.

Electron result 
![overflow](https://user-images.githubusercontent.com/6961047/36311892-10a2e9b6-132d-11e8-928f-b9d96e303bce.jpg)

Correct Android result
![2018_02_16_15 35 19](https://user-images.githubusercontent.com/6961047/36312605-52289af0-132f-11e8-98c4-f392910e39b1.png)

**Comment by erictraut** [comment]
The HTML layout engine handles this case differently from the RN layout engine on iOS and Android. Working around this difference within ReactXP would be difficult. In your case, there's an easy workaround within your app's code. Simply truncate the string at the first new line sequence before rendering it.
