### ISSUE TITLE
I'm not 100 % clear on this.   What benefits do i get from ReactXP   

### ISSUE THREAD

**Issue by jpca999** [Microsoft/reactxp#51]
I'm just begining to port my phone application from ionic to React native. 

I can write an app for ios and for android with react native, but React native doesnt work on web. 
so ReactXP provides a way to run the app work on web just like  https://goo.gl/pO9crq 

What other benefits do i get from ReactXP if I'm already using React Native ?

**Comment by erictraut** [comment]
Let me know if the [FAQ](https://microsoft.github.io/reactxp/docs/faq.html) answers your question.

**Comment by kokizzu** [comment]
I think the main benefit would be single codebase/project for all supported platform: Android, iOS, Web, and Windows.
