### ISSUE TITLE
Cheers!!

### ISSUE THREAD

**Issue by dooboolab** [Microsoft/reactxp#510]
Hi! Thanks for really interesting work. This is not an issue, I just wanted to share my experience and thought about this work.

It would be really great if this repo collaborates with [expo](http://expo.io) to support web and window platforms with existing expo library. If it may not be possible, I hope [reactxp](https://microsoft.github.io/reactxp/docs/getting-started.html) creates more libraries like expo does for react-native.

I tried to use reactxp for my project since my service did not depend on native part too much. However, the critical issue was that I should create my own facebook login and google login for window, web, and react-native (ios & android mostly). I found out that this will be a bit time consuming, and sadly gave up with this. I was also afraid if my hard work will remain consistent.

Hope there are more supports with basic utilities that most app uses which can be found mostly in [expo doc](https://docs.expo.io/versions/latest/index.html).
Also, hope this project gains much more power by MS software team so many interested developers get involved in it in some respects.

I'm also willing to contribute some libraries if I find out that MS & Skype team is looking forward to power up [reactxp](https://microsoft.github.io/reactxp/docs/getting-started.html).

Thank you for reading. Have a nice day.

Also, it would be really nice if there is a guide to making library like [react-native link](https://facebook.github.io/react-native/docs/linking-libraries-ios.html) for [reactxp](https://microsoft.github.io/reactxp/docs/getting-started.html) so many developers can contribute to libraries easily.

**Comment by erictraut** [comment]
Thanks for the input, @dooboolab. 

We welcome the addition of new ReactXP extensions — either as part of the reactxp github repo or as stand-alone projects. 

If you're interested in building an extension, I recommend starting from one of the existing extensions like image-svg. Look in the extensions directory for other examples. You should be able to copy most of the existing files and simply modify the extension-specific core logic.

I also recently expanded the [ReactXP extension documentation](https://microsoft.github.io/reactxp/docs/extensions.html) based on feedback from others.
