### ISSUE TITLE
Import font-family

### ISSUE THREAD

**Issue by alexbom** [Microsoft/reactxp#513]
Greetings!
Tell me, please, is there a chance to import a third-party font to my ReactXP application?
I can't find the answer to this question in the documentation and other topics.

**Comment by alexbom** [comment]
I've tried this one: https://medium.com/react-native-training/react-native-custom-fonts-ccc9aacf9e5e
But unlucky - linked font doesn't connect by fontFamily in RX.Styles.createViewStyle

**Comment by erictraut** [comment]
Yes, it's possible to add a custom font. The process differs a bit from one platform to another. It sounds like you're interested in iOS or Android. The link you posted above provides instructions for how to add the font to your XCode or Android Studio project. Once added, you can simply reference the font by name within your app code.

You can't add a fontFamily to a View. It's applicable only to Text or TextInput. Use RX.Styles.createTextStyle or RX.Styles.createTextInputStyle, respectively.
