### ISSUE TITLE
Line height size

### ISSUE THREAD

**Issue by zarubond** [Microsoft/reactxp#522]
Hi I am trying to set the line height on RX.Text element in browser.

Example:
`<RX.Text style={{lineHeight: 33}}>X</RX.Text>`

The expected behavior would be to set the line style to 33px. But unfortunately the postfix is not set and the browser thinks that I want a line height of 33 times font size.

![lineheight](https://user-images.githubusercontent.com/6961047/36603136-21060cce-18ba-11e8-9ca3-a1b0b44515a2.jpg)

**Comment by erictraut** [comment]
The problem is that you're not using the appropriate style creation methods in RX. In this case, you should use RX.Styles.createTextStyle({ lineHeight: 33 } to allocate the style.

**Comment by zarubond** [comment]
Thanks, that solved the problem.
