### ISSUE TITLE
Animating CSS props with dashes does not work in Browser

### ISSUE THREAD

**Issue by robeeeert** [Microsoft/reactxp#528]
## Description

I encountered this while trying to animate the `background-color` property.

ReactXP v0.51.9
React v16.2.0
ReactNative v0.51.0

Windows 10
Google Chrome v64.0.3282.167

Minimal example component to reproduce issue:

```
import * as React from 'react';
import * as RX from 'reactxp';

export class BackgroundAnim extends React.PureComponent<{}, {}> {
	private backgroundStyle: RX.Types.ViewStyleRuleSet;
	private animatedBackground: RX.Animated.Value;
	private animatedBackgroundStyle: RX.Types.AnimatedViewStyleRuleSet;

	constructor(props: {}) {
		super(props);
		this.animatedBackground = RX.Animated.createValue(0);
		this.animatedBackgroundStyle = RX.Styles.createAnimatedViewStyle({
			backgroundColor: RX.Animated.interpolate(this.animatedBackground,
				[0, 1],
				['#000000', '#ffffff'],
			)
		});
		this.backgroundStyle = RX.Styles.createViewStyle({
			width: 200,
			height: 200,
		});
	}

	componentDidMount(): void {
		RX.Animated.timing(this.animatedBackground, {
			toValue: 1,
			duration: 1000
		}).start();
	}

	render(): JSX.Element {
		return (
			<RX.Animated.View style={[this.backgroundStyle, this.animatedBackgroundStyle]} />
		);
	}
}
```

The `executeTransition` function adds the following transition to the style attribute:

```
transition: backgroundColor 1000ms ease 0ms;
```

## Problem

This does not work, because `backgroundColor` is not a valid CSS prop.

## Solution

The solution I found was to simply wrap the property in a lodash `kebabCase` call in `web/animated/executeTransition.ts`, line 29:

```
const property = _.kebabCase(transition.property);
```

For consistency, line 94 should be edited equally.

Cheers,
Rob

**Comment by erictraut** [comment]
Thanks for reporting this issue. I already fixed this recently. It's included in the "1.0.0-alpha.2" pre-release version and will be part of the "1.0.0" production version, which we'll publish soon.
