### ISSUE TITLE
Navigator documentation

### ISSUE THREAD

**Issue by olivoil** [Microsoft/reactxp#53]
is there an example use of the Navigator component? Currently the doc only says:

> TODO: Need to add full documentation that includes sample usage, styles, props, and methods. See other components for a template.

**Comment by erictraut** [comment]
The engineer who wrote the navigator doc and is most familiar with it is slated to write the documentation, but he's currently busy with some other high-priority stuff. It's on his to-do list.

**Comment by olivoil** [comment]
Thanks, looking forward to it!

**Comment by vitorlans** [comment]
Hi, there are any news about documentation of Navigator component?

How can I create more than one screen using reactXP without Navigator?
Thanks.

**Comment by simonas-notcat** [comment]
I'm also waiting for Navigator documentation. Could we get at least a small usage example?

Thanks

**Comment by cduplantis** [comment]
Eagerly awaiting any sort of Navigator example.

**Comment by erictraut** [comment]
As requested, I added a Navigator example to the ReactXP "hello-world". The documentation is next on my to-do list. You should be able to mostly figure it out from the sample.

**Comment by erictraut** [comment]
Thanks for your patience. I finally had time to write the [documentation for Navigator](https://microsoft.github.io/reactxp/docs/components/navigator.html).
