### ISSUE TITLE
Expose PureComponent from React

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#542]
Is there an implementation reason why `React.PureComponent` isn't exported from ReactXP.ts?

**Comment by erictraut** [comment]
We've never needed it before. We always derive props from RX.Types.CommonProps, and we use RX.Stateless if a component has no state. So the equivalent of React.PureComponent is:
RX.Component<RX.Types.CommonProps, RX.Stateless>

**Comment by Fitzpasd** [comment]
They are slightly different, `React.PureComponent` implements a shallow `shouldComponentUpdate` automatically.  This is usually the first route people take when trying to increase perf: change components to Pure wherever possible.

**Comment by Fitzpasd** [comment]
Worth noting that some people believe PureComponent should have been the default.  Perhaps it would be worthwhile considering adding a default shallow copy `shouldComponentUpdate` to the base class exposed by this library.

**Comment by erictraut** [comment]
I assume you mean "shallow comparison". It would break lots of code if we made this the default for RX.Component.

You can always use React.PureComponent if that's the behavior you're looking for.

**Comment by Fitzpasd** [comment]
That's what we're doing, just added noise of having an extra import now in all our tsx files, rather than fully relying on RX.   Personally I think it should be added, but understand not wanting to also and don't feel very strongly either way.
