### ISSUE TITLE
ScrollView use the scrollTop - Function

### ISSUE THREAD

**Issue by Turtle0601** [Microsoft/reactxp#543]
Hi,
my scenario:

I have a scrollview with diffrent views. This views can open...for example a accordion. 
The scrollview must react with the clicked view and should scroll this on the top. 

I think i must use the scrollTop- Funktion, but i can't call to the scrollview. 

I have read, that can call the scrollview with ref. But its get an error, that the component that found have not the scrollTop - Function.

<RX.ScrollView style={styles.scroll} ref="scrollView" >
     <RX.View style={styles.container} scrollToTop={ () => this._scrollToTop}></RX.View>
     <RX.View style={styles.container} scrollToTop={ () => this._scrollToTop}></RX.View>
     <RX.View style={styles.container} scrollToTop={ () => this._scrollToTop}></RX.View>
</RX.ScrollView>

private _scrollToTop = () => {
    this.refs.scrollView.setScrollTop({scrollTop:0, animate: true});
}

What is wrong?

**Comment by erictraut** [comment]
setScrollTop doesn't take an object as a parameter. It takes two parameters. Try changing your code to:
this.refs.scrollView.setScrollTop(0, true);

You should consider moving to TypeScript. Bugs like this are found immediately by the TypeScript compiler.

**Comment by Turtle0601** [comment]
Hi, thanks for this tip! 
It works!
