### ISSUE TITLE
TextInput [web] input validation doesn't work if keyboardType = 'numeric'

### ISSUE THREAD

**Issue by RomanLysogor** [Microsoft/reactxp#553]
Existing logic in TextInput defining which type will be applied on `<input>` element:
```
        let keyboardTypeValue = 'text';
        let wrapInForm = false;
        let pattern = undefined;

        if (this.props.keyboardType === 'numeric') {
            pattern = '\\d*';
            keyboardTypeValue = 'number';
        } else if (this.props.keyboardType === 'number-pad') {
            keyboardTypeValue = 'tel';
        } else if (this.props.keyboardType === 'email-address') {
            keyboardTypeValue = 'email';
        }
```
There are a couple of issues with it when running on web when "numeric" keyboardType is passed:

1. _pattern_ is applied only when <input> is wrapped into <form>. The same idea is already implemented for returnKeyType === 'search';
2. _pattern_ will work as a post validation. It will be used only when user submits or press "Enter" as an example. This means that user can type everything in the field;
3. comparing with the numeric keyboard in ReactNative. RN will use a keyboard with 0-9 + ".", so user cannot type anything except numbers. With a current pattern "\d*" only digits allowed, so no float value can be validated.
4. keyboardTypeValue = 'tel'. Input type = 'tel' is supported only supported in [Safari 8](https://www.w3schools.com/html/html_form_input_types.asp), so it is almost not used anywhere. 

Suggested solutions (when keyboardType === 'numeric'):

1.  set `keyboardTypeValue = 'number'`. That will restrict (pre-validation) user input only to digits, "." and "-". The disadvantage is that RN doesn't have "-" when numeric keyboardType is specified. 
2. update pattern to support "." and set `wrapInForm = true`. It will make post-validation happening. The disadvantage is that user can input anything in the field and validation will happen only onSubmit/Enter + it will have built-in validation styling based on the browser

**Comment by erictraut** [comment]
The current implementation works as documented. Input validation is not implied by "keyboardType". The keyboardType is intended only as a hint for which on-screen keyboard to display for touch-based systems. If you want to implement input validation, you can do so within your app's logic.
