### ISSUE TITLE
npm run tslint: No valid rules have been specified

### ISSUE THREAD

**Issue by alexbom** [Microsoft/reactxp#554]
Hello!
I'm trying to run tslint with default package.json command and default tsconfig.json, but get the error i don't understand:

npm run tslint
> tslint --project tsconfig.json -r tslint.json -r ./node_modules/tslint-microsoft-contrib --fix || true
No valid rules have been specified

package.json

>  "scripts": {
    "web-watch": "webpack --progress --colors --watch",
    "rn-watch": "tsc --watch",
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "android": "node node_modules/react-native/local-cli/cli.js run-android",
    "ios": "node node_modules/react-native/local-cli/cli.js run-ios",
    "tslint": "tslint --project tsconfig.json -r tslint.json -r ./node_modules/tslint-microsoft-contrib --fix || true",
    "start:dev": "webpack-dev-server"
  },

tsconfig.json

> {
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "declaration": false,
    "noResolve": false,
    "jsx": "react",
    "reactNamespace": "RX",
    "module": "commonjs",
    "target": "es5",
    "experimentalDecorators": true,
    "sourceMap": true,
    "noImplicitAny": false,
    "noImplicitReturns": true,
    "outDir": "./dist/",
    "types": [
      "node"
    ]
  },
  "include": [
    "./src/**/*"
  ]
}

What i make wrong?

**Comment by erictraut** [comment]
Looks like you're missing the tslint.json file that defines which lint rules you want to enable. You can copy [this one](https://github.com/Microsoft/reactxp/blob/master/tslint.json) from reactxp if you'd like.

**Comment by alexbom** [comment]
God bless you, Eric :) Sorry for the stupid question.
