### ISSUE TITLE
There are an implementation for an accordion / collapsible list for reactXP?

### ISSUE THREAD

**Issue by Turtle0601** [Microsoft/reactxp#555]
Hi,

i need an accordion or collapsible list for my project. 

There are an example for an implemantion for this? 
Or there are cool tips for this themes?

Thanks for help!

**Comment by erictraut** [comment]
I'm not aware of any collapsible list controls built for reactxp. It should be relatively straightforward to implement this using the reactxp primitive controls — assuming your lists are relatively short and don't require virtualization.
