### ISSUE TITLE
fadeDuration added by default on Android for RX.Image is resulting in error

### ISSUE THREAD

**Issue by simonghales** [Microsoft/reactxp#56]
```
ExceptionsManager.js:71 Warning: Failed prop type: Invalid props.style key `fadeDuration` supplied to `RCTImageView`.
Bad object: {
  "width": 360,
  "height": 360,
  "overflow": "hidden",
  "flex": 0,
  "borderRadius": 5,
  "fadeDuration": 0
}
```

Here's the code I'm creating my ImageStyle with

```
artistImageStyle =  RX.Styles.createImageStyle({
            borderRadius: 5,
            height: width,
            width: width
        });
```

And here's my Image element.

```
<RX.Image source={track.getHighResImage()} style={artistImageStyle}/>
```

Looking through the source, I believe this is where fadeDuration is being set

https://github.com/Microsoft/reactxp/blob/0e195c9cac45b15bcee324945720b91d1249b6d7/src/android/Image.tsx

I'm running the build through Android Studio and testing on my Samsung Galaxy S6.

Cheers

**Comment by berickson1** [comment]
@simonghales, fadeDuration is not a supported prop in reactxp since it isn't implemented in react-native iOS or web
Please see: https://microsoft.github.io/reactxp/docs/components/image.html

**Comment by simonghales** [comment]
Sure, but I am not adding fadeDuration in my code, it's being added by
reactxp (see the file I linked to above).

On 19 Apr 2017 5:34 PM, "Brent Erickson" <notifications@github.com> wrote:

@simonghales <https://github.com/simonghales>, fadeDuration is not a
supported prop in reactxp since it isn't implemented in react-native iOS or
web
Please see: https://microsoft.github.io/reactxp/docs/components/image.html

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/reactxp/issues/56#issuecomment-295139978>,
or mute
the thread

**Comment by berickson1** [comment]
Interesting. My apologies, I misread your post. The FadeDuration prop had been supported in an undocumented state for approximately a year (https://github.com/facebook/react-native/blame/master/Libraries/Image/Image.android.js) and we utilize it inside reactxp to remove the differences between image loading on platforms. 
What version of react-native is your project running? I can whip up an example in the morning to see if something changed in RN support of this prop

**Comment by simonghales** [comment]
No worries mate.
I'm using the version of react-native used in the hello-world example `0.42.3`

https://github.com/simonghales/reactxp-hello-world/blob/master/package.json

**Comment by berickson1** [comment]
I've confirmed that this is a valid issue. I'm trying to figure out why this got missed in our testing.  For the time being, this shouldn't block you aside from the annoying warning dialogues.  I'll try to get this sorted out asap :) It looks like it should be a prop, not a style attribute
