### ISSUE TITLE
Importing react-native results in errors

### ISSUE THREAD

**Issue by simonghales** [Microsoft/reactxp#57]
Hey there,

Apologies as this issue might not be specifically due to ReactXP, but I'm building upon the Hello World example and when I import react-native I'm getting a series of errors:

`const ReactNative: any = require('react-native');`
_(importing it as any temporarily to avoid issues I was having with the typings files)_

```
ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Can't resolve 'ActivityIndicator' in '/Users/surfacepro/WebstormProjects/hydric-noodles-reactxp/node_modules/react-native/Libraries/react-native'
 @ ./~/react-native/Libraries/react-native/react-native.js 30:35-63
 @ ./src/App.tsx
 @ ./src/index.tsx

ERROR in ./~/react-native/Libraries/react-native/react-native.js
Module not found: Error: Can't resolve 'ReactNativeART' in '/Users/surfacepro/WebstormProjects/hydric-noodles-reactxp/node_modules/react-native/Libraries/react-native'
 @ ./~/react-native/Libraries/react-native/react-native.js 31:21-46
 @ ./src/App.tsx
 @ ./src/index.tsx
```

etc..

It would seem that if I open up `node_modules/react-native/Libraries/react-native/react-native.js` every single `require('...')` within the file is unable to resolve itself. I'm a bit uncertain about how to fix it up so that all the requires are able to resolve themselves.

Apologies again that this isn't about ReactXP itself, but I figured it'd be pretty common for somebody to continue on from the example project and try to implement some React Native components. So thank you if anyone is able to offer any suggestions on how to address the issue.

**Comment by simonghales** [comment]
Scratch that folks, I believe I've identified the issue will be solved by including the react-native typings provided in this repo, and by using the import syntax of `import ReactNative = require('react-native');`

Marking this as closed.

**Comment by simonghales** [comment]
I thought it had fixed the issue, but I'm still getting the errors.

**Comment by dryganets** [comment]
@simonghales apologize for the inconvenience, I fixed the samples recently.

Make sure that you run npm install once you update your code.
Ping me if you still have issues.
