### ISSUE TITLE
RX.Image issue (where source is only known at runtime)

### ISSUE THREAD

**Issue by MartinOrtiz** [Microsoft/reactxp#573]
Is there no way to do below? 

<RX.Image
style={styles.image}
//source={require("./images/rg1.png")}    <--- works in Android emulator 
//source={require("./images/" + x.RaygunPicURL)} <--- does not work in Android emulator 
source={"./images/" + x.RaygunPicURL}         <--- does not work in Android emulator (but works in web)
resizeMode={"cover"}
/>

**Comment by erictraut** [comment]
See this [blog article](https://microsoft.github.io/reactxp/blog/2017/06/29/asset-loading.html).

**Comment by erictraut** [comment]
Ah, I misunderstood. You want to dynamically generate a path for an asset. No, that won't work in React Native. RN's asset loading mechanism uses build-time resolution, so the path needs to be a string literal, not an expression that's evaluated at runtime.

Out of curiosity, why do you want to use a runtime-evaluated path for one of your packaged assets?

**Comment by MartinOrtiz** [comment]
How would you do a list? I have a list of images for a catalog demo app. I want to generate it at runtime.

**Comment by erictraut** [comment]
For a catalog app, you probably don't want the images of the items in the catalog to be hard-coded and packaged in the app, right? You'd want them to be dynamically fetched from a network source. You can dynamically generate URLs at runtime and use them as a "source" for images. The limitation that I mention above applies only to packaged assets.

If you do want to package the images of the items in the catalog, you'll need to provide a require() statement and a static path for each one of them.

**Comment by MartinOrtiz** [comment]
ok, thans for info/help
