### ISSUE TITLE
TextInput does not provide onCut event

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#574]
Hi,

I just found that `TextInput` does not implement `onCut`. Is there any particular reason for that?

I made a little effort and prepped a PR to add the support for web platform. This is something I can easily test here right now, but I need help to complete the task list for the rest of platforms.

Checklist:

- [X] Web platform support (see https://github.com/Microsoft/reactxp/pull/575)
- [ ] Mobile support
- [ ] Windows support
- [ ] MacOS support

Cheers,
Andrej

**Comment by erictraut** [comment]
There is no onCut support provided by React Native, so it doesn't make sense to expose it in ReactXP. From the perspective of a TextInput, there's no difference between the user pressing "delete" or "backspace" and a cut operation, so I don't know why your app would need an onCut callback. You can use onChangeText instead.

**Comment by pronebird** [comment]
Hi @erictraut,

Well that's pretty frustrating because at least iOS supports that, desktop supports that and whatnot.
 
I have a managed formatted input field so I don't listen to onChangeText and use keystrokes instead.
