### ISSUE TITLE
How to include custom icon font?

### ISSUE THREAD

**Issue by promosjotte** [Microsoft/reactxp#576]
Is there a way to use a custom icon font in reactxp? Found nothing in docs...

**Comment by erictraut** [comment]
Sure, you can use any font that's available or that you've packaged with your app. Packaging and registering fonts differs by platform and is something you need to do on the native side of a React Native application. Once it's registered, you can refer to it by its name in "fontFamily" attribute, which applies to Text, TextInput, and Link components.

**Comment by erictraut** [comment]
Here are some sites that discuss how to add a font to your React Native project:
https://blog.bam.tech/developper-news/add-a-custom-font-to-your-react-native-app
https://medium.com/@danielskripnik/how-to-add-and-remove-custom-fonts-in-react-native-b2830084b0e4

For the web version of your app, you can simply add a @font-face CSS attribute to the main page of your app. For details, see here:
https://insights.dice.com/2013/05/13/adding-custom-fonts-to-your-web-pages/

**Comment by promosjotte** [comment]
Thanks, it´s working now 👍 I struggled for a while with react-native-vector-icons due to a bug... 
For everyone with the same trouble there´s a workaround for now:

`rm ./node_modules/react-native/local-cli/core/__fixtures__/files/package.json`
brings it to work.
