### ISSUE TITLE
Navigation through the application using deep link urls

### ISSUE THREAD

**Issue by alexbom** [Microsoft/reactxp#579]
Good afternoon!
I'm trying to make that when I open a link (for example, localhost:8080/about) my web application runs and I navigate to the desired scene using the Navigator component.
How is it better to implement it? Alas, I did not find any examples of linking api: https://microsoft.github.io/reactxp/docs/apis/linking.html
I have more or less figured out the Navigator component, but I do not understand how the SPA application on ReactXP can intercept the navigation by links?

**Comment by erictraut** [comment]
I assume that you're talking about the initial URL that launches your web app — a deep link that allows the user to navigate to various parts of your app.

As part of your app's launch sequence, you should call RX.Linking.getInitialUrl(). This will return the URL used to launch the app. You can then parse the URL and convert it into a route. Depending on the navigation mechanism you're using, you can then convert this into a navigation context, which can then be used to render the appropriate scene. If you're using a "navigation stack", you'll need to build the stack of scenes that corresponds to the desired navigation context.

I wrote [a blog article](https://microsoft.github.io/reactxp/blog/2017/04/27/building-skype-on-reactxp.html) a while ago that describes how we do this in the Skype app. You may find it useful.

**Comment by alexbom** [comment]
Thanks, Eric!
Now everything is clear.
