### ISSUE TITLE
Dependencies outdated.

### ISSUE THREAD

**Issue by StevenTCramer** [Microsoft/reactxp#584]
run yarn outdated on hello world app. 

```
λ  yarn outdated
yarn outdated v1.5.1
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
Package                   Current Wanted Latest     Package Type    URL

@types/node               7.0.58  7.0.58 9.6.1      devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git
@types/webpack            2.2.16  2.2.16 4.1.3      devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git
awesome-typescript-loader 3.1.2   3.1.2  4.0.1      devDependencies https://github.com/s-panferov/awesome-typescript-loader
react                     16.2.0  16.2.0 16.3.0     dependencies    https://reactjs.org/

react-dom                 16.2.0  16.2.0 16.3.0     dependencies    https://reactjs.org/

react-native              0.53.3  0.53.3 0.54.4     dependencies    https://github.com/facebook/react-native#readme

react-native-windows      0.51.0  0.51.0 0.54.0     dependencies    https://github.com/ReactWindows/react-native-windows#readme
reactxp                   1.0.2   1.0.2  1.1.0-rc.2 dependencies    https://microsoft.github.io/reactxp/

source-map-loader         0.1.6   0.1.6  0.2.3      devDependencies https://github.com/webpack/source-map-loader#readme
ts-node                   3.3.0   3.3.0  5.0.1      devDependencies https://github.com/TypeStrong/ts-node

typescript                2.7.2   2.7.2  2.8.1      devDependencies http://typescriptlang.org/

webpack                   2.2.1   2.2.1  4.4.1      devDependencies https://github.com/webpack/webpack

Done in 2.17s.

```

**Comment by erictraut** [comment]
Just because there are newer versions of some packages doesn't mean that there's a problem with older versions. We periodically update the dependencies when there's a reason to do so. Remaining 100% up to date on all dependent packages is a non-goal.

**Comment by StevenTCramer** [comment]
I understand reaming 100% up to date may not be a goal.  But on the other hand people are working hard to update the other libraries and eventually upgrading will have a reason.  And the further you are behind the hard it is.

I think trying to keep up or at least logging that you recognize they exist and have a reason not to update is a better option.

If I were to start a reactXP app today then I couldn't even use the latest typescript?

I know it takes time but what is the down side of trying to keep up to date?

**Comment by erictraut** [comment]
Keeping dependencies completely up to date all the time would require checking on almost a daily basis, which isn't practical. But I agree that it's good to periodically update the dependencies. I've just updated all of the ReactXP sample apps. So at least for today, the dependencies all point to the latest available versions.
