### ISSUE TITLE
ReactXP Project generator + questions

### ISSUE THREAD

**Issue by dabit3** [Microsoft/reactxp#60]
I've been trying to create a ReactXP project generator similar to Create React App or the React Native CLI's `react-native init <Projectname>`

One stumbling block I've had so far is that the AppRegistry method is hard-coded in the ReactXP node module. [see this file](https://github.com/Microsoft/reactxp/blob/328a54affdd573aa99b348e5b60e65e3d4ba57a3/src/native-common/App.ts)

I was hoping someone from the team could give me some guidance / direction no only on this stumbling block but also if there are any features / requirements you would like to see in this generator.

I've registered it as `create-xp-app` with npm.

**Comment by erictraut** [comment]
Nice, thanks for doing this! Yeah, you're correct in that it assumes the registered app name is "RXApp". This is documented [here](https://microsoft.github.io/reactxp/docs/using-reactxp.html). Can your generator emit an [AppDelegate.m](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/ios/RXPHelloWorld/AppDelegate.m) for iOS and a [MainActivity.java](https://github.com/Microsoft/reactxp/blob/master/samples/hello-world/android/app/src/main/java/com/rxphelloworld/MainActivity.java) for Android?

We've talked in the past about removing this hard-coded name and instead requiring the name to be specified as part of ReactXP's initialization (in the App.initialize method). I'm open to that if there's a strong need to eliminate the hard-coded name.

**Comment by dabit3** [comment]
Yeah I think we can generate the AppDeleage.m & MainActivity.java. When we create the RN Project, I guess the idea would be to populate these as `RXApp` ?

I'm open to doing it whatever way you all think is best, and am not opinionated either way.

**Comment by erictraut** [comment]
Yeah, let's stick with a hard-coded "RXApp" for now. Your generator can include this string in the corresponding ".m" and ".java" files. Feel free to copy the corresponding files from the "hello world" app. Let us know if this turns out to be problematic for some reason.

**Comment by dabit3** [comment]
This is about ready, I'll update here on Sunday / Monday after I get it published!

**Comment by dabit3** [comment]
This is a very basic working version of what I have so far -> https://github.com/dabit3/create-xp-app 

I'll be working on this over the weekend to add some polish.

I will probably reach out after Microsoft Build to see how I can improve it.

**Comment by dabit3** [comment]
Published!
