### ISSUE TITLE
Implement events firing in sequence "keyDown, keyPress, keyUp" matching HTML standard. (was: Consolidate key events)

### ISSUE THREAD

**Issue by zholobov** [Microsoft/reactxp#602]
We need to consolidate key events. Currently there are keyDown and keyPress events dispatched for the same situation of a key pressed down by a user. It's not clear if application code should expect both of them fired or only one of them and which one, especially when processing them bubbled-up on higher levels of view hierarchy.

**Comment by erictraut** [comment]
The "onKeyPress", "onKeyUp" and "onKeyDown" events are pretty standard for most UI frameworks. They are part of the HTML standard. We could do a better job documenting them, perhaps, but I don't think there's a need to consolidate them. The behavior should match that of the HTML standard.

https://www.w3schools.com/jsref/event_onkeydown.asp

**Comment by zholobov** [comment]
Is it okay to repurpose this item for proper implementation of the "keyDown, keyPress, keyUp" sequence as specified in HTML?

**Comment by erictraut** [comment]
Sure, you can either reuse/rename it or close it and open a new one. Your choice.
