### ISSUE TITLE
ScrollView native justifyEnd

### ISSUE THREAD

**Issue by junseld** [Microsoft/reactxp#611]
I don't think there is an implementation for the `justifyEnd` prop on native (or at least I haven't seen it).

I think you can implement it in `common-native/ScrollView.tsx` with something like this (at least for me it works):
```
const internalProps = {
    ...
    contentContainerStyle: this.props.justifyEnd ? { flexGrow: 1, justifyContent: 'flex-end' } : {},
    ...
}
```
The problem is that the contentContainer then not always is the height of the actual content... no sure if that is really important though.

or is there a way to somehow pass that value as a workaround?
would like to hear your thoughts

Edit: ok with that change `onContentSizeChange` doesn't trigger until the content is bigger than the screen (actually kind of obvious) but for me that results in strange scroll behavior on iOS when showing/dismissing the keyboard and I need to be careful when to use `setScrollTop` :(

**Comment by erictraut** [comment]
In a scroll view, the contents define the height of the content container, and this should be completely independent of the size of the viewport (the visible portion of the scroll view). If the content container height happens to be smaller than the viewport height, the content container is positioned at the top of the view port, and there's no way to scroll it down.

Your proposal above attempts to make the content container size partly dependent on the viewport, which breaks existing assumptions about their independence.

Can you explain what you're trying to do? Are you trying to implement a view where the contents scroll from the bottom up, like in a chat app?

**Comment by junseld** [comment]
yeah I want to use it for something like a chat ;)
And your thoughts were exactly mine while I was having the problem with iOS... (it breaking the expected behavior)
The content container size with `flexGrow: 1` only depends on viewport while smaller than it (it can grow bigger).

- `justifyEnd`
yeah I was confused why you didn't have an implementation for it (and didn't mark it as web only). It now makes sense if it was an deprecated/unused prop.

do you have another way to do that without breaking that contentContainer behavior?

**Comment by erictraut** [comment]
I can think of two workarounds, but there are issues with each:
1. Add code that measures the height of the contents and the view port. This can be done through an onLayout callback. If the content height is smaller than the view port, render a placeholder view at the top.
2. For the chat view in the Skype client, we wrote our own custom virtualized chat canvas. It supports "infinite scrolling" (including on-demand loading of additional messages). To achieve this, the implementation needs to measure and position each item within the content region. It's very complicated and took us several tries to get it right.

I think there's a reasonable argument to be made for adding "justifyEnd" support, but we'd need to work through the following issues:
1. Should we generalize it to support top/bottom/center justification? If so, what should the prop be called? Perhaps "justifyContents"?
2. How does it interact with horizontal scroll views? Do we also need to generalize it for left/right/center? What about scroll views that support both horizontal and vertical.
3. Can we reliably and consistently implement this on all RN platforms? The trick of specifying "flexGrow: 1" for contentContainerStyle relies on undocumented behavior that could easily differ across platforms and RN implementation versions.

Until we work out these issues, I'm going to to ahead and remove the current "justifyEnd" prop so it doesn't create confusion for anyone else.
