### ISSUE TITLE
File Upload and Read

### ISSUE THREAD

**Issue by GolfredoPerezFernandez** [Microsoft/reactxp#625]
hi im trying to implement file upload and read this file.. i use react dropzone but gives erros on importing it, can u help me?

**Comment by erictraut** [comment]
React Upload is intended for use with React JS (web). It doesn't work with React Native. If you want to use it in a ReactXP app, you'll need to conditionally include it only for the web version. Do you need this functionality for your native versions as well? If so, you'll need to use a different approach.

**Comment by GolfredoPerezFernandez** [comment]
but now only web will be ok.. So i use react dropzone like this but does seem to work. 

here is my code:

import Dropzone from 'react-dropzone';


class FileUpload extends RX.Component<MenuHomeProps, null> {
     render() {
        return (
            <RX.View > 
                     
       <Dropzone onDrop={() => console.log("drop")}>
              <RX.View>Try dropping some files here, or click to select files to upload.</RX.View>
        </Dropzone>
  </RX.View > 
    )
  }

but gives me this error "Module not found: Error: Can't resolve 'react-dropzone' ". and i did yarn add react-dropzone

**Comment by GolfredoPerezFernandez** [comment]
Thanks you right :)
