### ISSUE TITLE
The tslint config doesn't support 'myField!: FieldType;', so running 'npm run build' breaks the code.

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#629]
There are 17 files currently which use this pattern:

```typescript
class MyClass {
  notInitializedAtCtorTimeField!: FieldType;
}
```

Running `npm run build` will run the linter with `--fix` and change the above to:

```typescript
class MyClass {
  notInitializedAtCtorTimeField!; : FieldType;
}
```

Which isn't valid.

**Comment by erictraut** [comment]
I'm not able to repro this problem. I assume you're talking about the main reactxp build, as opposed to extensions or samples? Are you sure you've run "npm i" to download the latest components?

**Comment by Fitzpasd** [comment]
I did not have the latest lint dependencies installed :(
