### ISSUE TITLE
Feature Request: autoreload for web-watch

### ISSUE THREAD

**Issue by kokizzu** [Microsoft/reactxp#63]
No autoreload for `web-watch` command on browser, just like Android and iOS version.

**Comment by ricklove** [comment]
I am using BrowserSync webpack plugin for this. It works well.

Here is an example config which is added to the plugins array in webpack:

```
new BrowserSyncPlugin({
            host: 'localhost',
            port: 3000,
            server: {
                baseDir: __dirname + '/dist/'
            }
        })
```

Also, here are the `package.json` dev dependencies needed for it:

```
    "browser-sync": "^2.18.8",
    "browser-sync-webpack-plugin": "^1.1.4",
```

**Comment by ThomasLaforge** [comment]
Maybe to add on project ? Good job mate
