### ISSUE TITLE
reactxp and office-ui-fabric-react ?

### ISSUE THREAD

**Issue by pawelmod** [Microsoft/reactxp#639]
Hello, 
Is [reactxp](https://github.com/Microsoft/reactxp/issues/new) compatible with [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react#advanced-usage)?
In other words: do we have out-of-the-box Android and iOS views for mobile and "office look" for Windows / Web?

If not: could it be **future request** to have it compatible?

**Comment by erictraut** [comment]
No, Office UI Fabric is not built on top of ReactXP.

Both projects come from Microsoft, and we talked about unifying them internally, but we ultimately decided against it. 

The design requirements for Office UI Fabric and ReactXP were somewhat different. Office UI Fabric includes a bunch of high-level controls that directly map to high-level controls provided by each platform. For example, it provides a "toggle button" control that is implemented with a platform-specific toggle button control for each platform. This control looks different on the web vs Mac vs Windows. The design philosophy behind ReactXP was to provide only basic UI primitives without any notion of styling, which is useful in cases where you want to control the look and feel of your controls and make that consistent across platforms. For example, in Skype, we wanted to write our own toggle button control that had a distinctively "Skype" look whether it was running on web, Android, Mac, Windows, etc. 

It would be possible to write a Fabric-like library on top of ReactXP, but it would need to be a different implementation from the existing Office UI Fabric library.

**Comment by tomByrer** [comment]
> So at this moment I think that

Perhaps for you, but for my project I would rather write once for both mobile & web.  ReactXP's strength (same across all 3 platforms) is also its weakness; depends on one's needs.

BTW, you might want to look into [Expo](https://expo.io/) for mobile.
