### ISSUE TITLE
[Docs|Feature] Converting from SyncTask to Promise

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/reactxp#644]
It would be nice to have some documentation in the README that explains how to safely convert a SyncTask back to an ES6 Promise. If there is a .toPromise() method on the SyncTask that just does this magically, that would be even better.

This is useful for consumers of ReactXP who want to consume its APIs (like Storage) but don't want to use SyncTasks.

**Comment by erictraut** [comment]
There's an easy way to convert _from_ an es6 promise to a SyncTasks promise — the static ```fromThenable``` method. But I don't think there's a method in SyncTasks to go in the other direction. It hasn't come up previously because we tend to prefer SyncTasks to ES6 promises. @deregtd, any thoughts here?

**Comment by luisnaranjo733** [comment]
I opened a [sibling issue](https://github.com/Microsoft/SyncTasks/issues/16#issuecomment-391876057) on the SyncTasks project as well that has gotten some attention.

Sounds like a asEsPromise() method will be added to the SyncTasks.Promise class soon.
Would probably be a nice thing to mention in the ReactXP docs for APIs that return a SyncTask, so others in the future can do this nicely

**Comment by luisnaranjo733** [comment]
This has been commited to SyncTasks. This [issue](https://github.com/Microsoft/SyncTasks/issues/20) tracks the publication of synctasks on npmjs.com

**Comment by luisnaranjo733** [comment]
The latest release of SyncTasks has the ability to convert back to a promise now. Thanks!
