### ISSUE TITLE
ReactXP docs update?

### ISSUE THREAD

**Issue by zetekla** [Microsoft/reactxp#646]
Currently, documentation for ReactXP is not sufficient and requires a lot of guessing to get things to work. ReactXP is incompatible with some of the community libraries: react-navigator...

**Comment by erictraut** [comment]
We try to provide clear and comprehensive documentation and sample code. If there is something specific that you think is missing, please let us know. For example, what aspects did you find required guesswork to get started?

Also, can you provide more details about the incompatibilities you’ve encountered?

**Comment by erictraut** [comment]
Closing because there's not enough information provided.
