### ISSUE TITLE
Strip out dependencies based on target

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#647]
Hi,

Since ReactXP combines together many worlds to bring seamless development experience for desktop and mobile at the same time, I feel like it would be appropriate to ask this question here. 

React-native is quite heavy weight sumo fighter and I'd like to strip it out from web builds, along with `react-native-windows` which I don't even use directly.

Are there any procedures in place that enable this or is it up to me how to do this? 

I wonder because if `react-native` is never referenced in `web` version then maybe I can `rm -rf` it in my build/dist script? Would that break `react-xp` when shipping for each platform individually?

Value your feedback,
Thank you!

**Comment by erictraut** [comment]
If you're using a bundler like webpack to build your app, this should be done automatically for you. Only the files that your app depends upon (e.g. the web modules of ReactXP and their dependencies) will be included in the final bundle. No need to manually delete anything.

**Comment by pronebird** [comment]
I use babel CLI and electron-builder only. Is there a list of files to include for web or how does it know?

**Comment by erictraut** [comment]
Bundlers follow the require statements to build the full dependency graph. Only the referenced files are included in the final bundle.

**Comment by pronebird** [comment]
That may be the case with web dependencies, but given that I run ReactXP in Electron, there is no way webpack does any bundling for native dependencies.

Maybe I should split the app on a few packages, this way I could manage which dependencies are used based on build target.

**Comment by erictraut** [comment]
When you say "native dependencies", are you talking about Electron plugins that involve native code? It's true that webpack won't handle those dependencies for you, but it should take care of all the JavaScript module dependencies. Since ReactXP is all JavaScript, webpack should include only the parts of ReactXP that are needed for the web implementation and strip out the RN implementation files.

**Comment by pronebird** [comment]
@erictraut exactly, the C++ modules for Node.js. Although Webpack didn't work for me, for some reason it follows `devDependencies` and eventually breaks. I raised an issue with them.

**Comment by erictraut** [comment]
Sounds like you're confusing two types of dependencies. Package-level dependencies are specified in package.json (in the dependencies and devDependencies section). This tells npm which packages to install. Webpack deals with file-level dependencies. It uses require/import statements to determine which files to include in the final bundle. It doesn't pay any attention to devDependencies.

As for C++ modules, that's an entirely different issue that has nothing to do with webpack or ReactXP. Generally you'll need to manage your dependencies on C++ modules manually in a make file, project file, or however else you're building these modules.

**Comment by pronebird** [comment]
Right! I think I misinterpreted the error coming from one of webpack plugins. 

In any case: when following the source tree, webpack will eventually stumble upon a require call of a binary blob (compiled native module). So then this has to be handled separately, i.e by copying such module somewhere into build folder along with a webpack bundle. I think it gets even more complex when using `node-pre-gyp` or `bindings` since they do a dynamic resolution and `require` expression.

That makes me think that the main use case of webpack in such context would be to merge relevant code into one blob and then copy `node_modules/` along, which brings me back to my original issue. 😃 

The issue is that I have `react-native` and `react-dom` as dependencies in `package.json`. Since NPM does not support targets there is no way to distinguish which dependencies should be used for bundling for desktop (`electron`) or mobile (`react-native`).

So I either have to split the app somehow on two packages or sort out dependencies at the packaging stage.

Thanks for brainstorming with me!
