### ISSUE TITLE
ReactXP Types.d.ts not up to date with types definition for React v15.0

### ISSUE THREAD

**Issue by josh0707** [Microsoft/reactxp#66]
Hello,

Thank you for open sourcing your library.

When using types definition for React v15.0 with ReactXP 0.42.0-rc.2 I get errors such has:
`reactxp/dist/common/Types.d.ts(207,54): error TS2314: Generic type 'HTMLAttributes<T>' requires 1 type argument(s).`

If I change reactxp/dist/common/Types.d.ts(207) from:
`export interface AccessibilityHtmlAttributes<T> extends React.HTMLAttributes {`
to:
`export interface AccessibilityHtmlAttributes<T> extends React.HTMLAttributes<T> {`
The error disappears.

It might be worth updating ReactXP types definition to reflect changes made in React types definition, such as:
`interface HTMLAttributes extends HTMLAttributesBase<HTMLComponent> {}`
changed to:
 `HTMLAttributes<T> extends DOMAttributes<T> { ... }`
Especially for those of us who want to access platform specific components provided by React Native.

Thanks,

Josh

**Comment by erictraut** [comment]
Fixed.
