### ISSUE TITLE
TextInput onBlur does not pass Event anymore

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#662]
Hi,

#498 and #594 break one of my components that relied on event data coming from `blur` event.

**Comment by erictraut** [comment]
What field(s) were you relying on in the event? RN doesn't appear to pass an event to onBlur for TextInput.

**Comment by pronebird** [comment]
The argument which is `FocusEvent` was always passed for blur events, but not anymore. 

I am not an expert in React-native but it seems that in fact they pass the event (based on their code)

https://github.com/facebook/react-native/blob/master/Libraries/Components/TextInput/TextInput.js#L1185

**Comment by erictraut** [comment]
@Fitzpasd, thoughts? 

I'm basing my assumption on the public react-native.d.ts interface, but that has been known to have bugs. I haven't looked at all the RN implementations to validate that a FocusEvent is passed in all cases.

**Comment by Fitzpasd** [comment]
I think this was a mix of me putting too much faith in the RN typings, and not testing the condition for this event well enough.  I've opened PR #664 to fix, and also opened a PR in the DefinitelyTyped repo to get the event added to their types.

Thanks @pronebird!

**Comment by pronebird** [comment]
Upgraded and briefly looked at the app. Everything seems to be working.
