### ISSUE TITLE
[Deprecated API] The native Network implementation uses a deprecated RN API

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/reactxp#667]
The [native network api](https://github.com/Microsoft/reactxp/blob/master/src/native-common/Network.ts#L22) uses RN's NetInfo module under the hood in a deprecated manner.

The "change" event is deprecated in favor of the "connectionChange" event. Also the NetInfo.getConnectionInfo() method is deprecated. The current xp flow uses both (you subscribe to change events, and then call getInfo on change if you want more details than a boolean)

> "change: This event is deprecated. Listen to connectionChange instead. Fires when the network status changes. The argument to the event handler is one of the deprecated connectivity types listed above." - from the [NetInfo docs](https://facebook.github.io/react-native/docs/netinfo.html)

I think the XP API should change to simply exposing the connectionChange event and ideally mapping it to a simpler type (like the one in place today, which is nice).

**Comment by nateabele** [comment]
See also #660.

**Comment by erictraut** [comment]
Do you happen to know which version of RN introduced the connectionChange event? ReactXP is meant to be used across a range of RN versions, so we generally don't want to depend on relatively new features. We sometimes add conditional code such that it continues to work across versions.

**Comment by luisnaranjo733** [comment]
Here's what I've found:

- [This](https://github.com/facebook/react-native/commits/master/Libraries/Network/NetInfo.js) is the commit history for the NetInfo.js file in the public rn repo
- There were 3 commits between July 24, 2017 and October 13, 2017 that reference or iterate on the deprecation
- The first commit ([this one](https://github.com/facebook/react-native/commit/fc38fe1736080215e3c462e25081d530a5399dc3#diff-b2ca6dcd2e267af29287d03191b8810a) on July 24) looks like it was the real deprecation. It had motivation and details in the commit message. Looks like the change might have been made by a MS employee (Adam Comella) to close [this](https://github.com/facebook/react-native/pull/14618) issue..
- Looking at the release [versions](https://www.npmjs.com/package/react-native) of react-native on npmjs.com, my best guess is that this shipped ~10 months ago between versions 0.46.4-0.47

Hope that is helpful. Thank you for taking some time to look into this :)

**Comment by luisnaranjo733** [comment]
sweet. thanks!
