### ISSUE TITLE
Instructions for building on Windows

### ISSUE THREAD

**Issue by radamanthus** [Microsoft/reactxp#67]
RXPHelloWorld contains only instructions for building on iOS, Android and Web. I thought the point of the library is to be able to target web, iOS, Android _and_ Windows. Where are the examples for building on Windows?

https://github.com/Microsoft/reactxp/tree/master/samples/hello-world

**Comment by erictraut** [comment]
As mentioned in the [FAQ](https://microsoft.github.io/reactxp/docs/faq.html), Windows support is a work in progress. Check back later -- or feel free to contribute.
