### ISSUE TITLE
Event for open/close of virtual keyboard on mobile web?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#671]
Is there any way to detect when a virtual keyboard is opened/closed on mobile web using ReactXP? This would apply to browsers on mobile, tablets, and any future devices where a virtual keyboard would appear on the screen when an input field is focused and disappear when blurred.

I thought of using an agent detector for mobile devices and tablets, but there may be additional devices (current or future ones) that may display a virtual keyboard that may not be detected by the regex.

Any idea how to detect the virtual keyboard open/close event with ReactXP?

**Comment by erictraut** [comment]
I don't think this belongs in ReactXP. This should be transparent to the app, in general. If your app needs access to this information, you can write your own app-specific logic.
