### ISSUE TITLE
User preferred language

### ISSUE THREAD

**Issue by pimuzzo** [Microsoft/reactxp#673]
What is the best approach to guess the user's preferred language using ReactXP?
The best thing would be to have it included here [international](https://microsoft.github.io/reactxp/docs/apis/international.html)

**Comment by erictraut** [comment]
We've talked about providing an abstraction for locales / languages. So far, it hasn't been a high enough priority. In the Skype app, we use a custom reactxp extension that gathers a bunch of additional device and environment information that is probably not of interest to most apps. So we'd need to refactor it significantly or implement it differently to provide a solution as part of the reactxp core.

I think that most developers simply use i18n. There's a native module [react-native-i18n](https://github.com/AlexanderZaytsev/react-native-i18n) that even handles dynamic language changes.

**Comment by pimuzzo** [comment]
@erictraut thank you for the hint, I think we can close this issue :tada:

**Comment by pimuzzo** [comment]
Sorry for "self-promotion", thanks to the advice of @erictraut I managed to reach my goal: https://github.com/pimuzzo/rx-i18n
at the moment I'm using it in development and everything seems to work
