### ISSUE TITLE
scrollview snapToInternal support for android?

### ISSUE THREAD

**Issue by yuzha** [Microsoft/reactxp#676]
Currently snapToInternal is marked as iOS only in the doc. Seems like react native has added fix for this, it would be great if this can be integrated in reactxp.
https://github.com/facebook/react-native/commit/b2848a54b05470b3e258c935dd33b8c11a31b3c3

**Comment by erictraut** [comment]
ReactXP implements this in a component that's common to both iOS and Android, so it should just work as soon as you upgrade to the latest RN for Android. I'll update the documentation to reflect the fact that it's no longer iOS-specific.

**Comment by yuzha** [comment]
Do you know when reactxp might upgrade to latest RN? Not sure if some components might ran into issue migrating as is? Also upgrade would probably result in lots of errors in the tsc command which we want to avoid if possible.

**Comment by erictraut** [comment]
Reactxp isn't bound to any particular version of RN. We try to make it compatible with all versions of RN that have been released in the past year — and all upcoming versions. You can decide which version of RN you want to include in your app. 

The tsc command shouldn't be an issue if your app's code is being built against the reactxp interface. If you're directly importing react-native in some parts of your app code (in which case it won't run on the web), an upgrade of RN and its type definition package (@types/react-native) may necessitate changes in your code.
