### ISSUE TITLE
Samples update with UWP support?

### ISSUE THREAD

**Issue by manuelelucchi** [Microsoft/reactxp#682]
It would be cool to have UWP included in the samples

Regards,
Manuele

**Comment by erictraut** [comment]
It is included in the RXPTest sample, but I agree it would be good to include it in the other samples as well.

**Comment by manuelelucchi** [comment]
Oh thanks i didn't noticed. Would be cool also to have something like react-create-app that creates an empty template with all the platforms already set

**Comment by erictraut** [comment]
Nader Dabit created [this tool](https://github.com/react-native-training/create-xp-app). I haven't tried it yet. If you try it out, I'd be interested in hearing how it works for you.

**Comment by manuelelucchi** [comment]
just tested and it's really easy to use but lacks of UWP support :/ I opened an issue but i don't think it's still developed :/

imho you should include it to the main repo, it would help a lot of devs to getting started with React XP instead of vanilla React Native. Also, but this is a bit more complicated :D it would be awesome to have the React XP docs in docs.microsoft.com

**Comment by erictraut** [comment]
The documents included in docs.microsoft.com are associated with Microsoft products with dedicated development and support teams. ReactXP is an open-source project that is maintained primarily by Microsoft employees. Our approach to documentation is similar to that of TypeScript and VS Code, where the docs live with the open-source code repository.

If you're interested in developing a tool like reactxp-create-app, we'd welcome the contribution.

**Comment by Licantrop0** [comment]
@deregtd were you working on updating the reactxp-create-app? (as you know, I'm interested in this too!)

**Comment by deregtd** [comment]
I started playing with the create-xp-app tool, but it's very out of date at this point.  The latest TodoList sample inside the reactxp codebase is the best cross-platform sample available right now.  It may be worth it for someone to take that sample and backport that into the create-xp-app infrastructure and release a new/forked version of it (depending on whether Nader still exists and cares).

As for UWP specifically, I haven't tried adding UWP support to that sample app.  Once I get a new app working with UWP support, it should be easy to back-port it into the sample app, though.

**Comment by erictraut** [comment]
@deregtd, any update on this one?

**Comment by a-tarasyuk** [comment]
@erictraut I've created prototype of [reactxp-cli](https://github.com/a-tarasyuk/reactxp-cli), maybe it will be useful for someone.

**Comment by a-tarasyuk** [comment]
There is also [**create-rx-app**](https://www.npmjs.com/package/create-rx-app), which aims to simplify start a new project on ReactXP.

**Comment by erictraut** [comment]
@a-tarasyuk - Thanks, this looks great. I'll update the ReactXP docs to point to it.

**Comment by a-tarasyuk** [comment]
@erictraut I think this issue can be marked as resolved because all samples include `windows` support. What do you think?

**Comment by erictraut** [comment]
Yep, I agree. Thanks.
