### ISSUE TITLE
Animated.Value.addListener is broken on RN

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#683]
RXP has this type def for a value listener:
```typescript
export interface ValueListener {
    setValue(valueObject: Value, newValue: number | string): void;
    startTransition(valueObject: Value, from: number|string, toValue: number|string, duration: number,
        easing: string, delay: number, onEnd: Types.Animated.EndCallback): void;
    stopTransition(valueObject: Value): number|string|undefined;
}
```

But the definition of the RN value listener is:
```typescript
type ValueListenerCallback = (state: { value: number }) => void;
```

The framework makes no effort to interop between these incompatible definitions, and therefore just crashes when the listener is invoked on RN.

Not sure how this ever worked, maybe RN changed their listeners to be simpler?  

Proposed fix:  Align to RN's API.  I can't imagine this is being used widely since it doesn't work, so the breaking change shouldn't affect people?  Alternatively, document that the `startTransition` and `stopTransition` methods only apply to Web and then interop the `setValue` call.  (Disclaimer:  I've only just started looking at the Animated API so maybe there's a hole in my knowledge that means this issue is incorrect) 

I can work on a fix when we align on the best approach.

**Comment by erictraut** [comment]
ValueListener is not documented as part of the public interface for ReactXP, and it was never meant to be part of it. Callers should never directly manipulate the ValueListener. They should use the Animated start/stop/setValue methods.

**Comment by Fitzpasd** [comment]
Should it be removed from the public API then?  I would typically expect anything that's exposed to be supported, and not check the documentation to see if it is.  

But I do think it's worth exposing a ValueListener that works cross-platform that people can use to just listen for value changes, identical to the RN implementation.  It doesn't expose any manipulation functionality, only the listener callback.

**Comment by erictraut** [comment]
Yes, it should probably be removed from the public interface. I didn't realize it was exported. I'll work on it. I don't think we can guarantee the same semantics for the ValueListener on web because we use CSS to implement it.

**Comment by Fitzpasd** [comment]
Thanks!

I don't know a lot about CSS animations, but from the code in `web/Animated.tsx` it does look like we should be able to expose a value listener for all platforms.  The `Value.setValue` method already notifies private listeners, or is that something different?

**Comment by erictraut** [comment]
I removed this method from the public interface. It's not intended to be exposed.
