### ISSUE TITLE
Example missing: How can ImageSvg load from external source?

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#686]
[The docs](https://microsoft.github.io/reactxp/docs/extensions/imagesvg.html) say, that there should be a way to show an external SVG file:

`This component displays a vector image (SVG format), which can come from *a local source or from the network*...`

Unfortunately I get no idea, how this should work, when looking at the docs. Even a glimpse [into the extension](https://github.com/Microsoft/reactxp/blob/master/extensions/imagesvg/src/typings/react-native-svg.d.ts) did not help me.

In any case, we should update the docs. If it works, tell me how. If not, don't promise.

Regards,
Sascha

**Comment by erictraut** [comment]
You are correct. The extension doesn't support external SVG files. This is a bug in the documentation. I've fixed it.

**Comment by shameister** [comment]
As I have found [an extension](https://github.com/vault-development/react-native-svg-uri) to react-native-svg, which seems to handle this properly... can we alter this ticket, to become a feature request?

**Comment by erictraut** [comment]
I'm reluctant to complicate the existing extension by adding a second native dependency. That will be a breaking change for everyone who has already taken a dependency on the existing extension because they'll all need to add the additional native files to their projects. 

As an alternative, would it be feasible to perform the network fetch within your own code (through an HXR GET request) and then use the fetched SVG data as input to the existing ImageSvg extension?

**Comment by shameister** [comment]
I can see, why you woudn't be happy, adding the next dependency. As my SVGs data is just a "normal SVG" and not prepared for ReactXP tags, I cannot see, how this would help me. Did I miss a thing?

**Comment by erictraut** [comment]
Yeah, if you want to render arbitrary SVGs with full support for all SVG primitives, this approach wouldn't work. If your SVGs are known to consist only of paths, you could parse out the paths and use the existing extension.

Another approach is to create a "reactxp-imagesvg-uri" extension that mirrors the functionality of react-native-svg-uri and provides a web implementation.

**Comment by shameister** [comment]
I think, for now I will change my SVG, but maybe later on, the approach of creating a "reactxp-imagesvg-uri" becomes as interesting for us, that we will provide it.
