### ISSUE TITLE
Docs: Example for importing the Network-API missing

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#687]
While trying to use the [Network-API](https://microsoft.github.io/reactxp/docs/apis/network) I am missing an example. Most important would be the line, whats the class to import.

I found [this class definition](https://github.com/Microsoft/reactxp/blob/master/src/web/Network.ts) and was able to implement my needed behavior using `RX.Network`. But the class definition found gave me the feeling I am supposed to use the more concrete implementation.

Or… am I on the wrong track?

**Comment by erictraut** [comment]
I just added a sample use case to the documentation.

Note that all of the APIs in ReactXP are used within the RXPTest sample app, so that's a good place to go if you want more detailed examples of how to use them.
