### ISSUE TITLE
Request: Getting Started Section in Documentation / README

### ISSUE THREAD

**Issue by damianesteban** [microsoft/reactxp#695]
ReactXP looks like an interesting solution and I would love to get started with it. I know there is a video tutorial but what would be great is a simple introduction similar to what is in the [TypeScript-React-Starter](https://github.com/Microsoft/TypeScript-React-Starter) repo. It would also help build up the ReactXP community.

**Comment by shameister** [comment]
Hey @damianesteban,

as I started one week ago without any knowledge about React and React Native, I see the point, that more documentation would be useful. I just started adding some docs, after I found out some parts, which was difficult for me to understand (like missing imports in sample code).

Your request is understandable, but to me it seems too generic. I think it would help, if you may write down the parts, that are blocking you, so these can be explained.

Sascha

**Comment by damianesteban** [comment]
@shameister I will gladly do so. Should have something up by the end of the weekend.

**Comment by erictraut** [comment]
@xogeny, thanks for the feedback. I don't recommend using ```create-xp-app``` because it's out of date and no longer maintained.

This CLI (and its brethren like ```create-react-native-app``` simply copies a sample project. I'm reluctant to create and publish a new project that does something so trivial. I have updated the "getting started" instructions based on your input to make the steps clearer. Hope that's useful.

**Comment by damianesteban** [comment]
Sorry that I never wrote up that guide - I will post a basic outline of what I think should be in a “Getting Started”.

**Comment by fbartho** [comment]
We have "Getting Started" docs here: https://microsoft.github.io/reactxp/docs/getting-started.html -- so I'm going to close this ticket!

**Comment by fbartho** [comment]
Rereading the thread, I'm going to keep this ticket closed as there were several discussions going on.

I'll put "Getting Started" as high on my list of Documentation Issues to work on soon.

**Comment by fbartho** [comment]
See that in #1232
