### ISSUE TITLE
Feature Request: Get multiple items of Storage-API simultaneously

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#699]
I like to request the feature of being able to get multiple items of the Storage-API simultaneously.

As the storage API returns `SyncTasks.Promise<string>`s, when using `getItem` (which I understand), it becomes complicated, if there is the need use multiple stored values.

There are two ways, I know to use, which I both do not really like. (maybe I missed a better way?)

1) Nest `getItem`-calls inside the Promises `done`-method.
-> This makes the time waiting for the values longer.

2) Store the values in a state, after receiving them and react, if all values are filled. 
-> This works, but spreads responsibility for the values througout the code.

My current case is storing credentials with host, email and password. I try to auto-login, in case all three fields have any value.

I suggest adding a method named `getItems(keys: string[]): SyncTasks.Promise<string>`
The promise should do it's callbacks just, when all values are fetched.

Looking forward to discuss, what would be the best solution and if it should be part of the public API and if it should be inside the `Storage` class.

**Comment by erictraut** [comment]
The Storage API is intended to be used for very simple state. If your needs are more sophisticated, you should use a real database like [this](https://microsoft.github.io/reactxp/docs/extensions/database.html).

**Comment by shameister** [comment]
I'll add a hint do Database on the Storage APIs page.

**Comment by deregtd** [comment]
The storage API also just reflects what the underlying layer provides.  A top level getItems API somewhat suggests that it's more optimized than multiple getItem calls, but literally all that it can do is return SyncTasks.all(_.map(keys, key => this.getItem(key))), so you're better off just building a helper yourself with that one-liner if it's helpful.

**Comment by erictraut** [comment]
If your storage needs are limited to just three pieces of data (host, email and password), then RX.Storage is probably still the best option. You can use the line that David posted above to fetch them all in parallel. The SyncTasks.all returns a promise that is resolved only when all of the sub-promises have been resolved. So it's effectively what you're asking for above.

If you expect to store more data as you add functionality to your app, a DB is probably the better solution.
