### ISSUE TITLE
Comparison with React Native?

### ISSUE THREAD

**Issue by rohmanhm** [Microsoft/reactxp#7]
It will be nice if you add some additional info about the differences between React Native.

**Comment by jthegedus** [comment]
A Venn diagram of ReactXP, React-Native and React would be ideal.

**Comment by ColCh** [comment]
Or just with React...

**Comment by dachibox** [comment]
And not to forget with Xamarin

**Comment by erictraut** [comment]
I've added a FAQ to address these questions: https://microsoft.github.io/reactxp/docs/faq
