### ISSUE TITLE
discrepancy between releases description on the website vs the releases in github

### ISSUE THREAD

**Issue by spointeau** [Microsoft/reactxp#703]
There is a discrepancy between what I can read on the web site, listing all releases up to Version 1.3.0-rc.3 (16 Jun 2018), and the releases in github, stopped at 0.42.0-rc.25 which can be interpreted as the project has no release since August 2017.

**Comment by erictraut** [comment]
I'm not sure what you mean by "releases in github". 

The version history on the web indicates which versions have been published to npm.

**Comment by spointeau** [comment]
I meant in the github repository -> Code -> Releases

![image](https://user-images.githubusercontent.com/11181886/41548520-82c916cc-7323-11e8-850b-4f7dec9bc9f0.png)

**Comment by erictraut** [comment]
For consistency, I'm going to continue to use [this page](https://microsoft.github.io/reactxp/versions/version_history.html) to report version updates.

**Comment by Joeao** [comment]
Some projects just state that an update has been released in the Github Releases tab rather than duplicating a changelog.
I personally find it useful when discovering a repo to see that the project is alive.
