### ISSUE TITLE
There are multiple modules with names that only differ in casing

### ISSUE THREAD

**Issue by alexbom** [Microsoft/reactxp#709]
Hi there!
After updating ReactXP version in my project, some warnings starts to come:

> client?cd17:153 ./node_modules/ReactXP/dist/common/Accessibility.js
> There are multiple modules with names that only differ in casing.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Use equal casing.

Can't understand the problem & how to fix it. Please, help!

**Comment by erictraut** [comment]
Does it provide any more details - like the name of the file that is being referenced? I've looked at the source file, and I don't see anything wrong with it.

Is it possible that you've taken a dependency on some other package that pulled in an npm module called "subscribableevent" or some variant that uses different capitalization? Perhaps check your node_modules directory to see if there are two such "subscribableevent" directories.

**Comment by alexbom** [comment]
Thanks, Eric!
I've found next import in one of my components:
`import RX = require('ReactXP');`
I think it was pasted automatically by IDE, because it's not my job :)
