### ISSUE TITLE
Feature Idea: aspectRatio style-support 

### ISSUE THREAD

**Issue by fbartho** [Microsoft/reactxp#715]
The React-Native Layout Engine supports aspectRatio for layouts.

>### aspectRatio
>
>Aspect ratio control the size of the undefined dimension of a node. Aspect ratio is a non-standard property only available in react native and not CSS.
>* On a node with a set width/height aspect ratio control the size of the unset dimension
>* On a node with a set flex basis aspect ratio controls the size of the node in the cross axis if unset
>* On a node with a measure function aspect ratio works as though the measure function measures the flex basis
>* On a node with flex grow/shrink aspect ratio controls the size of the node in the cross axis if unset
>* Aspect ratio takes min/max dimensions into account

From: https://facebook.github.io/react-native/docs/layout-props.html#aspectratio

It'd be awesome if we could use this feature nonetheless with ReactXP -- especially for RX.Image

**Comment by erictraut** [comment]
Because this isn't available on CSS, there's no good way to support it for the web platform. That greatly limits its utility for cross-platform code. Because of this, I don't think it makes sense to add to the RX interface.

**Comment by fbartho** [comment]
Bummer. I assume we wouldn't want to add it in the form of a [`calc()`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc) expression if the user gives a constrained dimension and an unconstrained dimension?

**Comment by erictraut** [comment]
I generally don't recommend this approach. Initial layout almost always completes before any of the images are downloaded or decoded. The only exception is if it's a very small image that happens to be in the cache. If your layout depends on the dimensions of an image, the layout is likely to change after the image loads. The result looks sloppy, and it can be disorienting to users to have items shift around.

**Comment by fbartho** [comment]
That’s actually a problem I’m trying to solve here. My image currently drops in and flickers. I wanted to constrain the aspect ratio so that it doesn’t do that.

**Comment by fbartho** [comment]
I know the dimensions of the image, but I support many screen sizes, so I want to constrain the aspect ratio within the layout.

**Comment by erictraut** [comment]
I don't understand the problem them. If you know the dimensions, you can specify either the desired height or the width and use resizeMode: 'contain' to have the image constrained to the available height or width.

**Comment by fbartho** [comment]
I was hoping to let flex & padding + margins & borders + aspectRatio express our layout’s intention, without needing to calculate all of that in inverse to hardcode the image dimensions.

Maybe I’m fundamentally thinking about layout in the wrong way though.

Given that I want to support dynamic layouts, on many screen sizes, with safe area views, dynamic status bar and keyboard heights, but I can’t distort these images, what should I be doing so that I don’t need to use aspect ratio? Is there any way to do this without precalculating things up front?

**Comment by erictraut** [comment]
OK, I can see why aspectRatio would be useful in your case. My recommendation is to write your own ImageWithAspectRatio (or whatever you want to call it). You can perform the aspect ratio math in this component. That way, it won't be necessary to scatter it throughout other parts of your code.
