### ISSUE TITLE
Pass data attributes to HTML components

### ISSUE THREAD

**Issue by robeeeert** [Microsoft/reactxp#719]
Hi, we are currently transforming our components to use the RX views as base components, but we found that RX.View does not support data attributes. We need them for our GUI tests to identify specific elements in the app. Are there any plans to support them in the near future?

**Comment by erictraut** [comment]
No, there are no plans to support data elements. That's a very web-specific concept, not something that would make sense in a cross-platform library. There's an [active discussion](https://github.com/Microsoft/reactxp/issues/563) about exposing some form of ID that test frameworks could use. On native platforms, it would use the ```testID``` prop, and on the web, it would translate to the ```id``` attribute. Would that address your requirements?

**Comment by robeeeert** [comment]
Thanks for the quick reply! Yes that would probably address the issue.
