### ISSUE TITLE
reactxp-imagesvg not in NPM

### ISSUE THREAD

**Issue by lfps** [Microsoft/reactxp#72]
There is `reactxp-virtuallistview`, but no `reactxp-imagesvg` extension published in NPM.

**Comment by erictraut** [comment]
Yes, it's on my to-do list. :)

**Comment by whonow** [comment]
I love 2000 e mails a week from this site

**Comment by whonow** [comment]
I've tried it all and it won't stop

**Comment by erictraut** [comment]
@whonow, you should be able to "Unwatch" the project if you don't want to receive emails.

**Comment by erictraut** [comment]
@lfps, I just published reactxp-imagesvg. Let me know if you run into any problems with it.

**Comment by lfps** [comment]
@erictraut, thanks. Before you published this to npm with some fixes, I think I ran into a problem with how Component is imported from `react-native@0.42.3` (rather than from react) in Path.js of `react-native-art-svg@1.1.0`. Didn't spend much time with it then, but I'll create a new issue if the problem wasn't local to my setup and still exists.

**Comment by mghazanfar** [comment]
Property 'ImageSvg' does not exist on type 'typeof ReactXP' is the error I get when I use:
<RX.ImageSvg height={ 20 } width={ 20 } style={ styles.container }>
                <RX.SvgPath fillColor={ 'orange' } d={ 'M 0 0 h 20 v 20 z' } />
</RX.ImageSvg>
Please help me with this error.

**Comment by erictraut** [comment]
ImageSvg is a ReactXP extension. It needs to be imported separately. Please refer to the [Hello World sample](https://github.com/Microsoft/reactxp/tree/master/samples/hello-world), which uses ImageSvg.
