### ISSUE TITLE
High vulnerabilities problem with npm

### ISSUE THREAD

**Issue by edd83** [Microsoft/reactxp#723]
There are some high vulnerabilities problems on npm install, in the samples. Tested hello-world, TodoList and ImageList.

Would love to use this library 😃 

`found 9 vulnerabilities (7 low, 1 moderate, 1 high)`

**Comment by erictraut** [comment]
Can you explain what you mean by "high vulnerabilities problem"?

**Comment by erictraut** [comment]
I ran [nsp](https://www.npmjs.com/package/nsp), and it didn't report any vulnerabilities. Which tool did you use to identify vulnerabilities?

**Comment by pronebird** [comment]
@erictraut that's looks like the output of NPM v6+

**Comment by pronebird** [comment]
@erictraut the NSP project is shutting down and `nsp` is deprecated.

**Comment by edd83** [comment]
Yeah it was a npm audit 😅Sorry for the delay.

Also npm install (after a pull few minutes ago) displayed it : 
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-windows@0.54.0 requires a peer of react-native@~0.54.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native@0.55.4 requires a peer of react@16.3.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

added 30 packages from 38 contributors, removed 232 packages, updated 88 packages, moved 1 package and audited 16118 packages in 26.77s
found 9 vulnerabilities (7 low, 1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

<img width="1440" alt="screen shot 2018-08-07 at 10 33 09" src="https://user-images.githubusercontent.com/6439429/43767936-1dd6e51e-9a2e-11e8-8d25-793c36de9bae.png">

Is it enough details? 🙂

**Comment by erictraut** [comment]
I ran npm audit on the latest reactxp repo, and it indicates 0 vulnerabilities.

**Comment by edd83** [comment]
If you take time to look at my screen, I am on the hello-world sample. 🙂Anyway I though it was a bit useful for beginner/learner.
