### ISSUE TITLE
Comparison with Appcelerator Titanium

### ISSUE THREAD

**Issue by niutech** [Microsoft/reactxp#725]
In the [FAQ](https://microsoft.github.io/reactxp/docs/faq.html) there is a comparison with React Native for Web, but how does ReactXP compare with [Appcelerator Titanium](https://www.appcelerator.com/Titanium/)? Both are open source and seem to reuse the same codebase for native and web apps. Titanium is much more mature, introduced back in 2008.

**Comment by erictraut** [comment]
I don't know anything about Appcelerator Titanium. Never heard of it before.

**Comment by niutech** [comment]
That's weird, because Titanium has been there for so many years and it was hugely popular before React Native/NativeScript appeared. According to [Wikipedia](https://en.wikipedia.org/wiki/Appcelerator_Titanium), _In February 2013, Business Insider estimated that 10% of all smartphones worldwide ran Titanium-built apps.[7] As of 2017, Titanium had amassed over 950,000 developer registrations._

I think you should add such a recognized framework to the comparison.

**Comment by erictraut** [comment]
We don't have any experience with Titanium, so we're not in a good position to make a comparison.
