### ISSUE TITLE
Image#resizeMode has unused value `auto`

### ISSUE THREAD

**Issue by a-tarasyuk** [Microsoft/reactxp#726]
**ReactXP** has `auto` value in [`resizeMode`](https://github.com/Microsoft/reactxp/blob/a14ef0cc6f8aa1620c231282f716555452d7b323/src/common/Types.ts#L524), which seems is unused - [`Web`](https://github.com/Microsoft/reactxp/blob/a14ef0cc6f8aa1620c231282f716555452d7b323/src/web/Image.tsx#L393), [`Native`](https://github.com/Microsoft/reactxp/blob/a14ef0cc6f8aa1620c231282f716555452d7b323/src/native-common/Image.tsx#L83)

```typescript
resizeMode?: 'stretch' | 'contain' | 'cover' | 'auto' | 'repeat';
                                                ^^^^^
```
I think this value can be removed, or am I wrong?

---

Also, [**RN.Image#resizeMode**](https://facebook.github.io/react-native/docs/image#resizemode) has `center` value, which ReactXP does not support.

> center: Center the image in the view along both dimensions. If the image is larger than the view, scale it down uniformly so that it is contained in the view.

_center_, _contain_

![center](https://user-images.githubusercontent.com/509265/41960358-36e25d1e-79f8-11e8-947d-448c6caa0283.png) ![contain](https://user-images.githubusercontent.com/509265/41960375-3fd31a30-79f8-11e8-9939-43b86479627f.png)

_cover_, _repeat_
![cover](https://user-images.githubusercontent.com/509265/41960583-d03c0de8-79f8-11e8-8d9e-b907c9f1b1d2.png) ![repeat](https://user-images.githubusercontent.com/509265/41960597-d93dfd98-79f8-11e8-9b40-546ce3e79e20.png)

_stretch_
![stretch](https://user-images.githubusercontent.com/509265/41960609-e13df12e-79f8-11e8-9b75-52403753a03d.png)

Does it make sense to support `center` in ReactXP?

**Comment by erictraut** [comment]
We shouldn't remove 'auto' because that would be a breaking change. On the web implementation, 'auto' causes the image to be centered without any stretching or repeating. When I initially implemented the RN, I don't think 'center' was an option. Now that it is, we can map 'auto' to 'center' on native.

**Comment by a-tarasyuk** [comment]
@erictraut

> On the web implementation, 'auto' causes the image to be centered without any stretching or repeating.

By default `Image` has `background-position: center center` and `background-size: contain`., Based on the current Web implementation `resizeMode={ 'auto' }` doesn't change `background-position`, `background-size`.

[`background-size: auto`](https://jsfiddle.net/b5g29naz/20/)
[`background-size: contain`](https://jsfiddle.net/b5g29naz/22/)

Maybe it is a bug, and missed `case` for `auto`

```typescript
case 'repeat':
case 'auto':
    resizeMode = 'auto';
    break;
```

```typescript
let resizeMode = 'contain';
switch (this.props.resizeMode) {
    case 'cover':
        resizeMode = 'cover';
        break;

    case 'stretch':
        resizeMode = '100% 100%';
        break;

   case 'repeat':
         resizeMode = 'auto';
         break;
}

combinedStyles['backgroundPosition'] = 'center center';
combinedStyles['backgroundSize'] = resizeMode;
combinedStyles['backgroundRepeat'] = this.props.resizeMode === 'repeat' ? 'repeat' : 'no-repeat';
```

```typescript
<Image resizeMode={ 'auto' } ... />
```

**Comment by erictraut** [comment]
Good point. Yeah, that's a bug. The intention was for 'auto' to imply that the image should be displayed at its native resolution centered in the container with no repeating.

**Comment by a-tarasyuk** [comment]
@erictraut ok, will fix it

**Comment by a-tarasyuk** [comment]
@erictraut I've investigated this issue, and found one difference between `RN.resizeMode=center` and `backgroundSize=auto. backgroundPosition=center center`. `RN.resizeMode=center` scales down image if it is smaller than original image size - [**RN Example**](https://snack.expo.io/H1P0t9PzQ), [**Web Example**](https://jsfiddle.net/b5g29naz/47/). 

`backgroundSize` does not provide such behavior _(need to check original image width and height and if it smaller than user set then use `cover` otherwise use `auto`)_.

There is [`object-fit`](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit), which provides the similar behavior like an RN, however, it applied only to `img` tag.

What do you think about this case?

**Comment by erictraut** [comment]
Sounds like we have two options:
1. Implement in the straightforward way and document the behavioral differences.
2. Jump through some hoops on either the RN or web side to provide the same behavior.

In this case, I'm leaning toward option 1 because it's an edge case, and option 2 potentially has some bad side effects for the more common (non-edge) cases.

**Comment by a-tarasyuk** [comment]
@erictraut thanks, will make PR for the first option.
