### ISSUE TITLE
[FeatureRequest] Support overriding the component that VirtualListView uses to render cells

### ISSUE THREAD

**Issue by Fitzpasd** [Microsoft/reactxp#728]
A similar API exists on react-natives [VirtualListView](https://facebook.github.io/react-native/docs/virtualizedlist#cellrenderercomponent).

A sample use-case for this is to use a View-like component on Android that doesn't get [clipped by its parent](https://github.com/entria/react-native-view-overflow#usage-with-flatlist)

**Comment by erictraut** [comment]
The VLV needs tight control over the cell component, so I'd prefer not to expose this generic override. There are other ways we can handling the clipping issue. Are there other use cases you have in mind?
