### ISSUE TITLE
"document is not defined" exception @ Electron

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#730]
Indirect import of anything that touches ReactXP started causing this error since the most recent release candidate `1.3.0-rc.6`:

<img width="532" alt="screenshot 2018-06-28 16 02 56" src="https://user-images.githubusercontent.com/704044/42039164-0aee63a6-7aed-11e8-8bfe-6f432ba66c2b.png">

My scenario is such as one JS file imports redux actions that use RX.Clipboard, but then at the same time the same file exports a few useful functions that I use from both Main and Renderer processes in Electron app.

I'll do better code separation of course, but this seems to be a regression in ReactXP, previously indirect imports wouldn't cause any harm.

PS: Not saying it has to be fixed, more of FYI in case if that was not intentional. Feel free to close the issue.

**Comment by erictraut** [comment]
I don't think this has anything to do with indirect imports. It's related to a reference to "document.documentElement" that I recently added. This works fine in the browser, but it's apparently not defined in Electron. I'll fix it.

**Comment by pronebird** [comment]
No wait, it works in Electron's `BrowserWindow` just like in any other browser, but apparently this line executes at some point if I import ReactXP in the main process which in Electron is not a browser process but rather node.js. I realize that ReactXP should not be included in non-browser environments.

**Comment by erictraut** [comment]
ReactXP should run OK in non-browser environments (e.g. unit test frameworks). I'll have a fix shortly.

**Comment by erictraut** [comment]
Fixed
