### ISSUE TITLE
Cannot disable TextInput

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#740]
Hi,

Just stumbled upon that issue today. Seems that `TextInput` does not propagate `disabled` field down to the underlying `input`. 

Can you reproduce this with 1.3.0 too?

<img width="501" alt="screenshot 2018-07-03 16 16 44" src="https://user-images.githubusercontent.com/704044/42225870-d9e03146-7edd-11e8-9380-804e797929f4.png">

**Comment by erictraut** [comment]
RX.TextInput doesn't support "disabled", but it does support "editable". If you pass editable={ false } as a prop, you should see it show up as disabled.

**Comment by pronebird** [comment]
My bad. Flow didn't catch that :/
