### ISSUE TITLE
Question about Pattern

### ISSUE THREAD

**Issue by jas99** [Microsoft/reactxp#742]
So lets say I wanna use react router for navigation in web app and react-navigation for native support.
Do I need to create and compile extension? or in the same project I have to create wrapper. Can I do platform specific components without wrapping?

**Comment by erictraut** [comment]
You need to apply some form of aliasing at build time so the appropriate module(s) are included in the bundle for each platform variant. If you unconditionally include react-navigation, for example, you'll pull in all of RN's JS files, and they'll fail to initialize. 

There are two ways you can perform this aliasing:
1. Write a separate ReactXP extension and leverage the built-in aliasing capabilities of RN packager and webpack to "bind" to the right version for each platform.
2. Use a more sophisticated build script in your app that applies the aliasing. An example of this technique is found in the [TodoList](https://github.com/Microsoft/reactxp/tree/master/samples/TodoList#platform-specific-code-modules) sample app.

**Comment by jas99** [comment]
So by built-in aliasing capabilities you mean use index.{platform}.tsx pattern; I guess I can create extension in same project and transpile the whole thing into respective builds, or do I need to transpile extensions first?

**Comment by erictraut** [comment]
Yeah, that's what I mean.

Yes, you should be able to create an extension within the same project.

The TodoList sample (option 2 above) implements a more sophisticated mechanism that searches for the best implementation for the current platform (e.g. "index.ios.tsx" => "index.native.tsx" => "index.tsx" or "index.web.tsx" => "index.tsx"). It also allows you to reference the module through an absolute path (e.g. "import Foo from 'module/foo'"). If you don't need that level of sophistication, then the built-in aliasing should work fine.

Webpack doesn't have any built-in aliasing rules. If you're using that for your web builds, you can name your module's web implementation "index.tsx" and webpack will pick it up.

**Comment by jas99** [comment]
Cool!!, at some point will try to turn my rn to rx 😄
