### ISSUE TITLE
Web Animation Issues and in-flexibility question

### ISSUE THREAD

**Issue by filipmares** [Microsoft/reactxp#750]
Hi,

I've been bringing over some of our RX animations we've had running on iOS/Android and noticing very strange behavior when running on web. Some examples below that seem unrelated to the limitations in the docs...

**Example 1:**
Scale + translate Y (using the limitation of same duration and easing) end up in wrong translate position. 
```
RX.Animated.parallel([
  RX.Animated.timing(animatedScaleValue, {
    toValue: 0.25,
    duration: 250,
    easing: RX.Animated.Easing.CubicBezier(someBezierValue)
  }),
  RX.Animated.timing(animatedTranslateYValue, {
    toValue: 0,
    duration: 250,
    easing: RX.Animated.Easing.CubicBezier(someBezierValue)
  }),
]);
```

**Example 2:**
A sequence of parallel animations (using the limitation of same duration and easing) only run the first set of timing functions. 
```
RX.Animated.sequence([
  RX.Animated.parallel(timingFunctions),
  RX.Animated.parallel(timingFunctions)
]);
```

**Example 3:**
TranslateY of component A jumps all over along the Y-axis and eventually ends up in the wrong position. When changing animatedTranslateYComponentA to a _'top'_ property things work as expected except for Example 1 issue. (using the limitation of same duration and easing)
```
RX.Animated.parallel([
  RX.Animated.timing(animatedTranslateYComponentA, {
    toValue: 60,
    duration: 250,
    easing: RX.Animated.Easing.CubicBezier(someBezierValue)
  }),
  RX.Animated.timing(animatedTranslateYComponentB, {
    toValue: 15,
    duration: 250,
    easing: RX.Animated.Easing.CubicBezier(someBezierValue)
  }),
  RX.Animated.timing(animatedScaleComponentB, {
    toValue: 0.25,
    duration: 250,
    easing: RX.Animated.Easing.CubicBezier(someBezierValue)
  })
]);
```

The limitations listed in the documentation really limit what can be done with animations, especially when compared to RN. We'd sacrifice a reasonable amount in terms of UX. I'm trying to find some workarounds in the meantime. 

@erictraut can you expand on the differences in animation APIs and reasoning behind the limitations?

Thanks.

**Comment by filipmares** [comment]
[Here is a gist](https://gist.github.com/filipmares/e2d345c1e9f4b6b2b5b16fb5e9acf968) with a variety of scenarios to help debug. You should be able to import it and select various scenarios from the dropdown. LMK if i can help further. 

Oddly I was only able to repro #1 (could have been the issue with the others) without some complex component nesting. Should be a good start. It looks like _scale_ affects _translate_ on the same element no matter what.

**Comment by erictraut** [comment]
@filipmares, I ran your sample code on both the web and iOS, and for all six animations, I'm seeing consistent behavior across both platforms. They're all working as I would expect. Am I missing something?

Perhaps you are not expecting the transforms to compose. Keep in mind that the "scale" transform affects the "translateX" transform, so the final translateX value will be 0.25x the value you've specified in the animation.

**Comment by filipmares** [comment]
Thanks for looking into this. 

You're right about the last part! This explains #1. I haven't been able to repro #2 and assume there was an error in my code. For #3, I'm going to need to clean up the code and generalize it as it's pretty app specific.
