### ISSUE TITLE
How to apply transform to image?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#754]
I tried to set a rotation on an image style like this:

```
rotated: RX.Styles.createImageStyle({
    borderRadius: 20,
    transform: {
      rotate: "90",
      // rotate: "deg(90)" tried this way too...
    }
  })
```

The `borderRadius` is picked up by that style, but the `transform` never applies the `rotate`. I didn't find any examples of the correct usage, just the docs which stated the type passed to `rotate` should be a string, which it is. 

Any idea what I'm doing wrong here?

**Comment by erictraut** [comment]
You should use the CSS syntax to specify the angle: "90deg".

This file in RXPTest shows how to apply a rotate transform and animate it:
https://github.com/Microsoft/reactxp/blob/master/samples/RXPTest/src/Tests/AnimationTest.tsx

**Comment by MovingGifts** [comment]
Got it, following that example syntax works, had to wrap it in brackets, thank you!
