### ISSUE TITLE
Popup prevent content getting cut off?

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#757]
I have an anchor for a popup and a popup, with `positionPriorities: ['bottom']`. I noticed when the popup is somewhere in the viewport, like the top, the full popup contents render under the anchor. However, if the anchor is towards the bottom of the viewport, the popup contents get cutoff, and you see a very small part of it, but cant see the full content.

I know I can set `positionPriorities: ['bottom', 'top']` and that would display popup under the anchor fully as long as there is sufficient space in the viewport beneath it. If there isn't and there is on top, it will use the top location and render the popup above the anchor.

What I am trying is to get the popup with a single position priority `positionPriorities: ['bottom']` to **always** display fully below the anchor, even when close to the bottom of the viewport. I tried so far adding a margin bottom to the parent container when the popup is shown, and hide it when not (and also tried right before it's shown as well), but it seems that it still cuts it the content as it is on the bottom of the viewport, even though now below the viewport there is a big extra margin, which is for sure enough space to display the full contents of the popup.

I was hoping there was a prop like `positionPriorities: ['bottomForced']` or `positionPriorities: ['bottom'], forcePosition: 'bottom'`for example, to ensure the contents are always visible and not cutoff at that bottom of the viewport.

Are there any thoughts on how to accomplish this?

**Comment by erictraut** [comment]
If the anchor is too close to the bottom of the viewport, there may be no space available to render the popup. It depends on the available space and the minimum height of your popup's content. The popup layout logic also tries to leave 8 pixels of space around the edge of the screen/window because it looks bad if popups appear too close to the edge.

What is the minimum height of your popup content? What is the distance from the bottom of your anchor to the bottom of the screen/window?

Could you provide a gist or a screen shot?

**Comment by erictraut** [comment]
OK, it's working exactly as I would expect. And it appears to be doing what you said above — "...to get the popup...to always display fully below the anchor, even when close to the bottom of the viewport". 

What do you expect to happen when there's insufficient space for the popup below the anchor?

**Comment by erictraut** [comment]
If you want the popup to appear somewhere other than immediately adjacent to the anchor (e.g. you want it to appear immediately under the mouse click location), you can apply a translateX and/or translateY transform to the popup contents when you render them. Maybe that will help you achieve the effect you're looking for?

**Comment by MovingGifts** [comment]
I was thinking since the position is bottom, and if you click item 28, the popup shows on the bottom but only partially. Instead, with a prop present perhaps, the popup should show fully on the bottom of the anchor (using the full height of the full popup), expanding to where you can see all the items under it.

**Comment by erictraut** [comment]
I don't know what you mean by "show fully on the bottom of the anchor". There's not enough space for it to be displayed fully beneath the anchor.

**Comment by MovingGifts** [comment]
Can it somehow make space on the bottom, just enough to fit the popup? I tried before by setting a `marginBottom:` popup height + few px on the container, to ensure it would have sufficient space to fit underneath the low viewport anchors, but wasn't able to get it to work, so I brought it up here to see if it's possible?

**Comment by erictraut** [comment]
Make space how? If the popup is 200 pixels high and there's only 100 pixels between the bottom of the anchor and the bottom of the screen, 100 pixels of the popup will not be visible.

**Comment by MovingGifts** [comment]
I thought maybe if the popup is 200 pixels high, on opening of the popup, give the popup the full height, add a margin or more height to the main container (to give more y axis room to fit), and scroll the anchor up to a higher position, that way everything fits. And on close of the popup, remove the extra margin or height which allowed for the space.

I may be over complicating this. It just feels like odd/inconsistent UX, top anchors display the adjacent bottom popup, and the user is used to that behavior. Then they can't be adjacent below anymore and are now above towards the bottom anchors. It just feels off from a UX perpective. Not sure...

**Comment by erictraut** [comment]
Ah, I see what you mean. Yeah, I think you're overcomplicating this.

I don't think that auto-scrolling is a good idea. Moving elements out from under the user's mouse after they click on something is generally disorienting. 

It's also not always possible to scroll. What if you're already scrolled all the way to the bottom of the contents? Temporarily adding more whitespace to the bottom of the ScrollView contents would be really strange.

I added support for multiple popup positions to solve this very problem. There are times when the default position isn't possible, so a secondary (or tertiary) position option may be required.

**Comment by MovingGifts** [comment]
That's sound reasoning. Thank you for that!
