### ISSUE TITLE
TestId of View is not exposed on Android/iOS

### ISSUE THREAD

**Issue by ania-s** [Microsoft/reactxp#758]
We are working on an app using typeScript and ReactXP. For its testing we use webdriver.io As suggested in the ReactXP documentation we added testId for different UI Components to be able to easily access them for the testing purposes. 

`<Text testId={"Heading"} style={styles.text}>
Heading: {this.state.heading}
</Text>`

In web app everything works fine and we can see **data-test-id**. The problem is with mobile apps, both android and iOS as none of the UI elements has **testID** exposed even though the property is added in the source code.

We are using the latest ReactXP - "reactxp": "^1.3.2".
Any suggestions what we are missing or is there an issue on ReactXP side?

**Comment by erictraut** [comment]
ReactXP simply passes through the testId to RN. (Note that it's spelled "testId" in ReactXP for consistency, whereas RN chose to call it "testID" with the last letter capitalized.) Which version of RN are you using? I forget which version of RN introduced support for testID, but I think it was fairly recent.

**Comment by ania-s** [comment]
Thanks for the quick feedback.
We are using RN 0.55.4 - maybe that's the problem and we should use the newer version. I will check it.
We are aware of the naming details, i.e. testId vs testID, so this shouldn't be an issue as we followed the official docs.

**Comment by luisnaranjo733** [comment]
My team is using the latest XP version and I can confirm that XP passes this prop through correctly (except for the extensions who don't all have fixes for this yet). We are using Detox to drive e2e.

I would suggest making sure you aren't accidentally losing the testID prop in some intermediate storybook/shared component. It's very easy to do, unless you are very careful about how you spread your props through before they make it down to XP.

**Comment by ania-s** [comment]
We haven't upgraded to the latest react-native yet, however, I took the ReactXP sample app - RXPTest upgraded the react-native version to the latest one:
`"dependencies": {
    "appium": "^1.8.1",
    "appium-doctor": "^1.4.3",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-native": "^0.56.0",
    "react-native-windows": "^0.55.0-rc.0",
    "reactxp": "^1.3.2"
  }`

and I added the testId prop to some UI Elements. In RXPTest/src/TestListView.tsx I modified:
`return (
            <RX.View testId={'1view'} useSafeInsets={ true } style={ _styles.container }>
                <RX.View testId={'2view'} style={ [_styles.header, RX.StatusBar.isOverlay() && _styles.headerSpacer] }>
                    <RX.Text testId={'Sselect'} style={ _styles.explainText }>
                        { 'Select test to run' }
                    </RX.Text>
                    <RX.Button testId={'RrunAll_test1'} style={ _styles.button } onPress={ this._runAll }>
                        <RX.Text style={ _styles.buttonText }>
                            { 'Run All' }
                        </RX.Text>
                    </RX.Button>
                </RX.View>
                <RX.ScrollView style={ _styles.scrollView }>
                    { testListItems }
                </RX.ScrollView>
            </RX.View>
        );`
Of coure I can see all of testIds, I added, in browser. However, not on the mobile. I checked it with appium ui inspector and:

- ios: I see <RX.Text testId={'Sselect'}...> and <RX.Button testId={'RrunAll_test1'}...> and they are both exposed and accessibilityLabels. 
- android: I see only <RX.Button testId={'RrunAll_test1'}...> exposed as text (in general android behaves in a weird way as sometimes I see this testId sometimes not)

Anyway, I have some issues seeing this properties even with your sample project. And they are not exposed as testID at least via Appium. I will configure Detox for this Sample app as well and see how it behaves, however, if you have any suggestions: what I do wrong or what I should change please let me know.

**Comment by ania-s** [comment]
So Detox doesn't see testId for RX.View either for the RXPTest sample project.

**Comment by ania-s** [comment]
I modified the title as I have mostly problems with exposing testId for View as mentioned in the previous comment. It's the same with your sample app and our code. Anyone can help me with that please?

**Comment by ania-s** [comment]
Ok, I got it working now. It looks that it was on our app side. So at least for now everything looks good and testId is visible on mobile side as well.
