### ISSUE TITLE
Build Failure for RXPTest

### ISSUE THREAD

**Issue by xogeny** [Microsoft/reactxp#762]
If I clone the `reactxp` directory and extract the `samples/RXPTest` directory and then run `yarn install` followed by `yarn rn-watch`, I get a bunch of errors.  It looks like an issue with `@types/react` since I get messages like this:

```
node_modules/reactxp/node_modules/@types/react/index.d.ts:3736:19 - error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component<any, {}>' and 'Component<any, {}, any>'.
  Named property 'setState' of types 'Component<any, {}>' and 'Component<any, {}, any>' are not identical.
```

I tried for some time to figure out how to address this.  It is similar to [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25145) although I haven't gotten those solutions to work.  Clearly there is some mismatch in versions.  I often see this with definitely typed packages that use a `"*"` to list dependencies (as `@types/react-dom` does for `@types/react` 😢).

This could be easily addressed in the `samples` directories by the use of a `.lock` file (either via `yarn` or `npm`).  This would record the particular combination of dependencies to use so new users don't have to worry about these issues.

If anybody has any suggestions on how to get this example compiling, let me know.  If I find something I'll update this issue.  But ideally the solution should be to avoid the problem by getting it working out of the box so people won't have to look through the issues to find a fix.

**Comment by xogeny** [comment]
It turns out adding

```
  "resolutions": {
    "@types/react": "16.3.9"
  },
```

to `package.json` seems to address the problem.  At least I can get it to compile then.

**Comment by erictraut** [comment]
I'm not able to repro the problem you're seeing. I'm using npm, so perhaps this is a yarn-specific issue?

**Comment by erictraut** [comment]
Yeah, I'm able to repro with yarn. I'm not that familiar with yarn, but I thought its behavior was supposed to be the same as npm. Apparently not.

In any case, the sample builds fine if you follow the [documented build steps](https://github.com/Microsoft/reactxp/tree/master/samples/RXPTest).
