### ISSUE TITLE
Text forces pointer cursor

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#768]
Hi,

Adding `onPress` handler on `<Text>` nodes forces `pointer` cursor. I suppose we should let the developer decide what the desired cusor is:

https://github.com/Microsoft/reactxp/blob/master/src/web/Text.tsx#L130

Same as with `Buttons` before, `Text` overwrites the original `cursor` 😅

**Comment by zarubond** [comment]
Here it a PR to fix the problem [https://github.com/Microsoft/reactxp/pull/793](https://github.com/Microsoft/reactxp/pull/793) .
