### ISSUE TITLE
window is not defined when running with mocha

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#772]
Hi,

I'd like to run React components tests with mocha, however mocha quits with the following error:

```
$ mocha -R spec --require babel-core/register --require "test/setup.js" "test/**/*.spec.js"
/Users/pronebird/app/node_modules/reactxp/dist/common/utils/Timers.js:15
var timerProvider = window || global;
                    ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/pronebird/app/node_modules/reactxp/dist/common/utils/Timers.js:15:21)
```

I thought this code is harmless, but then I opened `node` and unfortunately  `window || global` throws `ReferenceError` there too. As a workaround I can think of:

```
var window;
var timerProvider = window || global;
```

I know JSDom can fix this, but I am not sure if one needs DOM at all to run React :)

**Comment by pronebird** [comment]
Actually, Enzyme needs JSDOM, so I am plugging it in.

**Comment by thegalah** [comment]
@pronebird  How did you resolve this? I have also hit this issue. I've tried https://github.com/rstacruz/mocha-jsdom to no avail

**Comment by pronebird** [comment]
@thegalah I believe this was fixed in one of the PRs to reactxp. At the same time, I've switched to running mocha in electron renderer which is a browser itself.
