### ISSUE TITLE
Different behaviour of styling on web in development mode

### ISSUE THREAD

**Issue by francisbourquestudyo** [Microsoft/reactxp#774]
We've run into an issue where our components were not rendered the same in development and production  mode on the web. After seeing this error `Conflicting rules for margin specified.` being thrown, we managed to find why there was a difference. In the file `src/web/Styles.ts`, there is this block of code on line 37: 
```
if (AppConfig.isDevelopmentMode()) {
    if ((combinedStyles.marginLeft !== undefined || combinedStyles.marginRight !== undefined ||
              combinedStyles.marginTop !== undefined || combinedStyles.marginBottom !== undefined) &&
              combinedStyles.margin !== undefined) {
        console.error('Conflicting rules for margin specified.');
        delete combinedStyles.margin;
    }

   ...
}
```

It results in the margin property being deleted in development mode, but not in production, which is bad as the behaviour differs. The `AppConfig.isDevelopmentMode()` condition should only affect whether or not the `console.error()` is thrown. The same problem occurs in this file with the padding and other properties.

By the way, is there are reason why `delete combinedStyles.margin` has been put in place? The behaviour I would expect is that margin is a fallback value if a specific one has not been set. For example, this: 
```
const style = RX.Styles.createViewStyles({
    marginTop: 4,
    margin: 8
})
```
I would expect the margins to be the following:
Top => 4
Left => 8
Right => 8
Bottom => 8

**Comment by erictraut** [comment]
I agree that the behavior should be the same between dev and production mode. I'll remove the delete statement. 

The reason we don't combine them is that there's runtime overhead required to do so. This method is called very often, so it's important that it doesn't do more work than necessary. Since this is considered a programming error, we strip out the check in production builds.

**Comment by erictraut** [comment]
Thanks for reporting. I've removed the delete statements. The change will be incorporated in the next major release (1.4.0).
