### ISSUE TITLE
ReactNative@0.44

### ISSUE THREAD

**Issue by axemclion** [Microsoft/reactxp#79]
React Native 0.44 removes React Native's Experimental navigator as per this [commit](https://github.com/facebook/react-native/commit/febf3d00ed228391ee4dd6541b0d2746dc56d21f) and [release notes](https://github.com/facebook/react-native/releases/tag/v0.44.0).

ReactXP uses Navigation Experimental [here](https://github.com/Microsoft/reactxp/blob/master/src/native-common/NavigatorExperimentalDelegate.tsx#L30) and as a result, there is a compilation error when bundling ReactXP with react-native@0.44

**Comment by erictraut** [comment]
In general, we want to allow each consumer of ReactXP to specify which version of React and React Native they want to use in their apps. Most changes in React Native are forward compatible, so a "min compatible version" is sufficient. In some cases, like the one you mentioned, a breaking change will require a "max compatible version" as well.

The Navigation Experimental dependency will need to be addressed. It's on our to-do list.

**Comment by axemclion** [comment]
@erictraut Thanks. Is there a link to the list ? I was planning to demo this at build next week and wanted to see if this would be ready by then.

**Comment by erictraut** [comment]
Sorry, this won't be ready for build next week. Is there a reason you can't use an earlier version of React Native?

The "to-do" list is tracked in our internal bug list, so it's not publicly available.

**Comment by erictraut** [comment]
Updated to use RN 0.46.
