### ISSUE TITLE
RX.Text numberOfLines property doesnt work properly, if text contains line breaks

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#790]
I have a RX.Text component with numberOfLines={1} and display a variables text inside.

If the variables text is too long to be displayed in one line, the component truncates my text, as expected. But, if the text contains line breaks, the component becomes multiline, unfortunately.

I avoided the problem, by replacing line breaks with spaces. This gets the desired behavior back.

`<RX.Text numberOfLines={1}>{ description.replace(/\n/g, ' ') }</RX.Text>`

Target Platform: Web (Electron)

Regards,
Sascha

**Comment by erictraut** [comment]
You're correct. HTML doesn't have a way to specify that line ending should be ignored. There are a couple of solutions to this problem:

1. The approach you used, which requires dynamically replacing all line-break characters with white space.
2. Explicitly setting the height attribute of the text container to the line height of the text.

Option 2 adds a challenge on native platforms that support font scaling for accessibility purposes. To deal with this, you'll need to multiply the height by the value returned by RX.UserInterface.getContentSizeMultiplier(). So if option 1 is working for you, I'd stick with that.

We've thought about doing the replacement within the ReactXP implementation, but there are legitimate reasons for including line breaks in text, and this would also impose a not-insignificant performance overhead in the common case where the text contains no line breaks.

**Comment by erictraut** [comment]
Even if the RX.Text could determine the correct height (which it can't), setting this height internally has other undesirable side effects. So that approach won't work. 

This problem is enough of an edge case that I don't think we should add a separate platform-specific property to handle it. There's an easy and cheap workaround. I agree that documenting the behavior is worthwhile so others don't need to rediscover the workaround.

**Comment by deregtd** [comment]
Another thing to consider is that the performance overhead won't be huge on numberOfLines=1 cases.  You don't need to do it on every RX.Text in the world, but if the user is limiting the numberoflines, maybe it's worth it to do the replacement in RX?  I don't know enough of the use cases around intentionally using \n + numberOfLines at the same time.

**Comment by shameister** [comment]
Hey @deregtd,

our use case is very easy to describe. We have User generated content, which could be multiline and we are displaying it in a overview cell as one-lined teaser.

My first idea also was, that it would be enough, to handle this case only, if numberOfLines equals 1 (this would be enough for my case)… but it also could be, that one want to limit the lines to 3 and the text has 5 lines… so this might not be enough.

What do you think?

@erictraut, how does Skype handle this issue here?

<img width="322" alt="skype example" src="https://user-images.githubusercontent.com/98413/44997776-0f907e00-afb1-11e8-816a-db22a31d8e53.png">

**Comment by erictraut** [comment]
The Skype client uses numberOfLines=1 in thousands of places, and some of them are in perf-sensitive paths. In almost all cases, these strings are static, so we know they don't contain line breaks. In the few cases where we're displaying user-generated content with numberOfLines=1, we use one of the two techniques I mentioned above - either replace the line breaks or set the height explicitly.

It would still leave an edge case where an RX.Text with numberOfLines=1 contains multiple child RX.Text children that contain line break characters.

Also, keep in mind that we already have a difference in behavior for numberOfLines>1. HTML currently has no way of supporting this (although there's a proposal being considered). All of the native platforms already support numberOfLines>1.

**Comment by erictraut** [comment]
I added better documentation. Thanks for reporting the issue.
