### ISSUE TITLE
Text Input clear button doesn't work on web

### ISSUE THREAD

**Issue by roger4ever** [Microsoft/reactxp#791]
Repro Step:
1. Select the Text Input, type some texts, then click the clear button
2. The texts are cleared, the placeholder comes back
3. Move the mouse out of the Text Input, the previous texts come back

And is there way to disable the clear button? clearButtonMode is platform specific and doesn't seem to work for web.

**Comment by roger4ever** [comment]
FYI I found how to disable the clear button from the sample:
input::-ms-clear {
	display: none;
}

**Comment by erictraut** [comment]
Which platform and browser are you using to repro the problem? Most platforms and browsers don't have text input clear buttons.

**Comment by m1ck2** [comment]
Chrome browser and .js or even better coding in r but I need completion of coarse emailed to me with short cuts and combination keys ect. But everything else google with Apple layout and structure after completing configuration changes on prefer IBM thinkpad or Lenovo or Hp  but all lots of memory and ram extreme grafics and sound all must surpass alianwear computers. Tablets great too but other the a guidance and help others shouldn’t continue to change my settings ect this is mine and only access any other should get is to the app they specify assist with and nothing else any and all further bits of information from other apps should be treated as seperate development pending approval there for costly and time shaken to get access to many different applications. 


Sent from Yahoo Mail for iPhone


On Sunday, September 2, 2018, 2:41 am, Eric Traut <notifications@github.com> wrote:


Which platform and browser are you using to repro the problem? Most platforms and browsers don't have text input clear buttons.

**Comment by roger4ever** [comment]
Win10 and Edge. It's an Agave application in UWP
