### ISSUE TITLE
If we are building a React app for IOS and Windows what should we be utilizing. Is i react-native-windows or react-xp?

### ISSUE THREAD

**Issue by xtianus79** [Microsoft/reactxp#795]
##that's the question i can't seem to find the answer to...

**Comment by shameister** [comment]
Hey xtianus79,

we are using ReactXP to develop for both platforms. Since deployment target as Universal Application is not available so far, we wrap our web-build into an [electron](https://electronjs.org/). This works quite well.

Regards,
Sascha

**Comment by xtianus79** [comment]
@shameister what do you mean deployment target as Universal application?

**Comment by deregtd** [comment]
You can build for iOS and Windows using reactxp or you can build using straight react native if you want to go that route.

@shameister you should be able to deploy a fully native UWP app using react-native-windows with reactxp.

**Comment by erictraut** [comment]
@xtianus79, there are minor differences between RN interfaces for iOS, Android, and Windows. There are large differences between RN and ReactJS. ReactXP tries to smooth over all of these differences, presenting a unified interface and set of behaviors. The more platforms you intend to support, then more useful ReactXP is. If you're sure that you will support only iOS and Windows, then you can write directly to RN if you're careful to deal with the small differences in behaviors and features of these two RN implementations.
