### ISSUE TITLE
[Feature request] Add support for react-native 0.57

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/reactxp#797]
React-native 0.57 is [close](https://www.npmjs.com/package/react-native) to being released, and it is looking like this will be a major release that a lot of people will want to switch to as quickly as possible.

Here are a few of those compelling reasons....
* It is likely that 64 bit JSC support is finally going to land in 0.57. [This ](https://github.com/facebook/react-native/pull/18754)is a PR that has been accepted and [merged internally](https://github.com/facebook/react-native/pull/20993) to fix [this ](https://github.com/facebook/react-native/issues/2814#issuecomment-402640587)longstanding issue from 2015. This will unblock 64 bit support for react-native apps, which Google is [requiring for all apps by August 2019](https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html).
* [Revamped accessibility APIs](https://facebook.github.io/react-native/blog/2018/08/13/react-native-accessibility-updates) that converge Android+iOS. People at companies with a high accessibility quality bar (like Microsoft) will be excited to unlock this.
* New iOS webview that uses WkWebview behind the scenes to replace the deprecated UiWebView in iOS 12 (XP issue #765 will go away)

I think there is value in starting work on this ASAP to unblock the migration to 0.57 for XP's user base. Has there been any effort/investigation to support RN 0.57? Facebook has already put out several release candidates that can be used for this investigation.

**Comment by erictraut** [comment]
The Skype team hasn't done any investigation on RN 0.57 yet. It would be great if someone in the ReactXP community could help with this. Let me know if you see any incompatibilities. We haven't had any problems reported with any recent updates to RN, but if this is a major release, the chances of breaking changes increases.

**Comment by reseul** [comment]
I'm in line with the RN for Windows 0.57...

**Comment by fbartho** [comment]
I'm currently working on it for my team. I haven't gotten Jest to work yet, but I think I can get ReactXP to work on device/Simulator.

**Comment by luisnaranjo733** [comment]
Circling back here - I've migrated my team's project to RN 0.57 with XP. There were some hiccups but they were mostly unrelated to XP.

The only issue I've found is this, and even that might be a RN issue (haven't had time to investigate)
https://github.com/Microsoft/reactxp/issues/850

The other thing is that accessibility APIs have changed in RN 0.57. I haven't compared the XP types to the RN types, but it seems likely that the XP API is out of date. I have not investigated this yet either.

**Comment by fbartho** [comment]
My status update: I have the app mostly working, but not fully working with jest yet.

Currently: ironing out some changes in react-navigation, then will resume getting jest to work.

**Comment by fbartho** [comment]
Looks like everything is working now, with no changes from reactxp needed! I'm happy to help whomever is still struggling with this.

**Comment by luisnaranjo733** [comment]
Going to go ahead and close this issue since we know now that there are no major hurdles to overcome here. If there are any regressions, we can file issues as they are discovered.

Thanks everyone!

**Comment by erictraut** [comment]
Thanks for doing the investigation!
