### ISSUE TITLE
Animation features: Autoreverse and infinite loop

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#803]
Hello,

I'd like to implement an animation, which is repeating over and over again, like animating the opacity from 0 to 1 and back. I was not able to find a solution in the framework itself.

Using built in mechanisms led me to *Maximum call stack size exceeded* errors on target platform web (inside an electron):

Definition of animation
```
let activeAnimationValue = RX.Animated.createValue(0);

let animatedStyle = RX.Styles.createAnimatedViewStyle({
  opacity: activeAnimationValue
})
```

The triggering code inside the class
```
  componentDidMount()
  {
    let animation = RX.Animated.timing(activeAnimationValue, {
      toValue: 1,
      duration: 250,
      easing: RX.Animated.Easing.Linear(),
      delay: 250,
      // if using loop, the error written above appears
      // loop: {
      //   restartFrom: 0
      // }
    });


    animation.start();
  }
```

The JSX.Element
```
 <RX.Animated.View style={ [ ..., animatedStyle ]} />
```

How can I solve this issue?

Regards,
Sascha

**Comment by erictraut** [comment]
It sounds like you want a composite animation — two simple animations executed in parallel. The first would animate from 0 to 1, the second from 1 to 0. Is that correct?

To repeat the animation, you can add code that manually restarts it when it completes.

```
animation.start(() => {
   // Repeat the animation as long as the component is mounted.
   if (this._isMounted) {
        animation.start();
   }
});
```

Repeating animations should be used very sparingly — preferably for short periods of time. They tend to consume a lot of power on mobile devices and laptops if left running indefinitely.

**Comment by alecuba16** [comment]
> ```
> const animateThings = (reverse = false) => {
>     RX.Animated.timing(activeAnimationValue, {
>         toValue: reverse ? 0 : 1,
>         duration: 250,
>         easing: RX.Animated.Easing.Linear(),
>         delay: 250
>     }).start(() => {
>         this.animateThings(!reverse);
>     })
> }
> ```

Doesn't work in my case, I have the latest reactxp version.
> Uncaught RangeError: Maximum call stack size exceeded
>     at Value../node_modules/reactxp/dist/web/Animated.js.Value._updateFinalValue (bundle.js:57724)

**Comment by deregtd** [comment]
Is there any chance that your component hasn't mounted yet?  Check to see if the callback in your start() function there is being called synchronously from inside the start method, which would happen if your component wasn't mounted yet.  It's an odd idiosyncrasy of the web animation implementation.
