### ISSUE TITLE
VoiceOver/TalkBack can't read symbols in RX.Text component

### ISSUE THREAD

**Issue by jessamp** [Microsoft/reactxp#811]
Is it possible to have VoiceOver/TalkBack read text symbols in the Text component? If not, is it possible to add the accessibilityLabel prop into Text as well?

**Comment by mshoho** [comment]
@erictraut we will need to have accessibilityLabel for Text to properly announce the texts which describe, for example, the keyboard shortcuts. It is something we're already thinking about, it's a bit non-trivial for web, but I believe I have a proper hack to make it work nicely. I expect to make a PR for it relatively soon.
