### ISSUE TITLE
render web style as class instead of inline style

### ISSUE THREAD

**Issue by junseld** [Microsoft/reactxp#822]
Hi,

we are experimenting with google optimize (to select elements and test various style variations).
Therefore we would like to be able override the styles via css selectors. Also changing the style of all instances of a single component is basically impossible making it really inconvenient to test different style values.
Unfortuneately it's quite difficult to do so with reactxp rendering inline styles.

how high is the possibility for you to introduce that functionality?

**Comment by erictraut** [comment]
React Native requires inlined styles and doesn't work with CSS classes, so it wouldn't make sense for a cross-platform framework like reactxp to support CSS. If your app is targeting only the web, then reactxp isn't a good choice.

To implement theming support in a cross-platform manner, I recommend using React's "context" mechanism to specify styles that get applied throughout your app. You can change the theme in one place, and the entire app will update accordingly.

**Comment by junseld** [comment]
well you could just do it for web, so not all styles are inlined in the dom.
when using `create...Style` you could just inject a style tag with a class containing the styles and set that class on the element.

I haven't really considered all the advantages and disadvantages/inconsistencies but I think it would be nice to have.

**Comment by erictraut** [comment]
That would go against the core philosophy of reactxp because it would introduce different behaviors on different platforms. I recommend exploring the context-based solution if you want to implement theming in a reactxp-based app. Other apps (including the Skype app) have used this approach, and it works well in a cross-platform manner.
