### ISSUE TITLE
hello-world sample null not assignable to undefined

### ISSUE THREAD

**Issue by dwxw** [Microsoft/reactxp#824]
The hello-world sample was broken for me when I first came to try the project out.  Since this is all new to me, I'm not sure what the correct solution should be, I changed `_renderScene` to return `undefined` instead of `null` and all was good.

```src/App.tsx:40:17 - error TS2322: Type '(navigatorRoute: NavigatorRoute) => Element | null' is not assignable to type '(route: NavigatorRoute) => Element | undefined'.
  Type 'Element | null' is not assignable to type 'Element | undefined'.
    Type 'null' is not assignable to type 'Element | undefined'.

40                 renderScene={ this._renderScene }
                   ~~~~~~~~~~~
```

**Comment by erictraut** [comment]
Thanks for reporting the problem. It was due to a recent change I made in the reactxp-navigator extension. I've fixed the problem, so if you pull the latest copy and update the dependencies ("npm install"), the sample should build without error.

Your fix is also a fine temporary workaround.

**Comment by dwxw** [comment]
Yep, that's working again.  Thank you.
