### ISSUE TITLE
ReactNative

### ISSUE THREAD

**Issue by clifflo** [Microsoft/reactxp#83]
With regard to the version of React Native, would that be managed by ReactXP, meaning that we would only care about dependencies from ReactXP rather than installing React Native npm, or we can choose our own React Native versions by ourselves (considering both JS source code and also the respective typescript definitions)?
I ask this question because as per #79 if we choose the lastest React Native version it would be a breaking change. I assume that at this moment React XP would perhaps stay at some custom versions rather than following official React Native version.

**Comment by erictraut** [comment]
In general, you can choose your own version of React Native. Typically ReactXP will be forward-compatible with newer versions of React Native. However, version 0.44 of RN has introduced some breaking changes that will require us to make some corresponding changes in ReactXP. Until that's done, you'll need to stick with a version of RN that's older than 0.44.
