### ISSUE TITLE
Make x/y of a RX.Component readable properties

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#831]
Hello,

working with gestures works like a charm, but there is one issue we ran into.  When working with the gestures state for moving or resizing our views, we have to substract the delta from our view containers Y, so we could use the coordinates.

Currently we get the delta y from a "magic number", which we do not see as good code practice, but was fair enough so far. As our project evolves, we like to have a header with dynamic user generated content and thus variable height. 

Unfortunately I haven't found a method to read the position from a RX.Component. Right now, we´re not able to spot a solution for this issue, without asking for this feature.

![example](https://user-images.githubusercontent.com/98413/46282156-0cb58880-c571-11e8-9edd-908e8360746f.png)

Looking forward to solve this riddle with you.

Regards,
Sascha

**Comment by erictraut** [comment]
Does the onLayout callback solve your problem? It allows you to be notified when a view changes position or size. Alternatively, you can programmatically query the size and location of view using ```RX.UserInterface.measureLayoutRelativeToWindow``` or ```RX.UserInterface.measureLayoutRelativeToAncestor```.

**Comment by shameister** [comment]
`RX.UserInterface.measureLayoutRelativeToWindow` perfectly fitted my needs. Thank you 🥇
