### ISSUE TITLE
RX.Alert does not pass the Android specific AlertOptions object down to RN

### ISSUE THREAD

**Issue by luisnaranjo733** [Microsoft/reactxp#832]
The default behavior on Android is for dialogs to close when the user touches away from them. RN.Alert has an AlertOptions object that you can pass which allows you to configure this behavior, as well as get an onDismiss callback.

ReactXP does not pass this prop down to RN, making this behavior unreachable with RX.Alert.
I know that XP tries to keep away from platform specific stuff, but this is a pretty commonly desired feature on Android. Does this make the cut for getting added to RX.Types.AlertOptions so it can be plumbed down to RN?

**Comment by erictraut** [comment]
The ```PopupOptions``` interface supports an option called ```preventDismissOnPress```. I think it would make sense to add an option with the same name to ```AlertOptions```. It could be implemented on all platforms except for iOS. Does that sound good? If so, feel free to implement it (along with documentation and test code) and submit a PR.

**Comment by luisnaranjo733** [comment]
I like that.
I went ahead and opened a [PR](https://github.com/Microsoft/reactxp/pull/843/files).
