### ISSUE TITLE
Please update border style documentation

### ISSUE THREAD

**Issue by pronebird** [Microsoft/reactxp#837]
Hi,

It seems that React native supports various combos of `border[Top|Left|Right|Bottom]Width`, it would be ace to update documentation to reflect that:

https://microsoft.github.io/reactxp/docs/styles.html

**Comment by Joeao** [comment]
But that doesn't work in ReactXP, does it?

**Comment by deregtd** [comment]
ReactXP already supports it, the docs just look non-updated.

**Comment by Joeao** [comment]
Oh, how do you use it? Getting the `'border' does not exist in type 'ViewStyle'` error. when I try.

**Comment by erictraut** [comment]
ReactXP does support border[Top|Left|Right|Bottom]Width. It was inadvertently left out of the Styles documentation page. I've added it. Thanks for the report.
