### ISSUE TITLE
ImageSvg doesn't work on react-native

### ISSUE THREAD

**Issue by simonas-notcat** [Microsoft/reactxp#85]
Web version works fine, but the native version is throwing this error:

![image](https://cloud.githubusercontent.com/assets/16773277/25844075/090a4dca-34b2-11e7-8433-894f780e6d8a.png)

I guess it is because the extension is using old react-native-art-svg@1.1.0. This was [noticed here as well](https://github.com/Microsoft/reactxp/issues/72#issuecomment-297472078)

**Comment by erictraut** [comment]
Thanks for reporting the problem. I've updated reactxp-imagesvg to use the latest version of react-native-svg, which fixes this problem. I also added some sample code in the HelloWorld sample that uses the reactxp-imagesvg to draw an animated progress indicator.
