### ISSUE TITLE
sqlite plugin can't load in TodoList.sln

### ISSUE THREAD

**Issue by Zydnar** [microsoft/reactxp#855]
When I look at generated .sln at line 22 there is reference to not existing file:
```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "SQLitePlugin", "..\node_modules\react-native-sqlite-storage\src\windows\SQLitePlugin\SQLitePlugin.csproj", "{6A1F04D0-8750-11E6-AADE-EB9EAC8D95CF}"
```
![obraz](https://user-images.githubusercontent.com/20562545/46856760-a00b7b00-ce07-11e8-8377-d3d211bd9d98.png)
There is no windows folder under "src". Reinstalling node modules or upgrading them don't help.

**Comment by erictraut** [comment]
@a-tarasyuk, something for you to look at if you have time.

**Comment by Zydnar** [comment]
I've noticed a similar problem in react-native-windows can be solved by changing target windows platform and when asked after launching .sln in VS, installing missing SDK. I haven't tried it here yet.

**Comment by a-tarasyuk** [comment]
@erictraut I think the problem that [**react-native-sqlite-storage**](https://github.com/andpor/react-native-sqlite-storage)  does not have [`windows`](https://github.com/andpor/react-native-sqlite-storage/tree/master/src) support. Only [**iOS**](https://github.com/andpor/react-native-sqlite-storage#how-to-use-ios) and [**Android**](https://github.com/andpor/react-native-sqlite-storage#how-to-use-android). That's why VS cannot resolve this path `"..\node_modules\react-native-sqlite-storage\src\windows\SQLitePlugin\SQLitePlugin.csproj"`. There is another plugin [**react-native-sqlite-2**](https://github.com/craftzdog/react-native-sqlite-2) which supports [**Android**](https://github.com/craftzdog/react-native-sqlite-2#android), [**iOS**](https://github.com/craftzdog/react-native-sqlite-2#ios-1), and [Wi**n**dows](https://github.com/craftzdog/react-native-sqlite-2#windows).

**Comment by erictraut** [comment]
@deregtd maintains the sqlite plugin, so I'll defer to him on this issue.

**Comment by deregtd** [comment]
Yeah, I'm not sure of the best way to solve this.  We have a private fork of react-native-sqlite-storage that has support for Windows (and a bunch of changes to android.)

@dryganets: How far have we diverged from the open source module here?  Obviously PRing the windows port back would be easy enough, but I think you also mentioned that the author has no time to deal with it anymore either, so maybe we should just officially fork it?

**Comment by dryganets** [comment]
We can fork it. For Android we have a separate repository.
I rewrote the implementation completely. It is all typescript.

The major differences are:

   1. Implicit transactions. Every command should be wrapped into a
   transaction.
   2. markCompleted optimization. If it is known that there will be no more
   queries executed in this transaction you could call markCompleted to avoid
   extra bridge round-trip.
   3. More optimal serialization/de-serialization of data
   4. We could have more than 1 working thread per database.


There are no differences in terms of API or the data flow inside of
the NoSqlProvider.
If we will add support of iOS and Android to my implementation we could
opensource it as a NoSqlProvider extension.
For simplification, we could drop the support of the multiple thread
workers as we don't use this feature for Android now.


пн, 29 окт. 2018 г. в 11:25, David de Regt <notifications@github.com>:

**Comment by deregtd** [comment]
@dryganets Would it be a bunch of work to do that fork and merge over our private changes, or pretty quick?  Maybe makes sense to rename it like the react-native-sqlite-2 person did?

**Comment by dryganets** [comment]
@deregtd, moving to typescript only will be a bunch of work.

For your use-case, it will be easier to try to contribute the react-native windows.

I'll make a PR, as this is a new platform andpor could be less restrictive.

I've been trying to re-architect Android completely to allow an easy switch between different SQLite implementations. So unless you are going to use SQLite cipher you won't get any big gain for Android anyway.
Let me try to contribute our changes to the official repo first.

As for Android changes - the only change we benefit right now is a different serialization framework and it is in a separate internal repository anyway.

**Comment by dryganets** [comment]
I made a PR:
https://github.com/andpor/react-native-sqlite-storage/pull/302
Will see how it will go.

**Comment by deregtd** [comment]
@Zydnar Looks like @dryganets ' PR was merged into master.  Does that solve the problem you're seeing?

**Comment by Zydnar** [comment]
@deregtd Yes, this problem is solved. Now I encounter other problem:
![obraz](https://user-images.githubusercontent.com/20562545/48199064-383f4600-e35b-11e8-826a-d0fc950eafb3.png)
It says SQLitePlugin is not compatible with the target UAP version. Possibly it's just about changing to compatible target version.

**Comment by fbartho** [comment]
Is this still an issue @zydnar? I think this ticket can be closed.

**Comment by fbartho** [comment]
I'm going to close this for now, but please let me know if you want me to reopen it!
