### ISSUE TITLE
How to specify which child onPress function to use when parent accessible view is clicked and isImportantForAccessibility = Yes?

### ISSUE THREAD

**Issue by jessamp** [Microsoft/reactxp#866]
I have a parent view with two children, a button and an explanation text. When Voiceover/talkback is turned on, I want this whole view to be selected; so importantForAccessibility = Yes. When I click this view, I want the button onPress function to be called. However, the text onPress function is called. This only happens when the text view has a greater area then the button view. Is there a way to specify which onPress component to use?

**Comment by erictraut** [comment]
If there are two overlapping views at the same level of the view hierarchy that both have onPress handlers, the one that is visually "higher" (i.e. the one that was rendered last) should receive the press event. So I think you have a couple of options:
1. Make sure that peer elements don't overlap
2. Make one of the elements a child of the other, in which case events will bubble up the hierarchy
3. Change the render order so the button is rendered after the explanation text

**Comment by jessamp** [comment]
They don't overlap right now. I also can't wrap one child element into the other, because it throws off the styling and makes the text clickable when VoiceOver/TalkBack is turned off. My view looks like this:

```
<RX.View importantForAccessibility={RX.Types.ImportantForAccessibility.Yes}>
    <MyButton onPress={function} />
    <RX.Text>"caption"</RX.Text>
</RX.View>

**Comment by erictraut** [comment]
You said "the text onPress function is called", but I don't see an onPress prop on the RX.Text above. 

If you want to be able to click on either the text or the button, you can install the same onPress handler for both. Or if you want to be able to click anywhere within the containing view, then the containing view is really the "button", and it contains a view and a text item within it. Something like this:

```
<RX.Button importantForAccessibility={RX.Types.ImportantForAccessibility.Yes} onPress={function}>
    <RX.View />
    <RX.Text>"caption"</RX.Text>
</RX.Button>
```

**Comment by jessamp** [comment]
That's where I'm assuming the onPress is being swallowed up even though there's no onPress function defined in Text. 

But I just changed my button similar to the way you suggested, and it works the way I want. I think that's the best work around for now. Thanks!

**Comment by erictraut** [comment]
If you don't install an onPress handler on the RX.Text, clicking on the RX.Text will never invoke an onPress handler for one of its peer views. Events bubble up the view hierarchy, not sidewise or down.

**Comment by jessamp** [comment]
That's why I was confused about my above example. It wasn't working the way I thought it would even though the parent was the focus view. The problem only happened when VoiceOver/Talk Back was turned on.
