### ISSUE TITLE
RX.WebViews postMessage method is missing a transfer-object for payloads

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#876]
We like to post some data into our RX.WebView, after loaded them from the server. Currently it seems, like there is no way to add a `transfer` payload in postMessage as known in the [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage).

Is there currently a way to do this? How to pass data from my `RX.Component` into my `RX.WebView` way after load?

**Comment by erictraut** [comment]
Check out the [WebView](https://github.com/Microsoft/reactxp/blob/master/samples/RXPTest/src/Tests/WebViewDynamicTest.tsx) tests in RXPTests. They demonstrate how to post data to JS code running in the WebView.

**Comment by shameister** [comment]
This means, I can not use different 'keys' for my message and the key is 'message' all the time.

There *should* be a way to seperate key (event name) and payload from each other. 

There are workarounds, like wrapping everything into a JSON object and reading it on the other side in one event handler, but the system (in least in browsers) is designed to be used like I desired (as I understand it right).

Why is there a hard restriction?

**Comment by erictraut** [comment]
I think this is a limitation in RN's implementation of WebView.

**Comment by shameister** [comment]
Thanks. I think you are right with this. Maybe this will be changed later.
