### ISSUE TITLE
onScroll never fires

### ISSUE THREAD

**Issue by sonhanguyen** [Microsoft/reactxp#885]
[![onScroll never fires](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6xqqyonrwz?autoresize=1&expanddevtools=1&hidenavigation=1)

Strangely enough I tried `react-native-web`'s scroll views and none of them fire either. This is on web. What am I missing?

**Comment by erictraut** [comment]
Looks like I introduced a regression recently. I just pushed a fix and published 1.5.0-rc.2. Thanks for reporting the problem.

**Comment by sonhanguyen** [comment]
thanks for the quick fix, @erictraut, however, it was a false alarm. As long as I change the view back to fixed height it fires. I'm sure your fix addresses some subtle bug even though it wasn't my case.
