### ISSUE TITLE
ToDoList sample: Import sources within a group must be alphabetized.

### ISSUE THREAD

**Issue by flolege** [Microsoft/reactxp#889]
Hi, many thanks for [this fix in Resub](https://github.com/Microsoft/ReSub/pull/81), but could it be it causes another issue? I retested and now I got this error:

[21:09:25] Finished 'watch' after 29 ms
[21:09:25] Starting 'lint'...
[21:09:25] Starting 'ts-lint'...
[21:09:25] Starting 'gulpfile-lint'...
[21:09:26] Finished 'gulpfile-lint' after 313 ms
C:/Temp/reactXpSamples/TodoList/src/ts/utilities/ShimHelpers.ts:10:1
ERROR: 10:1  ordered-imports  Import sources within a group must be alphabetized.

The line 10 refers to

`import { Options as ReSubOptions } from 'resub';`

Could you please check?

**Comment by erictraut** [comment]
This was a separate problem. It's now fixed.
