### ISSUE TITLE
Use as a universal component library?

### ISSUE THREAD

**Issue by razagill** [Microsoft/reactxp#903]
Hi,
As far as I've read the documentation and the tooling around it, seems like this is supposed to be used from scratch and not in isolation. Can we use `reactxp` to build a cross platform UI library?

For instance, we have a mono repo setup with `lerna` where we already have a `react` web application and a `react-native` mobile application. We are now thinking of sharing the UI components between them and wanted to have an additional separate package in the mono repo setup where we could use `reactxp` to build the cross platform UIs and then use those components in the rest of the apps. Is this possible?

**Comment by erictraut** [comment]
If you build your higher-level UI components on top of the lower-level ReactXP "primitives", you can include those components in both ReactJS and React Native apps.

ReactXP assumes that it owns the "root view" — the main view that forms the root of your view hierarchy and covers the entire window or device screen. This is how it handles modals and popups. Within that root view, you can combine ReactXP and non-ReactXP components if you want.

**Comment by razagill** [comment]
@erictraut Thanks! Do you know of a sample repo or a possible example I can look into for this?

Just some follow up questions:
1. Can you explain a bit more what these "primitives" are (I'm guessing a list of more or less the same components that are in `react-primitives` package?)
2. This owning of the "root view", is this something we can tell `reactxp` explicitly? In the documentation it says that the root node has to be a specific name `app-container`, is that what you mean? Like giving the root container that id or is it something more elaborate. Sorry, if you can just point me to the right docs or in the general direction of this that'll be great!

**Comment by erictraut** [comment]
The "primitives" are documented in the Components section of the [documentation](https://microsoft.github.io/reactxp/docs/getting-started.html).

The "root view" is created by the ReactXP framework. If you're interested in the implementation details, here's the [source](https://github.com/Microsoft/reactxp/blob/master/src/native-common/RootView.tsx). The root view manages three layers of sub-views: the main layer, the modal layer, and the popup layer. Most of your app's contents appear in the main layer. You specify the contents of the main layer by calling [RX.UserInterface.setMainView](https://microsoft.github.io/reactxp/docs/apis/userinterface.html). Modals appear when you call [RX.Modal.show](https://microsoft.github.io/reactxp/docs/apis/modal.html), and popups appear when you call [RX.Popup.show](https://microsoft.github.io/reactxp/docs/apis/popup.html).

**Comment by razagill** [comment]
@erictraut Thanks for the pointers. But seems like any package that will depend on this "universal UI library" would have to setup a `reactxp` view at the root level (even though it's not using `reactxp` itself). At least that's what I figured. I'll investigate this further and perhaps post some more questions, but we can close this issue for now.

Thanks again for the help.
