### ISSUE TITLE
Possible to create an simple authentication example with identityserver4?

### ISSUE THREAD

**Issue by hmheng** [Microsoft/reactxp#907]
Possible to create an simple authentication example with identityserver4? specifically with PKCE support which security is emphasized.
I find it is essential as how React-native works with some packages are not supported in ReactXP, especially for web and windows.

**Comment by erictraut** [comment]
@deregtd, did you make any progress on the auth example that you were working on?

**Comment by deregtd** [comment]
The auth I’m using has to use ancient ADAL and custom MSA implementations due to first party client limitations for MS properties. I could release it as a sample but it’s pretty damn ugly. MSAL is a much better answer for everyone outside of MS right now.


________________________________

**Comment by hmheng** [comment]
nope, I didnt make it. given up. Would be good if you can make one as I am not really familiar with it

**Comment by hmheng** [comment]
any update on this?

**Comment by deregtd** [comment]
Sorry, forgot to update the thread with this:
https://github.com/deregtd/reactxp-msaadalauth

It's only for MSA/AAD auth, though, I don't know what "identityserver4" is.  But it will give you an idea how to do it in a cross-plat fashion.  If your auth uses generic oauth, it's pretty easy to adapt the various things in that module to handle other oauth providers.

**Comment by hmheng** [comment]
awesome, thank you @deregtd. Let me try it out and see if possible to get it works with Identityserver.

**Comment by hmheng** [comment]
for a quick one, you may find it useful.
http://docs.identityserver.io/en/latest/
