### ISSUE TITLE
Feature: Use styles that are not supported on different platforms

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#919]
As I developed just for deployment target web (Electron) so far, everything was fine, when I used 

`['backdropFilter' as string]: 'blur(2px) grayscale(50%)'`

I knew it would only work in web and not on mobile and this was perfectly ok for me. 

`"backdropFilter" is not a valid style property.`

When deploying for mobile, I expected this property would be ignored. Unfortunately it does not log a warning, instead this throws an error. So what I am searching for is a way to tell the interpreter to ignore this command on a given platform, if not available OR target a command to a specific platform.

Suggestion:

```
RX.Styles.createViewStyle({
  height: 20,
  platformDependent: {
    backdropFilter: platform('blur(2px) grayscale(50%)', 'web'),
    height: platform(50, [ 'android', 'ios' ]),
  }
})
```

Looking forward to discuss, how this is solved in other projects and if a generic solution should be added in RXP and if how.

Regards,
Sascha

**Comment by erictraut** [comment]
We've discussed this previously and concluded that it wasn't worth adding the extra complexity to the ReactXP interface. Your app code can already conditionally include platform-specific styles. ReactXP already supports nested arrays of styles that are combined into a final effective style.

If it's a common pattern in your code, you could create some utility functions around it, but here's effectively what it would look like:

```
const styles = {
myView: RX.Styles.createViewStyle({
  height: 20
},
myViewWeb: RX.Styles.createViewStyle({
    backdropFilter: platform('blur(2px) grayscale(50%)', 'web'),
}),
myViewMobile: RX.Styles.createViewStyle({
    height: 50
)};

const isWeb = RX.Platform.getType() === 'web';
const isMobile = RX.Platform.getType() === 'android' || RX.Platform.getType() === 'ios';
style={[styles.myView, isWeb && styles.myViewWeb, isMobile && styles.myViewMobile]}
```

**Comment by shameister** [comment]
Does not make me happy, since I expect this to be solved in the styling part of the application and not to be done in the 'code'.
