### ISSUE TITLE
How to config sandbox prop for RX.WebView?

### ISSUE THREAD

**Issue by adamchenwei** [Microsoft/reactxp#93]
When I set `sandbox = 1` it seems does not do `AllowScript` for iFrame, because I got some blocking going on in the site I refer to.

Any help on this?

Would be nice to have an example about how to config WebView in ReactXP

**Comment by erictraut** [comment]
@adamchenwei sandbox is a bitmask of sandbox features. You can "or" together the features you want.

const sandboxFeatures = RX.Types.WebViewSandboxMode.AllowForms |
    RX.Types.WebViewSandboxMode.AllowScripts |
    RX.Types.WebViewSandboxMode.AllowPopups |
    RX.Types.WebViewSandboxMode.AllowSameOrigin;

For detailed definitions of sandbox flags, refer to the [HTML documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).

I'll update the ReactXP documentation to make this clearer.
