### ISSUE TITLE
Support borderStyle: 'none' by removing property, when rendered on Mobile

### ISSUE THREAD

**Issue by shameister** [microsoft/reactxp#932]
I am using dotted and dashed border styles in my application for web (Electron), which works perfectly. On mobile I receive warnings, that these types are not supported, if the borders width is different for different directions.

![bildschirmfoto 2018-11-19 um 11 51 25](https://user-images.githubusercontent.com/98413/48702538-76592700-ebf1-11e8-8e89-4ce85d897bc8.png)

This is ok for me. But since I try to seperate styling from coding, I liked to write something like this:

```
RX.Styles.createViewStyle({
  borderStyle: RX.Platform.getType() == 'web' ? 'dotted' : 'none'
})
```

That code is completly accepted from TS, since `none` is a valid borderStyle-option [in the definitions](https://github.com/Microsoft/reactxp/blob/master/src/common/Types.ts#L188). Unfortunately this is not the case in [React Native](https://facebook.github.io/react-native/docs/view-style-props#borderstyle):

![bildschirmfoto 2018-11-19 um 11 54 01](https://user-images.githubusercontent.com/98413/48702723-ebc4f780-ebf1-11e8-9409-28afd01cba27.png)

That´s why I am asking for to solve this in ReactXP by removing the `borderStyle`-property from the `ViewStyle`, when running in a RN-environment.

Furthermore it would be great, if [the docs](https://microsoft.github.io/reactxp/docs/styles.html) could be updated to inform, that these kinds of borderStyles are not supported on mobile so far.

Regards,
Sascha

**Comment by erictraut** [comment]
I agree that the docs should be updated. However, I'm somewhat reluctant to do this special-case handling in the general style processing code. Style processing is done for every ReactXP component rendered, so it's important that we don't slow down this code path to handle extreme edge cases like this one. You can easily work around this case by composing platform-specific styles in your render method or in a const value like this:
```const myViewStyle = [_styles.crossPlatformStyle, RX.Platform.getType() === 'web' ? _styles.webStyle : undefined];```

**Comment by fbartho** [comment]
There hasn't been any activity on this for a while, and based on my understanding of this issue, I'm going to guess that this issue can be closed. If I've misunderstood the issue or somebody wants to submit a PR that fixes the concern in a way that matches @erictraut's technical concerns above, then I'm happy to reopen this.
