### ISSUE TITLE
RX.TextInput focus caret position incorrect

### ISSUE THREAD

**Issue by MovingGifts** [Microsoft/reactxp#936]
So it seems when focusing an `RX.TextInput` with a value in it, the caret position on focus goes to the very first position before the first character in the textarea, instead of after the very last character.

This is seen on web and mobile web.

[Here is a working example demonstrating the issue.](https://codesandbox.io/s/m7xzo4mpyj)

Here is the relevant code as well (also in the link):

```jsx
// TextInputTest.jsx
export default class TextInputTest extends RX.Component {
  handleButtonPress() {
    // should focus text input with caret at end position
    // instead it focuses at the start position
    this.textAreaTest.focus();
  }

  render() {
    const text =
      "this is a test to try and set the caret to the end position right here";

    return (
      <RX.View style={styles.wrapper}>
        <RX.Button
          style={styles.button}
          onPress={() => this.handleButtonPress()}
        >
          <RX.Text style={styles.text}>{"Focus"}</RX.Text>
        </RX.Button>
        <RX.TextInput
          autoFocus={true}
          ref={el => (this.textAreaTest = el)}
          value={text}
          multiline={true}
          style={styles.textInput}
        />
      </RX.View>
    );
  }
}
```

Please also check the link on a mobile device web browser (using safari mobile here on iphone), the keyboard opens, but the caret position is the beginning instead of the end.

Any idea how to get the caret position to be blinking after the last character in the textarea on focus on web and mobile web?

**Comment by erictraut** [comment]
The focus() call does not place the caret at the start or the end. It restores the previous selection or insertion point of the text input field. This is the standard behavior for text input focus on most platforms. If you want to override this default behavior and explicitly select all or place the insertion carat at the end of the existing text, you can do so by calling this.textAreaTest.setSelection(begin, end).

**Comment by MovingGifts** [comment]
Thank you, so I tried your advice both with and without the focus but it did not work. There are 70 characters in the text input, so doing the following should place the caret after the last character:

```js
 handleButtonPress() {
    // should focus text input with caret at end position
    // instead it focuses at the start position
    this.textAreaTest.focus(); // tried with this commented out too, but still does not place caret at end
    this.textAreaTest.setSelection(70, 70);
  }
```
Isn't that the correct way that should work?

**Comment by erictraut** [comment]
Yes, that should work. I confirmed it works for me.

One small difference between my code and yours (not sure if it makes a difference) is that you are not properly handling the button press. You should be specifying that the button press was handled and should not propagate. On some platforms, the default behavior for a button press is to set the focus to the button. It's always a good idea to call stopPropagation if/when you've handled an event.

```
handleButtonPress(e: RX.Types.SyntheticEvent) {
    e.stopPropagation();
    this.textAreaTest.focus();
    this.textAreaTest.setSelection(70, 70);
  }
```

I looked at your working example, but it looks like it was modified and is no longer working.
