### ISSUE TITLE
Improve docs for RX.Network.isConnected

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#938]
It took me ages to detect, that there is an extra permission needed in Android to make use of `RX.Network.isConnected()`.

This permission must be added to the `AndroidManifest.xml`:
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

It would be awesome if a short hint could be added for future developers.

Regards,
Sascha

**Comment by shameister** [comment]
I also like to add, that the [sample usage](https://github.com/Microsoft/reactxp/issues/938) is not correct, since `this.isConnected = RX.Network.isConnected();` returns a promise, instead of a boolean.

**Comment by erictraut** [comment]
Thanks for pointing it out. I've updated the documentation accordingly.
