### ISSUE TITLE
tabIndex prop doesn't work for RX.TextInput

### ISSUE THREAD

**Issue by roger4ever** [Microsoft/reactxp#953]
Setting tabIndex to RX.TextInput doesn't work, the generated html file doesn't have tabindex attribute. tabIndex for other things are working properly.

```
<RX.TextInput
              ref={ this.setTextInputCallbackRef }
              placeholder={ STRINGS('NoteTags.TagName') }
              clearButtonMode='never'
              onFocus={ this.onTextInputFocus }
              onBlur={ this.onTextInputBlur }
              onChangeText={ this.onChangeText }
              onKeyPress={ this.onTextInputKeyPress }
              tabIndex={ 1 }
              autoFocus={ true }
              maxLength={ 200 }/>
```

`<input style="outline: invert; border: 1px solid rgb(0, 0, 0); flex:0 0 auto; width: 280px; height: 28px; padding-left: 9px; display: flex; position: relative; overflow-x: hidden; overflow-y: auto; flex-direction: row; align-items: stretch;" type="text" size="1" maxlength="200" placeholder="Tag name" value="">`

**Comment by erictraut** [comment]
Thanks for the bug report. The fix will appear in the upcoming reactxp 1.5 release.
