### ISSUE TITLE
any third party component libraries for reactxp?

### ISSUE THREAD

**Issue by darrencruse** [Microsoft/reactxp#956]
New to ReactXP and just a question really:

I tried the TodoList sample yesterday and I like e.g. how it could show the same components side by side on a wide device or stacked on like a smartphone.

otoh though the look of the components weren't very polished but I read how the idea is for ReactXP core to stay small and just provide the simple primitives for more elaborate components to be built from.

My question is whether there are any third party component libraries compatible with ReactXP yet?  I was imagining e.g. ones that might implement Material Design?

For comparison I've also been trying react-native-web and I don't think there's many there either but googling I'd found a little e.g. [react-native-elements](https://github.com/react-native-training/react-native-elements) or [nachos-ui](https://github.com/nachos-ui/nachos-ui#features)
  
So my follow on question might be dumb (I'm still fuzzy about the architecture of things) but assuming there's not such component libraries for ReactXP is it conceivable that one could write a ReactXP wrapper that sat in front of the react-native/react-native-web libraries such as the two I mentioned above?  From my brief read of the ReactXP docs and how you write "extensions" that should be possible correct?

Does this seem like a reasonable thing to do?  (I might give it a shot if so - not sure if I'm missing anything though - also I'm pretty new to typescript but eager to learn...).

**Comment by erictraut** [comment]
No such library currently exists, but what you describe makes sense. Architecturally, it would layer nicely onto of ReactXP. There has been some interest within the community, so I'm guessing that you could find other collaborators if you start something.

One key decision about a higher-level set of controls is whether you want these controls to adopt different appearances and behaviors for each platform or whether you want to enable a common look and behavior across platforms but enable rich custom styling. Each approach has pros/cons, but I recommend that you pick one or the other and establish principles that you honor for the entire library.

**Comment by erictraut** [comment]
A ReactXP extension should expose the same interface and behaviors for all platforms, but the underlying implementation can differ by platform. For example, it could be implemented with native Objective-C code on iOS, native Java code on Android and TS/JS for web.

As a starting point, you might want to just clone the TodoList sample and create some new "modules" (in the subdirectory of that name). Each control you add to your control library would be a new module. Some controls (e.g. toggle switch or check box) might have common code. Other controls (e.g. date picker) might use platform-specific implementations and even native code modules. Once you have a module working within the TodoList app, it's relatively easy to move that module into its own independent extension that other developers can leverage.
