### ISSUE TITLE
TSLINT: [ts] JSX element type 'RX.Text' does not have any construct or call signatures. [2604]

### ISSUE THREAD

**Issue by alecuba16** [Microsoft/reactxp#963]
Hello,

I have this "error" on the visual studio code, code checker.

There is any fix / tslint.conf rule to avoid this kind of error?

I'm importing in this way: `import * as RX from 'reactxp';`

**Comment by alecuba16** [comment]
> I require ReactXP this way:
> 
> `import RX = require('reactxp');`
> 
> Hope this helps. :-)
> 
> Regards,
> Sascha

Hello Sascha, thanks for your suggestion, but it is forbidden by tslint:

> [ts] Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead. [1202]

**Comment by shameister** [comment]
`import * as RX from 'reactxp'` works here perfectly. Can you provide the contents of your `tslint.conf`? :)

**Comment by alecuba16** [comment]
Sure.

`{
  "rulesDirectory": [
    "./node_modules/tslint-microsoft-contrib",
    "./node_modules/tslint-react/rules"
  ],
  "rules": {
    // Rules from tslint-microsoft-contrib
    "function-name": [
      true,
      {
        "method-regex": "^[a-z]\\w+$",
        "private-method-regex": "^_[a-z]\\w+$",
        "protected-method-regex": "^[a-z_]\\w+$",
        "static-method-regex": "^[a-z]\\w+$",
        "function-regex": "^\\w+$"
      }
    ],
    "no-delete-expression": true,
    "no-document-domain": true,
    "no-disable-auto-sanitization": true,
    "no-exec-script": true,
    "no-function-constructor-with-string-args": true,
    "no-string-based-set-immediate": true,
    "no-string-based-set-interval": true,
    "no-string-based-set-timeout": true,
    "react-no-dangerous-html": true,
    "react-this-binding-issue": [true, { "allow-anonymous-listeners": true }],
    "no-inner-html": true,
    "no-document-write": true,

    // Rules from tslint-react
    "jsx-curly-spacing": [true, "always"],
    "jsx-equals-spacing": [true, "never"],

    // Rules that are built in to tslint
    "align": [true, "statements"],
    "class-name": true,
    "curly": true,
    "eofline": true,
    "forin": true,
    "indent": [true, "spaces"],
    "interface-name": [true, "never-prefix"],
    "label-position": true,
    "max-line-length": [true, 140],
    "member-access": [true, "no-public"],
    "new-parens": true,
    "no-arg": true,
    "no-bitwise": false,
    "no-console": [true, "debug", "info", "time", "timeEnd", "trace"],
    "no-consecutive-blank-lines": true,
    "no-conditional-assignment": true,
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-duplicate-super": true,
    "no-duplicate-switch-case": true,
    "no-eval": true,
    "no-inferrable-types": true,
    "no-invalid-this": true,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-var-keyword": true,
    "prefer-const": true,
    "no-string-literal": true,
    "no-sparse-arrays": true,
    "ban-comma-operator": true,
    "use-isnan": true,
    "linebreak-style": true,
    "comment-format": true,
    "no-boolean-literal-compare": true,
    "no-unnecessary-initializer": true,
    "space-before-function-paren": [true, "never"],
    "trailing-comma": [
      true,
      {
        "multiline": "never",
        "singleline": "never",
        "esSpecCompliant": true
      }
    ],
    "arrow-parens": [true, "ban-single-arg-parens"],
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-finally",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [true, "single", "jsx-single"],
    "radix": true,
    "semicolon": true,
    "triple-equals": true,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-module",
      "check-separator",
      "check-type",
      "check-rest-spread",
      "check-type-operator",
      "check-preblock"
    ],
    "arrow-return-shorthand": true,
    "no-angle-bracket-type-assertion": true,
    "one-variable-per-declaration": true,
    "no-object-literal-type-assertion": true,
    "no-unnecessary-type-assertion": true,
    "no-duplicate-imports": true,
    "import-spacing": true,
    "type-literal-delimiter": true,
    "no-floating-promises": [true],
    "file-header": [true],
    "ordered-imports": [
      true,
      {
        "import-sources-order": "case-insensitive",
        "module-source-path": "basename",
        "named-imports-order": "case-insensitive",
        "grouped-imports": true
      }
    ]
  }
}
`

**Comment by berickson1** [comment]
@alecuba16 - Can you provide a the code snippet/JSX block that causes this error?

**Comment by alecuba16** [comment]
> @alecuba16 - Can you provide a the code snippet/JSX block that causes this error?

This example has the tslint error 2604:

`// Loading screen
import * as React from "react";
import {
  Animated,
  CommonProps,
  Component,
  Styles,
  Text,
  View
} from "reactxp";

export interface LoadingProps extends CommonProps {
  text?: string;
  duration?: number;
}

const _styles = {
  popupText: Styles.createTextStyle({
    fontSize: 32,
    margin: 8,
    opacity: 1,
    color: "black"
  }),
  container: Styles.createViewStyle({
    flex: 1,
    flexGrow: 1,
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    // borderLeftWidth: 4,
    // borderColor: '#e9385a',
    paddingLeft: 10,
    backgroundColor: "#ffeef1"
  }),
  ldsRing: Styles.createViewStyle({
    position: "relative",
    height: 10,
    width: 64,
    borderRadius: 10,
    backgroundColor: "red",
    opacity: 0.9
  })
};

export default class Loading extends Component<LoadingProps, {}> {
  private _verticalAnimatedValue = new Animated.Value(0);
  private _verticalAnimatedStyle = Styles.createAnimatedViewStyle({
    transform: [
      {
        translateX: this._verticalAnimatedValue
      }
    ]
  });

  constructor(props: LoadingProps) {
    super(props);
    this.props.text = props.text ? props.text : "";
  }

  componentDidMount() {
    this.timing(this._verticalAnimatedValue);
  }

  timing(value: Animated.Value) {
    Animated.timing(value, {
      toValue: value._getInputValue() >= 300 ? -300 : 300,
      easing: Animated.Easing.Out(),
      duration: 1000,
      isInteraction: false
    }).start(() => this.timing(value));
  }

  render() {
    return (
      // Img
      // <div class="lds-ring"><div></div><div></div><div></div><div></div></div>
        <View style={ _styles.container }>
          <Text
            style={ _styles.popupText }>{ this.props.text }</Text>
          <Animated.View
            style={ [_styles.ldsRing, this._verticalAnimatedStyle] }
          />
        </View>
    );
  }
}`

**Comment by erictraut** [comment]
I'm not able to repro the problem. I receive three ts errors form the above code. All of these look like legitimate errors.
```
Cannot assign to 'text' because it is a read-only property.
Cannot assign to 'duration' because it is a read-only property.
Property 'ldsRing' does not exist on type '{ popupText: StyleRuleSet<TextStyle>; container: StyleRuleSet<ViewStyle>; }'.
```
But I'm still not receiving any errors or warnings from tslint.
What version of typescript and tslint are you using? I'm using typescript 3.2.1 and tslint 5.11.0.
What version of reactxp are you using? The latest is 1.5.0.

**Comment by alecuba16** [comment]
> I'm not able to repro the problem. I receive three ts errors form the above code. All of these look like legitimate errors.
> 
> ```
> Cannot assign to 'text' because it is a read-only property.
> Cannot assign to 'duration' because it is a read-only property.
> Property 'ldsRing' does not exist on type '{ popupText: StyleRuleSet<TextStyle>; container: StyleRuleSet<ViewStyle>; }'.
> ```
> But I'm still not receiving any errors or warnings from tslint.
> What version of typescript and tslint are you using? I'm using typescript 3.2.1 and tslint 5.11.0.
> What version of reactxp are you using? The latest is 1.5.0.

Sorry because the erros, the code is a stripped down version of the original, because company policies. I had to delete a lot of things.

I'm using typescript 3.1.3 tslint 5.11.0 and reactxp 1.5.0, maybe the typescript version is the source of the error 2604?

**Comment by erictraut** [comment]
One more thought... Could you post your tsconfig.json? In particular, I'm interested in the values you've set for "jsx" and "reactNamespace".

**Comment by alecuba16** [comment]
> One more thought... Could you post your tsconfig.json? In particular, I'm interested in the values you've set for "jsx" and "reactNamespace".

```javascript
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "strictPropertyInitialization": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "moduleResolution": "node",
    "strictNullChecks": true,
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "noImplicitThis": true,
    "declarationDir": "dist-types",
    "importHelpers": true,
    "noImplicitAny": true,
    "skipLibCheck": true,
    "declaration": true,
    "jsxFactory": "React",
    "noResolve": false,
    "module": "es2015",
    "target": "es2015",
    "jsx": "react",
    "lib": ["es5", "es2015", "dom"],
    "baseUrl": ".",
    "paths": {
      "modules/*": ["./src/modules/*/index.web", "./src/modules/*/index"]
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules", "node_modules/**"]
  }
}

```

**Comment by erictraut** [comment]
Still not able to repro. I even tried switching to typescript 3.1.3.

My only other thought is that you have a symbol called Text declared in an ambient module (i.e. a module with no export statements). This theory is supported by the fact that `Text` has a different color in the code pasted above. Try right clicking on it in VS Code and choosing "Go to Definition".

**Comment by alecuba16** [comment]
> Still not able to repro. I even tried switching to typescript 3.1.3.
> 
> My only other thought is that you have a symbol called Text declared in an ambient module (i.e. a module with no export statements). This theory is supported by the fact that `Text` has a different color in the code pasted above. Try right clicking on it in VS Code and choosing "Go to Definition".

The definition points to ReactXP.d.ts
![Screenshot](https://imgur.com/a/RVWrTUN)

**Comment by erictraut** [comment]
OK, so that seems to indicate that TS (or at least the VS Code TS extension) resolves it to ReactXP correctly. The problem appears to be with tslint though, which doesn't necessarily use the TS engine for its linting rules. Out of curiosity, try this:
`import { Text as RXText } from 'reactxp'` and then use `RXText` in the JSX statement. What does that do?

**Comment by erictraut** [comment]
Is this a tslint error or a ts error? The issue title seems to indicate both. How are you invoking tslint?

**Comment by alecuba16** [comment]
> OK, so that seems to indicate that TS (or at least the VS Code TS extension) resolves it to ReactXP correctly. The problem appears to be with tslint though, which doesn't necessarily use the TS engine for its linting rules. Out of curiosity, try this:
> `import { Text as RXText } from 'reactxp'` and then use `RXText` in the JSX statement. What does that do?
I have found the source of my problem I think, I had a "typings" subfolder inside the src/ folder with "react.d.ts" file. This file was in a reactxp template that my project is based on.  

Thanks for your support and sorry for any inconvenience that I have caused.
