### ISSUE TITLE
[discussion] - assert/throw

### ISSUE THREAD

**Issue by a-tarasyuk** [Microsoft/reactxp#968]
The following components use [assert](https://www.npmjs.com/package/assert) to throw errors:
- [Button](https://github.com/Microsoft/reactxp/blob/master/src/native-common/Button.tsx)
- [GestureView](https://github.com/Microsoft/reactxp/blob/master/src/native-common/GestureView.tsx)
- [PopupContainerView](https://github.com/Microsoft/reactxp/blob/master/src/native-common/PopupContainerView.tsx)
- [UserInterface](https://github.com/Microsoft/reactxp/blob/master/src/native-common/UserInterface.tsx)
- [View](https://github.com/Microsoft/reactxp/blob/master/src/native-common/View.tsx)
- [MonitorListEdits](https://github.com/Microsoft/reactxp/blob/master/src/web/listAnimations/MonitorListEdits.tsx)
- [restyleForInlineText](https://github.com/Microsoft/reactxp/blob/master/src/web/utils/restyleForInlineText.tsx)

Other components use native [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)., it looks a little bit inconsistent. 

Also, components which depend on [assert](https://www.npmjs.com/package/assert), use only one method and don't use the whole set of functions provided by this library., as the result _dist_  contains the entire set of methods provided by `assert`.

My proposal to drop [assert](https://www.npmjs.com/package/assert) dependency in favor of some the lightweight versions like [ok](https://www.npmjs.com/package/simple-assert-ok), [invariant](https://www.npmjs.com/package/invariant) _(React uses it)_, or use native [`Error`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) to throw errors like it was done in other parts of this project.

What do you think @erictraut @berickson1 @deregtd?

**Comment by deregtd** [comment]
I'm in favor of switching all of our projects to use your assert-ok library.  It's tiny and still allows you to use unassert to remove it in production.

**Comment by deregtd** [comment]
So is assert-ok.  @a-tarasyuk made it explicitly for our purpose. :)

https://github.com/a-tarasyuk/simple-assert-ok/blob/master/src/SimpleAssertOK.ts

**Comment by erictraut** [comment]
Yeah, I understand, but there are downsides of taking on external dependencies, and it's not justified in this case.

**Comment by a-tarasyuk** [comment]
Basically, this issue related to extensions too, and also to packages which depend on [assert](https://www.npmjs.com/package/assert) and use only one ok method. Do we need to spread own implementation to all packages? Anyway, the main point of this issue to standardize throwing errors.

**Comment by erictraut** [comment]
Creating an external package makes sense if there's sufficient complexity, but this involves literally five lines of code. An external package is not necessary here.

**Comment by a-tarasyuk** [comment]
@erictraut If we are talking about using native `Error` - it is _true_

```typescript
const assert = (cond, message) {
  if (!cond) {
    throw new Error(message);
  }
}
```

however, there is one difference - [assert](https://www.npmjs.com/package/assert) uses [`AssertionError`](https://github.com/browserify/commonjs-assert/blob/master/assert.js#L125) - it is the custom `Error` definition which extends default `Error`. Basically, [ok](https://github.com/a-tarasyuk/simple-assert-ok/blob/master/src/AssertionError.ts) follows this principle too. [invariant](https://github.com/zertosh/invariant/blob/master/invariant.js) uses default `Error`, however, for the `development` environment, invariant adds additional setup for the `Error`. So, I think we cannot say that both of them take five lines of code :).

If the first option is acceptable, we can create this util function, and use it in the **ReactXP**, also, copy to _extensions_, and then copy to other projects which use [cjs assert](https://www.npmjs.com/package/assert). What do you think? Does make sense to start work on the issue?
