### ISSUE TITLE
[discussion] - migrate from CJS to the ES Modules

### ISSUE THREAD

**Issue by a-tarasyuk** [Microsoft/reactxp#969]
`import module = require('module') / export = module` exists for [backward compatibility with earlier versions of TypeScript and CJS modules](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#1133-import-require-declarations), and better in the future migrate to [ES Modules](https://github.com/a-tarasyuk/reactxp/tree/feature/es-2015-modules). In order to have advantages of tools like Webpack, which has Tree Shaking and some other options to optimize bundle size need to use ES modules.

Maybe the cost of _dist_ size is not significant for Native applications, however, for Web it is important, and this change can save some bytes., right now `dist` size for the Web version which has several lines of code is equal 376KiB _minified_ and 112KiB _MINIFIED + GZIPPED_.

**Comment by deregtd** [comment]
I think we talked about this a while ago, but continuing the same build system work that you prototyped on our other smaller projects and applying it to reactxp seems like the easy button here, right?

**Comment by a-tarasyuk** [comment]
@deregtd you are right, we can use the same strategy which was applied to other projects. I see only one issue with `module` which converts code to [`IIFE`](http://www.typescriptlang.org/play/index.html#src=module%20ReactXP%20%7B%0A%20%20%20%20export%20const%20Text%20%3D%20()%20%3D%3E%20%7B%7D%3B%0A%7D%0A%0A), that is useless for ES Modules. However, as I understood ReactXP uses `module` to check that all platforms have the same public API. It can be covered by unit tests. In my opinion, would be useful in the future add the opportunity to export modules independently, however, the starting point should be migrating from IIEF/CJS to ES Modules. When I was working on the lodash example which shows problems with `import _ from 'lodash'` I created the prototype [repo](https://github.com/a-tarasyuk/reactxp/tree/feature/es-2015-modules) which uses ES Modules, anyone can try it.

**Comment by erictraut** [comment]
It's important for us to have a static way to validate that each platform implementation conforms to the interface. I'm fine with using a different static checking mechanism, but I don't want to rely on unit tests for this check.

I would like to reduce the size of the library, but I'm somewhat skeptical that this change will produce any meaningful decrease. Maybe a quick prototype would allow us to measure the decrease, which would help inform the importance of this change.

**Comment by a-tarasyuk** [comment]
> I'm somewhat skeptical that this change will produce any meaningful decrease

You are right, it will not be _meaningful decrease_, to make a significant impact on library size need to make more than simply moving to ES Modules. I think, need to apply changes/practices which can decrease the size, step by step.

The default `create-rx-app` app template weight is: 

```shell
376K - bundle.js     (MINIFIED)
96K  - bundle.js.gz (MINIFIED + GZIPPED)
```

With ES modules, weight is

```shell
350K - bundle.js     (MINIFIED)
87K  - bundle.js.gz (MINIFIED + GZIPPED)
```

**Comment by a-tarasyuk** [comment]
@erictraut  BTW - [Here](https://docs.google.com/document/d/1tj0mmo-bv2mAbPdRkebxNxcURfQerdsKZ4d8r8vnopw) an example how [ImageList](https://github.com/Microsoft/reactxp/tree/master/samples/ImageList) example can be [optimized](https://docs.google.com/spreadsheets/d/1zM1MzGwZMtKzqrp0P3ximyDkA58QB1VQ-06DCZKJLYs).

**Comment by a-tarasyuk** [comment]
@erictraut BTW - Here how ImageList example can be optimized. Results show, that with not complicated things application size can be reduced by 89 kB (MINIFIED) and 30 kB (MINIFIED + GZIPPED).
