### ISSUE TITLE
TextInput AutoFocus for Web Does Not Scroll to Input

### ISSUE THREAD

**Issue by ricklove** [Microsoft/reactxp#97]
If a TextInput is inside a ScrollView, Autofocus should also scroll the text to view.

Also, Autofocus does not work in web (Safari on iOS).

**Comment by erictraut** [comment]
This is unlikely to ever be implemented. HTML doesn't contain support for auto-scroll to a particular location, and it doesn't appear to expose enough information to implement this in JS.

**Comment by Inve1951** [comment]
[`element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) is a thing.

Simplified implementation:
```html
<input type="text" autofocus onFocus="this.scrollIntoView()" />
```

To scroll to a specific offset use `scrollContainer.scrollTop = offsetInPixels`.
