### ISSUE TITLE
[discussion] - lodashMini

### ISSUE THREAD

**Issue by a-tarasyuk** [Microsoft/reactxp#970]
ReactXP collects lodash helpers in one `lodashMini` file _(actually, each platform has own `lodashMini` file)_ in order to avoid issues related to _dist_ size. Usually, components import only several helpers _(I fount only one component which depends on 4 helpers)_. TypeScript does not handle the case when some helpers were not imported from `lodashMini`. To remove unused imports in `lodashMini` need to search in the entire project and by hand check and remove unused functions - and easy to forgot remove unused functions. However, TypeScript handles case with _unused local variables_. For instance component `Image` depends on `isEqual`, `omit`,

```typescript 
import isEqual from 'lodash/isEqual';
import omit from 'lodash/omit';
...

```
If someone removes code where was used `omit` - TypeScript will explicitly throw an error about `Unused locals`. Does that make sense? What do you think @erictraut @berickson1 @deregtd?

**Comment by deregtd** [comment]
Is the proposal to switch back to requiring directly from lodash and having babel-lodash do the conversion to separate imports, or to simply have each file do the individual requires manually?  Doing it in an automated fashion feels better to me.

**Comment by a-tarasyuk** [comment]
@deregtd 
> Doing it in an automated fashion feels better to me.

For me too, however, need to add additional dependencies to change the build process. I think, these changes will not be accepted :smile:. In my opinion, the ideal case is not to worry about `import` optimization at all, just use `import` as shown below:

```typescript
import _ from 'lodash';
```
or 
```typescript
import { map, each } from 'lodash';
```

> simply have each file do the individual requires manually

Yeah, that's what I meant. I noticed that easier to support (add/remove helpers) components with direct `import` and do not rely on file which collects lodash imports.

**Comment by erictraut** [comment]
I don't have a strong opinion on this one.
