### ISSUE TITLE
NPM - reactxp-virtuallistview

### ISSUE THREAD

**Issue by a-tarasyuk** [Microsoft/reactxp#973]
The current [virtuallistview documentation](https://microsoft.github.io/reactxp/docs/extensions/virtuallistview.html) does not match the latest published version on [NPM](https://www.npmjs.com/package/reactxp-virtuallistview). Is there any reason to not publish 2.0.0-rc.0?

**Comment by erictraut** [comment]
@berickson1, do you have any further breaking changes planned for the VLV 2.0 interface?

**Comment by berickson1** [comment]
I don't have anything breaking planned, but I'm still chasing one bug with respect to keyboard accessibility that occurs when items are removed from VLV, so I'd like to keep this as a rc-only for now

**Comment by a-tarasyuk** [comment]
As I see, signature for the `_renderItem` has been changed

Before:

```typescript
  private _renderItem(item: FruitListItemInfo, hasFocus?: boolean) {
```

After:
 
```typescript
  private _renderItem(details: VirtualListViewCellRenderDetails<FruitListItemInfo>) 
```

Right now docs follows 2.0.0-rc.0, however, the latest NPM version is 1.5.0 - it is a little bit confused.

**Comment by berickson1** [comment]
The pull request for 2.0.0 landed less than 24 hours ago. Often the ReactXP documentation is ahead of what's on NPM as releases are planned/staged

**Comment by alariej** [comment]
Any update on this? NPM version is still 1.5. I was hoping to use the initialSelectedKey prop, but it doesn't seem to be available on 1.5. Any idea when 2.0 will be released?

**Comment by berickson1** [comment]
@alariej - I just published 2.0.0-rc.1. I've been running this out of a private npm repository for a while and haven't seen any additional issues. Sorry for the delay

**Comment by erictraut** [comment]
Version 2.0.0-rc.1 has been published for a while already.

**Comment by erictraut** [comment]
Never mind. I guess @berickson1 just published it. Thanks Brent!
