### ISSUE TITLE
Load html template to WebView

### ISSUE THREAD

**Issue by SergeShkurko** [Microsoft/reactxp#979]
Can i load html template from `*.html` file ?

```javascript
require('./template.html') // returns 1 instead of a template
```
![image](https://user-images.githubusercontent.com/18213789/50188166-73616b80-0342-11e9-9306-285b8fe82344.png)
console.log: 
![image](https://user-images.githubusercontent.com/18213789/50188197-93912a80-0342-11e9-8b50-fa14cae3280e.png)

Are there any alternatives other than template strings?

**Comment by deregtd** [comment]
That's not a reactxp question, it's a matter for whatever loader/compilation system you're using.  Webpack can load it with a proper loader, for example.  However, loading HTML doesn't really help you on reactxp since you need native implementations as well, which won't be HTML.
