### ISSUE TITLE
GestureViews onTap prevents ScrollView to work properly on Android

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#981]
We like to detect, on which y position inside a ScrollView the user taps.

For this, we added a `RX.GestureView` inside the `RX.ScrollView` with full height and width.

On web, this works perfectly. But when it comes to electron, the ScrollView stops responding properly. 

```
<RX.ScrollView>
  <RX.GestureView onTap={() => {}} />
</RX.ScrollView>

```

 Therefore I am asking for a handler inside RX.ScrollView to detect the tap coordinates, that are used to start scrolling. This would help, to not prevent the view from scrolling.

Regards,
Sascha

**Comment by erictraut** [comment]
That's a pretty major abuse of GestureView. I wouldn't expect it to work on native platforms either because the GestureView will capture the gesture and prevent the user from scrolling the ScrollView.

I think you'll need to find another technique. Have you tried using an RX.View and adding an onPress handler? The event should include the clientX and clientY coordinates of the press/click.

**Comment by shameister** [comment]
Yes Eric, I tried `onPress` also. It produces the same kind of error.

**Comment by shameister** [comment]
Can you specify, what exactly is the major abuse of GestureView inside a ScrollView?

As this is crucial to our whole app (which runs perfectly on web), I'd like to discuss the options to handle this.

The behavior on the screencast is excessive use of GestureView inside a ScrollView and works fine (even on mobile). For mobile to start moving, you have to tap the clocking, which disables the `scrollEnabled` for the ScrollView. The one feature, that makes us trouble is the lack of the information, on which position inside a ScrollView a user taps without using `onPress` of a RX.View or `onTap` of an RX.GestureView.

Do you see any way to add something like onPress to RX.ScrollView?

![bildschirmaufnahme 2018-12-21 um 10 49 39](https://user-images.githubusercontent.com/98413/50336486-98a2d500-050e-11e9-8a83-a95f24e2065b.gif)

**Comment by shameister** [comment]
Solved.

```
<RX.ScrollView>
  <RX.View onPress={ /* Does not work*/ }>
    <RX.GestureView onPanVertical={...} />
  </RX.View>
</RX.ScrollView>
```

*This works for me*
```
<RX.ScrollView>
  <RX.GestureView onPanVertical={...} />
    <RX.View onPress={ /* Does Works */ }>
  </RX.GestureView>
</RX.ScrollView>
```

**Comment by erictraut** [comment]
It's fine to use a GestureView for a small subview within a ScrollView, but if the enclosed GestureView covers most of the ScrollView, it will become difficult for users to scroll on a touch-based device. 

Your solution also works - to add a mode that temporarily disables scrolling through some other gesture (like a tap).
