### ISSUE TITLE
Hello-world navigation example throwing errors in react-native

### ISSUE THREAD

**Issue by simonas-notcat** [Microsoft/reactxp#99]
In the hello-world sample, after navigating to the second panel, and then pressing "Go Back" I get this error:

```
undefined is not an object (evaluating 'sceneState.route')

_renderScene
    NavigatorExperimentalDelegate.js:55:27
render
    NavigationCard.js:104:21
....
```

![screen shot 2017-05-17 at 09 30 55](https://cloud.githubusercontent.com/assets/16773277/26141389/45634bfe-3ae4-11e7-84d0-70da4ebd76b9.png)

This happens on iOS and Android, but not on the web.

**Comment by simonas-notcat** [comment]
I noticed, that there is a fix for that in 56910c1dea02616d5c8b4f7ea3b167f9e56d4366, but it is not included in the latest reactxp release (0.42.0-rc.8)

**Comment by erictraut** [comment]
Yes, this will get fixed the next time we publish. Lately we've been doing so every few days.

**Comment by erictraut** [comment]
I just published a new version of reactxp that addresses this problem. Thanks for reporting.
