### ISSUE TITLE
Support for textTransform style prop

### ISSUE THREAD

**Issue by aschultz** [Microsoft/reactxp#992]
text-transform is supported in CSS as well as react native, but is not currently surfaced in ReactXP's TextStyle.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform
https://facebook.github.io/react-native/docs/text#style

**Comment by erictraut** [comment]
This is pretty easy to work around with a small amount of JS code. Also, it's not supported on Windows and is unstable on Android. So I'm going to close this.
